<?php

/**
 * Chilean places
 *
 * @author  Luis Sebastian Urrutia Fuentes <luis@urrutia.me> | * @version 1.0.0
 * @update  Elias Rabah <www.hazmeunapagina.cl> | * @version 1.0.1 (16 Regiones sin numerales / Agosto 2018)
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 */
global $places;

$places['CL'] = array(
	'ARI' => array(
		'Arica',
		'Camarones',
		'General Lagos',
		'Putre'
	),
	'TAR' => array(
		'Alto Hospicio',
		'Camiña',
		'Colchane',
		'Huara',
		'Iquique',
		'Pica',
		'Pozo almonte'
	),
	'ANT' => array(
		'Antofagasta',
		'Calama',
		'María Elena',
		'Mejillones',
		'Ollagüe',
		'San Pedro De Atacama',
		'Sierra Gorda',
		'Taltal',
		'Tocopilla'
	),
	'ATA' => array(
		'Alto Del Carmen',
		'Caldera',
		'Chañaral',
		'Copiapó',
		'Diego De Almagro',
		'Freirina',
		'Huasco',
		'Tierra Amarilla',
		'Vallenar'
	),
	'COQ' => array(
		'Andacollo',
		'Canela',
		'Combarbalá',
		'Coquimbo',
		'Illapel',
		'La Higuera',
		'La Serena',
		'Los Vilos',
		'Monte Patria',
		'Ovalle',
		'Paiguano',
		'Punitaqui',
		'Río Hurtado',
		'Salamanca',
		'Vicuña'
	),
	'VAL' => array(
		'Algarrobo',
		'Cabildo',
		'Calera',
		'Calle Larga',
		'Cartagena',
		'Casablanca',
		'Catemu',
		'Concón',
		'El Quisco',
		'El Tabo',
		'Hijuelas',
		'Isla De Pascua',
		'Juan Fernández',
		'La Cruz',
		'La Ligua',
		'Limache',
		'Llaillay',
		'Los Andes',
		'Nogales',
		'Olmué',
		'Panquehue',
		'Papudo',
		'Petorca',
		'Puchuncaví',
		'Putaendo',
		'Quillota',
		'Quilpué',
		'Quintero',
		'Rinconada',
		'San Antonio',
		'San Esteban',
		'San Felipe',
		'Santa María',
		'Santo Domingo',
		'Valparaíso',
		'Villa Alemana',
		'Viña Del Mar',
		'Zapallar'
	),
	'RM' => array(
		'Alhué',
		'Buin',
		'Calera de Tango',
		'Cerrillos',
		'Cerro Navia',
		'Colina',
		'Conchalí',
		'Curacaví',
		'El Bosque',
		'El Monte',
		'Estación Central',
		'Huechuraba',
		'Independencia',
		'Isla de Maipo',
		'La Cisterna',
		'La Florida',
		'La Granja',
		'La Pintana',
		'La Reina',
		'Lampa',
		'Las Condes',
		'Lo Barnechea',
		'Lo Espejo',
		'Lo Prado',
		'Macul',
		'Maipú',
		'María Pinto',
		'Melipilla',
		'Ñuñoa',
		'Padre Hurtado',
		'Paine',
		'Pedro Aguirre Cerda',
		'Peñaflor',
		'Peñalolén',
		'Pirque',
		'Providencia',
		'Pudahuel',
		'Puente Alto',
		'Quilicura',
		'Quinta normal',
		'Recoleta',
		'Renca',
		'San Bernardo',
		'San Joaquín',
		'San José de Maipo',
		'San Miguel',
		'San Pedro',
		'San Ramón',
		'Santiago',
		'Talagante',
		'Tiltil',
		'Vitacura'
	),
	'LIB' => array(
		'Chépica',
		'Chimbarongo',
		'Codegua',
		'Coinco',
		'Coltauco',
		'Doñihue',
		'Graneros',
		'La Estrella',
		'Las Cabras',
		'Litueche',
		'Lolol',
		'Machalí',
		'Malloa',
		'Marchihue',
		'Mostazal',
		'Nancagua',
		'Navidad',
		'Olivar',
		'Palmilla',
		'Paredones',
		'Peralillo',
		'Peumo',
		'Pichidegua',
		'Pichilemu',
		'Placilla',
		'Pumanque',
		'Quinta De Tilcoco',
		'Rancagua',
		'Rengo',
		'Requínoa',
		'San Fernando',
		'San Vicente',
		'Santa Cruz'
	),
	'MAU' => array(
		'Cauquenes',
		'Chanco',
		'Colbún',
		'Constitución',
		'Curepto',
		'Curicó',
		'Empedrado',
		'Hualañé',
		'Licantén',
		'Linares',
		'Longaví',
		'Maule',
		'Molina',
		'Parral',
		'Pelarco',
		'Pelluhue',
		'Pencahue',
		'Rauco',
		'Retiro',
		'Río claro',
		'Romeral',
		'Sagrada Familia',
		'San Clemente',
		'San Javier',
		'San Rafael',
		'Talca',
		'Teno',
		'Vichuquén',
		'Villa Alegre',
		'Yerbas Buenas'
	),
	'NUB' => array(
		'Cobquecura',
		'Coelemu',
		'Ninhue',
		'Portezuelo',
		'Quirihue',
		'Ránquil',
		'Treguaco',
		'Bulnes',
		'Chillán',
		'Chillán Viejo',
		'El Carmen',
		'Pemuco',
		'Pinto',
		'Quillón',
		'San Ignacio',
		'Yungay',
		'Coihueco',
		'Ñiquén',
		'San Carlos',
		'San Fabián',
		'San Nicolás',		
	),
	'BIO' => array(
		'Alto Biobío',
		'Antuco',
		'Arauco',
		'Cabrero',
		'Cañete',
		'Chiguayante',
		'Concepción',
		'Contulmo',
		'Coronel',
		'Curanilahue',
		'Florida',
		'Hualpén',
		'Hualqui',
		'Laja',
		'Lebu',
		'Los Alamos',
		'Los Angeles',
		'Lota',
		'Mulchén',
		'Nacimiento',
		'Negrete',
		'Penco',
		'Quilaco',
		'Quilleco',
		'San Pedro de la Paz',
		'San Rosendo',
		'Santa Bárbara',
		'Santa Juana',
		'Talcahuano',
		'Tirúa',
		'Tomé',
		'Tucapel',
		'Yumbel',
	),
	'ARA' => array(
		'Angol',
		'Carahue',
		'Cholchol',
		'Collipulli',
		'Cunco',
		'Curacautín',
		'Curarrehue',
		'Ercilla',
		'Freire',
		'Galvarino',
		'Gorbea',
		'Lautaro',
		'Loncoche',
		'Lonquimay',
		'Los Sauces',
		'Lumaco',
		'Melipeuco',
		'Nueva Imperial',
		'Padre las Casas',
		'Perquenco',
		'Pitrufquén',
		'Pucón',
		'Purén',
		'Renaico',
		'Saavedra',
		'Temuco',
		'Teodoro Schmidt',
		'Toltén',
		'Traiguén',
		'Victoria',
		'Vilcún',
		'Villarrica'
	),
	'RIO' => array(
		'Corral',
		'Futrono',
		'La Unión',
		'Lago Ranco',
		'Lanco',
		'Los Lagos',
		'Máfil',
		'Mariquina',
		'Paillaco',
		'Panguipulli',
		'Río Bueno',
		'Valdivia'
	),
	'LAG' => array(
		'Ancud',
		'Calbuco',
		'Castro',
		'Chaitén',
		'Chonchi',
		'Cochamó',
		'Curaco de Vélez',
		'Dalcahue',
		'Fresia',
		'Frutillar',
		'Futaleufú',
		'Hualaihué',
		'Llanquihue',
		'Los Muermos',
		'Maullín',
		'Osorno',
		'Palena',
		'Puerto Montt',
		'Puerto Octay',
		'Puerto Varas',
		'Puqueldón',
		'Purranque',
		'Puyehue',
		'Queilén',
		'Quellón',
		'Quemchi',
		'Quinchao',
		'Río Negro',
		'San Juan de la Costa',
		'San Pablo'
	),
	'AYS' => array(
		'Aisén',
		'Chile Chico',
		'Cisnes',
		'Cochrane',
		'Coihaique',
		'Guaitecas',
		'Lago Verde',
		'O\'Higgins',
		'Río Ibáñez',
		'Tortel'
	),
	'MAG' => array(
		'Antártica',
		'Cabo de Hornos (Ex-Navarino)',
		'Laguna Blanca',
		'Natales',
		'Porvenir',
		'Primavera',
		'Punta Arenas',
		'Río Verde',
		'San Gregorio',
		'Timaukel',
		'Torres Del Paine'

	),
);
