<?php

/** 
 * Districts of Kuwait
 * - 129 districts
 * 
 * Source: 
 * - [Please add the source(s) link(s) to check the list of places]
 * 
 * @author  3Lahoonk <bofro7@gmail.com> | https://twitter.com/3LaHoonK
 * @version 1.0.0
 * @license http://www.gnu.org/licenses/gpl-2.0.html
 */
global $places;

$places['KW'] = array(
	'AA' => array(		//AL Asimah  (العاصمة)
		_x('Abdullah Al-Salem', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Adailiya', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Bneid Al Qar', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Daiya', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Dasma', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Dasman', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Doha', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Faiha', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Ghornata', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Jaber Al Ahmad', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Kaifan', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Khaldiya', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Kuwait City', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Mansouriya', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Mirqab', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Mubarakiya Camps', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Nahda', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('North West Sulaibikhat', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Nuzha', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Qadsiya', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Qibla', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Qortuba', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Rawda', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Salhiya', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Shamiya', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Sharq', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Shuwaikh Administrative', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Shuwaikh Educational', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Shuwaikh Industrial 1', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Shuwaikh Industrial 2', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Shuwaikh Industrial 3', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Shuwaikh Medical', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Shuwaikh Residential', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Shuwaikh', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Sulaibikhat', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Surra', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Yarmouk', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
	),
	'HA' => array(		//Hawalli  (حولي)
		_x('Al-Bedae', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Bayan', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Hawally', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Hitteen', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Jabriya', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Maidan Hawally', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Ministries Zone', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Mishrif', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Mubarak Al-Abdullah - West Mishref', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Rumaithiya', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Salam', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Salmiya', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Salwa', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Shaab', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Shuhada', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Siddiq', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Zahra', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),

	),
	'AF' => array(		//AL Farwaniyah  (الفروانية)
		_x('Abdullah Al-Mubarak', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Airport', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Andalous', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Ardhiya 4', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Ardhiya', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Ardiya Small Industrial', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Ardiya Storage Zone', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Ashbeliah', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Dhajeej', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Farwaniya', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Ferdous', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Jeleeb Al-Shuyoukh', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Khaitan', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Omariya', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Rabiya', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Rai', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Reggai', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Rehab', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Sabah Al-Nasser', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Sheikh Saad Al Abdullah Airport', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),

	),
	'MK' => array(			//Mubarak Al-Kabeer  (المبارك الكبير)
		_x('Abu Ftaira', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Abu Hasaniya', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Adan', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Al Masayel', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Al-Qurain', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Al-Qusour', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Fnaitess', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Messila', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Mubarak Al-Kabir', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Sabah Al-Salem', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Sabhan Industrial', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('South Wista', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('West Abu Fetera Small Indust', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Wista', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
	),
	'AJ' => array(			//AL Jahra  (الجهراء)
		_x('Al Naeem', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Jahra Amgarah Industrial', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Jahra Area', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Kabd', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Alnasseem', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Aloyoun', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Alqasr', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Saad Al Abdullah', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Alsulaibiya Industrial 1', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Alsulaibiya Industrial 2', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Alsulaibiya', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Taima', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Alwaha', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Alqairawan', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
	),
	'AH' => array(			//AL Ahmadi   (الاحمدي)
		_x('Abu Halifa', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Al-Ahmadi', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Ali Sabah Al-Salem - Umm Al Hayman', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Al-Julaiaa', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Bnaider', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Dhaher', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Egaila', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Fahad Al Ahmed', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Fahaheel', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Fintas', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Hadiya', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Jaber Al Ali', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Khairan', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Magwa', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Mahboula', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Mangaf', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Mina Abdullah', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Nuwaiseeb', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Riqqa', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Sabah Al Ahmad Marine City', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Sabah AL Ahmad residential', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Sabahiya', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Shuaiba Port', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('South Sabahiya', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Wafra farms', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Wafra residential', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
		_x('Zour', 'District of Kuwait', 'states-cities-and-places-for-woocommerce'),
	),
);

// Use this filter to handle the Districts of Kuwait
$places['KW'] = apply_filters('scpwoo_custom_places_kw', $places['KW']);
