<?php

/**
 * Municipalities of Portugal
 *
 * @author  Javier Esteban <correo@javieresteban.org> | https://javieresteban.org
 * @version 1.0.0
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 */

global $places;

$places['PT'] = array(
/* Autonomous Region of Açores */
  'AC' => array(
    'Angra do Heroísmo',
    'Calheta',
    'Corvo',
    'Horta',
    'Lagoa',
    'Lajes Das Flores',
    'Lajes do Pico',
    'Madalena',
    'Nordeste',
    'Ponta Delgada',
    'Povoação',
    'Ribeira Grande',
    'São Roque do Pico',
    'Santa Cruz da Graciosa',
    'Santa Cruz das Flores',
    'Velas',
    'Vila do Porto',
    'Vila Franca do Campo',
    'Praia da Vitória',
  ),
/* District of Aveiro */
  'AV' => array(
    'Águeda',
    'Albergaria-a-Velha',
    'Anadia',
    'Arouca',
    'Aveiro',
    'Castelo da Paiva',
    'Espinho',
    'Estarreja',
    'Santa Maria da Feira',
    'Ílhavo',
    'Mealhada',
    'Murtosa',
    'Oliveira de Azeméis',
    'Oliveira do Bairro',
    'Ovar',
    'São João da Madeira',
    'Sever do Vouga',
    'Vagos',
    'Vale da Cambra',
  ),
/* District of Beja */
  'BE' => array(
    'Aljustrel',
    'Almodôvar',
    'Alvito',
    'Barrancos',
    'Beja',
    'Castro Verde',
    'Cuba',
    'Ferreira do Alentejo',
    'Mértola',
    'Moura',
    'Odemira',
    'Ourique',
    'Serpa',
    'Vidigueira',
  ),
/* District of Braga */
  'BR' => array(
    'Amares',
    'Barcelos',
    'Braga',
    'Cabeceiras de Basto',
    'Celorico de Basto',
    'Esposende',
    'Fafe',
    'Guimarães',
    'Póvoa de Lanhoso',
    'Terras de Bouro',
    'Vieira do Minho',
    'Vila Nova de Famalicão',
    'Vila Verde',
    'Vizela',
  ),
/* District of Bragança */
  'BA' => array(
    'Alfândega da Fé',
    'Bragança',
    'Carrazeda de Ansiães',
    'Freixo de Espada à Cinta',
    'Macedo de Cavaleiros',
    'Miranda do Douro',
    'Mirandela',
    'Mogadouro',
    'Torre de Moncorvo',
    'Vila Flor',
    'Vimioso',
    'Vinhais',
  ),
/* District of Castelo Branco */
  'CB' => array(
    'Belmonte',
    'Castelo Branco',
    'Covilhã',
    'Fundão',
    'Idanha-a-Nova',
    'Oleiros',
    'Penamacor',
    'Proença-a-Nova',
    'Sertã',
    'Vila de Rei',
    'Vila Velha de Ródão',
  ),
/* District of Coimbra */
  'CO' => array(
    'Arganil',
    'Cantanhede',
    'Coimbra',
    'Condeixa-a-Nova',
    'Figueira da Foz',
    'Góis',
    'Lousã',
    'Mira',
    'Miranda do Corvo',
    'Montemor-o-Velho',
    'Oliveira do Hospital',
    'Pampilhosa da Serra',
    'Penacova',
    'Penela',
    'Soure',
    'Tábua',
    'Vila Nova de Poiares',
  ),
/* District of Évora */
  'EV' => array(
    'Alandroal',
    'Arraiolos',
    'Borba',
    'Estremoz',
    'Évora',
    'Montemor-o-Novo',
    'Mora',
    'Mourão',
    'Portel',
    'Redondo',
    'Reguengos de Monsaraz',
    'Vendas Novas',
    'Viana do Alentejo',
    'Vila Viçosa',
  ),
/* District of Faro */
  'FA' => array(
    'Albufeira',
    'Alcoutim',
    'Aljezur',
    'Castro Marim',
    'Faro',
    'Lagoa (Algarve)',
    'Lagos',
    'Loulé',
    'Monchique',
    'Mourão',
    'Portimão',
    'São Brás de Alportel',
    'Silves',
    'Tavira',
    'Vila do Bispo',
    'Vila Real de Santo António',
  ),
/* District of Guarda */
  'GU' => array(
    'Aguiar da Beira',
    'Almeida',
    'Celorico da Beira',
    'Figueira de Castelo Rodrigo',
    'Fornos de Algodres',
    'Gouveia',
    'Guarda',
    'Manteigas',
    'Mêda',
    'Pinhel',
    'Sabugal',
    'Seia',
    'Trancoso',
    'Vila Nova de Foz Côa',
  ),
/* District of Leiria */
  'LE' => array(
    'Alcobaça',
    'Alvaiázere',
    'Ansião',
    'Batalha',
    'Bombarral',
    'Caldas da Rainha',
    'Castanheira de Pera',
    'Figueiró dos Vinhos',
    'Leiria',
    'Marinha Grande',
    'Nazaré',
    'Óbidos',
    'Pedrógão Grande',
    'Peniche',
    'Pombal',
    'Porto de Mós',
  ),
/* District of Lisboa */
  'LI' => array(
    'Alenquer',
    'Amadora',
    'Arruda dos Vinhos',
    'Azambuja',
    'Cadaval',
    'Cascais',
    'Lisboa',
    'Loures',
    'Lourinhã',
    'Mafra',
    'Oeiras',
    'Sintra',
    'Sobral de Monte Agraço',
    'Torres Vedras',
    'Vila Franca de Xira',
    'Odivelas',
  ),
/* Autonomous Region of Madeira */
  'MA' => array(
    'Calheta',
    'Câmara de Lobos',
    'Funchal',
    'Machico',
    'Ponta do Sol',
    'Porto Moniz',
    'Porto Santo',
    'Ribeira Brava',
    'Santa Cruz',
    'Santana',
    'São Vicente',
  ),
/* District of Portalegre */
  'PA' => array(
    'Alter do Chão',
    'Arronches',
    'Avis',
    'Campo Maior',
    'Castelo de Vide',
    'Crato',
    'Elvas',
    'Fronteira',
    'Gavião',
    'Marvão',
    'Monforte',
    'Nisa',
    'Ponte de Sor',
    'Portalegre',
    'Sousel',
  ),
/* District of Porto */
  'PO' => array(
    'Amarante',
    'Baião',
    'Felgueiras',
    'Gondomar',
    'Lousada',
    'Maia',
    'Marco de Canaveses',
    'Matosinhos',
    'Paços de Ferreira',
    'Paredes',
    'Penafiel',
    'Porto',
    'Póvoa de Varzim',
    'Santo Tirso',
    'Valongo',
    'Vila do Conde',
    'Vila Nova de Gaia',
    'Trofa',
  ),
/* District of Santarém */
  'SA' => array(
    'Abrantes',
    'Alcanena',
    'Almeirim',
    'Alpiarça',
    'Benavente',
    'Cartaxo',
    'Chamusca',
    'Constância',
    'Coruche',
    'Entroncamento',
    'Ferreira do Zêzere',
    'Golegã',
    'Mação',
    'Ourém',
    'Rio Maior',
    'Salvaterra de Magos',
    'Santarém',
    'Sardoal',
    'Tomar',
    'Torres Novas',
    'Vila Nova da Barquinha',
  ),
/* District of Setúbal */
  'SE' => array(
    'Alcácer do Sal',
    'Alcochete',
    'Almada',
    'Barreiro',
    'Grândola',
    'Moita',
    'Montijo',
    'Palmela',
    'Santiago do Cacém',
    'Seixal',
    'Sesimbra',
    'Setúbal',
    'Sines',
  ),
/* District of Viana do Castelo */
  'VC' => array(
    'Arcos de Valdevez',
    'Caminha',
    'Melgaço',
    'Monção',
    'Paredes de Coura',
    'Ponte da Barca',
    'Ponte de Lima',
    'Valença',
    'Viana do Castelo',
    'Vila Nova de Cerveira',
  ),
/* District of Vila Real */
  'VR' => array(
    'Alijó',
    'Boticas',
    'Chaves',
    'Mesão Frio',
    'Mondim de Basto',
    'Montalegre',
    'Murça',
    'Peso da Régua',
    'Ribeira de Pena',
    'Sabrosa',
    'Santa Marta de Penaguião',
    'Valpaços',
    'Vila Pouca de Aguiar',
    'Vila Real',
  ),
/* District of Viseu */
  'VI' => array(
    'Armamar',
    'Carregal do Sal',
    'Castro Daire',
    'Cinfães',
    'Lamego',
    'Mangualde',
    'Moimenta da Beira',
    'Mortágua',
    'Nelas',
    'Oliveira de Frades',
    'Penalva do Castelo',
    'Penedono',
    'Resende',
    'São João da Pesqueira',
    'São Pedro do Sul',
    'Santa Comba Dão',
    'Sátão',
    'Sernancelhe',
    'Tabuaço',
    'Tarouca',
    'Tondela',
    'Vila Nova de Paiva',
    'Viseu',
    'Vouzela',
  ),
);

// Use this filter to handle the Municipalities of Portugal
$places['PT'] = apply_filters('scpwoo_custom_places_pt', $places['PT']);
