<?php

/**
 * Cities of Egypt
 *
 * Source:
 * https://www.citypopulation.de/en/egypt/cities/
 *
 * @author  Heba Fareed
 * @version 1.0.0
 * @license http://www.gnu.org/licenses/gpl-2.0.html
 */

global $places;

$places['EG'] = array(
  'ISK' => array(
    _x('Alexandria', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Burj Al Arab', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('New Burj Al Arab', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
  ),
  'ASU' => array(
    _x('Abnoub', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Abu Tig', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Assiut El Gedida', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Assiut', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Dayrout', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('El Badari', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('El Ghanaim', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Manfalut', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Qusiya', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Sahel Selim', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Sidfa', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
  ),
  'ASW' => array(
    _x('Abo Simbl Al Siyahia', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Al Basilia', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Al Sibaeia', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Al-Radisiyah', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Aswan El Gedida', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Aswan', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Drau', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Edfu', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Kalabsha', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Kom Ombo', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Nasr Al Nuba', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
  ),
  'BHR' => array(
    _x('Abu Homs', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Abu al-Matamir', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Badr', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Damanhour', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Delengat', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Edco', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Housh Eissa', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Itai Baroud', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Kafr El Dawar', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Kom Hamada', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Mahmoudiyah', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('New Nubaria', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Rahmaniyah', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Rashid', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Shubrakhit', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Wadi Natrun', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
  ),
  'BNS' => array(
    _x('Al Wasta', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Bani Sweif', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Beba', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Beni Suef El Gedida', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Ehnasia', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Fashn', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Naser', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Somasta', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
  ),
  'CAI' => array(
    _x('Cairo', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
  ),
  'DMI' => array(
    _x('Alruwda', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Alsaru', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Azbet Al Burg', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Damietta', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Faraskour', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Kafr El-Batikh', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Kafr Saad', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Meet Abou Ghalib', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('New Damietta', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Ras El Bar', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Zarqa', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
  ),
  'DQH' => array(
    _x('Aga', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Al Manzala', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Aljamalia', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Bani Ubaid', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Belqas', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Dekernes', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('El Kurdi', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Gamasa', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Mahalat Damana', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Mansoura', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Mataria', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Meet Salsil', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Menia El Nasr', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Mitt Ghamr', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Nabroh', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Sherbin', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Sinbillawin', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Talkha', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Tami al\'amdid', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
  ),
  'FYM' => array(
    _x('Epschway', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Etsa', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Fayoum El Gedida', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Fayoum', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Snores', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Tamiya', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Yusuf El Sediaq', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
  ),
  'GHB' => array(
    _x('Al Mahalla Al Kobra', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Basion', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('El Santa', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Kafr El Zayat', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Qutour', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Samannoud', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Tanta', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Zefta', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
  ),
  'GIZ' => array(
    _x('Abu Nomros', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Al Ayat', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Al Badrasheen', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Al-Bawaiti', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Atfih', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Cheikh Zayed', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Giza', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Hawamdiyah', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Kafr Ghati', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Kerdasa', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Manshiyet Al Bakari', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('ManshiyetAl Qanater', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Oaseem', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Saf', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Sixth of October', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
  ),
  'ISM' => array(
    _x('Abu Sawir', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('El Tal El Kabier', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Fayed', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Ismailia', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Kasasien El Gedida', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Qantara Gharb', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Qantara Sharq', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
  ),
  'KAS' => array(
    _x('Baltim', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Bella', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Burg Al Burullus', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Desouq', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Fooh', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Hamol', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Kafr El Sheikh', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Masief Baltim', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Metobas', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Qellen', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Riyadh', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Sidi Ghazi', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Sidi Salm', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
  ),
  'LUX' => array(
    _x('Al Bayadieh', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Al Qarna', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Al Tud', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Al ziynia', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Armant', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Esna', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Luxor', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('New Luxor', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('New Tiba', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
  ),
  'MAT' => array(
    _x('Al-Nagila', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Alamein', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Dabaa', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('El Hamam', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Marsa Matrouh', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Salloum', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Sidi Brani', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Siwa', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
  ),
  'MIN' => array(
    _x('Bani Mazar', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Deir Mawas', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('El Adwa', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Madinat El Fekria', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Magagha', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Mattay', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Meloy', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Minya El Gedida', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Minya', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Samalut', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
  ),
  'MNF' => array(
    _x('Al Bagor', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Al Shohada', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Ashmon', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Berkat El Saba', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Menouf', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Quesna', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Sadat City', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Sars El-Layan', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Shbeen El Koom', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Tala', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
  ),
  'NEV' => array(
    _x('Balat', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('El Kharga', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Farafra', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Mout', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Paris', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
  ),
  'NSI' => array(
    _x('Al Hasana', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Arish', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Bir al-Abed', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Nakhl', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Rafah', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Sheikh Zowaid', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
  ),
  'POS' => array(
    _x('Port Fouad', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Port Said', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
  ),
  'QLY' => array(
    _x('Al Qanater Charity', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Banha', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Kafr Shukr', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Khanka', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Khosous', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Obour', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Qaha', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Qalyub', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Shibin Al Qanater', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Shubra Al Khaimah', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Tukh', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
  ),
  'QNA' => array(
    _x('Abu Tesht', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Alwaqf', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Deshna', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Farshout', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Nag Hammadi', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Naqada', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('New Qena', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Qaft', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Qena', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Quos', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
  ),
  'BAH' => array(
    _x('El Qusiar', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Halaib', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Hurghada', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Marsa Alam', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Ras Ghareb', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Safaga', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Shalatin', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
  ),
  'SHA' => array(
    _x('Abu Hammad', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Abu Kabir', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Al Ashr Men Ramadan', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Al Ibrahimiyah', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Awlad Saqr', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Belbeis', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Deirb Negm', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('El Qurain', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('El Salihia El Gedida', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Faccus', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Hehia', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Husseiniya', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Kafr Saqr', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Manshayat Abu Omar', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Mashtoul El Souq', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Minya Al Qamh', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Qenaiat', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('San Alhajar Alqablia', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Zagazig', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
  ),
  'SOH' => array(
    _x('Akhmeem', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Akhmim El Gedida', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Albalina', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Almunsha\'a', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Dar AISalaam', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('El Maragha', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Gerga', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Jahina Al Gharbia', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Saqilatuh', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Sohag El Gedida', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Sohag', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Tahta', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Tama', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
  ),
  'SSI' => array(
    _x('Abu Redis', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Abu Zenaima', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Al Toor', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Dahab', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Nuweiba', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Ras Sidr', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Saint Catherine', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Sharm El-Shaikh', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
    _x('Taba', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
  ),
  'SUZ' => array(
    _x('Suez', 'City of Egypt', 'states-cities-and-places-for-woocommerce'),
  ),
);

// Use this filter to handle the Cities of Egypt
$places['EG'] = apply_filters('scpwoo_custom_places_eg', $places['EG']);
