<?php

/**
 * Districts of Pakistan
 * 
 * Sources:
 * - https://en.wikipedia.org/wiki/Districts_of_Pakistan
 *
 * @author   Faisal Basra <hello@faisalbasra.me>
 * @version  1.0.1
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * Credits: https://faisalbasra.blogspot.com/2013/11/cities-list-of-pakistan-in-excel-csv.html
 */
global $places;

$places['PK'] = array(
	'JK' => array(
		'Bagh',
		'Bhimber',
		'khuiratta',
		'Kotli',
		'Mangla',
		'Mirpur',
		'Muzaffarabad',
		'Plandri',
		'Rawalakot',
		'Punch'
	),
	'BA' => array(
		'Amir Chah',
		'Bazdar',
		'Bela',
		'Bellpat',
		'Bagh',
		'Burj',
		'Chagai',
		'Chah Sandan',
		'Chakku',
		'Chaman',
		'Chhatr',
		'Dalbandin',
		'Dera Bugti',
		'Dhana Sar',
		'Diwana',
		'Duki',
		'Dushi',
		'Duzab',
		'Gajar',
		'Gandava',
		'Garhi Khairo',
		'Garruck',
		'Ghazluna',
		'Girdan',
		'Gulistan',
		'Gwadar',
		'Gwash',
		'Hab Chauki',
		'Hameedabad',
		'Harnai',
		'Hinglaj',
		'Hoshab',
		'Ispikan',
		'Jhal',
		'Jhal Jhao',
		'Jhatpat',
		'Jiwani',
		'Kalandi',
		'Kalat',
		'Kamararod',
		'Kanak',
		'Kandi',
		'Kanpur',
		'Kapip',
		'Kappar',
		'Karodi',
		'Katuri',
		'Kharan',
		'Khuzdar',
		'Kikki',
		'Kohan',
		'Kohlu',
		'Korak',
		'Lahri',
		'Lasbela',
		'Liari',
		'Loralai',
		'Mach',
		'Mand',
		'Manguchar',
		'Mashki Chah',
		'Maslti',
		'Mastung',
		'Mekhtar',
		'Merui',
		'Mianez',
		'Murgha Kibzai',
		'Musa Khel Bazar',
		'Nagha Kalat',
		'Nal',
		'Naseerabad',
		'Nauroz Kalat',
		'Nur Gamma',
		'Nushki',
		'Nuttal',
		'Ormara',
		'Palantuk',
		'Panjgur',
		'Pasni',
		'Piharak',
		'Pishin',
		'Qamruddin Karez',
		'Qila Abdullah',
		'Qila Ladgasht',
		'Qila Safed',
		'Qila Saifullah',
		'Quetta',
		'Rakhni',
		'Robat Thana',
		'Rodkhan',
		'Saindak',
		'Sanjawi',
		'Saruna',
		'Shabaz Kalat',
		'Shahpur',
		'Sharam Jogizai',
		'Shingar',
		'Shorap',
		'Sibi',
		'Sonmiani',
		'Spezand',
		'Spintangi',
		'Sui',
		'Suntsar',
		'Surab',
		'Thalo',
		'Tump',
		'Turbat',
		'Umarao',
		'pirMahal',
		'Uthal',
		'Vitakri',
		'Wadh',
		'Washap',
		'Wasjuk',
		'Yakmach',
		'Zhob'

	),
	'GB' => array(
		'Astor',
		'Baramula',
		'Hunza',
		'Gilgit',
		'Nagar',
		'Skardu',
		'Shangrila',
		'Shandur'
	),
	'KP' => array(
		'Abbottabad',
		'Bajaur',
		'Ayubia',
		'Adezai',
		'Banda Daud Shah',
		'Bannu',
		'Batagram',
		'Birote',
		'Buner',
		'Chakdara',
		'Charsadda',
		'Chitral',
		'Dargai',
		'Darya Khan',
		'Dera Ismail Khan',
		'Drasan',
		'Drosh',
		'Hangu',
		'Haripur',
		'Hangu',
		'Kalam',
		'Karak',
		'Khanaspur',
		'Kohat',
		'Kohistan',
		'Kurram Agency',
		'Khyber Agency',
		'Lakki Marwat',
		'Latamber',
		'Lower Dir',
		'Madyan',
		'Malakand',
		'Mansehra',
		'Mardan',
		'Miram Shah',
		'Mohmand',
		'Mastuj',
		'Mongora',
		'Nowshera',
		'North Waziristan',
		'Paharpur',
		'Peshawar',
		'Saidu Sharif',
		'Shangla',
		'Sakesar',
		'Swabi',
		'Swat',
		'South Waziristan',
		'Tangi',
		'Tank',
		'Thall',
		'Tordher',
		'Upper Dir',
		'Wana'
	),

	'SD' => array(
		'Ali Bandar',
		'Baden',
		'Chachro',
		'Dadu',
		'Digri',
		'Diplo',
		'Dokri',
		'Gadra',
		'Ghanian',
		'Ghauspur',
		'Ghotki',
		'Hala',
		'Hyderabad',
		'Islamkot',
		'Jacobabad',
		'Jamesabad',
		'Jamshoro',
		'Janghar',
		'Jati (Mughalbhin)',
		'Jhudo',
		'Jungshahi',
		'Kandiaro',
		'Karachi',
		'Kashmor',
		'Keti Bandar',
		'Khairpur',
		'Khora',
		'Klupro',
		'Khokhropur',
		'Korangi',
		'Kotri',
		'Kot Sarae',
		'Larkana',
		'Lund',
		'Mathi',
		'Matiari',
		'Mehar',
		'Mirpur Batoro',
		'Mirpur Khas',
		'Mirpur Sakro',
		'Mithi',
		'Mithani',
		'Moro',
		'Nagar Parkar',
		'Naushara',
		'Naudero',
		'Noushero Feroz',
		'Nawabshah',
		'Nazimabad',
		'Naokot',
		'Pendoo',
		'Pokran',
		'Qambar',
		'Qazi Ahmad',
		'Ranipur',
		'Ratodero',
		'Rohri',
		'Saidu Sharif',
		'Sakrand',
		'Sanghar',
		'Shadadkhot',
		'Shahbandar',
		'Shahdadpur',
		'Shahpur Chakar',
		'Shikarpur',
		'Sujawal',
		'Sukkur',
		'Tando Adam',
		'Tando Allahyar',
		'Tando Bago',
		'Tar Ahamd Rind',
		'Thatta',
		'Tujal',
		'Umarkot',
		'Veirwaro',
		'Warah'

	),

	'PB' => array(
		'Ahmedpur East',
		'Ahmed Nager Chatha',
		'Ali Pur',
		'Arifwala',
		'Attock',
		'Basti Malook',
		'Bhagalchur',
		'Bhalwal',
		'Bahawalnagar',
		'Bahawalpur',
		'Bhaipheru',
		'Bhakkar',
		'Burewala',
		'Chailianwala',
		'Chakwal',
		'Chichawatni',
		'Chiniot',
		'Chowk Azam',
		'Chowk Sarwar Shaheed',
		'Daska',
		'Darya Khan',
		'Dera Ghazi Khan',
		'Derawar Fort',
		'Dhaular',
		'Dina City',
		'Dinga',
		'Dipalpur',
		'Faisalabad',
		'Fateh Jang',
		'Gadar',
		'Ghakhar Mandi',
		'Gujranwala',
		'Gujrat',
		'Gujar Khan',
		'Hafizabad',
		'Haroonabad',
		'Hasilpur',
		'Haveli Lakha',
		'Jampur',
		'Jhang',
		'Jhelum',
		'Kalabagh',
		'Karor Lal Esan',
		'Kasur',
		'Kamalia',
		'Kamokey',
		'Khanewal',
		'Khanpur',
		'Kharian',
		'Khushab',
		'Kot Addu',
		'Jahania',
		'Jalla Araain',
		'Jauharabad',
		'Laar',
		'Lahore',
		'Lalamusa',
		'Layyah',
		'Lodhran',
		'Mamoori',
		'Mandi Bahauddin',
		'Makhdoom Aali',
		'Mandi Warburton',
		'Mailsi',
		'Mian Channu',
		'Minawala',
		'Mianwali',
		'Multan',
		'Murree',
		'Muridke',
		'Muzaffargarh',
		'Narowal',
		'Okara',
		'Renala Khurd',
		'Rajan Pur',
		'Pak Pattan',
		'Panjgur',
		'Pattoki',
		'Pirmahal',
		'Qila Didar Singh',
		'Rabwah',
		'Raiwind',
		'Rajan Pur',
		'Rahim Yar Khan',
		'Rawalpindi',
		'Rohri',
		'Sadiqabad',
		'Safdar Abad – (Dhaban Singh)',
		'Sahiwal',
		'Sangla Hill',
		'Samberial',
		'Sarai Alamgir',
		'Sargodha',
		'Shakargarh',
		'Shafqat Shaheed Chowk',
		'Sheikhupura',
		'Sialkot',
		'Sohawa',
		'Sooianwala',
		'Sundar (city)',
		'Talagang',
		'Tarbela',
		'Takhtbai',
		'Taxila',
		'Toba Tek Singh',
		'Vehari',
		'Wah Cantonment',
		'Wazirabad'

	),

	'IS' => array(
		'Islamabad'
	)
);

// Use this filter to handle the Districts of Pakistan
$places['PK'] = apply_filters('scpwoo_custom_places_pk', $places['PK']);
