<?php

/**
 * Trinidad & Tobago
 * - UPSL Service Areas
 * 
 * Sources: 
 * - http://domestic.universalpackagesys.com/DSS/Tools/Estimate
 * 
 * @author  Marlon Dyce <marlon@dycedesigns.com>
 * @version 1.0.0
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * 
 */

global $places;

$places['TT'] = array(
  'Aranguez',
  'Arima',
  'Aripero',
  'Arouca',
  'Auchenskeoch',
  'Bacelot',
  'Barataria',
  'Barrackpore',
  'Basseterre',
  'Belmont',
  'Bethel',
  'Biche',
  'Black Rock',
  'Blanchisseuse',
  'Bon Accord',
  'Bonasse',
  'Bonne Terre',
  'Brasso Seco',
  'Brasso',
  'Brazil',
  'Buccoo',
  'Buenos Ayres',
  'Caigual',
  'Calder Hall',
  'California',
  'Canaan',
  'Canoe Bay',
  'Carapichaima',
  'Carapo',
  'Carenage',
  'Carmichael',
  'Carnbee',
  'Cascade',
  'Caroni',
  'Caparo',
  'Cedros',
  'Centeno',
  'Chaguanas',
  'Chaguaramas',
  'Charuma',
  'Chase Village',
  'Chatham',
  'Cheeyou',
  'Claxton Bay',
  'Cochrane',
  'Cocorite',
  'Concordia',
  'Coryal',
  'Courland',
  'Couva',
  'Cove Industrial Estate',
  'Crown Point',
  'Cuche',
  'Cumaca',
  'Cunaripa',
  'Cunupia',
  'Curepe',
  'Dabadie',
  'Diego Martin',
  'Ecclesville',
  'El Dorado',
  'El Socorro',
  'Erin',
  'Filette',
  'Flangin Town',
  'Fonrose',
  'Freeport',
  'Friendsfield',
  'Friendship',
  'Fullarton',
  'Fyzabad',
  'Galeota Point',
  'Gasparillo',
  'Golden Grove',
  'Grafton',
  'Grande Riviere',
  'Grange',
  'Granville',
  'Great Courland Bay',
  'Guaico Tamana',
  'Guanapo',
  'Guayaguayare',
  'Hardbargain',
  'Hasnalli',
  'Howsin',
  'Icacos',
  'Kilgwyn',
  'La Brea',
  'La Pastora',
  'La Romain',
  'La Veronica',
  'Lambeau',
  'Las Cuevas',
  'Las Lomas',
  'Laventille',
  'Lengua',
  'Little Rockly Bay',
  'Lopinot',
  'Los Bajos',
  'Lower Fishing Pond',
  'Lower Manzanilla',
  'Lowlands',
  'Mamon',
  'Mamoral',
  'Manzanilla',
  'Marabella',
  'Maracas Bay Village',
  'Maracas St. Joseph',
  'Maraval',
  'Marys Hill',
  'Matelot',
  'Matura',
  'Mayaro',
  'Mayo',
  'Monte Video',
  'Montgomery',
  'Morne Diablo',
  'Moruga',
  'Morvant',
  'Mount Grace',
  'Mount Harris',
  'Mount Lambert',
  'Mount Pleasant',
  'Mourne Quinton',
  'Mt Hope',
  'Mt. Irvine',
  'Mucurapo',
  'Mundo Nuevo',
  'Navet',
  'Nestor',
  'New Grant',
  'Newtown',
  'Orange Hill',
  'Oropouche',
  'Ortoire',
  'Palo Seco',
  'Paria',
  'Patience Hill',
  'Penal',
  'Petit Bourg',
  'Petit Trou',
  'Petit Valley',
  'Phoenix Park',
  'Piarco',
  'Pierreville',
  'Pigeon Point',
  'Plaisance',
  'Plum Mitan',
  'Plymouth',
  'Point Fortin',
  'Point Lisas',
  'Point Radix',
  'Pointe a Pierre',
  'Poole',
  'Port of Spain',
  'Preau',
  'Preysal',
  'Princess Town',
  'Prospect',
  'Rampanalgas',
  'Redhead',
  'Rio Claro',
  'Riseland',
  'Rockly Vale',
  'Rousillac',
  'Rushville',
  'Sadhoowa',
  'Salybia',
  'San Fernando',
  'San Francique',
  'San Juan',
  'Sandy Point',
  'Sangre Grande',
  'Sans Souci',
  'Santa Cruz',
  'Santa Flora',
  'Scarborough',
  'Sea Lots',
  'Shaw Park',
  'Shirvan',
  'Signal Hill',
  'Siparia',
  'Sixth Company',
  'St Anns',
  'St Augustine',
  'St Clair',
  'St Helena',
  'St James',
  'St Joseph',
  'St. Madeleine',
  'Stonehaven Bay',
  'Store Bay',
  'Tabaquite',
  'Tableland',
  'Tacarigua',
  'Talparo',
  'The Whim',
  'Thick',
  'Third Company',
  'Tobago Plantations',
  'Toco',
  'Trincity',
  'Tunapuna',
  'Unis',
  'Upper Fishing Pond',
  'Upper Manzanilla',
  'Valencia',
  'Valsayn',
  'Venado',
  'Verdant Vale',
  'Wallerfield',
  'Westmoorings',
  'Williamsville',
  'Woodbrook'
);

$states['TT'] = array(
  'Tobago' => 'Tobago',
  'Arima' => 'Arima',
  'Chaguanas' => 'Chaguanas',
  'Couva/Tabaquite/Talparo' => 'Couva/Tabaquite/Talparo',
  'Diego Martin' => 'Diego Martin',
  'Mayaro/Rio Claro' => 'Mayaro/Rio Claro',
  'Penal/Debe' => 'Penal/Debe',
  'Point Fortin' => 'Point Fortin',
  'Port of Spain' => 'Port of Spain',
  'Princes Town' => 'Princes Town',
  'San Fernando' => 'San Fernando',
  'San Juan/Laventille' => 'San Juan/Laventille',
  'Sangre Grande' => 'Sangre Grande',
  'Siparia' => 'Siparia',
  'Tunapuna/Piarco' => 'Tunapuna/Piarco'
);

foreach ($states['TT'] as $corp => $state) {
$places['TT'][$corp] = array(
  'Aranguez',
  'Arima',
  'Aripero',
  'Arouca',
  'Auchenskeoch',
  'Bacelot',
  'Barataria',
  'Barrackpore',
  'Basseterre',
  'Belmont',
  'Bethel',
  'Biche',
  'Black Rock',
  'Blanchisseuse',
  'Bon Accord',
  'Bonasse',
  'Bonne Terre',
  'Brasso Seco',
  'Brasso',
  'Brazil',
  'Buccoo',
  'Buenos Ayres',
  'Caigual',
  'Calder Hall',
  'California',
  'Canaan',
  'Canoe Bay',
  'Carapichaima',
  'Carapo',
  'Carenage',
  'Carmichael',
  'Carnbee',
  'Cascade',
  'Caroni',
  'Caparo',
  'Cedros',
  'Centeno',
  'Chaguanas',
  'Chaguaramas',
  'Charuma',
  'Chase Village',
  'Chatham',
  'Cheeyou',
  'Claxton Bay',
  'Cochrane',
  'Cocorite',
  'Concordia',
  'Coryal',
  'Courland',
  'Couva',
  'Cove Industrial Estate',
  'Crown Point',
  'Cuche',
  'Cumaca',
  'Cunaripa',
  'Cunupia',
  'Curepe',
  'Dabadie',
  'Diego Martin',
  'Ecclesville',
  'El Dorado',
  'El Socorro',
  'Erin',
  'Filette',
  'Flangin Town',
  'Fonrose',
  'Freeport',
  'Friendsfield',
  'Friendship',
  'Fullarton',
  'Fyzabad',
  'Galeota Point',
  'Gasparillo',
  'Golden Grove',
  'Grafton',
  'Grande Riviere',
  'Grange',
  'Granville',
  'Great Courland Bay',
  'Guaico Tamana',
  'Guanapo',
  'Guayaguayare',
  'Hardbargain',
  'Hasnalli',
  'Howsin',
  'Icacos',
  'Kilgwyn',
  'La Brea',
  'La Pastora',
  'La Romain',
  'La Veronica',
  'Lambeau',
  'Las Cuevas',
  'Las Lomas',
  'Laventille',
  'Lengua',
  'Little Rockly Bay',
  'Lopinot',
  'Los Bajos',
  'Lower Fishing Pond',
  'Lower Manzanilla',
  'Lowlands',
  'Mamon',
  'Mamoral',
  'Manzanilla',
  'Marabella',
  'Maracas Bay Village',
  'Maracas St. Joseph',
  'Maraval',
  'Marys Hill',
  'Matelot',
  'Matura',
  'Mayaro',
  'Mayo',
  'Monte Video',
  'Montgomery',
  'Morne Diablo',
  'Moruga',
  'Morvant',
  'Mount Grace',
  'Mount Harris',
  'Mount Lambert',
  'Mount Pleasant',
  'Mourne Quinton',
  'Mt Hope',
  'Mt. Irvine',
  'Mucurapo',
  'Mundo Nuevo',
  'Navet',
  'Nestor',
  'New Grant',
  'Newtown',
  'Orange Hill',
  'Oropouche',
  'Ortoire',
  'Palo Seco',
  'Paria',
  'Patience Hill',
  'Penal',
  'Petit Bourg',
  'Petit Trou',
  'Petit Valley',
  'Phoenix Park',
  'Piarco',
  'Pierreville',
  'Pigeon Point',
  'Plaisance',
  'Plum Mitan',
  'Plymouth',
  'Point Fortin',
  'Point Lisas',
  'Point Radix',
  'Pointe a Pierre',
  'Poole',
  'Port of Spain',
  'Preau',
  'Preysal',
  'Princess Town',
  'Prospect',
  'Rampanalgas',
  'Redhead',
  'Rio Claro',
  'Riseland',
  'Rockly Vale',
  'Rousillac',
  'Rushville',
  'Sadhoowa',
  'Salybia',
  'San Fernando',
  'San Francique',
  'San Juan',
  'Sandy Point',
  'Sangre Grande',
  'Sans Souci',
  'Santa Cruz',
  'Santa Flora',
  'Scarborough',
  'Sea Lots',
  'Shaw Park',
  'Shirvan',
  'Signal Hill',
  'Siparia',
  'Sixth Company',
  'St Anns',
  'St Augustine',
  'St Clair',
  'St Helena',
  'St James',
  'St Joseph',
  'St. Madeleine',
  'Stonehaven Bay',
  'Store Bay',
  'Tabaquite',
  'Tableland',
  'Tacarigua',
  'Talparo',
  'The Whim',
  'Thick',
  'Third Company',
  'Tobago Plantations',
  'Toco',
  'Trincity',
  'Tunapuna',
  'Unis',
  'Upper Fishing Pond',
  'Upper Manzanilla',
  'Valencia',
  'Valsayn',
  'Venado',
  'Verdant Vale',
  'Wallerfield',
  'Westmoorings',
  'Williamsville',
  'Woodbrook'
);
}

// Use this filter to handle the Villages / Towns / Cities of Trinidad & Tobago
$places['TT'] = apply_filters('scpwoo_custom_places_tt', $places['TT']);
