<?php

/**
 * Localities of United Arab Emirates
 * 
 * @author   Waqas Ahmad <https://www.apnawaqas.com>
 * @version  1.0.0
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 * @credit   Waqas @ Arabianwave.com <https://www.arabianwave.com>
 */

global $places;

$places['AE'] = array(
	'DXB' => array(
		__('Nad Alsheba', 'states-cities-and-places-for-woocommerce'),
		__('Abraj Al Jumeirah', 'states-cities-and-places-for-woocommerce'),
		__('Abu Hail', 'states-cities-and-places-for-woocommerce'),
		__('Umm Alsheif', 'states-cities-and-places-for-woocommerce'),
		__('Umm Ramol', 'states-cities-and-places-for-woocommerce'),
		__('Umm Suqeim', 'states-cities-and-places-for-woocommerce'),
		__('Al Ras', 'states-cities-and-places-for-woocommerce'),
		__('Al Rashidiya', 'states-cities-and-places-for-woocommerce'),
		__('Al Aweer', 'states-cities-and-places-for-woocommerce'),
		__('Al Quoz', 'states-cities-and-places-for-woocommerce'),
		__('Al Khawaneej', 'states-cities-and-places-for-woocommerce'),
		__('Jabal Ali', 'states-cities-and-places-for-woocommerce'),
		__('Al Badaa', 'states-cities-and-places-for-woocommerce'),
		__('Bur Dubai', 'states-cities-and-places-for-woocommerce'),
		__('Al Baraha', 'states-cities-and-places-for-woocommerce'),
		__('Al Barsha', 'states-cities-and-places-for-woocommerce'),
		__('Al Buteen', 'states-cities-and-places-for-woocommerce'),
		__('Bukadra', 'states-cities-and-places-for-woocommerce'),
		__('Talal Al Emarat', 'states-cities-and-places-for-woocommerce'),
		__('Al Jaffiliya', 'states-cities-and-places-for-woocommerce'),
		__('Al Jaddaf', 'states-cities-and-places-for-woocommerce'),
		__('Jumeirah', 'states-cities-and-places-for-woocommerce'),
		__('Al Hamriya', 'states-cities-and-places-for-woocommerce'),
		__('Al Khabaisi', 'states-cities-and-places-for-woocommerce'),
		__('Business Bay', 'states-cities-and-places-for-woocommerce'),
		__('Deira', 'states-cities-and-places-for-woocommerce'),
		__('Ras Al Khor', 'states-cities-and-places-for-woocommerce'),
		__('Al Rigga', 'states-cities-and-places-for-woocommerce'),
		__('Riggat Al Buteen', 'states-cities-and-places-for-woocommerce'),
		__('Zaabeel', 'states-cities-and-places-for-woocommerce'),
		__('Al Satwa', 'states-cities-and-places-for-woocommerce'),
		__('Grand Souq', 'states-cities-and-places-for-woocommerce'),
		__('Sheikh Zayed Road', 'states-cities-and-places-for-woocommerce'),
		__('Al Shindagha', 'states-cities-and-places-for-woocommerce'),
		__('Al Safa', 'states-cities-and-places-for-woocommerce'),
		__('Al Sufouh', 'states-cities-and-places-for-woocommerce'),
		__('Oud Metha', 'states-cities-and-places-for-woocommerce'),
		__('Al Garhoud', 'states-cities-and-places-for-woocommerce'),
		__('Al Qusais', 'states-cities-and-places-for-woocommerce'),
		__('Al Karama', 'states-cities-and-places-for-woocommerce'),
		__('Al Muhaisnah', 'states-cities-and-places-for-woocommerce'),
		__('Dubai Healthcare City', 'states-cities-and-places-for-woocommerce'),
		__('Mirdif', 'states-cities-and-places-for-woocommerce'),
		__('Al Muraqqabat', 'states-cities-and-places-for-woocommerce'),
		__('Trade Centre 1', 'states-cities-and-places-for-woocommerce'),
		__('Trade Centre 2', 'states-cities-and-places-for-woocommerce'),
		__('Al Mazhar', 'states-cities-and-places-for-woocommerce'),
		__('Al Muteena', 'states-cities-and-places-for-woocommerce'),
		__('Al Mamzar', 'states-cities-and-places-for-woocommerce'),
		__('Al Manara', 'states-cities-and-places-for-woocommerce'),
		__('Al Mankhool', 'states-cities-and-places-for-woocommerce'),
		__('Naif', 'states-cities-and-places-for-woocommerce'),
		__('Nadd Al Hamar', 'states-cities-and-places-for-woocommerce'),
		__('Nad Al Shamma', 'states-cities-and-places-for-woocommerce'),
		__('Al Nahda', 'states-cities-and-places-for-woocommerce'),
		__('Hor Al Anz', 'states-cities-and-places-for-woocommerce'),
		__('Al Waheda', 'states-cities-and-places-for-woocommerce'),
		__('Warsan', 'states-cities-and-places-for-woocommerce'),
		__('Al Warqa', 'states-cities-and-places-for-woocommerce'),
		__('Al Wasl', 'states-cities-and-places-for-woocommerce'),
		__('Oud Al Muteena', 'states-cities-and-places-for-woocommerce'),
		__('Al Refaa', 'states-cities-and-places-for-woocommerce'),
		__('Arabian Ranches', 'states-cities-and-places-for-woocommerce'),
		__('Al Twar', 'states-cities-and-places-for-woocommerce'),
		__('Umm Ramool', 'states-cities-and-places-for-woocommerce')
	),
	'AUB' => array(
		__('Ghantoot', 'states-cities-and-places-for-woocommerce'),
		__('Bani Yas', 'states-cities-and-places-for-woocommerce'),
		__('Al Shamkhah', 'states-cities-and-places-for-woocommerce'),
		__('Al Sweihan', 'states-cities-and-places-for-woocommerce'),
		__('Al Adlah', 'states-cities-and-places-for-woocommerce'),
		__('Al Moazaz', 'states-cities-and-places-for-woocommerce'),
		__('Tarif', 'states-cities-and-places-for-woocommerce'),
		__('Al Bateen', 'states-cities-and-places-for-woocommerce'),
		__('Musaffah', 'states-cities-and-places-for-woocommerce'),
		__('Al Khalidiyah', 'states-cities-and-places-for-woocommerce'),
		__('Al Maqta', 'states-cities-and-places-for-woocommerce'),
		__('Al Mushrif', 'states-cities-and-places-for-woocommerce'),
		__('Al Zaab', 'states-cities-and-places-for-woocommerce'),
		__('Khalifa City', 'states-cities-and-places-for-woocommerce'),
		__('Bawabat Abu Dhabi', 'states-cities-and-places-for-woocommerce'),
		__('Al Bahyah', 'states-cities-and-places-for-woocommerce'),
		__('Al Falah', 'states-cities-and-places-for-woocommerce'),
		__('Al Raha Beach', 'states-cities-and-places-for-woocommerce'),
		__('Al Shahama', 'states-cities-and-places-for-woocommerce'),
		__('Al Samha', 'states-cities-and-places-for-woocommerce'),
		__('Al Wathbah', 'states-cities-and-places-for-woocommerce'),
		__('Madinat Zayed', 'states-cities-and-places-for-woocommerce'),
		__('Al Mafraq', 'states-cities-and-places-for-woocommerce'),
		__('Mohamed Bin Zayed City', 'states-cities-and-places-for-woocommerce'),
		__('Al Reem Island', 'states-cities-and-places-for-woocommerce'),
		__('Saadiyat Island', 'states-cities-and-places-for-woocommerce'),
		__('Yas Island', 'states-cities-and-places-for-woocommerce'),
		__('Al Muroor', 'states-cities-and-places-for-woocommerce'),
		__('Al Nahyan', 'states-cities-and-places-for-woocommerce'),
		__('Ministry Of Economy', 'states-cities-and-places-for-woocommerce'),
		__('Shakhbout City', 'states-cities-and-places-for-woocommerce'),
		__('Airport Road', 'states-cities-and-places-for-woocommerce'),
		__('Al Nahda East', 'states-cities-and-places-for-woocommerce'),
		__('Al Dhafra', 'states-cities-and-places-for-woocommerce'),
		__('Al Reef Villas', 'states-cities-and-places-for-woocommerce'),
		__('Al Wathbah', 'states-cities-and-places-for-woocommerce'),
		__('Al Zafaranah', 'states-cities-and-places-for-woocommerce'),
		__('Fotouh Al Khai', 'states-cities-and-places-for-woocommerce'),
		__('Exhibition Centre', 'states-cities-and-places-for-woocommerce'),
		__('Jawazat Street', 'states-cities-and-places-for-woocommerce'),
		__('Al Wahda Mall', 'states-cities-and-places-for-woocommerce'),
		__('Hamdan Bin Mohammed St', 'states-cities-and-places-for-woocommerce'),
		__('Jazeerat Al Shelaylah', 'states-cities-and-places-for-woocommerce'),
		__('Bawabat Abu Dhabi', 'states-cities-and-places-for-woocommerce'),
		__('Alriffa Ave', 'states-cities-and-places-for-woocommerce'),
		__('Al Zahiyah', 'states-cities-and-places-for-woocommerce'),
		__('Al Ain Tower', 'states-cities-and-places-for-woocommerce'),
		__('Mahwi', 'states-cities-and-places-for-woocommerce')
	),
	'ALN' => array(
		__('Al Bateen', 'states-cities-and-places-for-woocommerce'),
		__('Um Ghafah', 'states-cities-and-places-for-woocommerce'),
		__('Al Neyadat', 'states-cities-and-places-for-woocommerce'),
		__('Al Jahili', 'states-cities-and-places-for-woocommerce'),
		__('Al Mutarid', 'states-cities-and-places-for-woocommerce'),
		__('Al Jimi', 'states-cities-and-places-for-woocommerce'),
		__('Al Fouah', 'states-cities-and-places-for-woocommerce'),
		__('Al Maqam', 'states-cities-and-places-for-woocommerce'),
		__('Industrial Area', 'states-cities-and-places-for-woocommerce'),
		__('Al Khabaisi', 'states-cities-and-places-for-woocommerce'),
		__('Al Tiwayyah', 'states-cities-and-places-for-woocommerce'),
		__('Falaj Hazzaa', 'states-cities-and-places-for-woocommerce'),
		__('Al Markhaniyyah', 'states-cities-and-places-for-woocommerce'),
		__('Al Murabaa', 'states-cities-and-places-for-woocommerce'),
		__('Kuwaitat', 'states-cities-and-places-for-woocommerce'),
		__('Mazyad', 'states-cities-and-places-for-woocommerce'),
		__('Al Sarouj', 'states-cities-and-places-for-woocommerce'),
		__('Basrah', 'states-cities-and-places-for-woocommerce'),
		__('Al Masoudi Kindergarden', 'states-cities-and-places-for-woocommerce'),
		__('Al Hili', 'states-cities-and-places-for-woocommerce'),
		__('Al Manase', 'states-cities-and-places-for-woocommerce'),
		__('Tawam', 'states-cities-and-places-for-woocommerce'),
		__('Al Nabbagh', 'states-cities-and-places-for-woocommerce'),
		__('Abu Samrah', 'states-cities-and-places-for-woocommerce'),
		__('Zakhir', 'states-cities-and-places-for-woocommerce'),
		__('Al Hiyar', 'states-cities-and-places-for-woocommerce'),
		__('Sweihan', 'states-cities-and-places-for-woocommerce'),
		__('Nahil', 'states-cities-and-places-for-woocommerce'),
		__('Al Yahar', 'states-cities-and-places-for-woocommerce'),
		__('Al Dhahir', 'states-cities-and-places-for-woocommerce'),
		__('Neima', 'states-cities-and-places-for-woocommerce'),
		__('Al Shuiaba', 'states-cities-and-places-for-woocommerce'),
		__('Ramalat Zakher', 'states-cities-and-places-for-woocommerce'),
		__('Al Wiqan', 'states-cities-and-places-for-woocommerce'),
		__('Rumah', 'states-cities-and-places-for-woocommerce'),
		__('Asharij', 'states-cities-and-places-for-woocommerce'),
		__('Al Shiwayb', 'states-cities-and-places-for-woocommerce'),
		__('Al Salamat', 'states-cities-and-places-for-woocommerce'),
		__('Al Tiwayyah', 'states-cities-and-places-for-woocommerce'),
		__('Al Rawdah Al Sharqiyah', 'states-cities-and-places-for-woocommerce'),
		__('Bawadi', 'states-cities-and-places-for-woocommerce'),
		__('North Sea', 'states-cities-and-places-for-woocommerce'),
		__('Mirbah', 'states-cities-and-places-for-woocommerce'),
		__('Oasis', 'states-cities-and-places-for-woocommerce'),
		__('Civil Defence', 'states-cities-and-places-for-woocommerce'),
		__('Alswaib', 'states-cities-and-places-for-woocommerce'),
		__('Shiaab Al Ashkhar', 'states-cities-and-places-for-woocommerce'),
		__('Nasiriyah', 'states-cities-and-places-for-woocommerce'),
		__('Al Khaznah', 'states-cities-and-places-for-woocommerce'),
		__('Al Attarah', 'states-cities-and-places-for-woocommerce'),
		__('Al Sad', 'states-cities-and-places-for-woocommerce'),
		__('Al Qattarah', 'states-cities-and-places-for-woocommerce'),
		__('Al Salamat', 'states-cities-and-places-for-woocommerce'),
		__('Ghireebah', 'states-cities-and-places-for-woocommerce'),
		__('Oud Al Touba', 'states-cities-and-places-for-woocommerce'),
		__('Al Khalidiyah', 'states-cities-and-places-for-woocommerce')
	),
	'WRN' => array(
		__('Al Sila', 'states-cities-and-places-for-woocommerce'),
		__('Al Ruwais', 'states-cities-and-places-for-woocommerce'),
		__('Zayed City', 'states-cities-and-places-for-woocommerce'),
		__('Madinat Al Salam', 'states-cities-and-places-for-woocommerce'),
		__('Bada Zayed', 'states-cities-and-places-for-woocommerce'),
		__('Bad Al Mutawah', 'states-cities-and-places-for-woocommerce'),
		__('Ghiyathi', 'states-cities-and-places-for-woocommerce'),
		__('Liwa', 'states-cities-and-places-for-woocommerce')
	),
	'AAR' => array(
		__('Al Qoua', 'states-cities-and-places-for-woocommerce'),
		__('Al Wiqan', 'states-cities-and-places-for-woocommerce'),
		__('Al Dhahrah', 'states-cities-and-places-for-woocommerce'),
		__('Bu Kirayyah', 'states-cities-and-places-for-woocommerce'),
		__('Al Khaznah', 'states-cities-and-places-for-woocommerce'),
		__('Al Khtam', 'states-cities-and-places-for-woocommerce'),
		__('Rumah', 'states-cities-and-places-for-woocommerce'),
		__('Sweihan', 'states-cities-and-places-for-woocommerce'),
		__('Abu Samrah', 'states-cities-and-places-for-woocommerce'),
		__('Margham', 'states-cities-and-places-for-woocommerce'),
		__('Al Sad', 'states-cities-and-places-for-woocommerce'),
		__('Mazyad', 'states-cities-and-places-for-woocommerce')
	),
	'HTA' => array(
		__('Hatta', 'states-cities-and-places-for-woocommerce'),
		__('Al Madam', 'states-cities-and-places-for-woocommerce'),
		__('Huwaylat', 'states-cities-and-places-for-woocommerce'),
		__('Masfut', 'states-cities-and-places-for-woocommerce'),
		__('Nizwa', 'states-cities-and-places-for-woocommerce'),
		__('Wadi Al Qour', 'states-cities-and-places-for-woocommerce'),
		__('Al Manaie', 'states-cities-and-places-for-woocommerce'),
		__('Hatta Hill Park', 'states-cities-and-places-for-woocommerce'),
		__('Muzairah', 'states-cities-and-places-for-woocommerce')
	),
	'SHJ' => array(
		__('Al Khan', 'states-cities-and-places-for-woocommerce'),
		__('Al Dhaid', 'states-cities-and-places-for-woocommerce'),
		__('Khor Fakkan', 'states-cities-and-places-for-woocommerce'),
		__('Buteena', 'states-cities-and-places-for-woocommerce'),
		__('Al Azra', 'states-cities-and-places-for-woocommerce'),
		__('Al Falaj', 'states-cities-and-places-for-woocommerce'),
		__('Al Ghubaiba', 'states-cities-and-places-for-woocommerce'),
		__('Al Quoz', 'states-cities-and-places-for-woocommerce'),
		__('Al Jazzat', 'states-cities-and-places-for-woocommerce'),
		__('Al Khalidiyah', 'states-cities-and-places-for-woocommerce'),
		__('Al Layyeh Suburb', 'states-cities-and-places-for-woocommerce'),
		__('Al Majaz', 'states-cities-and-places-for-woocommerce'),
		__('Mansoura', 'states-cities-and-places-for-woocommerce'),
		__('AL Mirgab', 'states-cities-and-places-for-woocommerce'),
		__('Al Nahda', 'states-cities-and-places-for-woocommerce'),
		__('Nasiriyah', 'states-cities-and-places-for-woocommerce'),
		__('Al Nekhailat', 'states-cities-and-places-for-woocommerce'),
		__('Al Qadisiya', 'states-cities-and-places-for-woocommerce'),
		__('Al Ramlah', 'states-cities-and-places-for-woocommerce'),
		__('Defence', 'states-cities-and-places-for-woocommerce'),
		__('Al Sabkha', 'states-cities-and-places-for-woocommerce'),
		__('Al Talaa', 'states-cities-and-places-for-woocommerce'),
		__('Al Yarmook', 'states-cities-and-places-for-woocommerce'),
		__('Dasman', 'states-cities-and-places-for-woocommerce'),
		__('Al Yash', 'states-cities-and-places-for-woocommerce'),
		__('Maleha', 'states-cities-and-places-for-woocommerce'),
		__('Muwafjah', 'states-cities-and-places-for-woocommerce'),
		__('Muwailih Commercial', 'states-cities-and-places-for-woocommerce'),
		__('University of Sharjah', 'states-cities-and-places-for-woocommerce'),
		__('Sharqan', 'states-cities-and-places-for-woocommerce'),
		__('Al Gharayen', 'states-cities-and-places-for-woocommerce'),
		__('Al Noaf', 'states-cities-and-places-for-woocommerce'),
		__('Sharjah International Airport', 'states-cities-and-places-for-woocommerce'),
		__('Al Sajaa', 'states-cities-and-places-for-woocommerce'),
		__('Dibba Al Hisn', 'states-cities-and-places-for-woocommerce'),
		__('Al Taawun', 'states-cities-and-places-for-woocommerce'),
		__('Al Rafeea', 'states-cities-and-places-for-woocommerce'),
		__('Tarfana', 'states-cities-and-places-for-woocommerce'),
		__('Kalba', 'states-cities-and-places-for-woocommerce'),
		__('Al Shahba', 'states-cities-and-places-for-woocommerce'),
		__('Al Atain', 'states-cities-and-places-for-woocommerce'),
		__('Al Khezamia', 'states-cities-and-places-for-woocommerce'),
		__('Wasit St', 'states-cities-and-places-for-woocommerce'),
		__('Minazif', 'states-cities-and-places-for-woocommerce'),
		__('Al Rahmaniya', 'states-cities-and-places-for-woocommerce'),
		__('Al Ramtha', 'states-cities-and-places-for-woocommerce')
	),
	'FUJ' => array(
		__('Al Faisal', 'states-cities-and-places-for-woocommerce'),
		__('Chamber', 'states-cities-and-places-for-woocommerce'),
		__('Dibba Al Fujairah', 'states-cities-and-places-for-woocommerce'),
		__('Thaiba', 'states-cities-and-places-for-woocommerce'),
		__('Habheb', 'states-cities-and-places-for-woocommerce'),
		__('Mirbah', 'states-cities-and-places-for-woocommerce'),
		__('Wadi Al seder', 'states-cities-and-places-for-woocommerce'),
		__('Wadi Siji', 'states-cities-and-places-for-woocommerce'),
		__('Qidfa', 'states-cities-and-places-for-woocommerce'),
		__('Al Bidya', 'states-cities-and-places-for-woocommerce'),
		__('Tawyeen', 'states-cities-and-places-for-woocommerce'),
		__('Al Qurayya', 'states-cities-and-places-for-woocommerce'),
		__('Sharm', 'states-cities-and-places-for-woocommerce'),
		__('Dhadna', 'states-cities-and-places-for-woocommerce'),
		__('Rul Dhadna', 'states-cities-and-places-for-woocommerce'),
		__('Al Aqah', 'states-cities-and-places-for-woocommerce'),
		__('Masafi Al Fujairah', 'states-cities-and-places-for-woocommerce'),
		__('Al Bithnah', 'states-cities-and-places-for-woocommerce'),
		__('Al Hayl', 'states-cities-and-places-for-woocommerce'),
		__('Al Farfar', 'states-cities-and-places-for-woocommerce'),
		__('Wadi Saham', 'states-cities-and-places-for-woocommerce'),
		__('Al Halah', 'states-cities-and-places-for-woocommerce'),
		__('Wahla Fort', 'states-cities-and-places-for-woocommerce'),
		__('Sakamkam', 'states-cities-and-places-for-woocommerce'),
		__('Murshid', 'states-cities-and-places-for-woocommerce'),
		__('Sifuni', 'states-cities-and-places-for-woocommerce'),
		__('Madhab', 'states-cities-and-places-for-woocommerce')
	),
	'AJM' => array(
		__('Masfut', 'states-cities-and-places-for-woocommerce'),
		__('Manama', 'states-cities-and-places-for-woocommerce'),
		__('Al Helio', 'states-cities-and-places-for-woocommerce'),
		__('Al Bustan', 'states-cities-and-places-for-woocommerce'),
		__('Al Rumailah', 'states-cities-and-places-for-woocommerce'),
		__('Nuaimiya', 'states-cities-and-places-for-woocommerce'),
		__('Al Karama', 'states-cities-and-places-for-woocommerce'),
		__('Al Rashidiya', 'states-cities-and-places-for-woocommerce'),
		__('Al Muwaihat', 'states-cities-and-places-for-woocommerce'),
		__('Hamidiya', 'states-cities-and-places-for-woocommerce'),
		__('Jurf', 'states-cities-and-places-for-woocommerce'),
		__('Al Raqaib', 'states-cities-and-places-for-woocommerce'),
		__('Meshairef', 'states-cities-and-places-for-woocommerce'),
		__('Al Rawda', 'states-cities-and-places-for-woocommerce'),
		__('Al Swan', 'states-cities-and-places-for-woocommerce'),
		__('Old Industrial Area', 'states-cities-and-places-for-woocommerce'),
		__('New Industrial Area', 'states-cities-and-places-for-woocommerce'),
		__('Al Bahia', 'states-cities-and-places-for-woocommerce')
	),
	'RAK' => array(
		__('Khor Khuwaier', 'states-cities-and-places-for-woocommerce'),
		__('Ghalilah', 'states-cities-and-places-for-woocommerce'),
		__('Huwaylat', 'states-cities-and-places-for-woocommerce'),
		__('Al Jolan', 'states-cities-and-places-for-woocommerce'),
		__('Al Sharisha', 'states-cities-and-places-for-woocommerce'),
		__('Julphar', 'states-cities-and-places-for-woocommerce'),
		__('Al Mairid', 'states-cities-and-places-for-woocommerce'),
		__('Al Nakheel', 'states-cities-and-places-for-woocommerce'),
		__('Ghailan', 'states-cities-and-places-for-woocommerce'),
		__('Seih Al Harf', 'states-cities-and-places-for-woocommerce'),
		__('Wadi Al Qour', 'states-cities-and-places-for-woocommerce'),
		__('Wadi Al Ejili', 'states-cities-and-places-for-woocommerce'),
		__('Khuzam', 'states-cities-and-places-for-woocommerce'),
		__('Al Dhait', 'states-cities-and-places-for-woocommerce'),
		__('Al Kharran', 'states-cities-and-places-for-woocommerce'),
		__('Al Hayl', 'states-cities-and-places-for-woocommerce'),
		__('Al Mamurah', 'states-cities-and-places-for-woocommerce'),
		__('Al Ghubb', 'states-cities-and-places-for-woocommerce'),
		__('Al jeer', 'states-cities-and-places-for-woocommerce'),
		__('Shamal', 'states-cities-and-places-for-woocommerce'),
		__('Shaam', 'states-cities-and-places-for-woocommerce'),
		__('Al Rams', 'states-cities-and-places-for-woocommerce'),
		__('Al Digdaagah', 'states-cities-and-places-for-woocommerce'),
		__('Al Fahlain', 'states-cities-and-places-for-woocommerce'),
		__('Khatt', 'states-cities-and-places-for-woocommerce'),
		__('Adhen Village', 'states-cities-and-places-for-woocommerce'),
		__('Al Ghail', 'states-cities-and-places-for-woocommerce'),
		__('Wadi Kub', 'states-cities-and-places-for-woocommerce'),
		__('Masafi', 'states-cities-and-places-for-woocommerce'),
		__('Dfatta', 'states-cities-and-places-for-woocommerce'),
		__('Asimah', 'states-cities-and-places-for-woocommerce'),
		__('Sifuni', 'states-cities-and-places-for-woocommerce'),
		__('Shawkah', 'states-cities-and-places-for-woocommerce'),
		__('Al Manaie', 'states-cities-and-places-for-woocommerce'),
		__('Wadi Shaam', 'states-cities-and-places-for-woocommerce'),
		__('Al Zaab', 'states-cities-and-places-for-woocommerce'),
		__('Seih Al Burairat', 'states-cities-and-places-for-woocommerce'),
		__('Qudra', 'states-cities-and-places-for-woocommerce'),
		__('Airj', 'states-cities-and-places-for-woocommerce'),
		__('Al Jazirah Al Hamra', 'states-cities-and-places-for-woocommerce'),
		__('Al Hamraniyah', 'states-cities-and-places-for-woocommerce'),
		__('Al Uraibi', 'states-cities-and-places-for-woocommerce'),
		__('Alyanabee', 'states-cities-and-places-for-woocommerce')
	),
	'UAQ' => array(
		__('Falaj Al Mualla', 'states-cities-and-places-for-woocommerce'),
		__('Al Salamah', 'states-cities-and-places-for-woocommerce'),
		__('Al Sweihat', 'states-cities-and-places-for-woocommerce'),
		__('Ramla', 'states-cities-and-places-for-woocommerce'),
		__('Al Rashidiya', 'states-cities-and-places-for-woocommerce'),
		__('Mohammed Bin Rashid', 'states-cities-and-places-for-woocommerce'),
		__('Al Dar Al Baida', 'states-cities-and-places-for-woocommerce')
	),
);

// Use this filter to handle the Localities of United Arab Emirates
$places['AE'] = apply_filters('scpwoo_custom_places_ae', $places['AE']);
