<?php

/**
 * Cities of Bangladesh
 * - 1035 cities
 *
 * @author   S.M. Mehdi Akram <mehdi@royaltechbd.com> | https://www.royaltechbd.com
 * @version  1.0.0
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 */

global $places;

$places['BD'] = array(
	'dhaka' => array(
		__('12 Tala', 'states-cities-and-places-for-woocommerce'),
		__('Aam Bagan', 'states-cities-and-places-for-woocommerce'),
		__('Abdullah Bag', 'states-cities-and-places-for-woocommerce'),
		__('Abujar Bafari Gali', 'states-cities-and-places-for-woocommerce'),
		__('Abul Hotel', 'states-cities-and-places-for-woocommerce'),
		__('Addin Hospital', 'states-cities-and-places-for-woocommerce'),
		__('Adorsho Nagor', 'states-cities-and-places-for-woocommerce'),
		__('Aftab Nagor Block A To G', 'states-cities-and-places-for-woocommerce'),
		__('Agora', 'states-cities-and-places-for-woocommerce'),
		__('Alen Bari', 'states-cities-and-places-for-woocommerce'),
		__('Arambag', 'states-cities-and-places-for-woocommerce'),
		__('Arjot Para', 'states-cities-and-places-for-woocommerce'),
		__('Ashalota, Bonolota', 'states-cities-and-places-for-woocommerce'),
		__('Aurongojeb Road', 'states-cities-and-places-for-woocommerce'),
		__('Baf Shaheen College/Jahangir Gate', 'states-cities-and-places-for-woocommerce'),
		__('Baganbari', 'states-cities-and-places-for-woocommerce'),
		__('Banani ', 'states-cities-and-places-for-woocommerce'),
		__('Banani 1', 'states-cities-and-places-for-woocommerce'),
		__('Banani 11', 'states-cities-and-places-for-woocommerce'),
		__('Banani 17', 'states-cities-and-places-for-woocommerce'),
		__('Banani 2', 'states-cities-and-places-for-woocommerce'),
		__('Banani 21', 'states-cities-and-places-for-woocommerce'),
		__('Banani 23', 'states-cities-and-places-for-woocommerce'),
		__('Banani 27', 'states-cities-and-places-for-woocommerce'),
		__('Banani 8', 'states-cities-and-places-for-woocommerce'),
		__('Banani Chairman Bari', 'states-cities-and-places-for-woocommerce'),
		__('Banani Dohs', 'states-cities-and-places-for-woocommerce'),
		__('Bangshal', 'states-cities-and-places-for-woocommerce'),
		__('Bashtola', 'states-cities-and-places-for-woocommerce'),
		__('Bashundhara Block  A To L', 'states-cities-and-places-for-woocommerce'),
		__('Bata Gali', 'states-cities-and-places-for-woocommerce'),
		__('Begun Bari ', 'states-cities-and-places-for-woocommerce'),
		__('Bepari Gali', 'states-cities-and-places-for-woocommerce'),
		__('Bg Press', 'states-cities-and-places-for-woocommerce'),
		__('Bhauya Para', 'states-cities-and-places-for-woocommerce'),
		__('Biam Auditorium', 'states-cities-and-places-for-woocommerce'),
		__('Bibirbagicha', 'states-cities-and-places-for-woocommerce'),
		__('Bongsal', 'states-cities-and-places-for-woocommerce'),
		__('Dhoar', 'states-cities-and-places-for-woocommerce'),
		__('Boro Moghbazar', 'states-cities-and-places-for-woocommerce'),
		__('Center Point', 'states-cities-and-places-for-woocommerce'),
		__('Chairman Gali', 'states-cities-and-places-for-woocommerce'),
		__('Channel 24', 'states-cities-and-places-for-woocommerce'),
		__('Christian Para', 'states-cities-and-places-for-woocommerce'),
		__('Cid Office', 'states-cities-and-places-for-woocommerce'),
		__('Comilla Para', 'states-cities-and-places-for-woocommerce'),
		__('Dalibari Kachabazar', 'states-cities-and-places-for-woocommerce'),
		__('Demra', 'states-cities-and-places-for-woocommerce'),
		__('Dillu Road', 'states-cities-and-places-for-woocommerce'),
		__('Diplomatic Zone', 'states-cities-and-places-for-woocommerce'),
		__('Dit Project', 'states-cities-and-places-for-woocommerce'),
		__('Dnc Staff Quarter', 'states-cities-and-places-for-woocommerce'),
		__('Doctor Goli', 'states-cities-and-places-for-woocommerce'),
		__('Dokkhin Para', 'states-cities-and-places-for-woocommerce'),
		__('East Goran', 'states-cities-and-places-for-woocommerce'),
		__('East Nakhal Para', 'states-cities-and-places-for-woocommerce'),
		__('East Noyatola', 'states-cities-and-places-for-woocommerce'),
		__('East Rumpura', 'states-cities-and-places-for-woocommerce'),
		__('Eskaton', 'states-cities-and-places-for-woocommerce'),
		__('Fasertake', 'states-cities-and-places-for-woocommerce'),
		__('Gm Bari', 'states-cities-and-places-for-woocommerce'),
		__('Goran', 'states-cities-and-places-for-woocommerce'),
		__('Graveyard Road', 'states-cities-and-places-for-woocommerce'),
		__('Green Way', 'states-cities-and-places-for-woocommerce'),
		__('Gudara Ghat', 'states-cities-and-places-for-woocommerce'),
		__('Old Dhaka', 'states-cities-and-places-for-woocommerce'),
		__('Gulbag', 'states-cities-and-places-for-woocommerce'),
		__('Gulshan', 'states-cities-and-places-for-woocommerce'),
		__('Gulshan 1', 'states-cities-and-places-for-woocommerce'),
		__('Gulshan 2', 'states-cities-and-places-for-woocommerce'),
		__('Gulshan Arong', 'states-cities-and-places-for-woocommerce'),
		__('Gulshan Avenue', 'states-cities-and-places-for-woocommerce'),
		__('Gupi Para', 'states-cities-and-places-for-woocommerce'),
		__('Hazari Bari', 'states-cities-and-places-for-woocommerce'),
		__('Imam Bag', 'states-cities-and-places-for-woocommerce'),
		__('Jagonnath Pur', 'states-cities-and-places-for-woocommerce'),
		__('Jourshara And Lichu Bagan', 'states-cities-and-places-for-woocommerce'),
		__('Jurain', 'states-cities-and-places-for-woocommerce'),
		__('Kajla', 'states-cities-and-places-for-woocommerce'),
		__('Kakoli', 'states-cities-and-places-for-woocommerce'),
		__('Kalachad Pur And Norda', 'states-cities-and-places-for-woocommerce'),
		__('Kazi Office R Gali', 'states-cities-and-places-for-woocommerce'),
		__('Kemal Ataturk Avenue', 'states-cities-and-places-for-woocommerce'),
		__('Khilbarir Take', 'states-cities-and-places-for-woocommerce'),
		__('Khilgaon', 'states-cities-and-places-for-woocommerce'),
		__('Khilgaon Block A', 'states-cities-and-places-for-woocommerce'),
		__('Khilgaon Block B', 'states-cities-and-places-for-woocommerce'),
		__('Khilgaon Block C', 'states-cities-and-places-for-woocommerce'),
		__('Krishi Market', 'states-cities-and-places-for-woocommerce'),
		__('Kuni Para', 'states-cities-and-places-for-woocommerce'),
		__('Kunipara', 'states-cities-and-places-for-woocommerce'),
		__('Kuril Bisso Road', 'states-cities-and-places-for-woocommerce'),
		__('Kuril Chaurasta', 'states-cities-and-places-for-woocommerce'),
		__('Kuril Ghatpar', 'states-cities-and-places-for-woocommerce'),
		__('Lalbag', 'states-cities-and-places-for-woocommerce'),
		__('Lalmatia', 'states-cities-and-places-for-woocommerce'),
		__('Link Road', 'states-cities-and-places-for-woocommerce'),
		__('Lukaser Mor', 'states-cities-and-places-for-woocommerce'),
		__('Maasranga Television', 'states-cities-and-places-for-woocommerce'),
		__('Mailbag 1st Line', 'states-cities-and-places-for-woocommerce'),
		__('Malibag', 'states-cities-and-places-for-woocommerce'),
		__('Malibag Chowdhuripara', 'states-cities-and-places-for-woocommerce'),
		__('Malitola', 'states-cities-and-places-for-woocommerce'),
		__('Marul Badda', 'states-cities-and-places-for-woocommerce'),
		__('Mirbag', 'states-cities-and-places-for-woocommerce'),
		__('Mogbazar', 'states-cities-and-places-for-woocommerce'),
		__('Mohakhali Bus Terminal', 'states-cities-and-places-for-woocommerce'),
		__('Mohammadia Housing Limited', 'states-cities-and-places-for-woocommerce'),
		__('Mohammadia Housing Ltd', 'states-cities-and-places-for-woocommerce'),
		__('Mohammadpur', 'states-cities-and-places-for-woocommerce'),
		__('Mohanagor Project', 'states-cities-and-places-for-woocommerce'),
		__('Moinar Bag', 'states-cities-and-places-for-woocommerce'),
		__('Monipuripara', 'states-cities-and-places-for-woocommerce'),
		__('Motijheel', 'states-cities-and-places-for-woocommerce'),
		__('Mouchak', 'states-cities-and-places-for-woocommerce'),
		__('Navy Headquarters', 'states-cities-and-places-for-woocommerce'),
		__('Nazimuddir Road', 'states-cities-and-places-for-woocommerce'),
		__('Newmarket', 'states-cities-and-places-for-woocommerce'),
		__('Nijhum Officers Quarters', 'states-cities-and-places-for-woocommerce'),
		__('Niketon', 'states-cities-and-places-for-woocommerce'),
		__('Nobin Bag', 'states-cities-and-places-for-woocommerce'),
		__('Nobodoy Housing Ltd', 'states-cities-and-places-for-woocommerce'),
		__('North Goran', 'states-cities-and-places-for-woocommerce'),
		__('Notun Bag', 'states-cities-and-places-for-woocommerce'),
		__('Nurjahan Road', 'states-cities-and-places-for-woocommerce'),
		__('Paglamajar Gali', 'states-cities-and-places-for-woocommerce'),
		__('Pakistan Embassy', 'states-cities-and-places-for-woocommerce'),
		__('Panthapath', 'states-cities-and-places-for-woocommerce'),
		__('Pc Culture Housing', 'states-cities-and-places-for-woocommerce'),
		__('Police Plaza', 'states-cities-and-places-for-woocommerce'),
		__('Post Office Road', 'states-cities-and-places-for-woocommerce'),
		__('Postogola', 'states-cities-and-places-for-woocommerce'),
		__('Prime Minister Office', 'states-cities-and-places-for-woocommerce'),
		__('Prodan Muntri Karjaloy', 'states-cities-and-places-for-woocommerce'),
		__('Provati Bag', 'states-cities-and-places-for-woocommerce'),
		__('Purba Anchol Road', 'states-cities-and-places-for-woocommerce'),
		__('Qatwali', 'states-cities-and-places-for-woocommerce'),
		__('Radisson Water Blu Hotel', 'states-cities-and-places-for-woocommerce'),
		__('Rajabazar', 'states-cities-and-places-for-woocommerce'),
		__('Rampura Banassre', 'states-cities-and-places-for-woocommerce'),
		__('Rampura Bazar', 'states-cities-and-places-for-woocommerce'),
		__('Rampura Hazipara', 'states-cities-and-places-for-woocommerce'),
		__('Rangs Vaban', 'states-cities-and-places-for-woocommerce'),
		__('Razia Sultana Road', 'states-cities-and-places-for-woocommerce'),
		__('Riaz Bag', 'states-cities-and-places-for-woocommerce'),
		__('Roma Century ', 'states-cities-and-places-for-woocommerce'),
		__('Rosulbag', 'states-cities-and-places-for-woocommerce'),
		__('Sadhinata Tower', 'states-cities-and-places-for-woocommerce'),
		__('Santibag', 'states-cities-and-places-for-woocommerce'),
		__('Satrasta', 'states-cities-and-places-for-woocommerce'),
		__('Satta Gali', 'states-cities-and-places-for-woocommerce'),
		__('Sayed Nagor', 'states-cities-and-places-for-woocommerce'),
		__('Shadhinota Sharoni', 'states-cities-and-places-for-woocommerce'),
		__('Shahbag', 'states-cities-and-places-for-woocommerce'),
		__('Shahidbag', 'states-cities-and-places-for-woocommerce'),
		__('Shankar', 'states-cities-and-places-for-woocommerce'),
		__('Shanti Niketon', 'states-cities-and-places-for-woocommerce'),
		__('Shatar Kul', 'states-cities-and-places-for-woocommerce'),
		__('Shekerteak', 'states-cities-and-places-for-woocommerce'),
		__('Sheron Bag', 'states-cities-and-places-for-woocommerce'),
		__('Shersah Suri Road', 'states-cities-and-places-for-woocommerce'),
		__('Shubastu Najor Velly', 'states-cities-and-places-for-woocommerce'),
		__('Shyamoli', 'states-cities-and-places-for-woocommerce'),
		__('Siddiq Master Dhal', 'states-cities-and-places-for-woocommerce'),
		__('Sipahi Bag', 'states-cities-and-places-for-woocommerce'),
		__('Sismohol', 'states-cities-and-places-for-woocommerce'),
		__('Soilmaid', 'states-cities-and-places-for-woocommerce'),
		__('Soinik Club', 'states-cities-and-places-for-woocommerce'),
		__('South Badda', 'states-cities-and-places-for-woocommerce'),
		__('South Banassre', 'states-cities-and-places-for-woocommerce'),
		__('South Goran', 'states-cities-and-places-for-woocommerce'),
		__('Sukrabad', 'states-cities-and-places-for-woocommerce'),
		__('Sur Soyad Road', 'states-cities-and-places-for-woocommerce'),
		__('T&T Colony', 'states-cities-and-places-for-woocommerce'),
		__('T&T Gali', 'states-cities-and-places-for-woocommerce'),
		__('Tajmahal Road', 'states-cities-and-places-for-woocommerce'),
		__('Taltola', 'states-cities-and-places-for-woocommerce'),
		__('Tejgaon Industrial Area', 'states-cities-and-places-for-woocommerce'),
		__('Tejgaon Link Road', 'states-cities-and-places-for-woocommerce'),
		__('Tejgaon Truck Stand', 'states-cities-and-places-for-woocommerce'),
		__('Tibet', 'states-cities-and-places-for-woocommerce'),
		__('Town Hall', 'states-cities-and-places-for-woocommerce'),
		__('Truck Stand', 'states-cities-and-places-for-woocommerce'),
		__('United Hospital ', 'states-cities-and-places-for-woocommerce'),
		__('Uttorpara', 'states-cities-and-places-for-woocommerce'),
		__('Vatara', 'states-cities-and-places-for-woocommerce'),
		__('Vodro Gali', 'states-cities-and-places-for-woocommerce'),
		__('Vootergoli', 'states-cities-and-places-for-woocommerce'),
		__('West Mailbag', 'states-cities-and-places-for-woocommerce'),
		__('West Nakhal Para', 'states-cities-and-places-for-woocommerce'),
		__('West Panthapath', 'states-cities-and-places-for-woocommerce'),
		__('West Rumpura', 'states-cities-and-places-for-woocommerce'),
		__('Wreless Gate', 'states-cities-and-places-for-woocommerce'),
		__('Zigatala', 'states-cities-and-places-for-woocommerce'),
		__('Baridhara', 'states-cities-and-places-for-woocommerce'),
		__('Rampura', 'states-cities-and-places-for-woocommerce'),
		__('Banasree', 'states-cities-and-places-for-woocommerce'),
		__('Bashabo', 'states-cities-and-places-for-woocommerce'),
		__('Moghbazar', 'states-cities-and-places-for-woocommerce'),
		__('Tejgaon', 'states-cities-and-places-for-woocommerce'),
		__('Mohakhali', 'states-cities-and-places-for-woocommerce'),
		__('Mohakhali Dohs', 'states-cities-and-places-for-woocommerce'),
		__('Banani', 'states-cities-and-places-for-woocommerce'),
		__('Bashundhara R/A', 'states-cities-and-places-for-woocommerce'),
		__('Notun Bazar', 'states-cities-and-places-for-woocommerce'),
		__('Shahjadpur', 'states-cities-and-places-for-woocommerce'),
		__('Norda', 'states-cities-and-places-for-woocommerce'),
		__('Nakhalpara', 'states-cities-and-places-for-woocommerce'),
		__('Farmgate', 'states-cities-and-places-for-woocommerce'),
		__('Azimpur', 'states-cities-and-places-for-woocommerce'),
		__('Dhaka University', 'states-cities-and-places-for-woocommerce'),
		__('Kalabagan', 'states-cities-and-places-for-woocommerce'),
		__('Elephant Road', 'states-cities-and-places-for-woocommerce'),
		__('Asad Gate', 'states-cities-and-places-for-woocommerce'),
		__('Hazaribag', 'states-cities-and-places-for-woocommerce'),
		__('Adabar', 'states-cities-and-places-for-woocommerce'),
		__('Chankharpul', 'states-cities-and-places-for-woocommerce'),
		__('Nazimuddin Road', 'states-cities-and-places-for-woocommerce'),
		__('Kamrangirchor', 'states-cities-and-places-for-woocommerce'),
		__('Jatrabari', 'states-cities-and-places-for-woocommerce'),
		__('Shantinagar', 'states-cities-and-places-for-woocommerce'),
		__('Mugdapara', 'states-cities-and-places-for-woocommerce'),
		__('Chakbazar', 'states-cities-and-places-for-woocommerce'),
		__('Maniknagar', 'states-cities-and-places-for-woocommerce'),
		__('Kamalapur', 'states-cities-and-places-for-woocommerce'),
		__('Golapbag', 'states-cities-and-places-for-woocommerce'),
		__('Paltan', 'states-cities-and-places-for-woocommerce'),
		__('Gopibag', 'states-cities-and-places-for-woocommerce'),
		__('Kakrail', 'states-cities-and-places-for-woocommerce'),
		__('Tikatuli', 'states-cities-and-places-for-woocommerce'),
		__('Shonir Akhra', 'states-cities-and-places-for-woocommerce'),
		__('Gendaria', 'states-cities-and-places-for-woocommerce'),
		__('Mirpur', 'states-cities-and-places-for-woocommerce'),
		__('Mirpur 1', 'states-cities-and-places-for-woocommerce'),
		__('Mirpur 2', 'states-cities-and-places-for-woocommerce'),
		__('Mirpur 6', 'states-cities-and-places-for-woocommerce'),
		__('Mirpur 7', 'states-cities-and-places-for-woocommerce'),
		__('Mirpur 11', 'states-cities-and-places-for-woocommerce'),
		__('Mirpur 12', 'states-cities-and-places-for-woocommerce'),
		__('Mirpur Dohs', 'states-cities-and-places-for-woocommerce'),
		__('Mirpur 10', 'states-cities-and-places-for-woocommerce'),
		__('Mirpur 13', 'states-cities-and-places-for-woocommerce'),
		__('Mirpur 14', 'states-cities-and-places-for-woocommerce'),
		__('Kalshi', 'states-cities-and-places-for-woocommerce'),
		__('Agargaon', 'states-cities-and-places-for-woocommerce'),
		__('Shewrapara', 'states-cities-and-places-for-woocommerce'),
		__('Kazipara', 'states-cities-and-places-for-woocommerce'),
		__('Mirpur Cantonment', 'states-cities-and-places-for-woocommerce'),
		__('Kallaynnpur', 'states-cities-and-places-for-woocommerce'),
		__('Darus Salam', 'states-cities-and-places-for-woocommerce'),
		__('Azampur', 'states-cities-and-places-for-woocommerce'),
		__('Nikunjo 1', 'states-cities-and-places-for-woocommerce'),
		__('Khilkhet', 'states-cities-and-places-for-woocommerce'),
		__('Uttar Khan/Dakkhin Khan', 'states-cities-and-places-for-woocommerce'),
		__('Kafrul', 'states-cities-and-places-for-woocommerce'),
		__('Baridhara', 'states-cities-and-places-for-woocommerce'),
		__('Baridhara Dohs', 'states-cities-and-places-for-woocommerce'),
		__('Baridhara Block-J', 'states-cities-and-places-for-woocommerce'),
		__('Shajadpur East', 'states-cities-and-places-for-woocommerce'),
		__('Kuril', 'states-cities-and-places-for-woocommerce'),
		__('Shipahibag', 'states-cities-and-places-for-woocommerce'),
		__('Meradia', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi 9a', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi R/A', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi 9', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi 8a', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi 8', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi 1', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi 2', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi 11a', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi 12a', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi 10a', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi 1a', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi 2a', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi 3', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi 4', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi 3a', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi 4a', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi 5a', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi 5', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi 6', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi 6a', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi 7', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi 7a', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi 10', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi 11', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi 12', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi 13', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi 16', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi 13a', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi 14a', 'states-cities-and-places-for-woocommerce'),
		__('Dahnmondi 15a', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi 14', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi 15', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi 27', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi 31', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi 30', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi 32', 'states-cities-and-places-for-woocommerce'),
		__('Green Road', 'states-cities-and-places-for-woocommerce'),
		__('Vasan Tek', 'states-cities-and-places-for-woocommerce'),
		__('Jakir Hussain Road', 'states-cities-and-places-for-woocommerce'),
		__('Senpara', 'states-cities-and-places-for-woocommerce'),
		__('Bais Teki', 'states-cities-and-places-for-woocommerce'),
		__('Kochukhet', 'states-cities-and-places-for-woocommerce'),
		__('Ibrahimpur', 'states-cities-and-places-for-woocommerce'),
		__('Balughat', 'states-cities-and-places-for-woocommerce'),
		__('Matikata', 'states-cities-and-places-for-woocommerce'),
		__('Janata Housing', 'states-cities-and-places-for-woocommerce'),
		__('Eastern Housing', 'states-cities-and-places-for-woocommerce'),
		__('Pallabi', 'states-cities-and-places-for-woocommerce'),
		__('Rupnagor', 'states-cities-and-places-for-woocommerce'),
		__('Ahamedbag', 'states-cities-and-places-for-woocommerce'),
		__('Tolarbag', 'states-cities-and-places-for-woocommerce'),
		__('Ansar Camp', 'states-cities-and-places-for-woocommerce'),
		__('Golarteak', 'states-cities-and-places-for-woocommerce'),
		__('Pirerbag', 'states-cities-and-places-for-woocommerce'),
		__('Paikpara', 'states-cities-and-places-for-woocommerce'),
		__('Mazar Road', 'states-cities-and-places-for-woocommerce'),
		__('Uttara', 'states-cities-and-places-for-woocommerce'),
		__('Uttara Sector 1', 'states-cities-and-places-for-woocommerce'),
		__('Uttara Sector 3', 'states-cities-and-places-for-woocommerce'),
		__('Uttara Sector 4', 'states-cities-and-places-for-woocommerce'),
		__('Uttara Sector 5', 'states-cities-and-places-for-woocommerce'),
		__('Uttara Sector 6', 'states-cities-and-places-for-woocommerce'),
		__('Uttara Sector 8', 'states-cities-and-places-for-woocommerce'),
		__('Uttara Sector 7', 'states-cities-and-places-for-woocommerce'),
		__('Uttara Sector 9', 'states-cities-and-places-for-woocommerce'),
		__('Uttara Sector 10', 'states-cities-and-places-for-woocommerce'),
		__('Uttara Sector 11', 'states-cities-and-places-for-woocommerce'),
		__('Uttara Sector 12', 'states-cities-and-places-for-woocommerce'),
		__('Uttara Sector 13', 'states-cities-and-places-for-woocommerce'),
		__('Uttara Sector 14', 'states-cities-and-places-for-woocommerce'),
		__('Uttara Jasimuddin', 'states-cities-and-places-for-woocommerce'),
		__('Lake City', 'states-cities-and-places-for-woocommerce'),
		__('Ashkona', 'states-cities-and-places-for-woocommerce'),
		__('Nondipara', 'states-cities-and-places-for-woocommerce'),
		__('Wari', 'states-cities-and-places-for-woocommerce'),
		__('Foridabad', 'states-cities-and-places-for-woocommerce'),
		__('Sadarghat', 'states-cities-and-places-for-woocommerce'),
		__('Gulistan', 'states-cities-and-places-for-woocommerce'),
		__('Nawabpur', 'states-cities-and-places-for-woocommerce'),
		__('Lakshmibazar', 'states-cities-and-places-for-woocommerce'),
		__('Shajahanpur', 'states-cities-and-places-for-woocommerce'),
		__('Shutrapur', 'states-cities-and-places-for-woocommerce'),
		__('Fokirapool', 'states-cities-and-places-for-woocommerce'),
		__('Hazipara', 'states-cities-and-places-for-woocommerce'),
		__('Baily Road', 'states-cities-and-places-for-woocommerce'),
		__('Shaheenbag', 'states-cities-and-places-for-woocommerce'),
		__('Rajarbag', 'states-cities-and-places-for-woocommerce'),
		__('Abdullahpur', 'states-cities-and-places-for-woocommerce'),
		__('Mirpur', 'states-cities-and-places-for-woocommerce'),
		__('Badda', 'states-cities-and-places-for-woocommerce'),
		__('Middle Badda', 'states-cities-and-places-for-woocommerce'),
		__('North Badda', 'states-cities-and-places-for-woocommerce'),
		__('Bordhon Bari', 'states-cities-and-places-for-woocommerce'),
		__('West Rampura', 'states-cities-and-places-for-woocommerce'),
		__('Kalachandpur', 'states-cities-and-places-for-woocommerce'),
		__('Nurerchala', 'states-cities-and-places-for-woocommerce'),
		__('Gopipara', 'states-cities-and-places-for-woocommerce'),
		__('Manda', 'states-cities-and-places-for-woocommerce'),
		__('Bongshal', 'states-cities-and-places-for-woocommerce'),
		__('Bashundhara 300ft', 'states-cities-and-places-for-woocommerce'),
		__('Kaderabad Housing', 'states-cities-and-places-for-woocommerce'),
		__('Chan Mia Housing', 'states-cities-and-places-for-woocommerce'),
		__('Mohanogor Project', 'states-cities-and-places-for-woocommerce'),
		__('Dhanmondi 28', 'states-cities-and-places-for-woocommerce'),
		__('Dhaka Housing', 'states-cities-and-places-for-woocommerce'),
		__('Iqbal Road', 'states-cities-and-places-for-woocommerce'),
		__('Asad Avenue', 'states-cities-and-places-for-woocommerce'),
		__('Aziz Mohollah', 'states-cities-and-places-for-woocommerce'),
		__('Babar Road', 'states-cities-and-places-for-woocommerce'),
		__('Old Airport Road', 'states-cities-and-places-for-woocommerce'),
		__('Bfdc Mor', 'states-cities-and-places-for-woocommerce'),
		__('Shahjanpur', 'states-cities-and-places-for-woocommerce'),
		__('Shonargoan', 'states-cities-and-places-for-woocommerce'),
		__('Tejturi Bazar', 'states-cities-and-places-for-woocommerce'),
		__('Kawran Bazar', 'states-cities-and-places-for-woocommerce'),
		__('Fdc', 'states-cities-and-places-for-woocommerce'),
		__('Noyatola', 'states-cities-and-places-for-woocommerce'),
		__('Peyarabag', 'states-cities-and-places-for-woocommerce'),
		__('Pollima', 'states-cities-and-places-for-woocommerce'),
		__('Ansar Camp(Moghbazar)', 'states-cities-and-places-for-woocommerce'),
		__('Khilgaon Taltola', 'states-cities-and-places-for-woocommerce'),
		__('Tilpa Para', 'states-cities-and-places-for-woocommerce'),
		__('Modhubag', 'states-cities-and-places-for-woocommerce'),
		__('Ulon', 'states-cities-and-places-for-woocommerce'),
		__('Aftab Nagar', 'states-cities-and-places-for-woocommerce'),
		__('Shatarkul', 'states-cities-and-places-for-woocommerce'),
		__('Jamuna Future Park', 'states-cities-and-places-for-woocommerce'),
		__('Aziz Sarani', 'states-cities-and-places-for-woocommerce'),
		__('Coca-Cola', 'states-cities-and-places-for-woocommerce'),
		__('Apollo Hospital', 'states-cities-and-places-for-woocommerce'),
		__('Shoinik Club', 'states-cities-and-places-for-woocommerce'),
		__('Bangladesh Betar', 'states-cities-and-places-for-woocommerce'),
		__('Monipur', 'states-cities-and-places-for-woocommerce'),
		__('Sony Cienema Hall', 'states-cities-and-places-for-woocommerce'),
		__('South Bishil', 'states-cities-and-places-for-woocommerce'),
		__('Bangla College', 'states-cities-and-places-for-woocommerce'),
		__('Tolar Bag', 'states-cities-and-places-for-woocommerce'),
		__('Technical', 'states-cities-and-places-for-woocommerce'),
		__('Gabtoli', 'states-cities-and-places-for-woocommerce'),
		__('Nikunjo 2', 'states-cities-and-places-for-woocommerce'),
		__('Namapara', 'states-cities-and-places-for-woocommerce'),
		__('Pink City', 'states-cities-and-places-for-woocommerce'),
		__('Kawla', 'states-cities-and-places-for-woocommerce'),
		__('Airport', 'states-cities-and-places-for-woocommerce'),
		__('Haji Camp', 'states-cities-and-places-for-woocommerce'),
		__('Koshai Bari', 'states-cities-and-places-for-woocommerce'),
		__('Mollar Tek', 'states-cities-and-places-for-woocommerce'),
		__('Prem Bagan', 'states-cities-and-places-for-woocommerce'),
		__('Gawair', 'states-cities-and-places-for-woocommerce'),
		__('Azampur Kacha Bazar', 'states-cities-and-places-for-woocommerce'),
		__('Chalabon', 'states-cities-and-places-for-woocommerce'),
		__('Rajlakhsmi', 'states-cities-and-places-for-woocommerce'),
		__('House Building', 'states-cities-and-places-for-woocommerce'),
		__('Diya Bari', 'states-cities-and-places-for-woocommerce'),
		__('Uttara Residential Model Town', 'states-cities-and-places-for-woocommerce'),
		__('Faydabad', 'states-cities-and-places-for-woocommerce'),
		__('Kamarpara', 'states-cities-and-places-for-woocommerce'),
		__('Baitul Aman Housing', 'states-cities-and-places-for-woocommerce'),
		__('Bashbari', 'states-cities-and-places-for-woocommerce'),
		__('Chand Uddan', 'states-cities-and-places-for-woocommerce'),
		__('Geneva Camp', 'states-cities-and-places-for-woocommerce'),
		__('Humayun Road', 'states-cities-and-places-for-woocommerce'),
		__('Solimullah Road', 'states-cities-and-places-for-woocommerce'),
		__('Sher Shah Suri Road', 'states-cities-and-places-for-woocommerce'),
		__('Jafrabad', 'states-cities-and-places-for-woocommerce'),
		__('Katasur', 'states-cities-and-places-for-woocommerce'),
		__('Mohammadpur Thana (New)', 'states-cities-and-places-for-woocommerce'),
		__('Rayer Bazar', 'states-cities-and-places-for-woocommerce'),
		__('Modhu Bazar', 'states-cities-and-places-for-woocommerce'),
		__('Khamar Bari', 'states-cities-and-places-for-woocommerce'),
		__('Manik Mia Avenue', 'states-cities-and-places-for-woocommerce'),
		__('Sobhanbag', 'states-cities-and-places-for-woocommerce'),
		__('Tallabag', 'states-cities-and-places-for-woocommerce'),
		__('West Razabazar', 'states-cities-and-places-for-woocommerce'),
		__('Indira Road', 'states-cities-and-places-for-woocommerce'),
		__('East Razabazar', 'states-cities-and-places-for-woocommerce'),
		__('Kathalbagan', 'states-cities-and-places-for-woocommerce'),
		__('Cresent Road', 'states-cities-and-places-for-woocommerce'),
		__('North Road', 'states-cities-and-places-for-woocommerce'),
		__('Central Road', 'states-cities-and-places-for-woocommerce'),
		__('Hatirpool', 'states-cities-and-places-for-woocommerce'),
		__('Paribag', 'states-cities-and-places-for-woocommerce'),
		__('Science Lab', 'states-cities-and-places-for-woocommerce'),
		__('Nilkhet', 'states-cities-and-places-for-woocommerce'),
		__('Pilkhana', 'states-cities-and-places-for-woocommerce'),
		__('Gonok Tuli', 'states-cities-and-places-for-woocommerce'),
		__('Borhanpur', 'states-cities-and-places-for-woocommerce'),
		__('Polashi', 'states-cities-and-places-for-woocommerce'),
		__('Bakshi Bazar', 'states-cities-and-places-for-woocommerce'),
		__('Baridhara Diplomatic', 'states-cities-and-places-for-woocommerce'),
		__('Tb Gate', 'states-cities-and-places-for-woocommerce'),
		__('Rasulbag', 'states-cities-and-places-for-woocommerce'),
		__('Amtoli', 'states-cities-and-places-for-woocommerce'),
		__('Korail Bosti', 'states-cities-and-places-for-woocommerce'),
		__('Mohakhali Wireless', 'states-cities-and-places-for-woocommerce'),
		__('Elenbari', 'states-cities-and-places-for-woocommerce'),
		__('West Nakhalpara', 'states-cities-and-places-for-woocommerce'),
		__('East Nakhalpara', 'states-cities-and-places-for-woocommerce'),
		__('Nabisco', 'states-cities-and-places-for-woocommerce'),
		__('Jahangir Gate', 'states-cities-and-places-for-woocommerce'),
		__('Arjatpara', 'states-cities-and-places-for-woocommerce'),
		__('Tejgaon Old Airport', 'states-cities-and-places-for-woocommerce'),
		__('Joarsahara', 'states-cities-and-places-for-woocommerce'),
		__('Banani (Chairman Bari)', 'states-cities-and-places-for-woocommerce'),
		__('Mintu Road', 'states-cities-and-places-for-woocommerce'),
		__('Shideshwari', 'states-cities-and-places-for-woocommerce'),
		__('Shobujbag', 'states-cities-and-places-for-woocommerce'),
		__('Basabo Patwary Goli', 'states-cities-and-places-for-woocommerce'),
		__('Mather Tek', 'states-cities-and-places-for-woocommerce'),
		__('Matuwail', 'states-cities-and-places-for-woocommerce'),
		__('Dhonia', 'states-cities-and-places-for-woocommerce'),
		__('Madinabag', 'states-cities-and-places-for-woocommerce'),
		__('Rayerbag', 'states-cities-and-places-for-woocommerce'),
		__('Islampur', 'states-cities-and-places-for-woocommerce'),
		__('Patuatuli', 'states-cities-and-places-for-woocommerce'),
		__('Shammibag', 'states-cities-and-places-for-woocommerce'),
		__('Bonogram', 'states-cities-and-places-for-woocommerce'),
		__('Tatibazar', 'states-cities-and-places-for-woocommerce'),
		__('Kotowali', 'states-cities-and-places-for-woocommerce'),
		__('Babubazar', 'states-cities-and-places-for-woocommerce'),
		__('Mitford', 'states-cities-and-places-for-woocommerce'),
		__('Nayabazar', 'states-cities-and-places-for-woocommerce'),
		__('Chokbazar', 'states-cities-and-places-for-woocommerce'),
		__('Siddiqbazar', 'states-cities-and-places-for-woocommerce'),
		__('Saydabad', 'states-cities-and-places-for-woocommerce'),
		__('Dilkusha', 'states-cities-and-places-for-woocommerce'),
		__('Baytul Mokarrom', 'states-cities-and-places-for-woocommerce'),
		__('Gpo', 'states-cities-and-places-for-woocommerce'),
		__('Press Club', 'states-cities-and-places-for-woocommerce'),
		__('Bijay Nagar', 'states-cities-and-places-for-woocommerce'),
		__('Shegunbagicha', 'states-cities-and-places-for-woocommerce'),
		__('Aga Sadiq Road', 'states-cities-and-places-for-woocommerce'),
		__('Urdu Road', 'states-cities-and-places-for-woocommerce'),
		__('Begumbazar', 'states-cities-and-places-for-woocommerce'),
		__('Armanitola', 'states-cities-and-places-for-woocommerce'),
		__('Nazirabazar', 'states-cities-and-places-for-woocommerce'),
		__('Boro Shahebr Bazar', 'states-cities-and-places-for-woocommerce'),
		__('Jagannath University', 'states-cities-and-places-for-woocommerce'),
		__('Shakharibazar', 'states-cities-and-places-for-woocommerce'),
		__('Narinda', 'states-cities-and-places-for-woocommerce'),
		__('Chowdhury Para', 'states-cities-and-places-for-woocommerce'),
		__('Kuratoli', 'states-cities-and-places-for-woocommerce'),
		__('Bijoy Sharanani', 'states-cities-and-places-for-woocommerce'),
		__('Demra', 'states-cities-and-places-for-woocommerce'),
		__('Postogola', 'states-cities-and-places-for-woocommerce'),
		__('Jurain', 'states-cities-and-places-for-woocommerce'),
		__('Kajla', 'states-cities-and-places-for-woocommerce'),
		__('Bibirbagicha', 'states-cities-and-places-for-woocommerce'),
		__('Keraniganj Upazila Sadar', 'states-cities-and-places-for-woocommerce'),
	),
	'faridpur' => array(
		__('Alfadanga', 'states-cities-and-places-for-woocommerce'),
		__('Bhanga', 'states-cities-and-places-for-woocommerce'),
		__('Boalmari', 'states-cities-and-places-for-woocommerce'),
		__('Char Bhadrasan', 'states-cities-and-places-for-woocommerce'),
		__('Faridpur Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Madhukhali', 'states-cities-and-places-for-woocommerce'),
		__('Nagarkanda', 'states-cities-and-places-for-woocommerce'),
		__('Sadarpur', 'states-cities-and-places-for-woocommerce'),
		__('Saltha', 'states-cities-and-places-for-woocommerce'),
	),
	'gazipur' => array(
		__('Gazipur Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Kaliakair', 'states-cities-and-places-for-woocommerce'),
		__('Kaliganj', 'states-cities-and-places-for-woocommerce'),
		__('Kapasia', 'states-cities-and-places-for-woocommerce'),
		__('Sreepur', 'states-cities-and-places-for-woocommerce'),
		__('Tongi', 'states-cities-and-places-for-woocommerce'),
	),
	'gopalganj' => array(
		__('Gopalganj Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Kashiani', 'states-cities-and-places-for-woocommerce'),
		__('Kotalipara', 'states-cities-and-places-for-woocommerce'),
		__('Muksudpur', 'states-cities-and-places-for-woocommerce'),
		__('Tungipara', 'states-cities-and-places-for-woocommerce'),
	),
	'kishoreganj' => array(
		__('Austagram', 'states-cities-and-places-for-woocommerce'),
		__('Bajitpur', 'states-cities-and-places-for-woocommerce'),
		__('Bhairab', 'states-cities-and-places-for-woocommerce'),
		__('Hossainpur', 'states-cities-and-places-for-woocommerce'),
		__('Itna', 'states-cities-and-places-for-woocommerce'),
		__('Karimganj', 'states-cities-and-places-for-woocommerce'),
		__('Katiadi', 'states-cities-and-places-for-woocommerce'),
		__('Kishoreganj Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Kuliar Char', 'states-cities-and-places-for-woocommerce'),
		__('Mithamain', 'states-cities-and-places-for-woocommerce'),
		__('Nikli', 'states-cities-and-places-for-woocommerce'),
		__('Pakundia', 'states-cities-and-places-for-woocommerce'),
		__('Tarail', 'states-cities-and-places-for-woocommerce'),
	),
	'madaripur' => array(
		__('Kalkini', 'states-cities-and-places-for-woocommerce'),
		__('Madaripur Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Rajoir', 'states-cities-and-places-for-woocommerce'),
		__('Shibchar', 'states-cities-and-places-for-woocommerce'),
	),
	'manikganj' => array(
		__('Daulatpur', 'states-cities-and-places-for-woocommerce'),
		__('Ghior', 'states-cities-and-places-for-woocommerce'),
		__('Harirampur', 'states-cities-and-places-for-woocommerce'),
		__('Manikganj Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Saturia', 'states-cities-and-places-for-woocommerce'),
		__('Shibalaya', 'states-cities-and-places-for-woocommerce'),
		__('Singair', 'states-cities-and-places-for-woocommerce'),
    ),
    'munshiganj' => array(
		__('Gazaria', 'states-cities-and-places-for-woocommerce'),
		__('Lohajang', 'states-cities-and-places-for-woocommerce'),
		__(' Munshiganj Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Serajdikhan', 'states-cities-and-places-for-woocommerce'),
		__('Sreenagar', 'states-cities-and-places-for-woocommerce'),
		__('Tongibari', 'states-cities-and-places-for-woocommerce'),
	),
	'narayanganj' => array(
		__('Araihazar', 'states-cities-and-places-for-woocommerce'),
		__('Sonargaon', 'states-cities-and-places-for-woocommerce'),
		__('Bandar', 'states-cities-and-places-for-woocommerce'),
		__('Narayanganj Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Rupganj', 'states-cities-and-places-for-woocommerce'),
	),
	'narsingdi' => array(
		__('Belabo', 'states-cities-and-places-for-woocommerce'),
		__('Manohardi', 'states-cities-and-places-for-woocommerce'),
		__('Narsingdi Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Palash', 'states-cities-and-places-for-woocommerce'),
		__('Roypura', 'states-cities-and-places-for-woocommerce'),
		__('Shibpur', 'states-cities-and-places-for-woocommerce'),
	),
	'rajbari' => array(
		__('Baliakandi', 'states-cities-and-places-for-woocommerce'),
		__('Goalanda', 'states-cities-and-places-for-woocommerce'),
		__('Kalukhali', 'states-cities-and-places-for-woocommerce'),
		__('Pangsha', 'states-cities-and-places-for-woocommerce'),
		__('Rajbari Sadar', 'states-cities-and-places-for-woocommerce'),
	),
	'shariatpur' => array(
		__('Bhedarganj', 'states-cities-and-places-for-woocommerce'),
		__('Damudya', 'states-cities-and-places-for-woocommerce'),
		__('Gosairhat', 'states-cities-and-places-for-woocommerce'),
		__('Naria', 'states-cities-and-places-for-woocommerce'),
		__('Shariatpur Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Zanjira', 'states-cities-and-places-for-woocommerce'),
	),
	'tangail' => array(
		__('Basail', 'states-cities-and-places-for-woocommerce'),
		__('Bhuapur', 'states-cities-and-places-for-woocommerce'),
		__('Delduar', 'states-cities-and-places-for-woocommerce'),
		__('Dhanbari', 'states-cities-and-places-for-woocommerce'),
		__('Ghatail', 'states-cities-and-places-for-woocommerce'),
		__('Gopalpur', 'states-cities-and-places-for-woocommerce'),
		__('Kalihati', 'states-cities-and-places-for-woocommerce'),
		__('Madhupur', 'states-cities-and-places-for-woocommerce'),
		__('Mirzapur', 'states-cities-and-places-for-woocommerce'),
		__('Nagarpur', 'states-cities-and-places-for-woocommerce'),
		__('Sakhipur', 'states-cities-and-places-for-woocommerce'),
		__('Tangail Sadar', 'states-cities-and-places-for-woocommerce'),
	),
	'barisal' => array(
		__('Agailjhara', 'states-cities-and-places-for-woocommerce'),
		__('Babuganj', 'states-cities-and-places-for-woocommerce'),
		__('Bakerganj', 'states-cities-and-places-for-woocommerce'),
		__('Banari Para', 'states-cities-and-places-for-woocommerce'),
		__('Gaurnadi', 'states-cities-and-places-for-woocommerce'),
		__('Hizla', 'states-cities-and-places-for-woocommerce'),
		__('Barisal Sadar (Kotwali)', 'states-cities-and-places-for-woocommerce'),
		__('Mhendiganj', 'states-cities-and-places-for-woocommerce'),
		__('Muladi', 'states-cities-and-places-for-woocommerce'),
		__('Wazirpur', 'states-cities-and-places-for-woocommerce'),
	),
	'barguna' => array(
		__('Amtali', 'states-cities-and-places-for-woocommerce'),
		__('Bamna', 'states-cities-and-places-for-woocommerce'),
		__('Barguna Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Betagi', 'states-cities-and-places-for-woocommerce'),
		__('Patharghata', 'states-cities-and-places-for-woocommerce'),
		__('Taltali', 'states-cities-and-places-for-woocommerce'),
	),
	'bhola' => array(
		__(' Bhola Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Burhanuddin', 'states-cities-and-places-for-woocommerce'),
		__('Char Fasson', 'states-cities-and-places-for-woocommerce'),
		__('Daulat Khan', 'states-cities-and-places-for-woocommerce'),
		__('Lalmohan', 'states-cities-and-places-for-woocommerce'),
		__('Manpura', 'states-cities-and-places-for-woocommerce'),
		__('Tazumuddin', 'states-cities-and-places-for-woocommerce'),
	),
	'jhalakati' => array(
		__('Jhalokati Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Kanthalia', 'states-cities-and-places-for-woocommerce'),
		__('Nalchity', 'states-cities-and-places-for-woocommerce'),
		__('Rajapur', 'states-cities-and-places-for-woocommerce'),
	),
	'patuakhali' => array(
		__('Bauphal', 'states-cities-and-places-for-woocommerce'),
		__('Dashmina', 'states-cities-and-places-for-woocommerce'),
		__('Dumki', 'states-cities-and-places-for-woocommerce'),
		__('Galachipa', 'states-cities-and-places-for-woocommerce'),
		__('Kalapara', 'states-cities-and-places-for-woocommerce'),
		__('Mirzaganj', 'states-cities-and-places-for-woocommerce'),
		__('Patuakhali Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Rangabali', 'states-cities-and-places-for-woocommerce'),
	),
	'pirojpur' => array(
		__('Bhandaria', 'states-cities-and-places-for-woocommerce'),
		__('Kawkhali', 'states-cities-and-places-for-woocommerce'),
		__('Mathbaria', 'states-cities-and-places-for-woocommerce'),
		__('Nazirpur', 'states-cities-and-places-for-woocommerce'),
		__('Pirojpur Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Nesarabad (Swarupkati)', 'states-cities-and-places-for-woocommerce'),
		__('Zianagar', 'states-cities-and-places-for-woocommerce'),
	),
	'bandarban' => array(
		__('Alikadam', 'states-cities-and-places-for-woocommerce'),
		__('Bandarban Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Lama', 'states-cities-and-places-for-woocommerce'),
		__('Naikhongchhari', 'states-cities-and-places-for-woocommerce'),
		__('Rowangchhari', 'states-cities-and-places-for-woocommerce'),
		__('Ruma', 'states-cities-and-places-for-woocommerce'),
		__('Thanchi', 'states-cities-and-places-for-woocommerce'),
	),
	'brahmanbaria' => array(
		__('Akhaura', 'states-cities-and-places-for-woocommerce'),
		__('Banchharampur', 'states-cities-and-places-for-woocommerce'),
		__('Bijoynagar', 'states-cities-and-places-for-woocommerce'),
		__('Brahmanbaria Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Ashuganj', 'states-cities-and-places-for-woocommerce'),
		__('Kasba', 'states-cities-and-places-for-woocommerce'),
		__('Nabinagar', 'states-cities-and-places-for-woocommerce'),
		__('Nasirnagar', 'states-cities-and-places-for-woocommerce'),
		__('Sarail', 'states-cities-and-places-for-woocommerce'),
	),
	'chandpur' => array(
		__('Chandpur Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Faridganj', 'states-cities-and-places-for-woocommerce'),
		__('Haim Char', 'states-cities-and-places-for-woocommerce'),
		__('Hajiganj', 'states-cities-and-places-for-woocommerce'),
		__('Kachua', 'states-cities-and-places-for-woocommerce'),
		__('Matlab Dakshin', 'states-cities-and-places-for-woocommerce'),
		__(' Matlab Uttar', 'states-cities-and-places-for-woocommerce'),
		__('Shahrasti', 'states-cities-and-places-for-woocommerce'),
	),
	'chittagong' => array(
		__('Anowara', 'states-cities-and-places-for-woocommerce'),
		__('Bayejid Bostami', 'states-cities-and-places-for-woocommerce'),
		__('Banshkhali', 'states-cities-and-places-for-woocommerce'),
		__('Bakalia', 'states-cities-and-places-for-woocommerce'),
		__('Boalkhali', 'states-cities-and-places-for-woocommerce'),
		__('Chandanaish', 'states-cities-and-places-for-woocommerce'),
		__('Chandgaon', 'states-cities-and-places-for-woocommerce'),
		__('Chittagong Port', 'states-cities-and-places-for-woocommerce'),
		__('Double Mooring', 'states-cities-and-places-for-woocommerce'),
		__('Fatikchhari', 'states-cities-and-places-for-woocommerce'),
		__('Halishahar', 'states-cities-and-places-for-woocommerce'),
		__('Hathazari', 'states-cities-and-places-for-woocommerce'),
		__('Kotwali', 'states-cities-and-places-for-woocommerce'),
		__('Khulshi', 'states-cities-and-places-for-woocommerce'),
		__('Lohagara', 'states-cities-and-places-for-woocommerce'),
		__('Mirsharai', 'states-cities-and-places-for-woocommerce'),
		__('Pahartali', 'states-cities-and-places-for-woocommerce'),
		__('Panchlaish', 'states-cities-and-places-for-woocommerce'),
		__('Patiya', 'states-cities-and-places-for-woocommerce'),
		__('Patenga', 'states-cities-and-places-for-woocommerce'),
		__('Rangunia', 'states-cities-and-places-for-woocommerce'),
		__('Raozan', 'states-cities-and-places-for-woocommerce'),
		__('Sandwip', 'states-cities-and-places-for-woocommerce'),
		__('Satkania', 'states-cities-and-places-for-woocommerce'),
		__('Sitakunda', 'states-cities-and-places-for-woocommerce'),
		__('Agrabad ', 'states-cities-and-places-for-woocommerce'),
	),
	'comilla' => array(
		__('Barura', 'states-cities-and-places-for-woocommerce'),
		__('Brahman Para', 'states-cities-and-places-for-woocommerce'),
		__('Burichang', 'states-cities-and-places-for-woocommerce'),
		__('Chandina', 'states-cities-and-places-for-woocommerce'),
		__('Chauddagram', 'states-cities-and-places-for-woocommerce'),
		__('Comilla Sadar Dakshin', 'states-cities-and-places-for-woocommerce'),
		__('Daudkandi', 'states-cities-and-places-for-woocommerce'),
		__('Debidwar', 'states-cities-and-places-for-woocommerce'),
		__('Homna', 'states-cities-and-places-for-woocommerce'),
		__('Comilla Adarsha Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Laksam', 'states-cities-and-places-for-woocommerce'),
		__('Manoharganj', 'states-cities-and-places-for-woocommerce'),
		__('Meghna', 'states-cities-and-places-for-woocommerce'),
		__('Muradnagar', 'states-cities-and-places-for-woocommerce'),
		__('Nangalkot', 'states-cities-and-places-for-woocommerce'),
		__('Titas', 'states-cities-and-places-for-woocommerce'),
	),
	'coxsbazar' => array(
		__('Chakaria', 'states-cities-and-places-for-woocommerce'),
		__('Coxs Bazar Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Kutubdia', 'states-cities-and-places-for-woocommerce'),
		__('Maheshkhali', 'states-cities-and-places-for-woocommerce'),
		__('Pekua', 'states-cities-and-places-for-woocommerce'),
		__('Ramu', 'states-cities-and-places-for-woocommerce'),
		__('Teknaf', 'states-cities-and-places-for-woocommerce'),
		__('Ukhia', 'states-cities-and-places-for-woocommerce'),
	),
	'feni' => array(
		__('Chhagalnaiya', 'states-cities-and-places-for-woocommerce'),
		__('Daganbhuiyan', 'states-cities-and-places-for-woocommerce'),
		__('Feni Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Fulgazi', 'states-cities-and-places-for-woocommerce'),
		__('Parshuram', 'states-cities-and-places-for-woocommerce'),
		__('Sonagazi', 'states-cities-and-places-for-woocommerce'),
	),
	'khagrachhari' => array(
		__('Dighinala', 'states-cities-and-places-for-woocommerce'),
		__('Khagrachhari Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Lakshmichhari', 'states-cities-and-places-for-woocommerce'),
		__('Mahalchhari', 'states-cities-and-places-for-woocommerce'),
		__('Manikchhari', 'states-cities-and-places-for-woocommerce'),
		__('Matiranga', 'states-cities-and-places-for-woocommerce'),
		__('Panchhari', 'states-cities-and-places-for-woocommerce'),
		__('Ramgarh', 'states-cities-and-places-for-woocommerce'),
	),
	'lakshmipur' => array(
		__('Kamalnagar', 'states-cities-and-places-for-woocommerce'),
		__('Lakshmipur Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Roypur', 'states-cities-and-places-for-woocommerce'),
		__('Ramganj', 'states-cities-and-places-for-woocommerce'),
		__('Ramgati', 'states-cities-and-places-for-woocommerce'),
	),
	'noakhali' => array(
		__('Begumganj', 'states-cities-and-places-for-woocommerce'),
		__('Chatkhil', 'states-cities-and-places-for-woocommerce'),
		__('Companiganj', 'states-cities-and-places-for-woocommerce'),
		__('Hatiya', 'states-cities-and-places-for-woocommerce'),
		__('Kabirhat', 'states-cities-and-places-for-woocommerce'),
		__('Senbagh', 'states-cities-and-places-for-woocommerce'),
		__('Sonaimuri', 'states-cities-and-places-for-woocommerce'),
		__('Subarnachar', 'states-cities-and-places-for-woocommerce'),
		__('Noakhali Sadar', 'states-cities-and-places-for-woocommerce'),
	),
	'rangamati' => array(
		__('Baghaichhari', 'states-cities-and-places-for-woocommerce'),
		__('Barkal Upazila', 'states-cities-and-places-for-woocommerce'),
		__('Kawkhali (Betbunia)', 'states-cities-and-places-for-woocommerce'),
		__('Belai Chhari Upazi', 'states-cities-and-places-for-woocommerce'),
		__('Kaptai Upazila', 'states-cities-and-places-for-woocommerce'),
		__('Jurai Chhari Upazil', 'states-cities-and-places-for-woocommerce'),
		__('Langadu Upazila', 'states-cities-and-places-for-woocommerce'),
		__('Naniarchar Upazila', 'states-cities-and-places-for-woocommerce'),
		__('Rajasthali Upazila', 'states-cities-and-places-for-woocommerce'),
		__('Rangamati Sadar Up', 'states-cities-and-places-for-woocommerce'),
	),
	'jamalpur' => array(
		__('Bakshiganj', 'states-cities-and-places-for-woocommerce'),
		__('Dewanganj', 'states-cities-and-places-for-woocommerce'),
		__('Islampur', 'states-cities-and-places-for-woocommerce'),
		__('Jamalpur Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Madarganj', 'states-cities-and-places-for-woocommerce'),
		__('Melandaha', 'states-cities-and-places-for-woocommerce'),
		__('Sarishabari Upazila', 'states-cities-and-places-for-woocommerce'),
	),
	'mymensingh' => array(
		__('Bhaluka', 'states-cities-and-places-for-woocommerce'),
		__('Dhobaura', 'states-cities-and-places-for-woocommerce'),
		__('Fulbaria', 'states-cities-and-places-for-woocommerce'),
		__('Gaffargaon', 'states-cities-and-places-for-woocommerce'),
		__('Gauripur', 'states-cities-and-places-for-woocommerce'),
		__('Haluaghat', 'states-cities-and-places-for-woocommerce'),
		__('Ishwarganj', 'states-cities-and-places-for-woocommerce'),
		__('Mymensingh Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Muktagachha', 'states-cities-and-places-for-woocommerce'),
		__('Nandail', 'states-cities-and-places-for-woocommerce'),
		__('Phulpur', 'states-cities-and-places-for-woocommerce'),
		__('Trishal', 'states-cities-and-places-for-woocommerce'),
	),
	'netrakona' => array(
		__('Atpara', 'states-cities-and-places-for-woocommerce'),
		__('Barhatta', 'states-cities-and-places-for-woocommerce'),
		__('Durgapur', 'states-cities-and-places-for-woocommerce'),
		__('Khaliajuri', 'states-cities-and-places-for-woocommerce'),
		__('Kalmakanda', 'states-cities-and-places-for-woocommerce'),
		__('Kendua', 'states-cities-and-places-for-woocommerce'),
		__('Madan', 'states-cities-and-places-for-woocommerce'),
		__('Mohanganj', 'states-cities-and-places-for-woocommerce'),
		__('Netrokona Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Purbadhala', 'states-cities-and-places-for-woocommerce'),
	),
	'sherpur' => array(
		__('Jhenaigati', 'states-cities-and-places-for-woocommerce'),
		__('Nakla', 'states-cities-and-places-for-woocommerce'),
		__('Nalitabari', 'states-cities-and-places-for-woocommerce'),
		__('Sherpur Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Sreebardi', 'states-cities-and-places-for-woocommerce'),
	),
	'bagerhat' => array(
		__('Bagerhat Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Chitalmari', 'states-cities-and-places-for-woocommerce'),
		__('Fakirhat', 'states-cities-and-places-for-woocommerce'),
		__('Kachua', 'states-cities-and-places-for-woocommerce'),
		__('Mollahat', 'states-cities-and-places-for-woocommerce'),
		__('Mongla', 'states-cities-and-places-for-woocommerce'),
		__('Morrelganj', 'states-cities-and-places-for-woocommerce'),
		__('Rampal', 'states-cities-and-places-for-woocommerce'),
		__('Sarankhola', 'states-cities-and-places-for-woocommerce'),
	),
	'chuadanga' => array(
		__('Alamdanga', 'states-cities-and-places-for-woocommerce'),
		__('Chuadanga Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Damurhuda', 'states-cities-and-places-for-woocommerce'),
		__('Jiban Nagar', 'states-cities-and-places-for-woocommerce'),
	),
	'jessore' => array(
		__('Abhaynagar', 'states-cities-and-places-for-woocommerce'),
		__('Bagher Para', 'states-cities-and-places-for-woocommerce'),
		__('Chaugachha', 'states-cities-and-places-for-woocommerce'),
		__('Jhikargachha', 'states-cities-and-places-for-woocommerce'),
		__('Keshabpur', 'states-cities-and-places-for-woocommerce'),
		__('Jessore Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Manirampur', 'states-cities-and-places-for-woocommerce'),
		__('Sharsha', 'states-cities-and-places-for-woocommerce'),
		__('Benapole', 'states-cities-and-places-for-woocommerce'),
	),
	'jhenaidah' => array(
		__('Harinakunda', 'states-cities-and-places-for-woocommerce'),
		__('Jhenaidah Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Kaliganj', 'states-cities-and-places-for-woocommerce'),
		__('Kotchandpur', 'states-cities-and-places-for-woocommerce'),
		__('Maheshpur', 'states-cities-and-places-for-woocommerce'),
		__('Shailkupa', 'states-cities-and-places-for-woocommerce'),
	),
	'khulna' => array(
		__('Batiaghata', 'states-cities-and-places-for-woocommerce'),
		__('Dacope', 'states-cities-and-places-for-woocommerce'),
		__('Daulatpur', 'states-cities-and-places-for-woocommerce'),
		__('Dumuria', 'states-cities-and-places-for-woocommerce'),
		__('Dighalia', 'states-cities-and-places-for-woocommerce'),
		__('Khalishpur', 'states-cities-and-places-for-woocommerce'),
		__('Khan Jahan Ali', 'states-cities-and-places-for-woocommerce'),
		__('Khulna Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Koyra', 'states-cities-and-places-for-woocommerce'),
		__('Paikgachha', 'states-cities-and-places-for-woocommerce'),
		__('Phultala', 'states-cities-and-places-for-woocommerce'),
		__('Rupsa', 'states-cities-and-places-for-woocommerce'),
		__('Sonadanga', 'states-cities-and-places-for-woocommerce'),
		__('Terokhada', 'states-cities-and-places-for-woocommerce'),
	),
	'kushtia' => array(
		__('Bheramara', 'states-cities-and-places-for-woocommerce'),
		__('Daulatpur', 'states-cities-and-places-for-woocommerce'),
		__('Khoksa', 'states-cities-and-places-for-woocommerce'),
		__('Kumarkhali', 'states-cities-and-places-for-woocommerce'),
		__('Kushtia Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Mirpur', 'states-cities-and-places-for-woocommerce'),
	),
	'magura' => array(
		__('Magura Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Mohammadpur', 'states-cities-and-places-for-woocommerce'),
		__('Shalikha', 'states-cities-and-places-for-woocommerce'),
		__('Sreepur', 'states-cities-and-places-for-woocommerce'),
	),
	'meherpur' => array(
		__('Gangni', 'states-cities-and-places-for-woocommerce'),
		__('Mujib Nagar', 'states-cities-and-places-for-woocommerce'),
		__('Meherpur Sadar', 'states-cities-and-places-for-woocommerce'),
	),
	'narail' => array(
		__('Kalia', 'states-cities-and-places-for-woocommerce'),
		__('Lohagara', 'states-cities-and-places-for-woocommerce'),
		__('Narail Sadar', 'states-cities-and-places-for-woocommerce'),
	),
	'satkhira' => array(
		__('Assasuni', 'states-cities-and-places-for-woocommerce'),
		__('Debhata', 'states-cities-and-places-for-woocommerce'),
		__('Kalaroa', 'states-cities-and-places-for-woocommerce'),
		__('Kaliganj', 'states-cities-and-places-for-woocommerce'),
		__('Satkhira Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Shyamnagar', 'states-cities-and-places-for-woocommerce'),
		__('Tala', 'states-cities-and-places-for-woocommerce'),
	),
	'bogra' => array(
		__('Adamdighi', 'states-cities-and-places-for-woocommerce'),
		__('Bogra Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Dhunat', 'states-cities-and-places-for-woocommerce'),
		__('Dhupchanchia', 'states-cities-and-places-for-woocommerce'),
		__('Gabtali', 'states-cities-and-places-for-woocommerce'),
		__('Kahaloo', 'states-cities-and-places-for-woocommerce'),
		__('Nandigram', 'states-cities-and-places-for-woocommerce'),
		__('Sariakandi', 'states-cities-and-places-for-woocommerce'),
		__('Shajahanpur', 'states-cities-and-places-for-woocommerce'),
		__('Sherpur', 'states-cities-and-places-for-woocommerce'),
		__('Shibganj', 'states-cities-and-places-for-woocommerce'),
		__('Sonatola', 'states-cities-and-places-for-woocommerce'),
	),
	'chapainawabganj' => array(
		__('Bholahat', 'states-cities-and-places-for-woocommerce'),
		__('Gomastapur', 'states-cities-and-places-for-woocommerce'),
		__('Nachole', 'states-cities-and-places-for-woocommerce'),
		__('Chapai Nababganj Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Shibganj', 'states-cities-and-places-for-woocommerce'),
	),
	'jaipurhat' => array(
		__('Akkelpur', 'states-cities-and-places-for-woocommerce'),
		__('Joypurhat Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Kalai', 'states-cities-and-places-for-woocommerce'),
		__('Khetlal', 'states-cities-and-places-for-woocommerce'),
		__('Panchbibi', 'states-cities-and-places-for-woocommerce'),
	),
	'naogaon' => array(
		__('Atrai', 'states-cities-and-places-for-woocommerce'),
		__('Badalgachhi', 'states-cities-and-places-for-woocommerce'),
		__('Dhamoirhat', 'states-cities-and-places-for-woocommerce'),
		__('Manda', 'states-cities-and-places-for-woocommerce'),
		__('Mahadebpur', 'states-cities-and-places-for-woocommerce'),
		__('Naogaon Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Niamatpur', 'states-cities-and-places-for-woocommerce'),
		__('Patnitala', 'states-cities-and-places-for-woocommerce'),
		__('Porsha', 'states-cities-and-places-for-woocommerce'),
		__('Raninagar', 'states-cities-and-places-for-woocommerce'),
		__('Sapahar', 'states-cities-and-places-for-woocommerce'),
	),
	'natore' => array(
		__('Bagatipara', 'states-cities-and-places-for-woocommerce'),
		__('Baraigram', 'states-cities-and-places-for-woocommerce'),
		__('Gurudaspur', 'states-cities-and-places-for-woocommerce'),
		__('Lalpur', 'states-cities-and-places-for-woocommerce'),
		__('Natore Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Singra', 'states-cities-and-places-for-woocommerce'),
	),
	'pabna' => array(
		__('Atgharia', 'states-cities-and-places-for-woocommerce'),
		__('Bera', 'states-cities-and-places-for-woocommerce'),
		__('Bhangura', 'states-cities-and-places-for-woocommerce'),
		__('Chatmohar', 'states-cities-and-places-for-woocommerce'),
		__('Faridpur', 'states-cities-and-places-for-woocommerce'),
		__('Ishwardi', 'states-cities-and-places-for-woocommerce'),
		__('Pabna Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Santhia', 'states-cities-and-places-for-woocommerce'),
		__('Sujanagar', 'states-cities-and-places-for-woocommerce'),
	),
	'rajshahi' => array(
		__('Bagha', 'states-cities-and-places-for-woocommerce'),
		__('Baghmara', 'states-cities-and-places-for-woocommerce'),
		__('Boalia', 'states-cities-and-places-for-woocommerce'),
		__('Charghat', 'states-cities-and-places-for-woocommerce'),
		__('Durgapur', 'states-cities-and-places-for-woocommerce'),
		__('Godagari', 'states-cities-and-places-for-woocommerce'),
		__('Matihar', 'states-cities-and-places-for-woocommerce'),
		__('Mohanpur', 'states-cities-and-places-for-woocommerce'),
		__('Paba', 'states-cities-and-places-for-woocommerce'),
		__('Puthia', 'states-cities-and-places-for-woocommerce'),
		__('Rajpara', 'states-cities-and-places-for-woocommerce'),
		__('Shah Makhdum', 'states-cities-and-places-for-woocommerce'),
		__('Tanore', 'states-cities-and-places-for-woocommerce'),
	),
	'sirajganj' => array(
		__('Belkuchi', 'states-cities-and-places-for-woocommerce'),
		__('Chauhali', 'states-cities-and-places-for-woocommerce'),
		__('Kamarkhanda', 'states-cities-and-places-for-woocommerce'),
		__('Kazipur', 'states-cities-and-places-for-woocommerce'),
		__('Royganj', 'states-cities-and-places-for-woocommerce'),
		__('Shahjadpur', 'states-cities-and-places-for-woocommerce'),
		__('Sirajganj Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Tarash', 'states-cities-and-places-for-woocommerce'),
		__('Ullah Para', 'states-cities-and-places-for-woocommerce'),
	),
	'dinajpur' => array(
		__('Birampur', 'states-cities-and-places-for-woocommerce'),
		__('Birganj', 'states-cities-and-places-for-woocommerce'),
		__('Biral', 'states-cities-and-places-for-woocommerce'),
		__('Bochaganj', 'states-cities-and-places-for-woocommerce'),
		__('Chirirbandar', 'states-cities-and-places-for-woocommerce'),
		__('Fulbari', 'states-cities-and-places-for-woocommerce'),
		__('Ghoraghat', 'states-cities-and-places-for-woocommerce'),
		__('Hakimpur', 'states-cities-and-places-for-woocommerce'),
		__('Kaharole', 'states-cities-and-places-for-woocommerce'),
		__('Khansama', 'states-cities-and-places-for-woocommerce'),
		__('Dinajpur Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Nawabganj', 'states-cities-and-places-for-woocommerce'),
		__('Parbatipur', 'states-cities-and-places-for-woocommerce'),
	),
	'gaibandha' => array(
		__('Fulchhari', 'states-cities-and-places-for-woocommerce'),
		__('Gaibandha Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Gobindaganj', 'states-cities-and-places-for-woocommerce'),
		__('Palashbari', 'states-cities-and-places-for-woocommerce'),
		__('Sadullapur', 'states-cities-and-places-for-woocommerce'),
		__('Saghata', 'states-cities-and-places-for-woocommerce'),
		__('Sundarganj', 'states-cities-and-places-for-woocommerce'),
	),
	'kurigram' => array(
		__('Bhurungamari', 'states-cities-and-places-for-woocommerce'),
		__('Char Rajibpur', 'states-cities-and-places-for-woocommerce'),
		__('Chilmari', 'states-cities-and-places-for-woocommerce'),
		__('Phulbari', 'states-cities-and-places-for-woocommerce'),
		__('Kurigram Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Nageshwari', 'states-cities-and-places-for-woocommerce'),
		__('Rajarhat', 'states-cities-and-places-for-woocommerce'),
		__('Raumari', 'states-cities-and-places-for-woocommerce'),
		__('Ulipur', 'states-cities-and-places-for-woocommerce'),
	),
	'lalmonirhat' => array(
		__('Aditmari', 'states-cities-and-places-for-woocommerce'),
		__('Hatibandha', 'states-cities-and-places-for-woocommerce'),
		__('Kaliganj', 'states-cities-and-places-for-woocommerce'),
		__('Lalmonirhat Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Patgram', 'states-cities-and-places-for-woocommerce'),
	),
	'nilphamari' => array(
		__('Dimla Upazila', 'states-cities-and-places-for-woocommerce'),
		__('Domar Upazila', 'states-cities-and-places-for-woocommerce'),
		__('Jaldhaka Upazila', 'states-cities-and-places-for-woocommerce'),
		__('Kishoreganj Upazila', 'states-cities-and-places-for-woocommerce'),
		__('Nilphamari Sadar Upaz', 'states-cities-and-places-for-woocommerce'),
		__('Saidpur Upazila', 'states-cities-and-places-for-woocommerce'),
	),
	'panchagarh' => array(
		__('Atwari', 'states-cities-and-places-for-woocommerce'),
		__('Boda', 'states-cities-and-places-for-woocommerce'),
		__('Debiganj', 'states-cities-and-places-for-woocommerce'),
		__('Panchagarh Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Tentulia', 'states-cities-and-places-for-woocommerce'),
	),
	'rangpur' => array(
		__('Badarganj', 'states-cities-and-places-for-woocommerce'),
		__('Gangachara', 'states-cities-and-places-for-woocommerce'),
		__('Kaunia', 'states-cities-and-places-for-woocommerce'),
		__('Rangpur Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Mitha Pukur', 'states-cities-and-places-for-woocommerce'),
		__('Pirgachha', 'states-cities-and-places-for-woocommerce'),
		__('Pirganj', 'states-cities-and-places-for-woocommerce'),
		__('Taraganj', 'states-cities-and-places-for-woocommerce'),
	),
	'thakurgaon' => array(
		__('Baliadangi', 'states-cities-and-places-for-woocommerce'),
		__('Haripur', 'states-cities-and-places-for-woocommerce'),
		__('Pirganj', 'states-cities-and-places-for-woocommerce'),
		__('Ranisankail', 'states-cities-and-places-for-woocommerce'),
		__('Thakurgaon Sadar', 'states-cities-and-places-for-woocommerce'),
	),
	'habiganj' => array(
		__('Ajmiriganj', 'states-cities-and-places-for-woocommerce'),
		__('Bahubal', 'states-cities-and-places-for-woocommerce'),
		__('Baniachong', 'states-cities-and-places-for-woocommerce'),
		__('Chunarughat', 'states-cities-and-places-for-woocommerce'),
		__('Habiganj Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Lakhai', 'states-cities-and-places-for-woocommerce'),
		__('Madhabpur', 'states-cities-and-places-for-woocommerce'),
		__('Nabiganj', 'states-cities-and-places-for-woocommerce'),
	),
	'maulvibazar' => array(
		__('Barlekha', 'states-cities-and-places-for-woocommerce'),
		__('Juri', 'states-cities-and-places-for-woocommerce'),
		__('Kamalganj', 'states-cities-and-places-for-woocommerce'),
		__('Kulaura', 'states-cities-and-places-for-woocommerce'),
		__('Maulvibazar Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Rajnagar', 'states-cities-and-places-for-woocommerce'),
		__('Sreemangal', 'states-cities-and-places-for-woocommerce'),
	),
	'sunamganj' => array(
		__('Bishwambarpur', 'states-cities-and-places-for-woocommerce'),
		__('Chhatak', 'states-cities-and-places-for-woocommerce'),
		__('Dakshin Sunamganj', 'states-cities-and-places-for-woocommerce'),
		__('Derai', 'states-cities-and-places-for-woocommerce'),
		__('Dharampasha', 'states-cities-and-places-for-woocommerce'),
		__('Dowarabazar', 'states-cities-and-places-for-woocommerce'),
		__('Jagannathpur', 'states-cities-and-places-for-woocommerce'),
		__('Jamalganj', 'states-cities-and-places-for-woocommerce'),
		__('Sulla', 'states-cities-and-places-for-woocommerce'),
		__('Sunamganj Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Tahirpur', 'states-cities-and-places-for-woocommerce'),
	),
	'sylhet' => array(
		__('Balaganj', 'states-cities-and-places-for-woocommerce'),
		__('Beani Bazar', 'states-cities-and-places-for-woocommerce'),
		__('Bishwanath', 'states-cities-and-places-for-woocommerce'),
		__('Companiganj', 'states-cities-and-places-for-woocommerce'),
		__('Dakshin Surma', 'states-cities-and-places-for-woocommerce'),
		__('Fenchuganj', 'states-cities-and-places-for-woocommerce'),
		__('Golapganj', 'states-cities-and-places-for-woocommerce'),
		__('Gowainghat', 'states-cities-and-places-for-woocommerce'),
		__('Jaintiapur', 'states-cities-and-places-for-woocommerce'),
		__('Kanaighat', 'states-cities-and-places-for-woocommerce'),
		__('Sylhet Sadar', 'states-cities-and-places-for-woocommerce'),
		__('Zakiganj', 'states-cities-and-places-for-woocommerce'),
	),
	'saver' => array(
		__('Savar Bus Stand', 'states-cities-and-places-for-woocommerce'),
		__('Radio Collony', 'states-cities-and-places-for-woocommerce'),
		__('Rajashon', 'states-cities-and-places-for-woocommerce'),
		__('Enam Medical', 'states-cities-and-places-for-woocommerce'),
		__('Anondopur', 'states-cities-and-places-for-woocommerce'),
		__('Savar Bazar Road', 'states-cities-and-places-for-woocommerce'),
		__('Namabazar', 'states-cities-and-places-for-woocommerce'),
		__('Bank Collony', 'states-cities-and-places-for-woocommerce'),
		__('Arapara', 'states-cities-and-places-for-woocommerce'),
		__('Kashimpur', 'states-cities-and-places-for-woocommerce'),
		__('Savar-Ashulia', 'states-cities-and-places-for-woocommerce'),
		__('Nabinagar', 'states-cities-and-places-for-woocommerce'),
		__('Jahangirnagar', 'states-cities-and-places-for-woocommerce'),
		__('Narsinghopur', 'states-cities-and-places-for-woocommerce'),
		__('Jamgora', 'states-cities-and-places-for-woocommerce'),
		__('Polli Biddyut', 'states-cities-and-places-for-woocommerce'),
		__('Baipail', 'states-cities-and-places-for-woocommerce'),
		__('Jirabo', 'states-cities-and-places-for-woocommerce'),
		__('Jirani', 'states-cities-and-places-for-woocommerce'),
		__('Dhamrai', 'states-cities-and-places-for-woocommerce'),
	),
);

// Use this filter to handle the Cities of Bangladesh
$places['BD'] = apply_filters('scpwoo_custom_places_bd', $places['BD']);
