<?php

/**
 * Cantons of Ecuador
 * - 216 cantons
 *
 * Source:
 * - http://www.statoids.com/yec.html
 *
 * @author  Franklin Lucero Correa <frank_lucero@hotmail.com>
 * @version 1.0.0
 * @license http://www.gnu.org/licenses/gpl-2.0.html
 */

global $places;

$places['EC'] = array(
  'EC.AZ' => array(
    'Chordeleg',
    'Cuenca',
    'El Pan',
    'Guachapala',
    'Gualaceo',
    'Girón',
    'Nabón',
    'Oña',
    'Paute',
    'Pucará',
    'San Fernando',
    'Sigsig',
    'Santa Isabel',
    'Sevilla de Oro',
  ),
  'EC.BO' => array(
    'Caluma',
    'Chimbo',
    'Chillanes',
    'Echeandía',
    'Guaranda',
    'Las Naves',
    'San Miguel',
  ),
  'EC.CB' => array(
    'Alausí',
    'Chambo',
    'Cumandá',
    'Chunchi',
    'Colta',
    'Guamote',
    'Guano',
    'Pallatanga',
    'Penipe',
    'Riobamba',
  ),
  'EC.CN' => array(
    'Azogues',
    'Biblián',
    'Cañar',
    'Déleg',
    'El Tambo',
    'La Troncal',
    'Suscal',
  ),
  'EC.CR' => array(
    'Bolívar',
    'Espejo',
    'Mira',
    'Montúfar',
    'San Pedro de Huaca',
    'Tulcán',
  ),
  'EC.CT' => array(
    'Latacunga',
    'La Maná',
    'Pangua',
    'Pujilí',
    'Sigchos',
    'Salcedo',
    'Saquisilí',
  ),
  'EC.EO' => array(
    'Arenillas',
    'Atahualpa',
    'Balsas',
    'Chilla',
    'El Guabo',
    'Huaquillas',
    'Las Lajas',
    'Machala',
    'Marcabelí',
    'Pasaje',
    'Piñas',
    'Portovelo',
    'Santa Rosa',
    'Zaruma',
  ),
  'EC.ES' => array(
    'Atacames',
    'Eloy Alfaro',
    'Esmeraldas',
    'Muisne',
    'Quinindé',
    'Río Verde',
    'San Lorenzo',
  ),
  'EC.GA' => array(
    'Isabela',
    'San Cristóbal',
    'Santa Cruz',
  ),
  'EC.GY' => array(
    'Alfredo Baquerizo Moreno',
    'Balao',
    'Balzar',
    'Coronel Marcelino Maridueña',
    'Colimes',
    'Daule',
    'Durán',
    'El Empalme',
    'El Triunfo',
    'General Antonio Elizalde',
    'Guayaquil',
    'Isidro Ayora',
    'Lomas de Sargentillo',
    'Milagro',
    'Nobol',
    'Naranjal',
    'Naranjito',
    'Palestina',
    'Pedro Carbo',
    'Playas',
    'Simón Bolívar',
    'Santa Lucía',
    'Samborondón',
    'Salitre',
    'Yaguachi',
  ),
  'EC.IM' => array(
    'Antonio Ante',
    'Cotacachi',
    'Ibarra',
    'Otavalo',
    'Pimampiro',
    'San Miguel de Urcuquí',
  ),
  'EC.LJ' => array(
    'Celica',
    'Chaguarpamba',
    'Catamayo',
    'Calvas',
    'Espíndola',
    'Gonzanamá',
    'Loja',
    'Macará',
    'Olmedo',
    'Paltas',
    'Pindal',
    'Puyango',
    'Quilanga',
    'Saraguro',
    'Sozoranga',
    'Zapotillo',
  ),
  'EC.LR' => array(
    'Baba',
    'Buena Fé',
    'Babahoyo',
    'Mocache',
    'Montalvo',
    'Palenque',
    'Pueblo Viejo',
    'Quevedo',
    'Urdaneta',
    'Valencia',
    'Ventanas',
    'Vinces',
  ),
  'EC.MN' => array(
    'Bolívar',
    'Chone',
    'El Carmen',
    'Flavio Alfaro',
    'Jipijapa',
    'Jama',
    'Junín',
    'Jaramijó',
    'Manta',
    'Montecristi',
    'Olmedo',
    'Paján',
    'Pedernales',
    'Pichincha',
    'Puerto López',
    'Portoviejo',
    'Rocafuerte',
    'Santa Ana',
    'Sucre',
    'San Vicente',
    'Tosagua',
    'Veinticuatro de Mayo',
  ),
  'EC.MS' => array(
    'Gualaquiza',
    'Huamboya',
    'Limón Indanza',
    'Logroño',
    'Morona',
    'Palora',
    'Pablo Sexto',
    'Santiago',
    'San Juan Bosco',
    'Sucúa',
    'Taisha',
  ),
  'EC.NA' => array(
    'Archidona',
    'Carlos Julio Arosemena Tola',
    'El Chaco',
    'Quijos',
    'Tena',
  ),
  'EC.OR' => array(
    'Aguarico',
    'Francisco de Orellana',
    'Joya de los Sachas',
    'Loreto',
  ),
  'EC.PA' => array(
    'Arajuno',
    'Mera',
    'Pastaza',
    'Santa Clara',
  ),
  'EC.PC' => array(
    'Cayambe',
    'Mejía',
    'Pedro Moncayo',
    'Puerto Quito',
    'Pedro Vicente Maldonado',
    'Quito',
    'Rumiñahui',
    'San Miguel de los Bancos',
  ),
  'EC.SD' => array(
    'Santo Domingo de los Tsáchilas',
  ),
  'EC.SE' => array(
    'La Libertad',
    'Santa Elena',
    'Salinas',
  ),
  'EC.SU' => array(
    'Cascales',
    'Cuyabeno',
    'Gonzalo Pizarro',
    'Lago Agrio',
    'Putumayo',
    'Shushufindi',
    'Sucumbíos',
  ),
  'EC.TU' => array(
    'Ambato',
    'Baños',
    'Cevallos',
    'Mocha',
    'Patate',
    'Pelileo',
    'Píllaro',
    'Quero',
    'Tisaleo',
  ),
  'EC.ZC' => array(
    'Centinela del Cóndor',
    'Chinchipe',
    'El Pangui',
    'Nangaritza',
    'Palanda',
    'Yacuambi',
    'Yantzaza',
    'Zamora',
  ),
);

// Use this filter to handle the Municipalities of Cantons of Ecuador
$places['EC'] = apply_filters('scpwoo_custom_places_ec', $places['EC']);
