<?php

/**
 * Cities and Towns of Ghana
 * - 730 cities and towns
 * 
 * Source: 
 * - [https://en.wikipedia.org/wiki/List_of_cities_in_Ghana]
 * 
 * @author  Edem Adjokatcher <adjokatsee@gmail.com> | https://flipmartgh.com
 * @version 1.0.0
 * @license http://www.gnu.org/licenses/gpl-2.0.html
 */

global $places;

$places['GH'] = array(

  'GRA' => array(
    '37',
    'Abeka',
    'Abelemkpe',
    'Ablekuma (Block Factory)',
    'Ablekuma (Central)',
    'Ablekuma (Fanmilk)',
    'Ablekuma (North)',
    'Ablekuma (South)',
    'Ablekuma (Vicolis)',
    'Ablekuma (West)',
    'Ablorh Adjei',
    'Abofu',
    'Abokobi',
    'Abossey Okai',
    'Accra',
    'Accra Newtown',
    'Achimota',
    'Ada Foah',
    'Ada Kasseh',
    'Adabraka',
    'Adenta',
    'Adenta Commandos',
    'Adenta East',
    'Adjankote',
    'Adjei Kodjo',
    'Adjen Kotoku',
    'Adjiriganor',
    'Afienya',
    'Agbogba',
    'Agbogbloshie',
    'Airport',
    'Akweteyman',
    'Alajo',
    'Amasaman',
    'Amrahia',
    'Anyaa',
    'Apaapa',
    'Apenkwa',
    'Aplaku',
    'Ashaiman',
    'Ashaley Botwe',
    'Ashongman',
    'Asoprochona',
    'Atomic',
    'Avenor',
    'Awoshie',
    'Ayi Mensah',
    'Baatsona',
    'Banana Inn',
    'Bansa',
    'Bubuashie',
    'Bukom',
    'Burma Camp',
    'Cantonments',
    'Carprice',
    'Chantang',
    'Chorkor',
    'Circle',
    'Coastal Estates',
    'Christian Village',
    'Danfa',
    'Dansoman',
    'Darkuman',
    'Dawhenya',
    'Dodowa',
    'Dome',
    'Dzorwulu',
    'East Legon',
    'Eleme',
    'Fadama',
    'Fise',
    'Gbawe',
    'Gbegbe',
    'Greda Estates',
    'Haatso',
    'James Town',
    'Kanda',
    'Kaneshie',
    'Kisseman',
    'Kokomlemle',
    'Kokrobite',
    'Korle Bu',
    'Korle Gono',
    'Kotobabi',
    'Kpone',
    'Kuku Hills',
    'Kuntunse',
    'Kwabenya',
    'Kwame Nkrumah Avenue',
    'Kwashieman',
    'Labadi',
    'Lapaz',
    'Latebiokorshie',
    'Legon',
    'Maamobi',
    'Madina',
    'Makola',
    'Mallam',
    'Mallam Atta',
    'Mamprobi',
    'Mataheko',
    'Maccathy Hill',
    'Medie',
    'Miotso',
    'New Bortianor',
    'New Ningo',
    'Nii Boi Town',
    'Nima',
    'Nmai Dzorn',
    'North Industrial Area',
    'North Kaneshie',
    'North Legon',
    'Nungua',
    'Nyamekye',
    'Odorkor',
    'Ogbodjo',
    'Okponglo',
    'Old Bortianor',
    'Old Ningo',
    'Opeibea',
    'Opeikuma',
    'Osu',
    'Oyarifa',
    'Oyibi',
    'Paraku Estates',
    'Pantang',
    'Pig Farm',
    'Pokuase',
    'Prampram',
    'Ridge',
    'Sahara',
    'Sakaman',
    'Sakumono',
    'Sampa Valley',
    'Sapeiman',
    'Santa Maria',
    'Santeo',
    'Sege',
    'Shai Hiils',
    'Shiashie',
    'Sowutuom',
    'Spintex',
    'Sugbaniate',
    'Sukura',
    'Swalaba',
    'Tabora',
    'Taifa',
    'Tantra Hill',
    'Tebibianor',
    'Tema',
    'Tema Manhean',
    'Tema Newtown',
    'Tesano',
    'Teshie',
    'Teshie Estates',
    'Tetegu',
    'Tingatinga',
    'Torkuase',
    'Tuba',
    'Tudu',
    'Weija',
    'West Legon',
  ),
  'ASH' => array(
    'Aboaso',
    'Abofour',
    'Abrepo',
    'Abuakwa Asante',
    'Adabraka (Kumasi)',
    'Adadeentem',
    'Adanwomase',
    'Aduman',
    'Afrancho',
    'Agogo',
    'Agona',
    'Agroyesum',
    'Ahwiaa',
    'Ahwiren',
    'Akrofonso',
    'Akrofuom',
    'Akrokerri',
    'Akumadan',
    'Amowi',
    'Ankasi',
    'Antoa',
    'Antoakrom',
    'Anwia-Nkwanta',
    'Asafo Kumasi',
    'Asaman',
    'Asamang',
    'Asankare',
    'Asiwa',
    'Asokore',
    'Asokore Mampong',
    'Asonomaso',
    'Atimatim',
    'Bampanase',
    'Barekese',
    'Bekwai',
    'Beposo',
    'Bobiri',
    'Bodwesango',
    'Bompata',
    'Bonwire',
    'Bremang',
    'Bunso',
    'Buoho',
    'Dadease',
    'Datano',
    'Dominase',
    'Dompoase',
    'Effiduasi',
    'Ejisu',
    'Ejura',
    'Esase Bontefufuo',
    'Fawoade',
    'Fomena',
    'Jachie-Pramso',
    'Jacobu',
    'Jamasi',
    'Juaben',
    'Juaso',
    'Kasei',
    'Kodie',
    'Kokofu',
    'Konongo',
    'Kortwia-Abodom',
    'Kumasi',
    'Kumawu',
    'Kuntanase',
    'Kwadaso',
    'Kwaso',
    'Maabang',
    'Mampong',
    'Mamponteng',
    'Mankranso',
    'Manso Adubia',
    'Manso Atwere',
    'Manso Nkwanta',
    'Mpasatia',
    'Mprim',
    'Namong',
    'New Edubiase',
    'Nkawie',
    'Nsuta',
    'Nsuta-Beposo',
    'Ntonso',
    'Nyinahin',
    'Obuasi',
    'Odumasi Krobo',
    'Oduom',
    'Offinso',
    'Ofoase-Kokoben',
    'Onwe',
    'Oyoko',
    'Pankrono',
    'Potrikrom',
    'Sakora Wonoo',
    'Sekyedumase',
    'Sewua',
    'Tafo',
    'Tano Dumasi',
    'Tanoso',
    'Tepa',
    'Toase',
    'Tontokrom',
    'Trabuom',
    'Wiamoase',
    'Yawkasakrom',
  ),
  'VOT' => array(
    'Abor',
    'Abutia Kpota',
    'Abutia-Teti',
    'Adafienu',
    'Adaklu',
    'Adaklu Waya',
    'Adidome',
    'Aflao',
    'Agbozume',
    'Agortime-Kpetoe',
    'Akatsi',
    'Akome',
    'Akpafu',
    'Akpafu-Todzi',
    'Akrofu',
    'Alakple',
    'Alavanyo',
    'Amedzofe',
    'Anfoega',
    'Anlo Afiadenyigba',
    'Anloga',
    'Anyako',
    'Anyanui',
    'Asukawkaw',
    'Atiavi',
    'Atimpoku',
    'Ave-Dakpa',
    'Aveyime-Battor',
    'Baglo',
    'Bame',
    'Brewaniase',
    'Dabala',
    'Dafor',
    'Denu',
    'Dzelukope',
    'Dzodze',
    'Dzolokpuita',
    'Gbefi',
    'Gbledi-Agbogame',
    'Hatsukope',
    'Hedzranawo',
    'Hlefi',
    'Ho',
    'Hohoe',
    'Juapong',
    'Keta',
    'Klefe',
    'Klikor',
    'Kpale Kpalime',
    'Kpalime Duga',
    'Kpando',
    'Kpedze',
    'Kpeme',
    'Kpetoe',
    'Kpeve',
    'Kpeve New Town',
    'Leklebi',
    'Likpe-Mate',
    'Logba Adzekoe',
    'Lolobi',
    'Mafi-Kumasi',
    'Mepe',
    'Nkonya',
    'Nogokpo',
    'Peki',
    'Podoe',
    'Seva',
    'Shia',
    'Sogakope',
    'Sokpoe',
    'Tadzewu',
    'Tanyigbe',
    'Tapa Abotoase',
    'Taviefe',
    'Tefle',
    'Tegbi',
    'To Kpalime',
    'Tokor',
    'Tongor Kaira',
    'Tsito',
    'Vakpo',
    'Vane Avatime',
    'Ve Golokwati',
    'Ve-Koloenu',
    'Vume',
    'Wegbe Kpalime',
    'Wheta',
    'Woe',
  ),
  'WST' => array(
    'Aboadze',
    'Aboso',
    'Adum Banso',
    'Agona Nkwanta',
    'Agufo',
    'Airport Ridge (Takoradi)',
    'Akotom',
    'Akwidaa',
    'Anaji',
    'Apowa',
    'Apremodo',
    'Asankragua',
    'Atuabo',
    'Awaso',
    'Axim',
    'Benchema-Nkatieso',
    'Beyin',
    'Bogoso',
    'Botumagyabu',
    'Busua',
    'Butre',
    'Daboase',
    'Dentokrom',
    'Dentukrom',
    'Diabene',
    'Dixcove',
    'Domun',
    'Domunli',
    'Effasu',
    'Effia',
    'Effiakuma',
    'Eikwe',
    'Ejan',
    'Ellembelle',
    'Elubo',
    'Essiama',
    'Essikado (Sekondi)',
    'Essipong',
    'Fijai',
    'Half Assini',
    'Half Assini – New Town Road',
    'Huni Valley',
    'Inchaban',
    'Juabo',
    'Kengen',
    'Ketan',
    'Kojokrom',
    'Kwawkrom',
    'Kwesimintsim',
    'Manso',
    'Mpintsin',
    'New Takoradi',
    'New Town (Jomoro)',
    'Nkroful',
    'Nsein',
    'Nzulezo',
    'Omanpe',
    'Prestea',
    'Princes Town',
    'Samreboi',
    'Sefwi-Bekwai',
    'Sekondi',
    'Sekondi-Takoradi',
    'Shama',
    'Tanokrom (Takoradi)',
    'Tarkwa',
    'Tikobo No. 1 (Jomoro)',
    'Tikobo No. 2 (Jomoro)',
    'Wassa-Akropong',
    'Windy Ridge (Takoradi)',
  ),
  'EST' => array(
    'Abetifi',
    'Abiriw',
    'Abomosu',
    'Aburi',
    'Achiasi',
    'Adeiso',
    'Adiemmra',
    'Adoagyiri',
    'Agormanya',
    'Akim Begoro',
    'Akim Oda',
    'Akim Swedru',
    'Akim Tafo',
    'Akosombo',
    'Akropong',
    'Akuapem-Akropong',
    'Akuapim-Mampong',
    'Akuse',
    'Akwamufie',
    'Akwatia',
    'Akyem-Awenare',
    'Amanokrom',
    'Anum',
    'Anum-Boso',
    'Anyinam',
    'Apedwa',
    'Aperadi',
    'Asafo-Akyem',
    'Asamankese',
    'Asesewa',
    'Asiakwa',
    'Asona Town',
    'Asuboe',
    'Asuboni No.3',
    'Asuboni Rails',
    'Atibie',
    'Atimpoku',
    'Begoro',
    'Bepong',
    'Berekuso',
    'Boso',
    'Bososo',
    'Dago',
    'Dawu',
    'Densuano (Koforidua)',
    'Donkorkrom',
    'Ekowso',
    'Enyiresi',
    'Fodoa',
    'Gyakiti',
    'Jejeti',
    'Kade',
    'Kibi',
    'Koforidua',
    'Koforidua-Asokore',
    'Koforidua-Effiduase',
    'Kpong',
    'Krobo Odumase',
    'Kukurantumi',
    'Kwabeng',
    'Kwahu',
    'Kwahu Asafo',
    'Kwahu Nsaba',
    'Larteh Akuapem',
    'Manhyia',
    'Mpraeso',
    'Mpraeso Amanfrom',
    'New Abirem',
    'Nkawkaw',
    'Nkwatia Kwahu',
    'Nsawam',
    'Nuaso',
    'Oboo',
    'Oboo Kwahu',
    'Old Tafo',
    'Oseim',
    'Osino',
    'Otumi',
    'Pakro',
    'Pampanso',
    'Pepease',
    'Pokrom',
    'Senchi',
    'Somanya',
    'Suhum',
    'Topremang',
  ),
  'OTI' => array(
    'Ahamansu',
    'Dambai',
    'Dodi Papase',
    'Jasikan',
    'Kadjebi',
    'Kadjeto-Asato',
    'Kete Krachi',
    'Kpassa',
    'Nkonya Ahenkro',
    'Nkwanta',
    'Okadjakrom',
    'Teteman',
    'Worawora',
  ),
  'BNE' => array(
    'Agyina',
    'Amanten',
    'Atebubu',
    'Busunya',
    'Jema',
    'Kajaji Settlement Town',
    'Kintampo',
    'Kwame Danso',
    'Nkoranza',
    'Techiman',
    'Yeji',
  ),
  'AHO' => array(
    'Bechem',
    'Duayaw Nkwanta',
    'Goaso',
    'Hwidiem',
    'Kenyasi',
    'Kukuom',
  ),
  'BON' => array(
    'Abesim',
    'Acherensua',
    'Aworowa',
    'Banda Ahenkro',
    'Berekum',
    'Biadan',
    'Bomaa',
    'Bono State',
    'Buoyem',
    'Chiraa',
    'Domeabra',
    'Dormaa Ahenkro',
    'Drobo',
    'Fiapre',
    'Japekrom',
    'Jinijini',
    'Koase',
    'Kwadjokrom',
    'Kwasi Buokrom',
    'New Drobo',
    'Nkrankwanta',
    'Nsawkaw',
    'Nsoatre',
    'Odumase',
    'Offuman',
    'Sampa',
    'Seikwa',
    'Seikwa B/A',
    'Suma-Ahenkro',
    'Sunyani',
    'Techimantia',
    'Tuobodom',
    'Wamahinso',
    'Wamanafo',
    'Wamfie',
    'Wenchi',
    'Yamfo',
  ),
  'NHE' => array(
    'Bimbagu',
    'Bunkpurugu',
    'Chereponi',
    'Gambaga',
    'Gambaga Witch Camp',
    'Gushegu',
    'Nakpanduri',
    'Nalerigu',
    'Sheini',
    'Shienga',
    'Wulugu',
  ),
  'SVH' => array(
    'Bamboi',
    'Bole',
    'Buipe',
    'Daboya',
    'Damongo',
    'Larabanga',
    'Salaga',
    'Sawla',
    'Yapei',
  ),
  'WSN' => array(
    'Bibiani',
    'Enchi',
    'Essam',
    'Juaboso',
    'Sefwi Akontombra',
    'Sefwi Wiawso',
    'Wiawso',
  ),
  'CNT' => array(
    'Abakrampa',
    'Abandze',
    'Abeadzi Kyiakor',
    'Abrafo',
    'Abura-Dunkwa',
    'Adukrom',
    'Afransi',
    'Agona Abirem',
    'Agona Swedru',
    'Ajumako',
    'Amissano',
    'Ankaful',
    'Anomabu',
    'Anyimon',
    'Apam',
    'Asebu',
    'Assin Asempaneye',
    'Assin Darmang',
    'Assin Fosu',
    'Assin Kyekyewere',
    'Assin Manso',
    'Assin Nsuta',
    'Assin Praso',
    'Asutsuare',
    'Asylum Down',
    'Awutu Breku',
    'Ayanfuri',
    'Besease',
    'Biriwa',
    'Breman Asikuma',
    'Buduburam',
    'Cape Coast',
    'Dawurampon',
    'Diaso',
    'Dunkwa-On-Offin',
    'Effutu',
    'Elmina',
    'Esakyir',
    'Gomoa Amoanda',
    'Gomoa Mpota',
    'Hemang',
    'Jukwa',
    'Jukwaa',
    'Kasoa',
    'Kwamankese',
    'Kwanyako',
    'Mankessim',
    'Moree',
    'Mozano',
    'Mumford',
    'Nsaba',
    'Nyakrom',
    'Nyankumase Ahenkro',
    'Obrakyere',
    'Odoben',
    'Otuam',
    'Potsin',
    'Saltpond',
    'Senya',
    'Senya Beraku',
    'Swedru',
    'Twifo Praso',
    'Winneba',
    'Yamoransa',
  ),
  'UPE' => array(
    'Bawku',
    'Belingogo',
    'Binaba',
    'Bolgatanga',
    'Bongo',
    'Builsa',
    'Garu',
    'Gbeogo',
    'Kongo',
    'Kulungugu',
    'Navrongo',
    'Paga',
    'Pobaga',
    'Sandema',
    'Sirigu ',
    'Telania',
    'Tempane',
    'Tongo',
    'Wiaga',
    'Zebilla',
    'Zongoiri',
    'Zuarungu',
  ),
  'UPW' => array(
    'Charia',
    'Chato',
    'Eremon',
    'Funsi',
    'Gwollu',
    'Hamile',
    'Jirapa',
    'Kaleo',
    'Kambali',
    'Lambussie',
    'Lawra',
    'Nadowli',
    'Nandom',
    'Nasa',
    'Pudo',
    'Sabuli',
    'Tumu',
    'Wa',
    'Wechiau',
    'Zambo',
  ),
  'NTH' => array(
    'Adibo',
    'Bimbilla',
    'Gumani',
    'Karaga',
    'Kpabia',
    'Kpandae',
    'Kumbungu',
    'Nyankpala',
    'Saboba',
    'Sang',
    'Santa',
    'Savelugu',
    'Sumniboma',
    'Tamale',
    'Tatale',
    'Tolon',
    'Wulensi',
    'Yendi',
    'Zabzugu',
  ),
);

// Use this filter to handle the Cities and Towns of Ghana
$places['GH'] = apply_filters('scpwoo_custom_places_gh', $places['GH']);
