<?php

/**
* Municipalities of Honduras
* 298 municipalities
*
* Source:
* - https://es.wikipedia.org/wiki/Anexo:Municipios_de_Honduras
*
* @author  Jesus Bermudez <jbermudez01@gmail.com> | http://mintec.co
* @version 1.0.0
* @license http://opensource.org/licenses/gpl-license.php GNU Public License
*
*/

global $places;

$places['HN'] = array(
    // Cortés
    'HN1' => array(
        'Campana',
        'Choloma',
        'Cofradía',
        'Cuyamel',
        'La Lima',
        'Naco',
        'Omoa',
        'Peña Blanca',
        'Pimienta',
        'Potrerillos',
        'Puerto Cortés',
        'Río Lindo',
        'San Antonio de Cortés',
        'San Francisco de Yojoa',
        'San Manuel',
        'San Pedro Sula',
        'Santa Cruz de Yojoa',
        'Villanueva',
    ),
    // Francisco Morazán
    'HN2' => array(
        'Alubarén',
        'Cedros',
        'Cerro de Hula',
        'Comayaguela',
        'Curarén',
        'El Porvenir',
        'El Zamorano',
        'Guaimaca',
        'Jalteva',
        'La Libertad',
        'La Venta',
        'Lepaterique',
        'Maraita',
        'Marale',
        'Nueva Armenia',
        'Ojojona',
        'Orica',
        'Reitoca',
        'Sabanagrande',
        'San Antonio de Oriente',
        'San Buenaventura',
        'San Ignacio',
        'San Juan de Flores',
        'San Miguelito',
        'Santa Ana',
        'Santa Lucía',
        'Talanga',
        'Tatumbla',
        'Tegucigalpa',
        'Valle de Ángeles',
        'Vallecillo',
        'Villa de San Francisco',
    ),
    // Atlántida
    'HN3' => array(
        'Arizona',
        'El Porvenir',
        'Esparta',
        'Jutiapa',
        'La Ceiba',
        'La Masica',
        'San Francisco',
        'San Juan Pueblo',
        'Santa Ana',
        'Tela',
    ),
    // Colón
    'HN4' => array(
        'Balfate',
        'Bonito Oriental',
        'Iriona',
        'Limón',
        'Sabá',
        'Santa Fe',
        'Santa Rosa de Aguán',
        'Sonaguera',
        'Tocoa',
        'Trujillo',
    ),
    // Gracias a Dios
    'HN5' => array(
        'Ahuas',
        'Brus Laguna',
        'Juan Francisco Bulnes',
        'Puerto Lempira',
        'Ramón Villeda Morales',
        'Wampusirpe',
    ),
    // Copán
    'HN6' => array(
        'Cabañas',
        'Chalmeca',
        'Concepción',
        'Copán Ruinas',
        'Corquín',
        'Cucuyagua',
        'Dolores',
        'Dulce Nombre',
        'El Paraíso',
        'Florida',
        'La Entrada',
        'La Jigua',
        'La Unión',
        'Nueva Arcadia',
        'San Agustín',
        'San Antonio',
        'San Jerónimo',
        'San José',
        'San Juan de Opoa',
        'San Nicolás',
        'San Pedro',
        'Santa Rita',
        'Santa Rosa de Copán',
        'Trinidad de Copán',
        'Veracruz',
    ),
    // Santa Barbara
    'HN7' => array(
        'Arada',
        'Atima',
        'Azacualpa',
        'Ceguaca',
        'Chinda',
        'Concepción del Norte',
        'Concepción del Sur',
        'El Níspero',
        'Gualala',
        'Ilama',
        'Las Vegas',
        'Macuelizo',
        'Naranjito',
        'Nueva Frontera',
        'Nuevo Celilac',
        'Petoa',
        'Protección',
        'Quimistán',
        'San Francisco de Ojuera',
        'San José de Colinas',
        'San Luis',
        'San Marcos',
        'San Nicolás',
        'San Pedro Zacapa',
        'San Vicente Centenario',
        'Santa Bárbara',
        'Santa Rita',
        'Trinidad',
    ),
    // Yoro
    'HN8' => array(
        'Arenal',
        'El Negrito',
        'El Progreso',
        'Jocón',
        'Morazán',
        'Olanchito',
        'Santa Rita',
        'Sulaco',
        'Toyos',
        'Victoria',
        'Yorito',
        'Yoro',
    ),
    // Olancho
    'HN9' => array(
        'Campamento',
        'Catacamas',
        'Concordia',
        'Dulce Nombre de Culmí',
        'El Rosario',
        'Esquipulas del Norte',
        'Gualaco',
        'Guarizama',
        'Guata',
        'Guayape',
        'Jano',
        'Juticalpa',
        'La Unión',
        'Limones',
        'Mangulile',
        'Manto',
        'Olanchito',
        'Patuca',
        'Salamá',
        'San Esteban',
        'San Francisco de Becerra',
        'San Francisco de la Paz',
        'San Nicolás',
        'Santa María del Real',
        'Silca',
        'Yocón',
    ),
    // Ocotepeque
    'HN10' => array(
        'Belén Gualcho',
        'Concepción',
        'Dolores Merendón',
        'Fraternidad',
        'La Encarnación',
        'La Labor',
        'Lucerna',
        'Mercedes',
        'Ocotepeque',
        'San Fernando',
        'San Francisco del Valle',
        'San Jorge',
        'San Marcos',
        'Santa Fe',
        'Sensenti',
        'Sinuapa',
    ),
    // Lempira
    'HN11' => array(
        'Belén',
        'Candelaria',
        'Cololaca',
        'Erandique',
        'Gracias',
        'Gualcince',
        'Guarita',
        'La Campa',
        'La Iguala',
        'La Unión',
        'La Virtud',
        'Las Flores',
        'Lepaera',
        'Mapulaca',
        'Piraera',
        'San Andrés',
        'San Francisco',
        'San Juan Guarita',
        'San Manuel Colohete',
        'San Rafael',
        'San Sebastián',
        'Santa Cruz',
        'Talgua',
        'Tambla',
        'Tomalá',
        'Valladolid',
        'Virginia',
    ),
    // Intibucá
    'HN12' => array(
        'Camasca',
        'Colomoncagua',
        'Concepción',
        'Dolores',
        'Intibucá',
        'Jesús de Otoro',
        'La Esperanza',
        'Magdalena',
        'Masaguara',
        'San Antonio',
        'San Francisco de Opalaca',
        'San Isidro',
        'San Juan',
        'San Marcos de la Sierra',
        'San Miguel Guancapla',
        'Santa Lucía',
        'Yamaranguila',
    ),
    // Comayagua
    'HN13' => array(
        'Ajuterique',
        'Comayagua',
        'El Rosario',
        'Esquías',
        'Humuya',
        'La libertad',
        'La Trinidad',
        'Lamaní',
        'Las Lajas',
        'Lejamani',
        'Meambar',
        'Minas de Oro',
        'Ojos de Agua',
        'San Jerónimo',
        'San José de Comayagua',
        'San José del Potrero',
        'San Luis',
        'San Sebastián',
        'Siguatepeque',
        'Taulabé',
        'Villa de San Antonio',
        'Yarumela',
    ),
    // Valle
    'HN14' => array(
        'Alianza',
        'Amapala',
        'Aramecina',
        'Caridad',
        'El Amatillo',
        'El Cubulero',
        'Goascorán',
        'Jícaro Galán',
        'Langue',
        'Nacaome',
        'San Francisco de Coray',
        'San Jerónimo',
        'San Lorenzo',
    ),
    // La Paz
    'HN15' => array(
        'Aguanqueterique',
        'Cabañas',
        'Cane',
        'Chinacla',
        'Guajiquiro',
        'La Paz',
        'Lauterique',
        'Marcala',
        'Mercedes de Oriente',
        'Opatoro',
        'San Antonio del Norte',
        'San José',
        'San Juan',
        'San Pedro de Tutule',
        'Santa Ana',
        'Santa Elena',
        'Santa María',
        'Santiago de Puringla',
        'Yarula',
    ),
    // El Paraíso
    'HN16' => array(
        'Alauca',
        'Danlí',
        'El Paraíso',
        'Güinope',
        'Jacaleapa',
        'Jamastrán',
        'Jutiapa',
        'Las Manos',
        'Liure',
        'Morocelí',
        'Oropolí',
        'Palestina',
        'Potrerillos',
        'San Antonio de Flores',
        'San Lucas',
        'San Matías',
        'Soledad',
        'Teupasenti',
        'Texiguat',
        'Trojes',
        'Vado Ancho',
        'Yauyupe',
        'Yuscarán',
    ),
    // Choluteca
    'HN17' => array(
        'Apacilagua',
        'Choluteca',
        'Concepción de María',
        'Duyure',
        'El Corpus',
        'El Triunfo',
        'Marcovia',
        'Monjarás',
        'Morolica',
        'Namasigue',
        'Orocuina',
        'Pespire',
        'San Antonio de Flores',
        'San Isidro',
        'San Jerónimo',
        'San José',
        'San Marcos de Colón',
        'Santa Ana de Yusguare',
    ),
    // Islas de la Bahía
    'HN18' => array(
        'Roatán',
        'Guanaja',
        'José Santos Guardiola',
        'Utila',
    ),
);

// Use this filter to handle the Municipalities of Honduras
$places['HN'] = apply_filters('scpwoo_custom_places_hn', $places['HN']);
