<?php

/**
 * Cities of India
 * - 699 cities
 *
 * @author  Roni Mondal | https://github.com/ronimondal
 * @version 1.0.0
 * @license http://www.gnu.org/licenses/gpl-2.0.html
 */

global $places;

$places['IN'] = array(
	// West Bengal
	'WB' => array(
		'Alipurduar',
		'Bankura',
		'Birbhum',
		'Cooch Behar',
		'Dakshin Dinajpur',
		'Darjeeling',
		'Hooghly',
		'Howrah',
		'Jalpaiguri',
		'Jhargram',
		'Kalimpong',
		'Kolkata',
		'Maldah',
		'Murshidabad',
		'Nadia',
		'North 24 Parganas',
		'Paschim Bardhaman',
		'Purba Bardhaman',
		'Paschim Medinipur',
		'Purba Medinipur',
		'Purulia',
		'South 24 Parganas',
		'Uttar Dinajpur',		
	),	
	// Andra Pradesh
	'AP' => array(
		'Anantapur',
		'Chittoor',
		'East Godavari',
		'Guntur',
		'Krishna',
		'Kurnool',
		'Prakasam',
		'Srikakulam',
		'Sri Potti Sriramulu Nellore',
		'Visakhapatnam',
		'Vizianagaram',
		'West Godavari',
		'YSR District, Kadapa',		
	),	
	// Arunachal Pradesh
	'AR' => array(
		'Anjaw',
		'Changlang',
		'Dibang Valley',
		'East Kameng',
		'East Siang',
		'Kamle',
		'Kra Daadi',
		'Kurung Kumey',
		'Lepa Rada',
		'Lohit',
		'Lower Dibang Valley',
		'Lower Siang',
		'Lower Subansiri',
		'Namsai',
		'Pakke Kessang',
		'Papum Pare',
		'Shi Yomi',
		'Siang',
		'Tawang',
		'Tirap',
		'Upper Siang',
		'Upper Subansiri',
		'West Kameng',
		'West Siang',		
	),	
	// Assam
	'AS' => array(	
		'Baksa',
		'Barpeta',
		'Biswanath',
		'Bongaigaon',
		'Cachar',
		'Charaideo',
		'Chirang',
		'Darrang',
		'Dhemaji',
		'Dhubri',
		'Dibrugarh',
		'Dima Hasao (North Cachar Hills)',
		'Goalpara',
		'Golaghat',
		'Hailakandi',
		'Hojai',
		'Jorhat',
		'Kamrup',
		'Kamrup Metropolitan',
		'Karbi Anglong',
		'Karimganj',
		'Kokrajhar',
		'Lakhimpur',
		'Majuli',
		'Morigaon',
		'Nagaon',
		'Nalbari',
		'Sivasagar',
		'Sonitpur',
		'South Salamara-Mankachar',
		'Tinsukia',
		'Udalguri',
		'West Karbi Anglong',
	),
	// Bihar
	'BR' => array(	
		'Araria',
		'Arwal',
		'Aurangabad',
		'Banka',
		'Begusarai',
		'Bhagalpur',
		'Bhojpur',
		'Buxar',
		'Darbhanga',
		'East Champaran (Motihari)',
		'Gaya',
		'Gopalganj',
		'Jamui',
		'Jehanabad',
		'Kaimur (Bhabua)',
		'Katihar',
		'Khagaria',
		'Kishanganj',
		'Lakhisarai',
		'Madhepura',
		'Madhubani',
		'Munger (Monghyr)',
		'Muzaffarpur',
		'Nalanda',
		'Nawada',
		'Patna',
		'Purnia (Purnea)',
		'Rohtas',
		'Saharsa',
		'Samastipur',
		'Saran',
		'Sheikhpura',
		'Sheohar',
		'Sitamarhi',
		'Siwan',
		'Supaul',
		'Vaishali',
		'West Champaran',
	),
	// Chhattisgarh
	'CT' => array(	 
		'Chandigarh',
	),
	// Goa
	'GA' => array(	 
		'North Goa',
		'South Goa',
	),
	// Gujarat
	'GJ' => array(
		'Ahmedabad',
		'Amreli',
		'Anand',
		'Aravalli',
		'Banaskantha (Palanpur)',
		'Bharuch',
		'Bhavnagar',
		'Botad',
		'Chhota Udepur',
		'Dahod',
		'Dangs (Ahwa)',
		'Devbhoomi Dwarka',
		'Gandhinagar',
		'Gir Somnath',
		'Jamnagar',
		'Junagadh',
		'Kachchh',
		'Kheda (Nadiad)',
		'Mahisagar',
		'Mehsana',
		'Morbi',
		'Narmada (Rajpipla)',
		'Navsari',
		'Panchmahal (Godhra)',
		'Patan',
		'Porbandar',
		'Rajkot',
		'Sabarkantha (Himmatnagar)',
		'Surat',
		'Surendranagar',
		'Tapi (Vyara)',
		'Vadodara',
		'Valsad',
	),
	// Haryana
	'HR' => array(
		'Ambala',
		'Bhiwani',
		'Charkhi Dadri',
		'Faridabad',
		'Fatehabad',
		'Gurugram (Gurgaon)',
		'Hisar',
		'Jhajjar',
		'Jind',
		'Kaithal',
		'Karnal',
		'Kurukshetra',
		'Mahendragarh',
		'Nuh',
		'Palwal',
		'Panchkula',
		'Panipat',
		'Rewari',
		'Rohtak',
		'Sirsa',
		'Sonipat',
		'Yamunanagar',
	),
	// Himachal Pradesh
	'HP' => array(		
		'Bilaspur',
		'Chamba',
		'Hamirpur',
		'Kangra',
		'Kinnaur',
		'Kullu',
		'Lahaul & Spiti',
		'Mandi',
		'Shimla',
		'Sirmaur (Sirmour)',
		'Solan',
		'Una',
	),
	// Jammu and Kashmir
	'JK' => array(
		'Anantnag',
		'Bandipore',
		'Baramulla',
		'Budgam',
		'Doda',
		'Ganderbal',
		'Jammu',
		'Kathua',
		'Kishtwar',
		'Kulgam',
		'Kupwara',
		'Poonch',
		'Pulwama',
		'Rajouri',
		'Ramban',
		'Reasi',
		'Samba',
		'Shopian',
		'Srinagar',
		'Udhampur',
	),
	// Jharkhand
	'JH' => array(
		'Bokaro',
		'Chatra',
		'Deoghar',
		'Dhanbad',
		'Dumka',
		'East Singhbhum',
		'Garhwa',
		'Giridih',
		'Godda',
		'Gumla',
		'Hazaribag',
		'Jamtara',
		'Khunti',
		'Koderma',
		'Latehar',
		'Lohardaga',
		'Pakur',
		'Palamu',
		'Ramgarh',
		'Ranchi',
		'Sahibganj',
		'Seraikela-Kharsawan',
		'Simdega',
		'West Singhbhum',
	),
	// Karnataka
	'KA' => array(
		'Bagalkot',
		'Ballari',
		'Belagavi',
		'Bangalore',
		'Bidar',
		'Chamarajanagar',
		'Chikballapur',
		'Chikkamagaluru',
		'Chitradurga',
		'Dakshina Kannada',
		'Davangere',
		'Dharwad',
		'Gadag',
		'Hassan',
		'Haveri',
		'Kalaburagi (Gulbarga)',
		'Kodagu',
		'Kolar',
		'Koppal',
		'Mandya',
		'Mysuru (Mysore)',
		'Raichur',
		'Ramanagara',
		'Shivamogga',
		'Tumakuru (Tumkur)',
		'Udupi',
		'Uttara Kannada (Karwar)',
		'Vijayapura (Bijapur)',
		'Yadgir',
	),
	// Kerala
	'KL' => array(  
		'Alappuzha',
		'Ernakulam',
		'Idukki',
		'Kannur',
		'Kasaragod',
		'Kollam',
		'Kottayam',
		'Kozhikode',
		'Malappuram',
		'Palakkad',
		'Pathanamthitta',
		'Thiruvananthapuram',
		'Thrissur',
		'Wayanad',
	),
	// Madhya Pradesh
	'MP' => array(
		'Agar Malwa',
		'Alirajpur',
		'Anuppur',
		'Ashoknagar',
		'Balaghat',
		'Barwani',
		'Betul',
		'Bhind',
		'Bhopal',
		'Burhanpur',
		'Chhatarpur',
		'Chhindwara',
		'Damoh',
		'Datia',
		'Dewas',
		'Dhar',
		'Dindori',
		'Guna',
		'Gwalior',
		'Harda',
		'Hoshangabad',
		'Indore',
		'Jabalpur',
		'Jhabua',
		'Katni',
		'Khandwa',
		'Khargone',
		'Mandla',
		'Mandsaur',
		'Morena',
		'Narsinghpur',
		'Neemuch',
		'Panna',
		'Raisen',
		'Rajgarh',
		'Ratlam',
		'Rewa',
		'Sagar',
		'Satna',
		'Sehore',
		'Seoni',
		'Shahdol',
		'Shajapur',
		'Sheopur',
		'Shivpuri',
		'Sidhi',
		'Singrauli',
		'Tikamgarh',
		'Ujjain',
		'Umaria',
		'Vidisha',
	),
	// Maharashtra
	'MH' => array(
		'Ahmednagar',
		'Akola',
		'Amravati',
		'Aurangabad',
		'Beed',
		'Bhandara',
		'Buldhana',
		'Chandrapur',
		'Dhule',
		'Gadchiroli',
		'Gondia',
		'Hingoli',
		'Jalgaon',
		'Jalna',
		'Kolhapur',
		'Latur',
		'Mumbai City',
		'Mumbai Suburban',
		'Nagpur',
		'Nanded',
		'Nandurbar',
		'Nashik',
		'Osmanabad',
		'Palghar',
		'Parbhani',
		'Pune',
		'Raigad',
		'Ratnagiri',
		'Sangli',
		'Satara',
		'Sindhudurg',
		'Solapur',
		'Thane',
		'Wardha',
		'Washim',
		'Yavatmal',
	),
	// Manipur
	'MN' => array(
		'Bishnupur',
		'Chandel',
		'Churachandpur',
		'Imphal East',
		'Imphal West',
		'Jiribam',
		'Kakching',
		'Kamjong',
		'Kangpokpi',
		'Noney',
		'Pherzawl',
		'Senapati',
		'Tamenglong',
		'Tengnoupal',
		'Thoubal',
		'Ukhrul',
	),
	// Meghalaya
	'ML' => array(
		'East Garo Hills',
		'East Jaintia Hills',
		'East Khasi Hills',
		'North Garo Hills',
		'Ri Bhoi',
		'South Garo Hills',
		'South West Garo Hills',
		'South West Khasi Hills',
		'West Garo Hills',
		'West Jaintia Hills',
		'West Khasi Hills',
	),
	// Mizoram
	'MZ' => array(
		'Aizawl',
		'Champhai',
		'Kolasib',
		'Lawngtlai',
		'Lunglei',
		'Mamit',
		'Saiha',
		'Serchhip',
	),
	// Nagaland
	'NL' => array(
		'Dimapur',
		'Kiphire',
		'Kohima',
		'Longleng',
		'Mokokchung',
		'Mon',
		'Peren',
		'Phek',
		'Tuensang',
		'Wokha',
		'Zunheboto',
	),
	// Orissa
	'OR' => array(
		'Angul',
		'Balangir',
		'Balasore',
		'Bargarh',
		'Bhadrak',
		'Boudh',
		'Cuttack',
		'Deogarh',
		'Dhenkanal',
		'Gajapati',
		'Ganjam',
		'Jagatsinghapur',
		'Jajpur',
		'Jharsuguda',
		'Kalahandi',
		'Kandhamal',
		'Kendrapara',
		'Kendujhar (Keonjhar)',
		'Khordha',
		'Koraput',
		'Malkangiri',
		'Mayurbhanj',
		'Nabarangpur',
		'Nayagarh',
		'Nuapada',
		'Puri',
		'Rayagada',
		'Sambalpur',
		'Sonepur',
		'Sundargarh',
	),
	// Punjab
	'PB' => array(
		'Amritsar',
		'Barnala',
		'Bathinda',
		'Faridkot',
		'Fatehgarh Sahib',
		'Fazilka',
		'Ferozepur',
		'Gurdaspur',
		'Hoshiarpur',
		'Jalandhar',
		'Kapurthala',
		'Ludhiana',
		'Mansa',
		'Moga',
		'Muktsar',
		'Nawanshahr',
		'Pathankot',
		'Patiala',
		'Rupnagar',
		'Sahibzada Ajit Singh Nagar (Mohali)',
		'Sangrur',
		'Tarn Taran',
	),
	// Rajasthan
	'RJ' => array(
		'Ajmer',
		'Alwar',
		'Banswara',
		'Baran',
		'Barmer',
		'Bharatpur',
		'Bhilwara',
		'Bikaner',
		'Bundi',
		'Chittorgarh',
		'Churu',
		'Dausa',
		'Dholpur',
		'Dungarpur',
		'Hanumangarh',
		'Jaipur',
		'Jaisalmer',
		'Jalore',
		'Jhalawar',
		'Jhunjhunu',
		'Jodhpur',
		'Karauli',
		'Kota',
		'Nagaur',
		'Pali',
		'Pratapgarh',
		'Rajsamand',
		'Sawai Madhopur',
		'Sikar',
		'Sirohi',
		'Sri Ganganagar',
		'Tonk',
		'Udaipur',
	),
	// Sikkim
	'SK' => array(
		'East Sikkim',
		'North Sikkim',
		'South Sikkim',
		'West Sikkim',
	),
	// Tamil Nadu
	'TN' => array(
		'Ariyalur',
		'Chengalpattu',
		'Chennai',
		'Coimbatore',
		'Cuddalore',
		'Dharmapuri',
		'Dindigul',
		'Erode',
		'Kallakurichi',
		'Kanchipuram',
		'Kanyakumari',
		'Karur',
		'Krishnagiri',
		'Madurai',
		'Nagapattinam',
		'Namakkal',
		'Nilgiris',
		'Perambalur',
		'Pudukkottai',
		'Ramanathapuram',
		'Ranipet',
		'Salem',
		'Sivaganga',
		'Tenkasi',
		'Thanjavur',
		'Theni',
		'Thoothukudi (Tuticorin)',
		'Tiruchirappalli',
		'Tirunelveli',
		'Tirupathur',
		'Tiruppur',
		'Tiruvallur',
		'Tiruvannamalai',
		'Tiruvarur',
		'Vellore',
		'Viluppuram',
		'Virudhunagar',
	),
	// Telangana
	'TL' => array(
		'Adilabad',
		'Bhadradri Kothagudem',
		'Hyderabad',
		'Jagtial',
		'Jangaon',
		'Jayashankar Bhoopalpally',
		'Jogulamba Gadwal',
		'Kamareddy',
		'Karimnagar',
		'Khammam',
		'Komaram Bheem Asifabad',
		'Mahabubabad',
		'Mahabubnagar',
		'Mancherial',
		'Medak',
		'Medchal',
		'Nagarkurnool',
		'Nalgonda',
		'Nirmal',
		'Nizamabad',
		'Peddapalli',
		'Rajanna Sircilla',
		'Rangareddy',
		'Sangareddy',
		'Siddipet',
		'Suryapet',
		'Vikarabad',
		'Wanaparthy',
		'Warangal (Rural)',
		'Warangal (Urban)',
		'Yadadri Bhuvanagiri',
	),
	// Tripura
	'TR' => array(		
		'Dhalai',
		'Gomati',
		'Khowai',
		'North Tripura',
		'Sepahijala',
		'South Tripura',
		'Unakoti',
		'West Tripura',
	),
	// Uttarakhand
	'UK' => array(
		'Almora',
		'Bageshwar',
		'Chamoli',
		'Champawat',
		'Dehradun',
		'Haridwar',
		'Nainital',
		'Pauri Garhwal',
		'Pithoragarh',
		'Rudraprayag',
		'Tehri Garhwal',
		'Udham Singh Nagar',
		'Uttarkashi',
	),
	// Uttar Pradesh
	'UP' => array(
		'Agra',
		'Aligarh',
		'Allahabad',
		'Ambedkar Nagar',
		'Amethi (Chatrapati Sahuji Mahraj Nagar)',
		'Amroha (J.P. Nagar)',
		'Auraiya',
		'Azamgarh',
		'Baghpat',
		'Bahraich',
		'Ballia',
		'Balrampur',
		'Banda',
		'Barabanki',
		'Bareilly',
		'Basti',
		'Bhadohi',
		'Bijnor',
		'Budaun',
		'Bulandshahr',
		'Chandauli',
		'Chitrakoot',
		'Deoria',
		'Etah',
		'Etawah',
		'Faizabad',
		'Farrukhabad',
		'Fatehpur',
		'Firozabad',
		'Gautam Buddha Nagar',
		'Ghaziabad',
		'Ghazipur',
		'Gonda',
		'Gorakhpur',
		'Hamirpur',
		'Hapur (Panchsheel Nagar)',
		'Hardoi',
		'Hathras',
		'Jalaun',
		'Jaunpur',
		'Jhansi',
		'Kannauj',
		'Kanpur Dehat',
		'Kanpur Nagar',
		'Kanshiram Nagar (Kasganj)',
		'Kaushambi',
		'Kushinagar (Padrauna)',
		'Lakhimpur - Kheri',
		'Lalitpur',
		'Lucknow',
		'Maharajganj',
		'Mahoba',
		'Mainpuri',
		'Mathura',
		'Mau',
		'Meerut',
		'Mirzapur',
		'Moradabad',
		'Muzaffarnagar',
		'Pilibhit',
		'Pratapgarh',
		'RaeBareli',
		'Rampur',
		'Saharanpur',
		'Sambhal (Bhim Nagar)',
		'Sant Kabir Nagar',
		'Shahjahanpur',
		'Shamali (Prabuddh Nagar)',
		'Shravasti',
		'Siddharth Nagar',
		'Sitapur',
		'Sonbhadra',
		'Sultanpur',
		'Unnao',
		'Varanasi',
	),
	// Andaman and Nicobar Islands
	'AN' => array(
		'Nicobar',
		'North and Middle Andaman',
		'South Andaman',
	),
	// Chandigarh
	'CH' => array(
		'Chandigarh',
	),
	// Dadar and Nagar Haveli
	'DN' => array(
		'Dadra & Nagar Haveli',
	),
	// Daman and Diu
	'DD' => array(
		'Daman',
		'Diu',
	),
	// Delhi
	'DL' => array(
		'Central Delhi',
		'East Delhi',
		'New Delhi',
		'North Delhi',
		'North East Delhi',
		'North West Delhi',
		'Shahdara',
		'South Delhi',
		'South East Delhi',
		'South West Delhi',
		'West Delhi',
	),
	// Ladakh
	'LK' => array(
		'Kargil',
		'Leh',
	),
	// Lakshadeep
	'LD' => array(
		'Lakshadweep',
	),
	// Pondicherry (Puducherry)
	'PY' => array(
		'Karaikal',
		'Mahe',
		'Puducherry',
		'Yanam',
	),
);

// Use this filter to handle the Cities of India
$places['IN'] = apply_filters('scpwoo_custom_places_in', $places['IN']);
