<?php

/**
 * Towns in Jamaica Parishes
 * - 244 Towns
 * 
 * Source: 
 * - https://en.wikipedia.org/wiki/List_of_cities_and_towns_in_Jamaica
 * 
 * @author  Ryon Whyte <ryon@sitepact.com> | https://sitepactja.com
 * @version 1.0.0
 * @license http://www.gnu.org/licenses/gpl-2.0.html
 */

global $places;

$places['JM'] = array(
  // Kingston and ST Andrew 
  'JM-01' => array(
    'Allerdyce',
    'Allman Town',
    'August Town',
    'Backto',
    'Barbican',
    'Belgrade Mews',
    'Beverley Hills',
    'Bournemouth Gardens',
    'Bull Bay',
    'Callaloo Bed',
    'Cherry Gardens',
    'Cockburn Gardens',
    'College Common',
    'Constant Spring',
    'Cross Roads',
    'Denham Town',
    'Downtown Kingston',
    'Duhaney Park',
    'Eastwood Park Gardens',
    'Eden Gardens',
    'Elletson Flats',
    'Forest Gardens',
    'Forest Hills',
    'Forest Hills Gardens',
    'Franklyn Town',
    'Greenwich Town',
    'Half Way Tree',
    'Harbour View',
    'Havendale',
    'Hope Pastures',
    'Hopewell',
    'Hughenden',
    'Ithaca',
    'Jack\'s Hill',
    'Jones Town',
    'Kencot',
    'Kingston',
    'Kintyre',
    'Liguanea',
    'Long Mountain',
    'Marverley',
    'Meadowbrook',
    'Meadowbrook Estates',
    'Molynes Gardens',
    'Mona',
    'Mountain View',
    'New Castle',
    'New Haven',
    'New Kingston',
    'Norbrook',
    'Norbrook',
    'Norman Gardens',
    'Olympic Garden',
    'Papine',
    'Patrick City',
    'Patrick Gardens',
    'Payne Land',
    'Pembroke Hall',
    'Pembrook Hall',
    'Port Royal',
    'Queen Hill',
    'Rae Town',
    'Red Hills',
    'Riva Ridge',
    'Riverton Meadows',
    'Seaview Gardens',
    'Smokey Vale',
    'Stony Hill',
    'Tivoli Gardens',
    'Trafalgar Park',
    'Trenchtown',
    'Vineyard Town',
    'Washington Gardens',
    'Waterhouse',
    'Whitfield Town',
    'Woodford Park',
    'Zaidie Gardens',
  ),
  //Saint Thomas
  'JM-03' => array(
    'Bath',
    'Bull Bay',
    'Easington',
    'Dalvey',
    'Duckenfield',
    'Golden Grove',
    'Hampton Court',
    'Lyssons',
    'Morant Bay',
    'Port Morant',
    'Seaforth',
    'Trinity Ville',
    'Wilson Gap / Richmond Vale',
    'Yallahs',
    'White Horses',
  ),
  //Portland
  'JM-04' => array(
    'Buff Bay',
    'Cattawood Springs',
    'Hope Bay',
    'Manchioneal',
    'Port Antonio',
    'St. Margarets Bay',
    'Norwich',
    'Snow Hill',
    'Boston',
    'Drapers',
    'Fruitful Vale',
    'Shrewsbury',
    'Coopers Hill',
    'Moore Town',
    'Charles Town, Jamaica',
    'Fellowship',
    'Mount Pleasant',
  ),
  //Saint Mary
  'JM-05' => array(
    'Annotto Bay',
    'Carron Hall',
    'Gayle',
    'Guys Hill',
    'Highgate',
    'Islington',
    'Lucky Hill',
    'Oracabessa',
    'Port Maria',
    'Retreat',
    'Richmond',
  ),
  //Saint Ann
  'JM-06' => array(
    'Alexandria',
    'Bamboo',
    'Beecher Town',
    'Borobridge',
    'Brown\'s Town',
    'Calderwood',
    'Cave Valley',
    'Claremont',
    'Discovery Bay',
    'Dry Harbour',
    'Exchange',
    'Gibraltar',
    'Golden Grove',
    'Lime Hall',
    'Moneague',
    'Nine Mile',
    'Ocho Rios',
    'Runaway Bay',
    'Saint Ann\'s Bay',
    'Watt Town',
  ),
  //Trelawny
  'JM-07' => array(
    'Albert Town',
    'Clark\'s Town',
    'Duncans',
    'Falmouth',
    'Jackson Town',
    'Rio Bueno',
    'Ulster Spring',
    'Wakefield',
    'Wait-A-Bit',

  ),
  //Saint James
  'JM-08' => array(
    'Adelphi',
    'Anchovy',
    'Bogue',
    'Cambridge',
    'Catadupa',
    'Dumfries',
    'Fairfield',
    'Granville',
    'Irwin',
    'Johns Hall',
    'Maroon Town',
    'Montego Bay',
    'Montpelier',
    'Rose Hall',
    'Somerton',
  ),
  //Hanover
  'JM-09' => array(
    'Cascade',
    'Dias',
    'Green Island',
    'Hopewell',
    'Lucea',
    'Ramble',
    'Sandy Bay',
  ),
  //Westmoreland
  'JM-10' => array(
    'Bethel Town',
    'Bluefields',
    'Darliston',
    'Frome',
    'Grange Hill',
    'Hopewell',
    'Little London',
    'Negril',
    'Petersfield',
    'Savanna-la-Mar',
    'Seaford Town',
    'White House',
  ),
  //Saint Elizabeth
  'JM-11' => array(
    'Balaclava',
    'Black River',
    'Bull Savanna',
    'Junction',
    'Lacovia',
    'Maggotty',
    'Malvern',
    'Middle Quarters.',
    'Mountainside',
    'Nain',
    'New Market',
    'Newell',
    'Siloah',
    'Southfield',
  ),
  //Manchester
  'JM-12' => array(
    'Alligator Pond',
    'Christiana',
    'Coleyville',
    'Cross Keys',
    'Mandeville',
    'Mile Gully',
    'Newport',
    'Porus',
    'Pratville',
    'Spalding',
    'Williamsfield',
  ),
  //Clarendon
  'JM-13' => array(
    'Aenon Town',
    'Alston',
    'Chapelton',
    'Croft\'s Hill',
    'Frankfield',
    'Gimme-Me-Bit',
    'James Hill',
    'Kellits',
    'Kemps Hill',
    'Lionel Town',
    'May Pen',
    'Milk River',
    'Mitchell Town',
    'Mocho',
    'Osbourne Store',
    'Race Course',
    'Rock River',
    'Rocky Point',
    'Thompson Town',
    'Toll Gate',
    'York Town',
  ),
  //Saint Catherine
  'JM-14' => array(
    'Above Rocks',
    'Bog Walk',
    'Central Village',
    'Ewarton',
    'Glengoffe',
    'Guy\’s Hill',
    'Kitson Town',
    'Linstead',
    'Lluidas Vale',
    'Old Harbour',
    'Point Hill',
    'Riversdale',
    'Sligoville',
    'Spanish Town',
    'Troja',
  )
);

// Use this filter to handle the Cities of Jamaica
$places['JM'] = apply_filters('scpwoo_custom_places_jm', $places['JM']);