<?php

/**
 * Cities Of Lebanon
 * - 2032 cities
 * 
 * Source: 
 * - Liban Post Back end
 * 
 * @author  Your Mohamad Ali MAKKEH <makkehma@hotmail.fr | https://gmartgroup.com/
 * @version 1.0.0
 * @license http://www.gnu.org/licenses/gpl-2.0.html
 */

global $places;

$places['LB'] = array( 
/* Province of Beirut */
  'BA' => array(
    'Tarik El Jdidet',
    'Kola (Musaitbeh)',
    'Nejmeh',
    'Majidiyeh',
    'Patriarcat',
    'Yassouiyeh',
    'Mar Maroun',
    'Gemmayze',
    'Jamia',
    'Joumblat',
    'Manara',
    'Raouche',
    'Zarif',
    'Tallet El Druz',
    'Dar El Fatwa',
    'Unesco',
    'Malaab',
    'El Horge',
    'Parc',
    'Aamiliyeh',
    'Furn El Hayek',
    'Nasra',
    'Hotel Dieu',
    'Mar Mitr',
    'Aadliyeh',
    'Sioufi',
    'Ghabi',
    'Cornich El Nahr',
    'Mar Nicolas',
    'Hikmat',
    'Orthodox Hospital',
    'Khodor',
    'Jisr',
    'Qobaiyat',
    'Snoubra',
    'Mar Mikhael',
    'Getawi',
    'Zaidanieh',
    'Ramlet El Baida',
    'Bab Idriss',
    'Aradi Jalloul',
    'Achrafieh',
    'Rmeil',
    'Medawar',
    'Marfaa',
    'Bachoura',
    'Saifi',
    'Ras Beirut',
    'Mouseitbeh',
    'Mazraa',
    'Zoukak El Blat',
    'Mina El Hosn',
    'Ein El Mreisseh',
    'Hamra',
    'Basta Faouqa',
    'Kola (Mazraa)',
    'Ras El Nabeh',
    'Sanayeh',
    'Qantari',
    'khandak Al Ghamik',
    'Tallet El Khayat',
    'Wata El Msaytbeh',
    'Borj Abi Haydar',
    'Ain El Tineh (Beirut)',
    'Sakiet El Janzir',
    'Barbour',
    'Shatila',
    'Badaro',
    'Verdun',
    'Noueiry',
    'Malla',
    'Qraytem',
    'Sadat',
    'Basta Tahta',
    'Mar Elias',
    'Saray',
    'Furn El Chebback',
    'Chyah',
    'Ghobeiry',
    'Ain El Remmaneh (Baabda)',
    'Borj El Barajneh',
    'Haret Hreik',
    'Roueiss',
    'Ouzaii',
    'Sfeir',
    'Mousharrafieh',
    'Gallery Semaan',
    'Jnah',
    'Tayouneh',
    'Bir Hasan',
    'Bir El Abed',
    'Hay Madi',
    'Borj Hammoud',
    'Sin El Fil',
    'Aaraya',
    'Shoueit',
    'Ras El Harf',
    'Haret Hamzeh',
    'Betchay',
    'Merdashi',
    'Haret El Sitt',
    'Wadi El Dlab',
    'Bsaba (Baabda)',
    'Wadi Chahrour',
    'Mrayjeh',
    'Laylaki',
    'Tahwitat El Ghadir',
    'Hadath (Baabda)',
    'Sebnieh',
    'Haret El Botm',
    'Baabda',
    'Hazmieh',
    'Louayzeh',
    'Kfarchima',
    'Hammana',
    'Falougha',
    'Khelwat Falougha',
    'Khraybeh',
    'Kalaa',
    'Baalshmay',
    'Roueiset El Ballout',
    'Ain Mouaffak',
    'Shamsieh',
    'Hlalieh',
    'Kbayh',
    'Karieh',
    'Kseibeh',
    'Ktaleh',
    'Aabadieh',
    'Btekhnay',
    'Kornayel',
    'Ras El Metn',
    'Salima',
    'Dlaybeh',
    'Bemrime',
    'Bzebdine',
    'Arsoun',
    'Deir El Harf',
    'Knayseh',
    'Zandouka',
    'Aarbanieh',
    'Kfarselwane',
    'Tarshish',
    'Jouar El Hoz',
    'Fayadieh',
    'Mar Takla',
    'Jamhour',
    'Brazilia',
    'Shbanieh',
    'Kahaleh',
    'Maamoura',
    'Hay EL Sullom',
    'Dhour El Shoueir',
    'Cocodi',
    'Raml El Aali',
    'Tahwitat El Nahr',
    'Dhour El Aabadieh',
    'Sahraa El Shoueifat',
    'Sahraa',
    'Tiro',
    'Hadath El Shmali',
    'Bramieh (Baabda)',
    'Kortada',
    'Mar Mikhael',
    'Aoukar',
  ),
/* Province of Mount Lebanon */
  'JL' => array(
    'Camp Maraach',
    'Camp Kilikia',
    'Camp Tomerza',
    'Camp Yozghad',
    'Sharee Siwas',
    'Camp Aghapios',
    'Camp Sis',
    'Camp Koliach',
    'Ghilane',
    'Nabaa',
    'Dekwaneh',
    'Jal El Hama',
    'Mazraat Maa El Heloueh',
    'Camp Byrat',
    'Camp Trad Al Kadim',
    'Bsefrine',
    'Zahrieh',
    'Baakrif',
    'Deir El Kalaa',
    'Mazraat Al Nakhleh',
    'Kseibeh',
    'Antelias',
    'Naccache',
    'Mtayleb',
    'Rabieh',
    'Bteghrine (Metn)',
    'Khenshara',
    'Mrouj',
    'Bolonia',
    'Khelleh',
    'Zaraoun',
    'Marjaba',
    'Zeghrine',
    'Ain El Teffaha',
    'Shouaya',
    'Jouar',
    'Shrine',
    'Ain El Safsaf',
    'Mar Mikhael',
    'Ras Nabeh Antelias',
    'Haret Wazen',
    'Haret Sheikh El Ghoueysat',
    'Balouh',
    'Beit Aayal',
    'Tabsheh',
    'Deir Mar Youhanna',
    'Baushrieh',
    'Baskinta',
    'Kfaraakab',
    'Wadi El Karm',
    'Mashraa',
    'Ain El Kabou',
    'Kfartay',
    'Zabbougha',
    'Mar Mitr Nabee El Saleh',
    'Mar Roukoz',
    'Broumana',
    'Ghabeh',
    'Jouret El Ballout',
    'Ouyoune',
    'Maska',
    'Mar Shaaya',
    'Dahr El Hosein',
    'Dbayeh',
    'Deir Aoukar',
    'Zouk El Khrab',
    'Haret El Bellaneh',
    'Ain Saadeh',
    'Roumieh',
    'Beit Mery',
    'Dhour Shoueir',
    'Ain El Sindyaneh',
    'Kaakour',
    'Deir Mar Abda Al Mshammar',
    'Wakf Dair Mar Gerges',
    'Mar Yousef El Borj',
    'Zalka',
    'Amaret Chalhoub',
    'Sakiat El Misk',
    'Bhersah',
    'Bikfaya',
    'Mhaydtheh',
    'Mayaseh',
    'Wadi Shahine',
    'Ain El Kharroubeh',
    'Hamlaya',
    'Douar',
    'Ayroun',
    'Mar Moussa',
    'Abou Mizane',
    'Deir Shamra',
    'Ain El Lokoch',
    'Shamis',
    'Jal El Dib',
    'Bkennaya',
    'Bsalim',
    'Majzoub',
    'Mezher',
    'Nabay',
    'Byakout',
    'Beit El Shaar',
    'Mazraat El Hadira',
    'Deir Tamish',
    'Kornet Shehwane',
    'Ain Aar (Metn)',
    'Beit El Kekko',
    'Dik El Mehdi',
    'Zakrit',
    'Kornet El Hamra',
    'Mazraat Yashouh',
    'Frikeh',
    'Aatchaneh',
    'Shaouyeh',
    'Ain Aalak',
    'Hbous',
    'Beit Chabab',
    'Mar Boutros',
    'Makhadah',
    'Sfayleh',
    'Jdeidet',
    'Aamarieh',
    'Fanar',
    'Mkalles',
    'Dayshounieh',
    'Mansourieh',
    'Baabdat',
    'Dahr El Sawwan',
    'Mtein',
    'Aintoura (Metn)',
    'Majdal Tarshish',
    'Bshellama',
    'Ain El Zaytouneh',
    'Mshikha',
    'Daoura (Metn)',
    'New Raouda',
    'Raouda',
    'Sabtieh',
    'Hadira',
    'Qennabet Broumana',
    'Beit Misk',
    'Aylout',
    'Elissar',
    'Bayada-Metn',
    'Sed El Baoushrieh',
    'Raboueh',
    'Aoukar',
    'Hasbaya (Metn)',
    'Jisr El Basha',
    'Kantara',
    'Monteverde',
    'Jdeidet (Roueissat)',
    'Shoueir',
    'Menshara',
    'Horsh Tabet',
    'Jisr El Wati',
    'Tehnaya',
    'Mazraat Bnabil',
    'Deir El Kamar',
    'khelwat Gernaya',
    'Haret El Naameh',
    'Maaser Bayteddine',
    'Kfarnabrakh',
    'Ain Aazimeh',
    'Ain w zein',
    'Bsayeh',
    'Batloun',
    'Farridess',
    'Barouk',
    'Ain Zhalta',
    'Aadays',
    'Nabeh El Safa',
    'Kafra',
    'Ain Abed',
    'Beayn',
    'Nahleh',
    'Kharroubeh',
    'Mreijat',
    'Kfarnis',
    'JADAYEL',
    'Shourit Kfarha',
    'Majdel El Meoush',
    'Boudine',
    'Shamshieh',
    'Shourit',
    'Bekftay',
    'Zahnan',
    'Bireh (Chouf)',
    'Wadi El Sit',
    'Brih',
    'Mtayleh',
    'Warhanieh',
    'Fawarah',
    'Kfar Hamal',
    'Kfar Katra',
    'Mazraat El Doueir',
    'Besnay',
    'Knayseh',
    'Deir Koushah',
    'Beshtfine',
    'Kfarfakoud',
    'Deir Baba',
    'Mghayrieh',
    'Dmit',
    'Baydar El Raml',
    'Kfarhim',
    'Ghabet Jaafar',
    'Aashkitah',
    'Shoueit',
    'Maaser El Shouf',
    'Bakrzieh',
    'Deir Dourit',
    'Srejbal',
    'Banawati (Chouf)',
    'Bekayaah',
    'Jahlieh',
    'Wadi El Dair',
    'Wadi Bnahlieh',
    'Ammik (Chouf)',
    'Baakline',
    'Aamatour',
    'Marj Bsarri',
    'Haret Jendol',
    'Jabali',
    'Bater',
    'Niha',
    'Mrasti',
    'Jbah',
    'Baadaran',
    'Khraybeh',
    'Ain Kani',
    'Batmah',
    'Mokhtara',
    'Jdeidet',
    'Baykoun',
    'Kahlouneh',
    'Mazraat El Chouf',
    'Aatrine',
    'Aanbal',
    'Ain El Nour',
    'Barghoutieh',
    'Aalman (Chouf)',
    'Rmeileh',
    'Mazraat Abou Yousef',
    'Jalileh',
    'Haret El Saouda',
    'Mazraat El Dahr',
    'Bekaata',
    'Damour',
    'Saadiat',
    'Boustane Yarouti',
    'Naameh',
    'Deir El Naameh',
    'Klayleh',
    'Zir',
    'Barja',
    'Jadra',
    'Ain El Hor',
    'Bkeshtine',
    'Borjein',
    'Debbieh',
    'Mshaayah',
    'Jieh',
    'Meksba',
    'Ksouba',
    'Wadi El Zineh',
    'Baasir',
    'Haret Baasire',
    'Dahr El Mghara',
    'Fokhtay',
    'Katalet Issa',
    'Baksi',
    'Shmaarine',
    'Bakaoun',
    'Bakhaoun (Chouf)',
    'Lahbieh',
    'Sayar',
    'Dalhmieh (Chouf)',
    'Waznieh',
    'Btal',
    'Meshref',
    'Matriat',
    'Daraya (Chouf)',
    'Terbla',
    'Bnamra',
    'Kherbet El Mrah',
    'Aanout',
    'Hasrout',
    'Zaarourieh',
    'Sebline',
    'Werdanieh',
    'Ketermaya',
    'Maanieh',
    'Ain El Asad',
    'Shamis',
    'Dalhoun',
    'Mazboud',
    'Ghrayfeh',
    'Bsaba (Chouf)',
    'Semkanieh',
    'Chehim',
    'Mazmoura',
    'Jabal Sweid',
    'El Qasr',
    'Jamilieh',
    'Joun',
    'Fathiyat',
    'Ghrifeh',
    'Kahlounieh',
    'Majdalouna',
    'Daouha',
    'Beiteddine',
    'Mtelleh',
    'Marj Barja',
    'Kfarbit',
    'Tannourine',
    'Shrine',
    'Bkifa',
    'Ain El Remmaneh (Aley)',
    'Ain El Jdeideh',
    'Ain Joueik',
    'Bkhechtay',
    'Aley',
    'Bhamdoun El Mhatta',
    'Rashmaya',
    'Ain Traz',
    'Shartoun',
    'Meghwaya',
    'Ghaboune',
    'Rajmeh',
    'Bejwarah',
    'Kfaraamayh',
    'Kalaa',
    'Saoufar',
    'Bhamdoun El Karieh',
    'Batloune',
    'Taazanieh',
    'Ain El Jawzeh (Aley)',
    'Ain Dara',
    'Maaysra',
    'Bmahrieh',
    'Aghmid',
    'Sharoun',
    'Sharkieh',
    'Bedghane',
    'Wadi Bedghane',
    'Majdel Baana',
    'Shanay',
    'Btater',
    'Ain El Halzoun',
    'Bserrine',
    'Rouayset El Naaman',
    'Deir Sir',
    'Aadayset Sir',
    'Maasrita',
    'Rmeileh',
    'Mazraat El Nahr',
    'Habramoun',
    'Ain El Farrides',
    'Aazounieh',
    'Mansourieh',
    'Ain El Marj',
    'Souk El Gharb',
    'Bemkine',
    'Kmatieh',
    'Kayfoun',
    'Baysour (Aley)',
    'Shemlane',
    'Aaynab',
    'Dfoun',
    'Remhala',
    'Ain Ksour',
    'Jisr El Kadi',
    'Abay',
    'Kfarmatta',
    'Bnayeh',
    'Ain Drafil',
    'Majdlaya',
    'Selfaya',
    'Doueir El Remmane',
    'Mazraat Hammoud',
    'Bou Zreideh',
    'Aytat',
    'Choueifat',
    'Deir Koubel',
    'Bshamoun',
    'Ain Aanoub',
    'Aramoun (Aley)',
    'Fesakine',
    'Baourta',
    'Bouar Eddine',
    'Dkoun',
    'Srehmol',
    'Kahaleh',
    'Bsous',
    'Haret Salem',
    'Bdadoune',
    'Houmale',
    'Blaybel',
    'Daouhat Aramoun',
    'Aamrousieh',
    'Mashraka',
    'Kabrshmoun',
    'Saray',
    'Jamhour (Aley)',
    'Basatine',
    'Khalde',
    'Kobbeh',
    'Ain El Sayde',
    'Oumaraa',
    'Ghadir',
    'Meshref',
    'Rshikha',
    'Meshrefeh',
    'Ghadir',
    'Sahel Alma',
    'Safra',
    'Ghosta',
    'Bkakeddine',
    'Bouar',
    'Daraoun',
    'Wata El Salam',
    'Kfaryassine',
    'Raashine',
    'Wata El Joz',
    'Bzoummar',
    'Ain El Delbeh (Keserwan)',
    'Tabarja',
    'Batha',
    'Adma',
    'Defneh',
    'Harisa',
    'Ghazir',
    'Aramoun (Keserwan)',
    'Harharya',
    'Kettine',
    'Jdeidet Ghazir',
    'Sarba',
    'Haret Sakhr',
    'Dlebta',
    'Maarab',
    'Kfour',
    'Ghineh',
    'Jouret El Termos',
    'Ghbaleh',
    'Yahshoush',
    'Azraa',
    'Zaaytre',
    'Shahtoul',
    'Zaitoun',
    'Nammoura',
    'Hayatta',
    'Mradieh',
    'Maaysrah',
    'Jouret Bedran',
    'Hsein',
    'Shnaniir',
    'Fatka',
    'Nahr El Zahab',
    'Ghedras',
    'Bezhol',
    'Shouan',
    'Jouret Mhad',
    'Zouk Mosbeh',
    'Rayfoun',
    'Ajaltoun',
    'Kleiaat',
    'Feytroun',
    'Mazraat Kfarzebian',
    'Bkaatouta',
    'Bekaatat Kenaan',
    'Kfartay',
    'Daraya (Keserwan)',
    'Zouk Mikael',
    'Shayleh',
    'Jeita',
    'Aintoura (Keserwan)',
    'Ballouneh',
    'Ain El Rihaneh',
    'Mar Elias El Ras',
    'Ashkout',
    'Faraya',
    'Mayrouba',
    'Hrajel',
    'Bekaatat Ashkout',
    'Jounieh',
    'Kfarhbab',
    'Maameltein',
    'Jbeil',
    'Kaslik',
    'Kharaeb Nahr Ibrahim',
    'Maghayer',
    'Adonis (Jounieh)',
    'Okeybeh',
    'Bahwita',
    'Adma W El Dafneh',
    'Ghora',
    'Tertej',
    'Jbeil',
    'Hbaline',
    'Rihanieh',
    'Kfarkeddeh',
    'Gharfine',
    'Aydamoune (Jbeil)',
    'Bekhaaz',
    'Monsef',
    'Jdayel',
    'Hosrayel',
    'Kor El Hawa',
    'Gharzouz',
    'Fghal',
    'Berbara (Jbeil)',
    'Shikhane',
    'Maad',
    'Shammout',
    'Jaliseh',
    'Sebrine',
    'Bmahrine',
    'Breij',
    'Hboub',
    'Karkaz',
    'Jonjol',
    'Haret Jahjah',
    'Deir El Banat',
    'Mazraat El Khraybeh',
    'Jouret El Kettine',
    'Jisr El Djaj',
    'Bejrein',
    'Halat',
    'Fidar',
    'Shaabaya',
    'Syrane',
    'Maaytik',
    'Halb (Jbeil)',
    'Mrah',
    'Doueir (Jbeil)',
    'Ftah El Mir',
    'Harf (Jbeil)',
    'Nahr Ibrahim',
    'Ain Kfah',
    'Ghbaline',
    'Hsarat',
    'Raskifa',
    'Bejjeh',
    'Amchit (Jbeil)',
    'Ghalboun',
    'Edde (Jbeil)',
    'Kfar Kewas',
    'Kfarhatti',
    'Beit El Ghazal',
    'Blat (Jbeil)',
    'Aynata (Jbeil)',
    'Bkedna',
    'Kartboune',
    'Mastita',
    'Kfar Klas',
    'Kfarzbouna',
    'Madamit',
    'Akoura',
    'Ghabat',
    'Roueiss',
    'Shouata',
    'Sakiet El Khayt',
    'Ramout',
    'Beit Hbak',
    'Saydet Habil',
    'Mazraat El Jamil',
    'Kfarmshhoune',
    'Aabadat',
    'Wadi El Kalb',
    'Shamat',
    'Bentael',
    'Fouar (Jbeil)',
    'Kharbeh',
    'Jaj',
    'Tertej',
    'Fetry/ Bir El Hayth',
    'Aalita',
    'Lehfod',
    'Saka Rashmaya',
    'Habil',
    'Mayfouk',
    'Laklouk',
    'Bahdaydat',
    'Kfoun',
    'Meshmesh',
    'Mar Zakhia',
    'Hakel',
    'Deir Al Kattara',
    'Kafr',
    'Mar Gergeos El Kafr',
    'Hjoula',
    'Jrabta',
    'Hosn Aar',
    'Berket Hjoula',
    'Ain Aar (Jbeil)',
    'Beshtlida',
    'Mrah El Saghir',
    'Kfarshbouh',
    'Zebdine',
    'Hakl El Tineh',
    'Hakl El Ain',
    'Moftah El Selm',
    'Kartaba',
    'Hdineh',
    'Tedmor',
    'Berhol',
    'Karkarya',
    'Sariita',
    'Kohmoz',
    'Afka',
    'Lasa',
    'Jannet Mar Sarkis',
    'Mar Sarkis',
    'Aalmat',
    'Mejdel',
    'Mnaytra',
    'Mshan',
    'Bshally',
    'Ehmej',
    'Aanaya',
    'Adonis (Jbeil)',
    'Mazraat El Syad',
    'Oueyni',
    'Dmalsa',
    'Mechehlan',
    'النمورة',
    'Nammoura',
    'Baziyoun',
    'Ghaboun',
    'Hsoun',
    'Kfersala',
    'Bahha',
    'Mghayri',
    'Ras Asta',
    'Ain El Delbeh (Jbeil)',
    'Bezboun',
    'Ain El Koubieh',
    'Ain El Shellal',
    'Rimah',
    'Tannourine',
    'Yanouh',
    'Halliseh',
    'Obeidat',
  ),
 /* Province of North Lebanon */
  'AS' => array(
    'Tripoli',
    'Wabel',
    'Minaa',
    'Menieh',
    'Beddawi',
    'Kobbeh',
    'Malouleh',
    'Tebbaneh',
    'Tall',
    'Kalamoun',
    'Bkerhadna',
    'Hakl El Azimah',
    'Abi Samra',
    'Zahrieh',
    'Nouri',
    'Tripoli Center',
    'Basloukit',
    'Aazki',
    'Dennieh',
    'Baal Mehsen',
    'Souaykah',
    'Khannaka',
    'Manara',
    'Mounla',
    'Jabal Mehsen',
    'Hdadine (Tripoli)',
    'Tarbiha',
    'Bkamra',
    'Bab El Raml',
    'Zahr Bteghrine',
    'Bhanine (Tripoli)',
    'Yahsa',
    'Basatin Tripoli',
    'Hawaret Trablos',
    'Mahatrah',
    'Askeleh',
    'Remmaneh',
    'Maalaka Al Shimali',
    'Ayto',
    'Draya (Tripoli)',
    'Amioun',
    'Enfeh',
    'Kalbata',
    'Bziza',
    'Balamand',
    'Betroumine (Koura)',
    'Bahsas',
    'Deddeh',
    'Beshmezzine',
    'Kousba',
    'Bterram',
    'Dahr El Ain',
    'Nakhleh',
    'Barsa',
    'Ras Maska',
    'Haykalieh',
    'Btouratij',
    'Hraysheh',
    'Kfar Hazir',
    'Kfar Aakka',
    'Fih',
    'Kfar Kahel',
    'Samrieh',
    'Aaba',
    'Bsarma',
    'Bedba',
    'Reshdbine',
    'Dar Baachtar',
    'Bahboush',
    'Aafsdik',
    'Kfarsaroun',
    'Kalhat',
    'Bazghoun',
    'Mejdel',
    'Kefraya',
    'Kfarhata',
    'Ain Akrine',
    'Bednayel',
    'Bkeftine',
    'Metrit',
    'Bekayaa',
    'Mogher El Ahwal',
    'Zakroun',
    'Haret El Khassa',
    'Ajd Ebrine',
    'Barghoune',
    'Rashdine',
    'Hamat (Koura)',
    'Torza',
    'Ras Sakka',
    'Kfarhazir',
    'Kfarkahel',
    'Kaftoun',
    'Dhour El Hawa',
    'Bnehrane',
    'Haret El Khata',
    'Zghorta El Mtawleh',
    'Bdayhoun',
    'Hatrit',
    'Btaaboura',
    'Zghorta',
    'Ehden',
    'Miziyara',
    'Kfarhata',
    'Bcharry (Zghorta)',
    'Aanas',
    'Meryata',
    'Aakabeh (Zghorta)',
    'Majdlaya',
    'Sereol',
    'Kfarzayna',
    'Sebeol',
    'Khaldieh',
    'Rashiine',
    'Aashash',
    'Ardeh',
    'Kfaryashite',
    'Bnaachi',
    'Alma',
    'Kfardlakos',
    'Kfarsghab',
    'Al Houwara',
    'Sakhra',
    'Bsebaal',
    'Beshnine',
    'Karrah Bash',
    'Mazraat El Faradis',
    'Zgharteghrine',
    'Hawka',
    'Aslout',
    'Hilan',
    'Al Ayrounieh',
    'Hawara',
    'Hraykes',
    'Toula',
    'Harf Ardeh',
    'Fouar (Zghorta)',
    'Bayader',
    'Kfarfo',
    'Hay Al Maaser',
    'Ras Kifa',
    'Daraya (Zghorta)',
    'Karm Sadda',
    'Aarjos',
    'Arabet Kezhaya',
    'Kfarhaoura',
    'Sebiin',
    'Iyaal',
    'Kfarshakhna',
    'Marh Kfarsghab',
    'Mazraat El Toufah',
    'Salib Al Shemali',
    'Saydeh El Sharki',
    'Abto',
    'Mazraat El Nahr',
    'Karmada',
    'Asfoun',
    'Kefraya',
    'Ejbeh',
    'Batroun',
    'Kfaraabay',
    'Chekka',
    'Kfaraabida',
    'Thoum',
    'Al Heri',
    'Bejderfel',
    'Smar Jbeil',
    'Tannourine',
    'Ebrine',
    'Kour',
    'kabba',
    'Wajh El Hajar',
    'Shabtine',
    'Edde (Batroun)',
    'Bkesmaya',
    'Fattahat',
    'Besbina',
    'Mrah El Zayat',
    'Abdalli',
    'Hamat (Batroun)',
    'Selaata',
    'Douma',
    'Rashana',
    'Ram',
    'Sghar',
    'Dael',
    'Chnata El Fawka',
    'Chnata El Tahta',
    'Hadtoun',
    'Beshaaleh',
    'Ras Nhash',
    'Jebla',
    'Amya',
    'Ajdabra',
    'Rashkida',
    'Rasnhash',
    'Beshtekdar',
    'Wata Houb',
    'Aalali',
    'Deir Bella',
    'Kfarhay',
    'Kfarhalda',
    'Beit Shlala',
    'Beshtoudar',
    'Mrah Chdid',
    'Zan',
    'Jran',
    'Kfour El Aarabi',
    'Saourat',
    'Niha',
    'Rashkdeh',
    'Ghouma',
    'Mhomrosh',
    'Kfarshilman',
    'Kfayfane',
    'Draya (Batroun)',
    'Kouba',
    'Dahr Abi Yaghi',
    'Sardine',
    'Toula',
    'Zouk',
    'Kfarhatna',
    'Sfar',
    'Shatine',
    'Hardine',
    'Mar Mama',
    'Douk',
    'Halta',
    'Jrabta',
    'Kfarhami',
    'Hourane',
    'Asia',
    'Akkar Al Atika',
    'Meniara',
    'Ain El Zayt',
    'Rahbeh',
    'Sheikh Taba',
    'Bebnine',
    'Betroumine (Akkar)',
    'Mezdayeb',
    'Kobayat',
    'Halba',
    'Aaboudieh',
    'Berkael',
    'Sheikh Mouhamad',
    'Tekrit',
    'Aabdeh',
    'Deir Dloum',
    'Shadra',
    'Ain Yaacoub',
    'Mhamra',
    'Haoushab',
    'Arida',
    'Aydamoune (Akkar)',
    'Andket',
    'Bkerzla',
    'Dousa',
    'Mashta Hammoud',
    'Danke',
    'Majdel',
    'Sahle',
    'Kouaikhat',
    'Mashta Hassan',
    'Al Daghle',
    'Klayaat',
    'Sheikh Znad',
    'Ain Tenta',
    'Ghzayle',
    'Kfar Harra',
    'Ain El Dahab',
    'Kashlak',
    'Saysouk',
    'Knaiset El Sahel',
    'Al Semmakieh',
    'Tall Hayat',
    'Bireh (Akkar)',
    'Jdeidet El Jouma',
    'Kaabarine',
    'Mar Touma',
    'Kousha',
    'Menjez',
    'Kayteh',
    'Mounseh',
    'Bohsa',
    'Dahr El Laysineh',
    'Zwarib',
    'Sfaynet El Kaytea',
    'Haytla',
    'Bayt El Haouch',
    'Kaabrine Al Charkieh',
    'Ilat',
    'Zouk El Habalssa',
    'Meshmesh',
    'Kebiit',
    'Shekka Hamoud',
    'Shir Hamiraine',
    'Hmayra',
    'Karzalla',
    'Karm Asfour',
    'Baino',
    'Bezbina',
    'Borj',
    'Daoura (Akkar)',
    'Aayat',
    'Dbabieh',
    'Mazraat Al Baldeh',
    'Hayzouk',
    'Rmah',
    'Beit Mlat',
    'Jdeidet',
    'Zwarine',
    'Taalbas El Gharbi',
    'Hakour',
    'Gebrayel',
    'Talmiaane',
    'Odbol',
    'Korkof',
    'Kfartoun',
    'Mashha',
    'Zouk El Kasharine',
    'Karzayla',
    'Tallet Weshtaha',
    'Haysah',
    'Beit Ayoub',
    'Tall Bira',
    'Tal Hmayra',
    'Beit Younes',
    'Arka',
    'Tlayl',
    'Tasheh',
    'Kboula',
    'Wadi El Jamous',
    'Sharbila',
    'Kariat',
    'Zouk Hdadeh',
    'Knaya',
    'Deir Jennine',
    'Majdala',
    'Noura',
    'Sheikh Lara',
    'Nafiseh',
    'Semmakieh',
    'Shaikh Znad',
    'Souaykah',
    'Akroum',
    'Wadi Kahled',
    'Khraybet El Jundi',
    'Had',
    'Kantara',
    'Bzal',
    'Souaida',
    'Saadine',
    'Aamar Al Baykat',
    'Dahr Hdara',
    'Darine',
    'Memneh',
    'Ghouaya',
    'Mkayteh Kfarmalkeh',
    'Habshit',
    'Ouyoune',
    'Borj Al Arab',
    'Korneh',
    'Shan',
    'Beit Aatas',
    'Masaoudieh',
    'Jdeidet El Kayteh',
    'Oueinat',
    'Siouf',
    'Hadid',
    'Kroum Arab',
    'Fnaydek',
    'Zek Al Maatrina',
    'Hrar',
    'Beit El Hajj',
    'Zghataa',
    'Rihanieh',
    'Dahr El Konbor',
    'Nahrieh',
    'Kwashra',
    'Doueir Adaouiyah',
    'Sindyaneh',
    'Kfar Melki',
    'Houeish',
    'Rimanieh',
    'Ouyoun El Ghezlane',
    'Kobbet Shamra',
    'Khreibet Daod',
    'Hadshab',
    'Makhbaz',
    'Tall Abbas Charkieh',
    'Bcharry',
    'Wadi Qannoubine',
    'Blawza',
    'Hadath El Jebbeh',
    'Sarafand',
    'Hadshit',
    'Karkash',
    'Beit Monzer',
    'Dimane',
    'Brahlioune',
    'Hasroun',
    'Mar Saba',
    'Ban',
    'Bazaoun',
    'Hay Al Saydeh (Bcharee)',
    'Abdine',
    'Hay Mar Youhanna',
    'Braysat',
    'Knat',
    'Bekaa Kafra',
    'Hdadine (Bcharee)',
    'Sir',
    'Safira',
    'Deir Aamar',
    'Bkarsouna',
    'Kfar Hebbo',
    'Aimar',
    'Asoun',
    'Bkaasefrine',
    'Markebta',
    'Taran',
    'Btormaz',
    'Deir Nbouh',
    'Mrah El Sraj',
    'Bakhaoun (Tripoli)',
    'Kfar Chellane',
    'Menieh -Nabi Youchaa',
  ),
/* Province of South Lebanon */
'JA' => array(
    'Dekerman',
    'Maamarieh',
    'Hajjeh',
    'Arky',
    'Aktanite',
    'Matariet Jbah',
    'Bnaafoul',
    'Ankoun',
    'Wasta',
    'Ghassanieh',
    'Sari',
    'Snayber',
    'Deir Takla',
    'Jdeidet (Saida)',
    'Tebneh',
    'Wastani Saida',
    'Kawthariet El Siyad',
    'Kawthariet El Riz',
    'Kaakariet El Sanaoubar',
    'Kfar Baddah',
    'Msayleh',
    'loubieh',
    'Marwanieh',
    'Boustane El Sheikh',
    'Mrah Kiwan',
    'Aarnaya',
    'Maksam El Jawhari',
    'Jal Ajram',
    'Maksam El Bizri',
    'Maksam El Zein',
    'Karm El Hanash',
    'Teffahta',
    'Khazir',
    'Zita',
    'Abra',
    'Salhieh',
    'Kefraya',
    'Bkasta',
    'Jamjim',
    'Hartieh',
    'Sini',
    'Matriyet El Shawmar',
    'Yahoudieh',
    'Jazira',
    'Majdaloun',
    'Hama',
    'Arab El Jall',
    'Arab Succar',
    'Khnousieh',
    'Kfar Djal',
    'Khobet Kataeb',
    'Kherbet El Basal',
    'Hbabieh',
    'Wisamiyat',
    'Daoudieh',
    'Maktounieh',
    'Baslaya',
    'Jenjlaya',
    'Mieh W Mieh',
    'Maghdousheh',
    'Tanbourite',
    'Darb El Sim',
    'Zghedraya',
    'Kfarbit',
    'Ain El Delb',
    'Karieh',
    'Barti',
    'Sfenty',
    'Kfar Melki',
    'Mazraat Tebaya',
    'Kfar Chlal',
    'Mazraat Iskandaroun',
    'Ain Al Kantara',
    'Mhaydleh',
    'Meghraka',
    'Husseinieh',
    'Hara',
    'Hlalyeh',
    'Ghazieh',
    'Saksakieh',
    'Adloun',
    'Knarit',
    'Sarafand',
    'Zrarieh',
    'Arzi',
    'Maamariet El Khrab',
    'Bablieh',
    'Ansarieh',
    'Kharayeb',
    'Khartoum',
    'Najjarieh',
    'Adoussieh',
    'Bramieh (Saida)',
    'Brak El Tall',
    'Yasarieh',
    'Kherbet El Dair',
    'Ain El Heloueh',
    'Wadi El Zayina',
    'Kiyaa',
    'Baysarieh',
    'Haret Saida',
    'Zoueitini',
    'Boustan El Kabir',
    'Aaqbieh',
    'Aytanieh',
    'Kfarhatta',
    'Tebbaya',
    'Saida',
    'Kbaa',
    'Sharhabil',
    'Sayroub',
    'Zahrani',
    'Manzaket El Wastani',
    'Shaaytieh',
    'Msalkhieh',
    'Kochk',
    'Rjal El Arbeein',
    'Kanan',
    'Kafrit',
    'Majdelyoun',
    'Kfarmatta',
    'Sabil',
    'Saray',
    'Ghaziz',
    'Shakra',
    'Kennayeh',
    'Sharee',
    'Maksar El Abd',
    'Zoutini',
    'Mar Nicolas',
    'Baysour (Saida)',
    'Jal El Bahr',
    'Sour',
    'Kleileh',
    'Omrane',
    'Hanieh',
    'Aazieh',
    'Alma El Shaab',
    'Btayshieh',
    'Mansoura',
    'Mahal Zouein',
    'Jabine',
    'Dahr El Bayada',
    'Saymine',
    'Byout El Sayed',
    'Zahira',
    'Biyada',
    'Tayr Harfa',
    'Nakoura',
    'Iskandaroun',
    'Yarine',
    'Om Toutah',
    'Abou Shish',
    'Oum Al Rab',
    'Layouneh',
    'Jamjim',
    'Hamoul',
    'Marwahine',
    'Boustane',
    'Maashouk',
    'Rashidieh',
    'Ras El knieh',
    'Hosh',
    'Ain Baal',
    'Hanouiyeh',
    'Knayseh',
    'Deir Kanoun',
    'Ras El Ain',
    'Shaaytieh',
    'Samaiyeh',
    'Maallalieh',
    'Ramlieh',
    'Jbal El Botm',
    'Taybeh',
    'Shernay',
    'Batouli',
    'Debbas',
    'Ramadieh',
    'Malkiet El Sahel',
    'Zabkine',
    'Hamarieh',
    'Borghlieh',
    'Mhayleb',
    'Bedias',
    'Ain Abou Abdallah',
    'Jouar El Nakhl',
    'Borj El Hawa',
    'Borj El Shemaly',
    'Borj El Kobli',
    'Jouaya',
    'Aaytit',
    'Taoura',
    'Mahrouneh',
    'Barish',
    'Deir Kifa',
    'Shhabieh',
    'Deir Semhat',
    'Mjadel',
    'Yanouh',
    'Sikket Basma',
    'Aabbassieh',
    'Toueyri',
    'Ain El Zarka',
    'Borj Rahhal',
    'Nfakhieh',
    'Baflieh',
    'Bestiat',
    'Shhour',
    'Deir Aas',
    'Biyad (Tyr)',
    'Wardani',
    'Reshknanieh',
    'Saddikine',
    'Hmayra',
    'Mazraat Meshref',
    'Kana',
    'Deir Kanoun El Nahr',
    'Maarakeh',
    'Hennata',
    'Wadi Jilo',
    'Derdkaya',
    'Rafid',
    'Marnaba',
    'Maaroub',
    'Salaa',
    'Srifa',
    'Niha',
    'Kfartay',
    'Arzoun',
    'Debaal',
    'Tayr Felsieh',
    'Zaloutieh',
    'Hallousieh',
    'Batoulieh',
    'Bass',
    'Klayleh',
    'Kasmieh',
    'Bazourieh',
    'Masaken',
    'Shibriha',
    'Tayr Debba',
    'Majdal Zoun',
    'Jenatta',
    'Hay El Jameh',
    'Shameh',
    'Hay El Orthodox',
    'Shihine',
    'Hay El Joura',
    'Hay El Mawarneh',
    'Hay El Catholique',
    'Hay El Husseinieh (Tyr)',
    'Hay Al Manara',
    'Jezzine',
    'Kfarhouna',
    'Rihane',
    'Aramta',
    'Aadou',
    'Likh',
    'Louayzeh',
    'Aiychieh',
    'Aazybeh',
    'Horty',
    'Daraya (Jezzine)',
    'Mlita',
    'Tamra',
    'Khelet Hasah',
    'Mahmoudieh',
    'Wazannieh',
    'Soueyri',
    'Zeghrine',
    'Katrani',
    'Shbeil',
    'Aarkoub',
    'Wazid',
    'Ain El Shafra',
    'Aknata',
    'Demashkieh',
    'Azimeh',
    'Karouh',
    'Wardieh',
    'Ain Majdline',
    'Srayreh',
    'Jark',
    'Mazraat El Rohbane',
    'Mazraa (Jezzine)',
    'Sojod',
    'Kaytouli',
    'Kobeh',
    'Saydoun',
    'Sennieh',
    'Baalieh',
    'Zhalti',
    'Kettine',
    'Haydab',
    'Maknounieh',
    'Kherkhaya',
    'Haytoura',
    'Homsieh',
    'Rimate',
    'Shkadif',
    'Dahr El Dair',
    'Bkassine',
    'Bsarri',
    'Tafid',
    'Midane',
    'Houranieh',
    'Mankaleh',
    'Jal Nashi',
    'Rekhsa',
    'Aazour',
    'Baba',
    'Jernaya',
    'Wadi Baankoudeine',
    'Baysour (Jezzine)',
    'Mjaydel',
    'Jenesnaya',
    'Anane',
    'Kalaat Abou El Hesen',
    'Rouous El Ifranj',
    'Shoualik',
    'Karkha',
    'Kfarjarra',
    'Lebaa',
    'Kfarfalous',
    'Marous',
    'Jouwanieh',
    'Branieh',
    'Mathanet El Watawit',
    'Ain El Mir',
    'Wadi El Laymoun',
    'Haytouli',
    'Bteddine El Kash',
    'Mashmousheh',
    'Maharbieh',
    'Hasanieh',
    'Mazraat El Mathaneh',
    'Harf (Jezzine)',
    'Saydet Mashmousheh',
    'Salima',
    'Roum',
    'Bhanine (Jezzine)',
    'Aarieh',
    'Shamikha',
    'Kfar Takla',
    'Roummaneh',
    'Masous',
    'Hawatieh',
    'Jabal Tora',
    'Ghbatieh',
    'Wadi El Zein',
    'Taoura El Sous',
    'Banawati (Jezzine)',
    'Ktaleh',
    'Baanoub',
    'Mathanet Seifeddine',
    'Borghol',
    'Sfarieh',
    'Mrah El Hbas',
    'Sabah',
    'Kfarjabra',
    'Taaid',
  ),
 /* Province of Bikaa */
'BI' => array(
    'Maalaka',
    'kark Nouh',
    'Ablah',
    'Niha',
    'Nabi Ayla',
    'Hosh Hala',
    'Hosh El Fikani',
    'Nasirieh',
    'Kousaya',
    'Masa',
    'Kfarzebd',
    'Tall Aamara',
    'Deir El Ghazal',
    'Dalhmieh (Zahle)',
    'Midane',
    'Saydet Al Najat',
    'Mar Antonios',
    'Hosh Al Zaraeneh',
    'Bar Elias',
    'Hoshmosh',
    'Terbol',
    'Majdal Anjar',
    'Hosh Moussa',
    'Berbara (Zahle)',
    'Saadnael',
    'Taalbaya',
    'Zobdol',
    'Taanael',
    'Wadi El Aarayech',
    'Hosh Al Oumara',
    'Jdita',
    'Chtoura',
    'Maksi',
    'Jlala',
    'Ksara',
    'Kaml',
    'Touiti',
    'Mreijat',
    'Bouarej',
    'Kab Elias',
    'Wadi El Delm',
    'Nasriet Tabet',
    'Biyad (Zahle)',
    'Siday',
    'Tal Al Akhdar',
    'Knaiytra',
    'Hwash',
    'Ajramouche',
    'Forzol',
    'Ali El Nahri',
    'Mar Elias',
    'Rasieh',
    'Aradi Zahle',
    'Hzarta',
    'Kaa El Rim',
    'Mar Gerges',
    'Mar Mikhael',
    'Raayt',
    'Riyak',
    'Masnaa',
    'Kferdane',
    'Karak',
    'Hosh El Ghanam',
    'Zahle',
    'Ain Ksein',
    'Faour',
    'Industrial City',
    'Dahr El Jamal',
    'Anjar',
    'Kherbet Kanafar',
    'Hay Al Saydeh (Zahle)',
    'Karmeh',
    'Beit Lahia (Zahle)',
    'Hadad El Zarka',
    'Rashaya',
    'Beshwat (Zahle)',
    'Jeb Jannine',
    'Raouda',
    'Bab Mareh',
    'Baaloul',
    'Tall Znoub',
    'Manara',
    'Hosh El Harimeh',
    'Wakf',
    'Halimeh El Soughra',
    'Jazira',
    'Hanout Al Midanieh',
    'Khiyara',
    'Kherbet Kanafar',
    'Dakoueh',
    'Deir Tahniche',
    'Zellaya',
    'Sohmor',
    'Sultan Yaacoub',
    'Ammik (West Bekaa)',
    'Aana',
    'Ain Zebdeh',
    'Aytanite',
    'Ain El Tineh (West Bekaa)',
    'Ghazza (West Bekaa)',
    'Karaoun',
    'Klieh',
    'Kamed El Laouz',
    'Lebbaya',
    'Lala',
    'Lousieh',
    'Marj',
    'Mansoura',
    'Mashghara',
    'Maydoun',
    'Yohmor',
    'Deir Ain El Jawzeh',
    'Kefraya',
    'Soueira',
    'Saghbine',
    'Istabel',
    'Hammara',
    'Amchit (West Bekaa)',
    'Kfardnis',
    'Kaoukaba',
    'Ain Aata (West Bekaa)',
    'Baalbeck',
    'Deir El Ahmar',
    'Safra',
    'Shaat',
    'Zabboud',
    'Sabbouya',
    'Knayseh',
    'Maaysrah',
    'Shlifa',
    'Btedehi',
    'Barka',
    'Aynata (Baalbeck)',
    'Nahleh',
    'Laboueh',
    'Ersal',
    'Nabi Othman',
    'Ain',
    'Ras Baalbeck',
    'Kaa',
    'Hlebta',
    'Majdaloun',
    'Shmestar',
    'Yammouneh',
    'Douris',
    'Brital',
    'Yahfoufa',
    'Toufail',
    'Saraain',
    'Nabi Shit',
    'Bednayel',
    'Temnine El Tahta',
    'Bouday',
    'Eyaat',
    'Fakiha',
    'Ksarnaba',
    'Khodr',
    'Beit Shama',
    'Hosh Al Snid',
    'Jenta',
    'Temnine El Fawaa',
    'Hallanieh',
    'Klaile And Harfoush',
    'Amhazieh',
    'Saidi',
    'Hosh El Nabi',
    'Hadath (Baalbeck)',
    'Hortaala',
    'Hoch El Rafka',
    'Beit Msheik',
    'Taoufikieh',
    'Talia',
    'Taraya',
    'Maarboune',
    'Khraybeh',
    'Rish El Gharbi',
    'Nabi Rashad',
    'Younine',
    'Mekneh',
    'Taybeh',
    'Hosh Barada',
    'Hosh Tall Safiah',
    'Taalbaya',
    'Nabi Inaam',
    'Jdeidet',
    'Beshwat (Baalbeck)',
    'Ain El Jawzeh (Baalbeck)',
    'Zarazir',
    'Hezzine',
    'Gherfeh',
    'Mahalet El Sejn Berbara',
    'Hay El Rish',
    'Ras El Ain',
    'Hay El Shams',
    'Mazraat Abou Slaybi',
    'Ansar (Baalbeck)',
    'Ram',
    'Nabi Sbat',
    'Kdam',
    'Niha',
    'Nabi Neam',
    'Hrabta',
    'Hay El Solh',
    'Wadi Mefarra',
    'Hosh Hala',
    'Mahalet El Masihiyine',
    'Ghefra',
    'Hay El Brak',
    'Safri',
    'Kferdane',
    'Riha',
    'Aallak',
    'Srabta',
    'Jabbouleh',
    'Masnaa Al Zahra',
    'Elaf',
    'Hbanieh',
    'Boueida',
    'Bteghrine (Baalbeck)',
    'Ain El Saouda',
    'Kfardabch',
    'Flawi',
    'Hay Ghafra',
    'Hermel',
    'Hmayra',
    'Shawaghir',
    'Sharbine',
    'Kouweikh',
    'Ras El Serj',
    'Hay El Hara',
    'Yahfoufa',
    'Wadi El Karm',
    'Hay El Wakf',
    'Boueida Al Shimalieh',
    'Wadi El Ratl',
    'Sharkieh',
    'Hay Bdita',
    'Mazraat El Fakih',
    'Zeghrine',
    'Brisa',
    'Beshwane',
    'Kasr',
    'Wadi El Zein',
    'Wadi Bnit',
    'Wadi El Torkman',
    'Zoueitini',
    'Rashaya',
    'Bireh (Rachaya)',
    'Dahr El Ahmar',
    'Jeb Farah',
    'Iiha',
    'Nafoura',
    'Kfarmashki',
    'Ayta El Fakhar',
    'Kherbet Rouha',
    'Rafid',
    'Mhaydtheh',
    'Rashaya El Wadi',
    'Kfarkouk',
    'Kfardines',
    'Beit Lahia (Rachaya)',
    'Bkifa',
    'Yanta',
    'Ain Aata (Rachaya)',
    'Mdawakh',
    'Ain Harshah',
    'Tannoura',
    'Hay El Midane',
    'Majdel Balkis',
    'Aakabeh (Rachaya)',
    'Heloueh',
    'Hosh',
    'Shebaa',
  ),
/* Province of Nabatieh */
'NB' => array(
    'Nabatieh',
    'Mayfadoun',
    'Shoukine',
    'Adshit',
    'Kseibeh',
    'Kfarsir',
    'Kaakaaiyet El Jisr',
    'Braykeh',
    'Syr El Gharbieh',
    'Kfartebnite',
    'Arnoune',
    'Yohmor',
    'Zaotar El Charkieh',
    'Zaoutar El Gharbieh',
    'Shkif',
    'Kfar Djal',
    'Kfarremmane',
    'Arab Slim',
    'Jarjouh',
    'Ain Besouar',
    'Jbah',
    'Ain kana',
    'Kfar Fila',
    'Houmine',
    'Sarba',
    'Roumine',
    'Habboush',
    'Deir Al Zahrani',
    'Bfaroueh',
    'Nmeirieh',
    'Zefta',
    'Khraybeh',
    'Biyad (Nabatieh)',
    'Hmeilah',
    'Aazzah',
    'Msayleh',
    'Doueir (Nabatieh)',
    'Zebdine',
    'Sharkieh',
    'Jebchit',
    'Kfarjaouz',
    'Al Najariah',
    'Toul',
    'Aaba (Nabatieh)',
    'Harouf',
    'Ansar (Nabatieh)',
    'Kfour',
    'Ghazza (Nabatieh)',
    'Kaakaiyeh',
    'Bint Jbeil',
    'Beit Lif',
    'Debl',
    'Oumaya',
    'Katmoun',
    'Aytaroun',
    'Aynata (Bent Jbeil)',
    'Maroun El Ras',
    'Ayta El Shaab',
    'Ramieh',
    'Beit Yahoun',
    'Hanine',
    'Rmeish',
    'Sammoukha',
    'Jbab Al Arab',
    'Tayri',
    'Ain Ebel',
    'Kounine',
    'Yaroun',
    'Kozah',
    'Hmayri',
    'Salhani',
    'Tebnine',
    'Borj Kalouieh',
    'Hdatha',
    'Kherbet Selm',
    'Rshaf',
    'Safad Al Batikh',
    'Kalawiyah',
    'Froun',
    'Yater',
    'Kfardounine',
    'Braashit',
    'Jmayjmeh',
    'Harise',
    'Deir Antar',
    'Sarbine',
    'Ghandourieh',
    'Ayta El Zot',
    'Kafra',
    'Yahoudieh',
    'Shakra',
    'Doubieh',
    'Sultanieh',
    'Ain El Saghirah',
    'Hay El Hwara',
    'Hay El Husseinieh (Bent Jbail)',
    'Hay El Birkeh',
    'Hay El Hdadeh',
    'Hay El Saha',
    'Kfarfila',
    'Hasbaya',
    'Kfeir',
    'Khelwat',
    'Sfineh',
    'Ain Jarfa',
    'Farrides',
    'Shebaa',
    'Mari',
    'Kfar Hamam',
    'Berghoz',
    'Ain Fjour',
    'Nakhileh',
    'Salib',
    'Majidieh',
    'Mimes',
    'Marj El Zouhour',
    'Shouaya',
    'Ain Kinia',
    'Hbarieh',
    'Kfarshouba',
    'Abou Kamha',
    'Kaoukaba',
    'Khraybeh',
    'Bayouda',
    'Debbine',
    'Blat (Marjayoun)',
    'Kleiaa',
    'Borj Al Molouk',
    'Deir Mimas',
    'Kfarkalla',
    'Hora',
    'Sardeh',
    'Omr',
    'Ebl El Saki',
    'Mazraat El Jaddayn',
    'Ain Arab',
    'Aadayseh',
    'Khiyam',
    'Houla',
    'Markaba',
    'Tallouseh',
    'Bani Hian',
    'Kantara',
    'Deir Seryan',
    'Taybeh',
    'Adshit Al Kassir',
    'Rab El Thlathine',
    'Sawwaneh',
    'Touline',
    'Majdel Selm',
    'Kabrikha',
    'Kasir',
    'Aalman (Marjayoun)',
    'Mays El Jabal',
    'Blida',
    'Zkei',
    'Mahib',
    'Wazzani',
    'Jdeidet',
    'Jdeidet Marjaaiyoun',
    'Shouaya',
    'Jdeidet Hay El Saray', 
  ),
);

// Use this filter to handle the Cities Of Lebanon
$places['LB'] = apply_filters('scpwoo_custom_places_lb', $places['LB']);
