<?php

/**
 * $country places/cities/municipalities/districts
 * - $count places/cities/municipalities/districts
 *
 * @author  Your Name Here <mr.kiddomonster@gmail.com>
 * @link https://mmprofessx.com
 * @version 1.0.0
 * @license http://www.gnu.org/licenses/gpl-2.0.html
 */

global $places;

$places['MM'] = array(
  'AYA' => array(
    'Pathein Township (ပုသိမ်မြို့နယ်)',
    'Kangyidaunt Township (ကန်ကြီးတောင့်မြို့နယ်)',
    'Ngaputaw Township (ငပုတောမြို့နယ်)',
    'Thabaung Township (သာပေါင်းမြို့နယ်)',
    'Kyaunggon Township (ကျောင်းကုန်းမြို့နယ်)',
    'Kyonpyaw Township (ကျုံပျော်မြို့နယ်)',
    'Yegyi Township (ရေကြည်မြို့နယ်)',
    'Hinthada Township (ဟင်္သာတမြို့နယ်)',
    'Zalun Township (ဇလွန်မြို့နယ်)',
    'Laymyethna Township (လေးမျက်နှာမြို့နယ်)',
    'Myanaung Township (မြန်အောင်မြို့နယ်)',
    'Kyangin Township (ကြံခင်းမြို့နယ်)',
    'Ingapu Township (အင်္ဂပူမြို့နယ်)',
    'Myaungmya Township (မြောင်းမြ)',
    'Einme Township (အိမ်မဲမြို့နယ်)',
    'Wakema Township (ဝါးခယ်မမြို့နယ်)',
    'Maubin Township (မအူပင်မြို့နယ်)',
    'Pantanaw Township (ပန်းတနော်မြို့နယ်)',
    'Nyaungdon Township(ညောင်တုန်းမြို့နယ်)',
    'Danubyu Township (ဓနုဖြူမြို့နယ်)',
    'Pyapon Township (ဖျာပုံမြို့နယ်)',
    'Bogale Township (ဘိုကလေးမြို့နယ်)',
    'Kyaiklat Township (ကျိုက်လတ်မြို့နယ်)',
    'Dedaye Township (ဒေးဒရဲမြို့နယ်)',
    'Labutta Township (လပွတ္တာမြို့နယ်)',
    'Mawlamyinegyun Township (မော်လမြိုင်ကျွန်းမြို့နယ်)',
  ),
  'BGO' => array(
    'Kawa Township (ကဝမြို့နယ်)',
    'Kyaukkyi Township (ကျောက်ကြီးမြို့နယ်)',
    'Kyauktaga Township (ကျောက်တံခါးမြို့နယ်)',
    'Gyobingauk Township (ကြို့ပင်ကောက်မြို့နယ်)',
    'Zigon Township (ဇီးကုန်းမြို့နယ်)',
    'Nyaunglebin Township (ညောင်လေးပင်မြို့နယ်)',
    'Taungoo Township (တောင်ငူမြို့နယ်)',
    'Tantabin Township (ထန်းတပင်မြို့နယ်)',
    'Daik-U Township (ဒိုက်ဦးမြို့နယ်)',
    'Nattalin Township (နတ်တလင်း)',
    'Bago Township (ပဲခူးမြို့နယ်)',
    'Padaung Township (ပန်းတောင်း)',
    'Paukkaung Township (ပေါက်ခေါင်းမြို့နယ်)',
    'Paungde Township (ပေါင်းတည်မြို့နယ်)',
    'Pyay Township (ပြည်မြို့နယ်)',
    'Pyu Township (ဖြူးမြို့နယ်)',
    'Minhla Township (မင်းလှမြို့နယ်)',
    'Monyo Township (မိုးညိုမြို့နယ်)',
    'Yedashe Township (ရေတာရှည်မြို့နယ်)',
    'Shwegyin Township (ရွှေကျင်မြို့နယ်)',
    'Shwedaung Township (ရွှေတောင်မြို့နယ်)',
    'Letpadan Township (လက်ပံတန်းမြို့နယ်)',
    'Waw Township (ဝေါမြို့နယ်)',
    'Thanatpin Township (သနပ်ပင်မြို့နယ်)',
    'Thayarwaddy Township (သာယာဝတီမြို့နယ်)',
    'Thegon Township (သဲကုန်းမြို့နယ်)',
    'Oktwin Township (အုတ်တွင်းမြို့နယ်)',
    'Okpho Township (အုတ်ဖိုမြို့နယ်)',
  ),
  'CHN' => array(
    'Kanpetlet Township (ကန်ပက်လက်မြို့နယ်)',
    'Tonzang Township ( တွန်းဇံမြို့နယ်)',
    'Tedim Township (တီးတိန်မြို့နယ်)',
    'Thantlang Township (ထန်တလန်မြို့နယ်)',
    'Paletwa Township (ပလက်ဝမြို့နယ်)',
    'Falam Township (ဖလမ်းမြို့နယ်)',
    'Mindat Township (မင်းတပ်မြို့နယ်)',
    'Matupi Township (မတူပီမြို့နယ်)',
    'Hakha Township (ဟားခါးမြို့နယ်)',
  ),
  'KCN' => array(
    'Myitkyina Township (မြစ်ကြီးနားမြို့နယ်)',
    'Waingmaw Township (ဝိုင်းမော်မြို့နယ်)',
    'N Jang Yang Township (အင်ဂျန်းယန်)',
    'Tanai Township (တနိုင်းမြို့နယ်)',
    'Chipwi Township (ချီဖွေမြို့နယ်)',
    'Tsawlaw Township (ဆော့လော်မြို့နယ်)',
    'Bhamo Township (ဗန်းမော်မြို့နယ်)',
    'Shwegu Township (ရွှေကူမြို့နယ်)',
    'Momauk Township (မိုးမောက်မြို့နယ်)',
    'Mansi Township (မံစီမြို့နယ်)',
    'Putao Township (ပူတာအိုမြို့နယ်)',
    'Putao Township (ပူတာအိုမြို့နယ်)',
    'Machanbaw Township (မချမ်းဘော)',
    'Khaunglanhpu Township (ခေါင်လန်ဖူး)',
    'Nogmung Township (နောင်မွန်းမြို့နယ်)',
    'Mogaung Township (မိုးကောင်းမြို့နယ်)',
    'Hpakan Township (ဖားကန့်မြို့နယ်)',
  ),
  'KYH' => array(
    'Loikaw Township (လွိုင်ကော်မြို့နယ်)',
    'Demoso Township (ဒီမောဆိုး‌မြို့နယ်)',
    'Hpruso Township (ဖရူဆိုမြို့နယ်)',
    'Shadaw Township (ရှားတော‌မြို့နယ်)',
    'Bawlakhe Township (ဘောလခဲမြို့နယ်)',
    'Hpasawng Township (ဖားဆောင်းမြို့နယ်)',
    'Mese Township (မယ်စဲ့‌မြို့နယ်)',
  ),        
  'KYN' => array(
    'Kawkareik Township (ကောဝ်တြာ်ကၞင့် - ကီၢ်ကရံၣ်ကီၢ်ဆၣ် - ကော့ကရိတ်မြို့နယ်)',
    'Kyain Seikgyi Township (ကြာအင်းဆိပ်ကြီးမြို့နယ်)',
    'Hpapun Township (ဖာပံင်ကၞင့် - ဖးဖူကီၢ်ဆၣ်- ဖာပွန်မြို့နယ်)',
    'Hpa-an Township (ဖၣ်အၣ်ကီၢ်ဆၣ် - ထ်ုအင်ကၞင့် - ဘားအံမြို့နယ်)',
    'Myawaddy Township (ရါမတံၤကီၢ်ဆၣ် - မေဝ်ပ္တီကၞင့် - မြဝတီမြို့နယ်)',
    'Hlaingbwe Township (လူၢ်ပျဲၢ်ကီၢ်ဆၣ် - ပါ်စံင်ကၞင့် - လှိုင်းဘွဲ့မြို့နယ်)',
    'Thandaunggyi Township (သါတီကၠံၤကီၢ်ဆၣ် - သင်တင်ဍောဟ်ကၞင့် - သံတောင်ကြီးမြို့နယ်)',
  ),
  'MDY' => array(
    'Maha Aungmye Township (မဟာအောင်မြေမြို့နယ်)',
    'Aungmyethazan Township (အောင်မြေသာစံမြို့နယ်)',
    'Chanayethazan Township (ချမ်းအေးသာစံမြို့နယ်)',
    'Chanmyathasi Township (ချမ်းမြသာစည်မြို့နယ်)',
    'Pyigyidagun Township (ပြည်ကြီးတံခွန်မြို့နယ်)',
    'Amarapura Township (အမရပူရမြို့နယ်)',
    'Patheingyi Township (ပုသိမ်ကြီးမြို့နယ်)',
  ),
  'MGY' => array(
    'Yenangyaung Township (ရေနံချောင်းမြို့နယ်)',
    'Natmauk Township (နတ်မောတ်မြို့နယ်)',
    'Myothit Township (မြို့သစ်မြို့နယ်)',
    'Taungdwingyi Township (တောင်တွင်းကြီးမြို့နယ်)',
    'Minbu Township (မင်းဘူးမြို့နယ်)',
    'Pwintbyu Township (ပွင့်ဖြူမြို့နယ်)',
  ),
  'MON' => array(
    'Mawlamyine Township (မော်လမြိုင်မြို့နယ်)',
    'Kyaikmaraw Township (ကျိုက်မရောမြို့နယ်)',
    'Chaungzon Township (ချောင်းဆုံမြို့နယ်)',
    'Thanbyuzayat Township (သံဖြူဇရပ်မြို့နယ်)',
    'Mudon Township (မုဒုံမြို့နယ်)',
    'Ye Township (ရေးမြို့နယ်)',
    'Thaton Township (သထုံမြို့နယ်)',
    'Paung Township (ပေါင်မြို့နယ်)',
    'Kyaikto Township (ကျိုက်ထိုမြို့နယ်)',
    'Bilin Township (ဘီးလင်းမြို့နယ်)',
  ),
  'NPT' => array(
    'Zabuthiri Township (ဇမ္ဗူသီရိမြို့နယ်)',
    'Zeyathiri Township (ဇေယျာသီရိမြို့နယ်)',
    'Tatkon Township (တပ်ကုန်းမြို့နယ်)',    
    'Dekkhina Thiri Township (ဒက္ခိဏသီရိမြို့နယ်)',
    'Pobbathiri Township (ပုဗ္ဗသီရိမြို့နယ်)',
    'Pyinmana Township (ပျဉ်းမနားမြို့နယ်)',
    'Lewe Township (လယ်ဝေးမြို့နယ်)',
    'Oattara Thiri Township (ဥတ္တရသီရိမြို့နယ်)',   
  ),
  'RKN' => array(
    'Sittwe Township (စစ်တွေမြို့နယ်)',
    'Ponnagyun Township (ပုဏ္ဏားကျွန်းမြို့နယ်)',
    'Pauktaw Township (ပေါက်တောမြို့နယ်)',
    'Rathedaung Township (ရသေ့တောင်မြို့နယ်)',
    'Maungdaw Township (မောင်တောမြို့နယ်)',
    'Buthidaung Township (ဘူးသီးတောင်မြို့နယ်)',
    'Kyaukpyu Township (ကျောက်ဖြူ)',
    'Munaung Township (မာန်အောင်မြို့နယ်)',
    'Ramree Township (ရမ်းဗြဲမြို့နယ်)',
    'Ann Township (အမ်းမြို့နယ်)',
    'Thandwe Township (သံတွဲမြို့နယ်)',
    'Taungup Township (တောင်ကုတ်မြို့နယ်)',
    'Gwa Township (ဂွမြို့နယ်)',
    'Mrauk-U Township (မြောက်ဦးမြို့နယ်)',
    'Kyauktaw Township (ကျောက်တော်မြို့နယ်)',
    'Minbya Township (မင်းပြားမြို့နယ်)',
    'Myebon Township (မြေပုံမြို့နယ်)',
  ),
  'SGN' => array(
    'Hkamti Township (ခန္တီးမြို့နယ်)',
    'Homalin Township (ဟုမ္မလင်းမြို့နယ်)',
    'Kale Township (ကလေးမြို့နယ်)',
    'Kalewa Township (ကလေးဝမြို့နယ်)',
    'Mingin Township (မင်းကင်းမြို့နယ်)',
    'Katha Township (ကသာမြို့နယ်)',
    'Indaw Township (အင်းတော်မြို့နယ်)',
    'Banmauk Township (ဗန်းမောက်မြို့နယ်)',
    'Htigyaing Township (ထီးချိုင့်မြို့နယ်)',
    'Kawlin Township (ၸႄႈဝဵင်းၵေႃလၢင်း - ကောလင်းမြို့နယ်)',
    'Pinlebu Township (ပင်လယ်ဘူးမြို့နယ်)',
    'Wuntho Township (ဝန်းသိုမြို့နယ်)',
    'Kanbalu Township (ကန့်ဘလူမြို့နယ်)',
    'Kyunhla Township (ကျွန်းလှမြို့နယ်)',
    'Mawlaik Township (မော်လိုက်မြို့နယ်)',
    'Paungbyin Township (ဖောင်းပြင်မြို့နယ်)',
    'Monywa Township (မုံရွာမြို့နယ်)',
    'Ayadaw Township (အရာတော်မြို့နယ်)',
    'Chaung-U Township (ချောင်းဦးမြို့နယ်)',
    'Budalin Township (ဘုတလင်မြို့နယ်)',
    'Sagaing Township (စစ်ကိုင်းမြို့နယ်)',
    'Myinmu Township (မြင်းမူမြို့နယ်)',
    'Myaung Township (မြောင်မြို့နယ်)',
    'Shwebo Township (ရွှေဘိုမြို့နယ်)',
    'Ye-U Township (ရေဦးမြို့နယ်)',
    'Khin-U Township (ခင်ဦးမြို့နယ်)',
    'Wetlet Township (ဝက်လက်မြို့နယ်)',
    'Tant-Se Township (တန့်ဆည်မြို့နယ်)',
    'Tabayin Township (ဒီပဲယင်းမြို့နယ်)',
    'Tamu Township (တမူးမြို့နယ်)',
    'Yinmabin District (ယင်းမာပင်ခရိုင်)',
    'Yinmabin Township (ယင်းမာပင်မြို့နယ်)',
    'Salingyi Township (ဆားလင်းကြီးမြို့နယ်)',
  ),
  'SHN' => array(
    'Kengtung Township (ကျိုင်းတုံမြို့နယ်)',
    'Mong Khet Township (မိုင်းခတ်မြို့နယ်)',
    'Mong Ping Township (မိုင်းပြင်းမြို့နယ်)',
    'Mong Yang Township (မိူင်းယၢင် - မိုင်းယန်းမြို့နယ်)',
    'Mongla Township (မိုင်းလားမြို့နယ်)',
    'Mong Hsat Township (မိုင်းဆတ်မြို့နယ်)',
    'Mong Ton Township (မိုင်းတုံမြို့နယ်)',
    'Tachileik Township (တာချီလိတ်မြို့နယ်)',
    'Mong Hpayak Township (မိုင်းဖြတ်မြို့နယ်)',
    'Mong Yawng Township (မိုင်းယောင်းမြို့နယ်)',
    'Kyaukme Township (ကျောက်မဲမြို့နယ်)',
    'Nawnghkio Township (နောင်ချိုမြို့နယ်)',
    'Hsipaw Township (သီပေါမြို့နယ်)',
    'Namtu Township (နမ္မတူမြို့နယ်)',
    'Namhsan Township (နမ့်ဆန်မြို့နယ်)',
    'Mantong Township (မန်တုံမြို့နယ်)',
    'Kunlong Township (ကွမ်းလုံမြို့နယ်)',
    'Lashio Township (လားရှိုးမြို့နယ်)',
    'Hsenwi Township (သိန္နီမြို့နယ်)',
    'Mongyai Township (မိုင်းရယ်မြို့နယ်)',
    'Tangyan Township (တန့်ယန်းမြို့နယ်)',
    'Konkyan Township (ကုန်းကြမ်းမြို့နယ်)',
    'Laukkaing Township (လောက်ကိုင်မြို့နယ်)',
    'Pangwaun Township (ပန်ဝိုင်မြို့နယ်)',
    'Mongmao Township (မိုင်းမောမြို့နယ်)',
    'Hopang Township (ဟိုပန်မြို့နယ်)',
    'Mu Se Township (မူဆယ်မြို့နယ်)',
    'Namhkam Township (နမ့်ခမ်းမြို့နယ်)',
    'Kutkai Township (ကွတ်ခိုင်မြို့နယ်)',
    'Mongmit Township (မိူင်းမိတ်ႈ - မိုးမိတ်မြို့နယ်)',
    'Mabein Township (မဘိမ်းမြို့နယ်)',
    'Pangsang Township (ပန်ဆန်းမြို့နယ်)',
    'Matman Township (မက်မန်းမြို့နယ်)',
    'Namphan Township (နားဖန်းမြို့နယ်)',
    'Langhko Township (လင်းခေးမြို့နယ်)',
    'Mong Nai Township (မိုးနဲမြို့နယ်)',
    'Mong Pan Township (မိုင်းပန်မြို့နယ်)',
    'Mawkmai Township (မောက်မယ်မြို့နယ်)',
    'Loilem Township (လွိုင်လင်မြို့နယ်)',
    'Lai-Hka Township (လဲချားမြို့နယ်)',
    'Nansang Township (နမ့်စန်မြို့နယ်)',
    'Kunhing Township (ကွန်ဟိန်းမြို့နယ်)',
    'Kyethi Township (ကျေးသီးမြို့နယ်)',
    'Mong Kung Township (မိုင်းကိုင်မြို့နယ်)',
    'Mong Hsu Township (မိုင်းရှူးမြို့နယ်)',
    'Taunggyi Township (တောင်ကြီးမြို့နယ်)',
    'Nyaungshwe Township (ညောင်ရွှေမြို့နယ်)',
    'Hopong Township (ဟိုပုံးမြို့နယ်)',
    'Hsi Hseng Township (ဆီဆိုင်မြို့နယ်)',
    'Kalaw Township (ကလောမြို့နယ်)',
    'Pindaya Township (ပင်းတယမြို့နယ်)',
    'Ywangan Township (ရွာငံမြို့နယ်)',
    'Lawksawk Township (ရပ်စောက်မြို့နယ်)',
    'Pinlaung Township (ပင်လောင်းမြို့နယ်)',
    'Pekon Township (ဖယ်ခုံမြို့နယ်)',
  ),
  'TNT' => array(
    'Dawei Township (ထားဝယ်မြို့နယ်)',
    'Launglon Township (လောင်းလုံမြို့နယ်)',
    'Thayetchaung Township (သရက်ချောင်းမြို့နယ်)',
    'Yebyu Township (ရေဖြူမြို့နယ်)',
    'Kyunsu Township (ကျွန်းစုမြို့နယ်)',
    'Myeik Township (မြိတ်မြို့နယ်)',
    'Palaw Township (ပုလောမြို့နယ်)',
    'Tanintharyi Township (တနင်္သာရီမြို့နယ်)',
    'Bokpyin Township (ဘုတ်ပြင်းမြို့နယ်)',
    'Kawthaung Township (ကော့သောင်းမြို့နယ်)',
  ),  
  'YGN' => array(
    'Kamayut Township (ကမာရွတ်မြို့နယ်)',
    'Kawhmu Township (ကော့မှူးမြို့နယ်)',
    'Kyauktada Township (ကျောက်တံတားမြို့နယ်)',
    'Kyimyindaing Township (ကြည့်မြင်တိုင်မြို့နယ်)',
    'Kungyangon (ကွမ်းခြံကုန်း)',
    'Kyauktan (ကျောက်တန်း)',
    'Cocokyun Township (ကိုကိုးကျွန်းမြို့နယ်)',
    'Kayan (ခရမ်းမြို့နယ်)',
    'Sanchaung Township (စမ်းချောင်းမြို့နယ်)',
    'Seikgyi Village (ဆိပ်ကြီး ရွာ)',
    'South Okkalapa Township (တောင်ဥက္ကလာပမြို့နယ်)',
    'Dagon Township (ဒဂုံမြို့နယ်)',
    'South Dagon Township (ဒဂုံမြို့သစ်တောင်ပိုင်းမြို့နယ်)',
    'North Dagon Township (ဒဂုံမြို့သစ်မြောက်ပိုင်းမြို့နယ်)',
    'East Dagon Township (ဒဂုံမြို့သစ်အရှေ့ပိုင်းမြို့နယ်)',
    'Dagon Seikkan Township (ဒဂုံဆိပ်ကမ်းမြို့နယ်)',
    'Dala Township (ဒလမြို့နယ်)',
    'Dawbon Township (ဒေါပုံမြို့နယ်)',
    'Pazundaung Township (ပုဇွန်တောင်မြို့နယ်)',
    'Pabedan Township (ပန်းဘဲတန်းမြို့နယ်)',
    'Botataung Township (ဗိုလ်တထောင်မြို့နယ်)',
    'Bahan Township (ဗဟန်းမြို့နယ်)',
    'Mayangon Township (မရမ်းကုန်းမြို့နယ်)',
    'North Okkalapa Township (မြောက်ဥက္ကလာပမြို့နယ်)',
    'Mingala Taungnyunt Township (မင်္ဂလာ‌တောင်ညွန့်မြို့နယ်)',
    'Tamwe Township (တာမွေမြို့နယ်)',
    'Twante Township (တွံတေးမြို့နယ်)',
    'Taikkyi Township (တိုက်ကြီးမြို့နယ်)',
    'Tantabin Township (ထန်းတပင်မြို့နယ်)',
    'Hmawbi Township (မှော်ဘီမြို့နယ်)',
    'North Okkalapa Township (မြောက်ဥက္ကလာပမြို့နယ်)',
    'Yankin Township (ရန်ကင်းမြို့နယ်)',
    'Shwepyitha Township (ရွှေပြည်သာမြို့နယ်)',
    'Hlaing Township (လှိုင်မြို့နယ်)',
    'Hlaingthaya Township (လှိုင်သာယာမြို့နယ်)',
    'Latha Township (လသာမြို့နယ်)',
    'Hlegu Township (လှည်းကူးမြို့နယ်)',
    'Lanmadaw Township (လမ်းမတော်မြို့နယ်)',
    'Thingangyun Township (သင်္ဃန်းကျွန်းမြို့နယ်)',
    'Thaketa Township (သာကေတမြို့နယ်)',
    'Thanlyin (သန်လျင်မြို့)',
    'Thongwa (သုံးခွမြို့နယ်)',
    'Ahlon Township (အလုံမြို့နယ်)',
    'Insein Township (အင်းစိန်မြို့နယ်)',
  ),
);