<?php

/**
 * Districts of Peru
 * - 877 districts
 *
 * Updated: September 18th, 2020
 * By Yordan Soares <contact@yordansoar.es> | https://yordansoar.es
 * 
 * Source:
 * - https://es.db-city.com/Per%C3%BA
 *
 * @author  David Soto <ddiods@hotmail.com>
 * @version 1.1.0
 * @license http://www.gnu.org/licenses/gpl-2.0.html
 */

global $places;

$places['PE'] = array(
    // Amazonas
    'AMA' => array(
        'Aramango',
        'Bagua',
        'Cajaruro',
        'Camporredondo',
        'Chachapoyas',
        'Chirimoto',
        'Chuquibamba',
        'Cocabamba',
        'Colcamar',
        'Conila',
        'Copallin',
        'Cumba',
        'El Cenepa',
        'El Milagro',
        'Florida',
        'Huambo',
        'Imaza',
        'Jamalca',
        'Jazan',
        'La Jalca',
        'La Peca',
        'Lamud',
        'Leimebamba',
        'Limabamba',
        'Lonya Grande',
        'Luya',
        'Molinopampa',
        'Nieva',
        'Ocalli',
        'Ocumal',
        'Omia',
        'Otro',
        'Pisuquia',
        'Rio Santiago',
        'San Nicolas',
        'Santa Catalina',
        'Santo Tomas',
        'Vista Alegre',
        'Yambrasbamba',
        'Yamon',
        'Bagua Grande',
    ),
    // Áncash
    'ANC' => array(
        'Caceres Del Peru',
        'Caraz',
        'Carhuaz',
        'Casma',
        'Chacas',
        'Chavin de Huantar',
        'Coishco',
        'Conchucos',
        'Huallanca',
        'Huaraz',
        'Huari',
        'Huarmey',
        'Independencia',
        'Jangas',
        'Llumpa',
        'Mancos',
        'Marcara',
        'Mirgas',
        'Moro',
        'Nepeña',
        'Nuevo Chimbote',
        'Otros',
        'Pamparomas',
        'Pampas',
        'Pariacoto',
        'Parobamba',
        'Pomabamba',
        'Pueblo Libre',
        'Quillo',
        'San Juan',
        'San Luis',
        'San Marcos',
        'Santa Cruz',
        'Santa',
        'Sihuas',
        'Tarica',
        'Yanama',
        'Yautan',
        'Yauya',
        'Yungay',
        'Chimbote',
    ),
    // Apurímac
    'APU' => array(
        'Abancay',
        'Anco_huallo',
        'Andahuaylas',
        'Andarapa',
        'Antabamba',
        'Chalhuanca',
        'Challhuahuacho',
        'Chincheros',
        'Chuquibambilla',
        'Cotabambas',
        'Cotaruse',
        'Coyllurqui',
        'Curahuasi',
        'Gamarra',
        'Haquira',
        'Huaccana',
        'Huancarama',
        'Huancaray',
        'Huanipaca',
        'Kishuara',
        'Lambrama',
        'Mara',
        'Ocobamba',
        'Ongoy',
        'Oropesa',
        'Otro',
        'Pacobamba',
        'Pacucha',
        'Pichirhua',
        'Progreso',
        'Ranracancha',
        'San Antonio de Cachi',
        'San Jeronimo',
        'San Pedro de Cachora',
        'Santa Maria de Chicmo',
        'Talavera',
        'Tambobamba',
        'Tamburco',
        'Tintay',
        'Turpo',
        'Uranmarca',
    ),
    // Arequipa
    'ARE' => array(
        'Alto Selva Alegre',
        'Aplao',
        'Arequipa',
        'Atico',
        'Bella Union',
        'Camana',
        'Cayma',
        'Cerro Colorado',
        'Chala',
        'Chaparra',
        'Characato',
        'Chivay',
        'Cocachacra',
        'Dean Valdivia',
        'Islay',
        'Jacobo Hunter',
        'Jose Luis Bustamante Y Rivero',
        'La Joya',
        'Majes',
        'Mariano Melgar',
        'Mariano Nicolas Valcarcel',
        'Mariscal Caceres',
        'Miraflores',
        'Mollendo',
        'Nicolas de Pierola',
        'Ocoña',
        'Orcopampa',
        'Otro',
        'Paucarpata',
        'Punta de Bombon',
        'Sabandia',
        'Sachaca',
        'Samuel Pastor',
        'Santa Rita de Siguas',
        'Socabaya',
        'Tiabaya',
        'Uchumayo',
        'Uraca',
        'Yanahuara',
        'Yanaquihua',
        'Yura',
    ),
    // Ayacucho
    'AYA' => array(
        'Acocro',
        'Acos Vinchos',
        'Anchihuay',
        'Anco',
        'Andres Avelino Caceres Dorregaray',
        'Aucara',
        'Ayacucho',
        'Ayahuanco',
        'Ayna',
        'Cabana',
        'Cangallo',
        'Carmen Alto',
        'Chiara',
        'Chungui',
        'Chuschi',
        'Coracora',
        'Huamanguilla',
        'Huanta',
        'Jesus Nazareno',
        'Llochegua',
        'Los Morochucos',
        'Luricocha',
        'Ocros',
        'Otro',
        'Paras',
        'Pucacolpa',
        'Pullo',
        'Puquio',
        'Quinua',
        'San Juan Bautista',
        'San Miguel',
        'Sancos',
        'Santa Rosa',
        'Santillana',
        'Sivia',
        'Socos',
        'Tambillo',
        'Tambo',
        'Vilcas Huaman',
        'Vinchos',
        'Vischongo',
    ),
    // Cajamarca
    'CAJ' => array(
        'Asuncion',
        'Bambamarca',
        'Bellavista',
        'Cachachi',
        'Cajabamba',
        'Cajamarca',
        'Callayuc',
        'Catache',
        'Celendin',
        'Chalamarca',
        'Chirinos',
        'Chontali',
        'Chota',
        'Colasay',
        'Condebamba',
        'Cutervo',
        'Encañada',
        'Hualgayoc',
        'Huarango',
        'Huasmin',
        'Jaen',
        'Jesus',
        'Jose Sabogal',
        'La Coipa',
        'Lajas',
        'Los Baños Del Inca',
        'Namballe',
        'Namora',
        'Otro',
        'Pedro Galvez',
        'Pomahuaca',
        'Querocotillo',
        'San Ignacio',
        'San Jose de Lourdes',
        'San Miguel',
        'San Pablo',
        'Santa Cruz',
        'Santa Rosa',
        'Socota',
        'Tabaconas',
        'Tacabamba',
    ),
    // Callao
    'CAL' => array(
        'Bellavista',
        'Callao',
        'Carmen de la Legua Reynoso',
        'La Perla',
        'La Punta',
        'Mi Perú',
        'Ventanilla',
    ),
    // Cusco
    'CUS' => array(
        'Anta',
        'Calca',
        'Ccatca',
        'Challabamba',
        'Chamaca',
        'Chinchero',
        'Colquemarca',
        'Colquepata',
        'Coporaque',
        'Cusco',
        'Echarate',
        'Espinar',
        'Huancarani',
        'Kimbiri',
        'Limatambo',
        'Livitaca',
        'Machupicchu',
        'Marangani',
        'Ocongate',
        'Ollantaytambo',
        'Otro',
        'Paucartambo',
        'Pichari',
        'Pisac',
        'Pomacanchi',
        'Poroy',
        'Quellouno',
        'Quiquijana',
        'San Jeronimo',
        'San Sebastian',
        'Santa Ana',
        'Santiago',
        'Santo Tomas',
        'Sicuani',
        'Urcos',
        'Urubamba',
        'Velille',
        'Vilcabamba',
        'Wanchaq',
        'Yanaoca',
        'Yanatile',
    ),
    //Huancavelica
    'HUV' => array(
        'Acobamba',
        'Acobambilla',
        'Acoria',
        'Acostambo',
        'Acraquia',
        'Ahuaycha',
        'Anchonga',
        'Anco',
        'Andabamba',
        'Andaymarca',
        'Anta',
        'Ascension',
        'Castrovirreyna',
        'Chinchihuasi',
        'Chincho',
        'Churcampa',
        'Colcabamba',
        'Congalla',
        'Cosme',
        'Daniel Hernandez',
        'Huachocolpa',
        'Huancavelica',
        'Huando',
        'Huaribamba',
        'Lircay',
        'Locroja',
        'Ñahuimpuquio',
        'Otro',
        'Pampas',
        'Paucara',
        'Paucarbamba',
        'Pilpichaca',
        'Pomacocha',
        'Quichuas',
        'Quishuar',
        'Rosario',
        'San Antonio de Antaparco',
        'San Marcos de Rocchac',
        'Secclla',
        'Surcubamba',
        'Yauli',
    ),
    // Huánuco
    'HUC' => array(
        'Amarilis',
        'Ambo',
        'Baños',
        'Chaglla',
        'Chinchao',
        'Cholon',
        'Churubamba',
        'Codo Del Pozuzo',
        'Conchamarca',
        'Daniel Alomia Robles',
        'Honoria',
        'Huacar',
        'Huacaybamba',
        'Huacrachuco',
        'Huanuco',
        'Jose Crespo Y Castillo',
        'La Uniòn',
        'Llata',
        'Luyando',
        'Margos',
        'Mariano Damaso Beraun',
        'Marias',
        'Molino',
        'Monzon',
        'Otro',
        'Pachas',
        'Panao',
        'Pillco Marca',
        'Pinra',
        'Puerto Inca',
        'Quisqui (kichki)',
        'Ripan',
        'Rondos',
        'Rupa-rupa',
        'San Miguel de Cauri',
        'San Pedro de Chaulan',
        'San Rafael',
        'Santa Maria Del Valle',
        'Umari',
        'Yacus',
        'Yuyapichis',
    ),
    // Ica
    'ICA' => array(
        'Alto Laran',
        'Changuillo',
        'Chavin',
        'Chincha Alta',
        'Chincha Baja',
        'El Carmen',
        'El Ingenio',
        'Grocio Prado',
        'Huancano',
        'Humay',
        'Ica',
        'Independencia',
        'La Tinguiña',
        'Llipata',
        'Los Aquijes',
        'Marcona',
        'Nasca',
        'Ocucaje',
        'Otro',
        'Pachacutec',
        'Palpa',
        'Paracas',
        'Parcona',
        'Pisco',
        'Pueblo Nuevo',
        'Pueblo Nuevo',
        'Rio Grande',
        'Salas',
        'San Andres',
        'San Clemente',
        'San Jose de Los Molinos',
        'San Juan Bautista',
        'San Pedro de Huacarpana',
        'Santa Cruz',
        'Santiago',
        'Subtanjalla',
        'Sunampe',
        'Tambo de Mora',
        'Tate',
        'Tupac Amaru Inca',
        'Vista Alegre',
    ),
    // Junín
    'JUN' => array(
        'Acobamba',
        'Acolla',
        'Carhuamayo',
        'Chanchamayo',
        'Chilca',
        'Chupaca',
        'Comas',
        'Concepcion',
        'Coviriali',
        'El Tambo',
        'Huancan',
        'Huancayo',
        'Huasahuasi',
        'Huayucachi',
        'Jauja',
        'Junin',
        'La Oroya',
        'Llaylla',
        'Mazamari',
        'Otro',
        'Palcamayo',
        'Pampa Hermosa',
        'Pangoa',
        'Perene',
        'Pichanaqui',
        'Pilcomayo',
        'Rio Negro',
        'Rio Tambo',
        'San Agustin',
        'San Jeronimo de Tunan',
        'San Jose de Quero',
        'San Luis de Shuaro',
        'San Ramon',
        'Santa Rosa de Sacco',
        'Santo Domingo de Acobamba',
        'Sapallanga',
        'Satipo',
        'Sicaya',
        'Tapo',
        'Tarma',
        'Yauyos',
    ),
    // La Libertad
    'LAL' => array(
        'Agallpampa',
        'Casa Grande',
        'Cascas',
        'Chao',
        'Chepen',
        'Chicama',
        'Chillia',
        'Chocope',
        'Chugay',
        'El Porvenir',
        'Florencia de Mora',
        'Guadalupe',
        'Guadalupito',
        'Huamachuco',
        'Huanchaco',
        'Julcan',
        'La Esperanza',
        'Laredo',
        'Marcabal',
        'Moche',
        'Otro',
        'Otuzco',
        'Pacanga',
        'Pacasmayo',
        'Paijan',
        'Parcoy',
        'Pueblo Nuevo',
        'Quiruvilca',
        'Salaverry',
        'San Jose',
        'San Pedro de Lloc',
        'Sanagoran',
        'Santiago de Cao',
        'Santiago de Chuco',
        'Sarin',
        'Sartimbamba',
        'Tayabamba',
        'Trujillo',
        'Usquil',
        'Victor Larco Herrera',
        'Viru',
    ),
    // Lambayeque
    'LAM' => array(
        'Cayalti',
        'Cañaris',
        'Chiclayo',
        'Chochope',
        'Chongoyape',
        'Eten Puerto',
        'Eten',
        'Ferreñafe',
        'Illimo',
        'Incahuasi',
        'Jayanca',
        'Jose Leonardo Ortiz',
        'La Victoria',
        'Lagunas',
        'Lambayeque',
        'Manuel Antonio Mesones Muro',
        'Mochumi',
        'Monsefu',
        'Morrope',
        'Motupe',
        'Nueva Arica',
        'Olmos',
        'Otro',
        'Oyotun',
        'Pacora',
        'Patapo',
        'Picsi',
        'Pimentel',
        'Pitipo',
        'Pomalca',
        'Pucala',
        'Pueblo Nuevo',
        'Reque',
        'Salas',
        'San Jose',
        'Santa Rosa',
        'Saña',
        'Tucume',
        'Tuman',
    ),
    // Lima Metropolitana
    'LIM' => array(
        'Ancón',
        'Ate Vitarte',
        'Barranco',
        'Breña',
        'Carabayllo',
        'Chaclacayo',
        'Chorrillos',
        'Cieneguilla',
        'Comas',
        'El Agustino',
        'Independencia',
        'Jesús María',
        'La Molina',
        'La Victoria',
        'Lima Cercado',
        'Lince',
        'Los Olivos',
        'Lurigancho',
        'Lurín',
        'Magdalena del Mar',
        'Miraflores',
        'Pachacamac',
        'Pucusana',
        'Pueblo Libre',
        'Puente Piedra',
        'Punta Hermosa',
        'Punta Negra',
        'Rímac',
        'San Bartolo',
        'San Borja',
        'San Isidro',
        'San Juan de Lurigancho',
        'San Juan de Miraflores',
        'San Luis',
        'San Martín de Porres',
        'San Miguel',
        'Santa Anita',
        'Santa María del Mar',
        'Santa Rosa',
        'Santiago de Surco',
        'Surquillo',
        'Villa El Salvador',
        'Villa María del Triunfo',
    ),
    // Lima Provincia
    'LMA' => array(
        'Barranca',
        'Cajatambo',
        'Canta',
        'Cañete',
        'Huaral',
        'Huarochiri',
        'Huaura',
        'Oyon',
        'Yauyos',
    ),
    // Loreto
    'LOR' => array(
        'Andoas',
        'Balsapuerto',
        'Barranca',
        'Belen',
        'Cahuapanas',
        'Contamana',
        'Emilio San Martin',
        'Fernando Lores',
        'Indiana',
        'Iquitos',
        'Jeberos',
        'Jenaro Herrera',
        'Lagunas',
        'Las Amazonas',
        'Manseriche',
        'Maquia',
        'Mazan',
        'Morona',
        'Napo',
        'Nauta',
        'Otros',
        'Padre Marquez',
        'Pampa Hermosa',
        'Parinari',
        'Pastaza',
        'Pebas',
        'Puinahua',
        'Punchana',
        'Putumayo',
        'Ramon Castilla',
        'Requena',
        'San Juan Bautista',
        'San Pablo',
        'Sarayacu',
        'Teniente Cesar Lopez Rojas',
        'Tigre',
        'Trompeteros',
        'Urarinas',
        'Vargas Guerra',
        'Yavari',
        'Yurimaguas',
    ),
    // Madre de Dios
    'MDD' => array(
        'Fitzcarrald',
        'Huepetuhe',
        'Iberia',
        'Inambari',
        'Iñapari',
        'Laberinto',
        'Las Piedras',
        'Madre de Dios',
        'Manu',
        'Otros',
        'Tahuamanu',
        'Tambopata',
    ),
    // Moquegua
    'MOQ' => array(
        'Carumas',
        'Chojata',
        'Coalaque',
        'Cuchumbaya',
        'El Algarrobal',
        'Ichuña',
        'Ilo',
        'La Capilla',
        'Lloque',
        'Matalaque',
        'Moquegua',
        'Omate',
        'Otro',
        'Pacocha',
        'Puquina',
        'Quinistaquillas',
        'Samegua',
        'San Cristobal',
        'Torata',
        'Ubinas',
        'Yunga',
    ),
    // Pasco
    'PAS' => array(
        'Chacayan',
        'Chaupimarca',
        'Chontabamba',
        'Constitucion',
        'Goyllarisquizga',
        'Huachon',
        'Huancabamba',
        'Huariaca',
        'Huayllay',
        'Ninacaca',
        'Otro',
        'Oxapampa',
        'Palcazu',
        'Pallanchacra',
        'Paucar',
        'Paucartambo',
        'Pozuzo',
        'Puerto Bermudez',
        'San Francisco de Asis de Yarusyacan',
        'San Pedro de Pillao',
        'Santa Ana de Tusi',
        'Simon Bolivar',
        'Tapuc',
        'Ticlacayan',
        'Tinyahuarco',
        'Vicco',
        'Vilcabamba',
        'Villa Rica',
        'Yanacancha',
        'Yanahuanca',
    ),
    // Piura
    'PIU' => array(
        'Ayabaca',
        'Bellavista',
        'Castilla',
        'Catacaos',
        'Chalaco',
        'Chulucanas',
        'Colan',
        'Cura Mori',
        'El Carmen de la Frontera',
        'Frias',
        'Huancabamba',
        'Huarmaca',
        'Ignacio Escudero',
        'La Arena',
        'La Brea',
        'La Huaca',
        'La Matanza',
        'La Uniòn',
        'Lancones',
        'Las Lomas',
        'Los Organos',
        'Mancora',
        'Marcavelica',
        'Miguel Checa',
        'Morropon',
        'Otro',
        'Pacaipampa',
        'Paimas',
        'Paita',
        'Pariñas',
        'Piura',
        'Querecotillo',
        'San Miguel de El Faique',
        'Sapillica',
        'Sechura',
        'Sondorillo',
        'Sullana',
        'Suyo',
        'Tambo Grande',
        'Vice',
        'Yamango',
    ),
    // Puno
    'PUN' => array(
        'Acora',
        'Alto Inambari',
        'Ananea',
        'Asillo',
        'Ayapata',
        'Ayaviri',
        'Azangaro',
        'Capachica',
        'Chupa',
        'Coasa',
        'Crucero',
        'Desaguadero',
        'Huacullani',
        'Huancane',
        'Huata',
        'Ilave',
        'Juli',
        'Juliaca',
        'Kelluyo',
        'Lampa',
        'Macari',
        'Macusani',
        'Moho',
        'Nuñoa',
        'Orurillo',
        'Otro',
        'Paratia',
        'Pilcuyo',
        'Pisacoma',
        'Pomata',
        'Puno',
        'Putina',
        'Saman',
        'San Anton',
        'San Juan Del Oro',
        'San Pedro de Putina Punco',
        'Sandia',
        'Taraco',
        'Usicayos',
        'Yunguyo',
        'Zepita',
    ),
    // San Martín
    'SAM' => array(
        'Alonso de Alvarado',
        'Alto Biavo',
        'Awajun',
        'Bajo Biavo',
        'Barranquita',
        'Bellavista',
        'Campanilla',
        'Caynarachi',
        'Chazuta',
        'Elias Soplin Vargas',
        'Huicungo',
        'Jepelacio',
        'Juanjui',
        'La Banda de Shilcayo',
        'Lamas',
        'Morales',
        'Moyobamba',
        'Nueva Cajamarca',
        'Nuevo Progreso',
        'Otro',
        'Pajarillo',
        'Pardo Miguel',
        'Picota',
        'Pinto Recodo',
        'Polvora',
        'Rioja',
        'San Hilarion',
        'San Jose de Sisa',
        'San Martin',
        'San Pablo',
        'San Rafael',
        'Santa Rosa',
        'Saposoa',
        'Sauce',
        'Shamboyacu',
        'Soritor',
        'Tabalosos',
        'Tarapoto',
        'Tocache',
        'Tres Unidos',
        'Uchiza',
    ),
    // Tacna
    'TAC' => array(
        'Alto de la Alianza',
        'Cairani',
        'Calana',
        'Camilaca',
        'Candarave',
        'Ciudad Nueva',
        'Coronel Gregorio Albarracin Lanchipa',
        'Curibaya',
        'Estique',
        'Estique-pampa',
        'Heroes Albarracin',
        'Huanuara',
        'Ilabaya',
        'Inclan',
        'Ite',
        'La Yarada Los Palos',
        'Locumba',
        'Otro',
        'Pachia',
        'Palca',
        'Pocollay',
        'Quilahuani',
        'Sama',
        'Sitajara',
        'Susapaya',
        'Tacna',
        'Tarata',
        'Tarucachi',
        'Ticaco',
    ),
    // Tumbes
    'TUM' => array(
        'Aguas Verdes',
        'Canoas de Punta Sal',
        'Casitas',
        'Corrales',
        'La Cruz',
        'Matapalo',
        'Otro',
        'Pampas de Hospital',
        'Papayal',
        'San Jacinto',
        'San Juan de la Virgen',
        'Tumbes',
        'Zarumilla',
        'Zorritos',
    ),
    // Ucayali
    'UCA' => array(
        'Alexander Von Humboldt',
        'Calleria',
        'Campoverde',
        'Curimana',
        'Iparia',
        'Irazola',
        'Manantay',
        'Masisea',
        'Neshuya',
        'Nueva Requena',
        'Padre Abad',
        'Purus',
        'Raymondi',
        'Sepahua',
        'Tahuania',
        'Yarinacocha',
        'Yurua'
    )
);

// Use this filter to handle the Districts of Peru
$places['PE'] = apply_filters('scpwoo_custom_places_pe', $places['PE']);
