<?php

/**
 * Cities and Municipalities of the Philippines
 * - 146 Cities & 1,488 Municipalities
 *
 * Source:
 * - https://psa.gov.ph/classification/psgc/?q=psgc/provinces
 *
 * @author  David Webb Espiritu <webbteche@gmail.com> | https://www.linkedin.com/in/webbteche
 * @version 1.0.0
 * @license http://www.gnu.org/licenses/gpl-2.0.html
 */

global $places;

$places['PH'] = array(
  // Abra
  'ABR' => array(
    'Bangued (Capital)',
    'Boliney',
    'Bucay',
    'Bucloc',
    'Daguioman',
    'Danglas',
    'Dolores',
    'La Paz',
    'Lacub',
    'Lagangilang',
    'Lagayan',
    'Langiden',
    'Licuan-Baay',
    'Luba',
    'Malibcong',
    'Manabo',
    'Peñarrubia',
    'Pidigan',
    'Pilar',
    'Sallapadan',
    'San Isidro',
    'San Juan',
    'San Quintin',
    'Tayum',
    'Tineg',
    'Tubo',
    'Villaviciosa',
  ),

  // Agusan del Norte
  'AGN' => array(
    'Buenavista',
    'Butuan City (Capital)',
    'Cabadbaran City',
    'Carmen', 'Jabonga',
    'Kitcharao',
    'Las Nieves',
    'Magallanes',
    'Nasipit',
    'Santiago',
    'Tubay',
    'Remedios T. Romualdez',
  ),

  // Agusan del Sur
  'AGS' => array(
    'Bayugan City',
    'Bunawan',
    'Esperanza',
    'La Paz',
    'Loreto',
    'Prosperidad (Capital)',
    'Rosario', 'San Francisco',
    'San Luis',
    'Santa Josefa',
    'Talacogon',
    'Trento',
    'Veruela',
    'Sibagat',
  ),

  // Aklan
  'AKL' => array(
    'Altavas',
    'Balete',
    'Banga',
    'Batan',
    'Buruanga',
    'Ibajay',
    'Kalibo (Capital)',
    'Lezo',
    'Libacao',
    'Madalag',
    'Makato',
    'Malay',
    'Malinao',
    'Nabas',
    'New Washington',
    'Numancia',
    'Tangalan',
  ),

  // Albay
  'ALB' => array(
    'Bacacay',
    'Camalig',
    'Daraga',
    'Guinobatan',
    'Jovellar',
    'Legazpi City (Capital)',
    'Libon',
    'Ligao City',
    'Malilipot',
    'Malinao',
    'Manito',
    'Oas',
    'Pio Duran',
    'Polangui',
    'Rapu-Rapu',
    'Santo Domingo',
    'Tabaco City',
    'Tiwi',
  ),

  // Antique
  'ANT' => array(
    'Anini-Y',
    'Barbaza',
    'Belison',
    'Bugasong',
    'Caluya',
    'Culasi',
    'Tobias Fornier',
    'Hamtic',
    'Laua-An',
    'Libertad',
    'Pandan',
    'Patnongon',
    'San Jose (Capital)',
    'San Remigio',
    'Sebaste',
    'Sibalom',
    'Tibiao',
    'Valderrama',
  ),

  // Apayao
  'APA' => array(
    'Calanasan',
    'Conner',
    'Flora',
    'Kabugao (Capital)',
    'Luna',
    'Pudtol',
    'Santa Marcela',
  ),

  // Aurora
  'AUR' => array(
    'Baler (Capital)',
    'Casiguran',
    'Dilasag',
    'Dinalungan',
    'Dingalan',
    'Dipaculao',
    'Maria Aurora',
    'San Luis',
  ),

  // Basilan
  'BAS' => array(
    'Lamitan City (Capital)',
    'Lantawan',
    'Maluso',
    'Sumisip',
    'Tipo-Tipo',
    'Tuburan',
    'Akbar',
    'Al-Barka',
    'Hadji Mohammad Ajul',
    'Ungkaya Pukan',
    'Hadji Muhtamad',
    'Tabuan-Lasa',
  ),

  // Bataan
  'BAN' => array(
    'Abucay',
    'Bagac',
    'Balanga City (Capital)',
    'Dinalupihan',
    'Hermosa',
    'Limay',
    'Mariveles',
    'Morong',
    'Orani',
    'Orion',
    'Pilar',
    'Samal',
  ),

  // Batanes
  'BTN' => array(
    'Basco (Capital)',
    'Itbayat',
    'Ivana',
    'Mahatao',
    'Sabtang',
    'Uyugan',
  ),

  // Batangas
  'BTG' => array(
    'Agoncillo',
    'Alitagtag',
    'Balayan',
    'Balete',
    'Batangas City (Capital)',
    'Bauan',
    'Calaca',
    'Calatagan',
    'Cuenca',
    'Ibaan',
    'Laurel',
    'Lemery',
    'Lian',
    'Lipa City',
    'Lobo',
    'Mabini',
    'Malvar',
    'Mataasnakahoy',
    'Nasugbu',
    'Padre Garcia',
    'Rosario',
    'San Jose',
    'San Juan',
    'San Luis',
    'San Nicolas',
    'San Pascual',
    'Santa Teresita',
    'Sto. Tomas City',
    'Taal', 'Talisay',
    'Tanauan City',
    'Taysan',
    'Tingloy',
    'Tuy',
  ),

  // Benguet
  'BEN' => array(
    'Atok',
    'Baguio City',
    'Bakun',
    'Bokod',
    'Buguias',
    'Itogon',
    'Kabayan',
    'Kapangan',
    'Kibungan',
    'La Trinidad (Capital)',
    'Mankayan',
    'Sablan',
    'Tuba',
    'Tublay',
  ),

  // Biliran
  'BIL' => array(
    'Almeria',
    'Biliran',
    'Cabucgayan',
    'Caibiran',
    'Culaba',
    'Kawayan',
    'Maripipi',
    'Naval (Capital)',
  ),

  // Bohol
  'BOH' => array(
    'Alburquerque',
    'Alicia',
    'Anda',
    'Antequera',
    'Baclayon',
    'Balilihan',
    'Batuan',
    'Bien Unido',
    'Bilar',
    'Buenavista',
    'Calape',
    'Candijay',
    'Carmen',
    'Catigbian',
    'Clarin',
    'Corella',
    'Cortes',
    'Dagohoy',
    'Danao',
    'Dauis',
    'Dimiao',
    'Duero',
    'Garcia Hernandez',
    'Guindulman',
    'Inabanga',
    'Jagna',
    'Getafe',
    'Lila',
    'Loay',
    'Loboc',
    'Loon',
    'Mabini',
    'Maribojoc',
    'Panglao',
    'Pilar',
    'President Carlos P. Garcia',
    'Sagbayan',
    'San Isidro',
    'San Miguel',
    'Sevilla',
    'Sierra Bullones',
    'Sikatuna',
    'Talibon',
    'Tagbilaran City (Capital)',
    'Trinidad',
    'Tubigon',
    'Ubay',
    'Valencia',
  ),

  // Bukidnon
  'BUK' => array(
    'Baungon',
    'Cabanglasan',
    'Damulog',
    'Dangcagan',
    'Don Carlos',
    'Impasug-ong',
    'Kadingilan',
    'Kalilangan',
    'Kibawe',
    'Kitaotao',
    'Lantapan',
    'Libona',
    'Malaybalay City (Capital)',
    'Malitbog',
    'Manolo Fortich',
    'Maramag',
    'Pangantucan',
    'Quezon',
    'San Fernando',
    'Sumilao',
    'Talakag',
    'Valencia City',
  ),

  // Bulacan
  'BUL' => array(
    'Angat',
    'Balagtas',
    'Baliuag',
    'Bocaue',
    'Bulacan',
    'Bustos',
    'Calumpit',
    'Guiguinto',
    'Hagonoy',
    'Malolos City (Capital)',
    'Marilao',
    'Meycauayan City',
    'Norzagaray',
    'Obando',
    'Pandi',
    'Paombong',
    'Plaridel',
    'Pulilan',
    'San Ildefonso',
    'San Jose Del Monte City',
    'San Miguel',
    'San Rafael',
    'Santa Maria',
    'Doña Remedios Trinidad',
  ),

  // Cagayan
  'CAG' => array(
    'Abulug',
    'Alcala',
    'Allacapan',
    'Amulung',
    'Aparri',
    'Baggao',
    'Ballesteros',
    'Buguey',
    'Calayan',
    'Camalaniugan',
    'Claveria',
    'Enrile',
    'Gattaran',
    'Gonzaga',
    'Iguig',
    'Lal-Lo',
    'Lasam',
    'Pamplona',
    'Peñablanca',
    'Piat',
    'Rizal',
    'Sanchez-Mira',
    'Santa Ana',
    'Santa Praxedes',
    'Santa Teresita',
    'Santo Niño',
    'Solana',
    'Tuao',
    'Tuguegarao City (Capital)',
  ),

  // Camarines Norte
  'CAN' => array(
    'Basud',
    'Capalonga',
    'Daet (Capital)',
    'San Lorenzo Ruiz',
    'Jose Panganiban',
    'Labo',
    'Mercedes',
    'Paracale',
    'San Vicente',
    'Santa Elena',
    'Talisay',
    'Vinzons',
  ),

  // Camarines Sur
  'CAS' => array(
    'Baao',
    'Balatan',
    'Bato',
    'Bombon',
    'Buhi',
    'Bula',
    'Cabusao',
    'Calabanga',
    'Camaligan',
    'Canaman',
    'Caramoan',
    'Del Gallego',
    'Gainza',
    'Garchitorena',
    'Goa',
    'Iriga City',
    'Lagonoy',
    'Libmanan',
    'Lupi',
    'Magarao',
    'Milaor',
    'Minalabac',
    'Nabua',
    'Naga City',
    'Ocampo',
    'Pamplona',
    'Pasacao',
    'Pili (Capital)',
    'Presentacion',
    'Ragay',
    'Sagñay',
    'San Fernando',
    'San Jose',
    'Sipocot',
    'Siruma',
    'Tigaon',
    'Tinambac',
  ),

  // Camiguin
  'CAM' => array(
    'Catarman',
    'Guinsiliban',
    'Mahinog',
    'Mambajao (Capital)',
    'Sagay',
  ),

  // Capiz
  'CAP' => array(
    'Cuartero',
    'Dao',
    'Dumalag',
    'Dumarao',
    'Ivisan',
    'Jamindan',
    'Ma-Ayon',
    'Mambusao',
    'Panay',
    'Panitan',
    'Pilar',
    'Pontevedra',
    'President Roxas',
    'Roxas City (Capital)',
    'Sapi-An',
    'Sigma',
    'Tapaz',
  ),

  // Catanduanes
  'CAT' => array(
    'Bagamanoc',
    'Baras',
    'Bato',
    'Caramoran',
    'Gigmoto',
    'Pandan',
    'Panganiban',
    'San Andres',
    'San Miguel',
    'Viga',
    'Virac (Capital)',
  ),

  // Cavite
  'CAV' => array(
    'Alfonso',
    'Amadeo',
    'Bacoor City',
    'Carmona',
    'Cavite City',
    'Dasmariñas City',
    'General Emilio Aguinaldo',
    'General Trias City',
    'Imus City',
    'Indang',
    'Kawit',
    'Magallanes',
    'Maragondon',
    'Mendez',
    'Naic',
    'Noveleta',
    'Rosario',
    'Silang',
    'Tagaytay City',
    'Tanza',
    'Ternate',
    'Trece Martires City (Capital)',
    'Gen. Mariano Alvarez',
  ),

  // Cebu
  'CEB' => array(
    'Alcantara',
    'Alcoy',
    'Alegria',
    'Aloguinsan',
    'Argao',
    'Asturias',
    'Badian',
    'Balamban',
    'Bantayan',
    'Barili',
    'Bogo City',
    'Boljoon',
    'Borbon',
    'Carcar City',
    'Carmen',
    'Catmon',
    'Cebu City (Capital)',
    'Compostela',
    'Consolacion',
    'Cordova',
    'Daanbantayan',
    'Dalaguete',
    'Danao City',
    'Dumanjug',
    'Ginatilan',
    'Lapu-Lapu City',
    'Liloan',
    'Madridejos',
    'Malabuyoc',
    'Mandaue City',
    'Medellin',
    'Minglanilla',
    'Moalboal',
    'Naga City',
    'Oslob',
    'Pilar',
    'Pinamungajan',
    'Poro',
    'Ronda',
    'Samboan',
    'San Fernando',
    'San Francisco',
    'San Remigio',
    'Santa Fe',
    'Santander',
    'Sibonga',
    'Sogod',
    'Tabogon',
    'Tabuelan',
    'Talisay City',
    'Toledo City',
    'Tuburan',
    'Tudela',
  ),

  // Cotabato
  'NCO' => array(
    'Alamada',
    'Carmen',
    'Kabacan',
    'Kidapawan City (Capital)',
    'Libungan',
    'Magpet',
    'Makilala',
    'Matalam',
    'Midsayap',
    'M\'lang',
    'Pigkawayan',
    'Pikit',
    'President Roxas',
    'Tulunan',
    'Antipas',
    'Banisilan',
    'Aleosan',
    'Arakan',
  ),

  // Davao del Norte
  'DAV' => array(
    'Asuncion',
    'Carmen',
    'Island Garden City of Samal',
    'Kapalong',
    'New Corella',
    'Panabo City',
    'Santo Tomas',
    'Tagum City (Capital)',
    'Talaingod',
    'Braulio E. Dujali',
    'San Isidro',
  ),

  // Davao del Sur
  'DAS' => array(
    'Bansalan',
    'Davao City',
    'Digos City (Capital)',
    'Hagonoy',
    'Kiblawan',
    'Magsaysay',
    'Malalag',
    'Matanao',
    'Padada',
    'Santa Cruz',
    'Sulop',
  ),

  // Davao de Oro
  'COM' => array(
    'Compostela',
    'Laak',
    'Mabini',
    'Maco',
    'Maragusan',
    'Mawab',
    'Monkayo',
    'Montevista',
    'Nabunturan (Capital)',
    'New Bataan',
    'Pantukan',
  ),

  // Davao Occidental
  'DAC' => array(
    'Don Marcelino',
    'Jose Abad Santos',
    'Malita (Capital)',
    'Santa Maria',
    'Sarangani',
  ),

  // Davao Oriental
  'DAO' => array(
    'Baganga',
    'Banaybanay',
    'Boston',
    'Caraga',
    'Cateel',
    'Governor Generoso',
    'Lupon',
    'Manay',
    'Mati City (Capital)',
    'San Isidro',
    'Tarragona',
  ),

  // Dinagat Islands
  'DIN' => array(
    'Basilisa',
    'Cagdianao',
    'Dinagat',
    'Libjo',
    'Loreto',
    'San Jose (Capital)',
    'Tubajon',
  ),

  // Eastern Samar
  'EAS' => array(
    'Arteche',
    'Balangiga',
    'Balangkayan',
    'Borongan City (Capital)',
    'Can-Avid',
    'Dolores',
    'General Macarthur',
    'Giporlos',
    'Guiuan',
    'Hernani',
    'Jipapad',
    'Lawaan',
    'Llorente',
    'Maslog',
    'Maydolong',
    'Mercedes',
    'Oras',
    'Quinapondan',
    'Salcedo',
    'San Julian',
    'San Policarpo',
    'Sulat',
    'Taft',
  ),

  // Guimaras
  'GUI' => array(
    'Buenavista',
    'Jordan (Capital)',
    'Nueva Valencia',
    'San Lorenzo',
    'Sibunag',
  ),

  // Ifugao
  'IFU' => array(
    'Banaue',
    'Hungduan',
    'Kiangan',
    'Lagawe (Capital)',
    'Lamut',
    'Mayoyao',
    'Alfonso Lista',
    'Aguinaldo',
    'Hingyon',
    'Tinoc',
    'Asipulo',
  ),

  // Ilocos Norte
  'ILN' => array(
    'Adams',
    'Bacarra',
    'Badoc',
    'Bangui',
    'Banna',
    'Batac City',
    'Burgos',
    'Carasi',
    'Currimao',
    'Dingras',
    'Dumalneg',
    'Laoag City (Capital)',
    'Marcos',
    'Nueva Era',
    'Pagudpud',
    'Paoay',
    'Pasuquin',
    'Piddig',
    'Pinili',
    'San Nicolas',
    'Sarrat',
    'Solsona',
    'Vintar',
  ),

  // Ilocos Sur
  'ILS' => array(
    'Alilem',
    'Banayoyo',
    'Bantay',
    'Burgos',
    'Cabugao',
    'Candon City',
    'Caoayan',
    'Cervantes',
    'Galimuyod',
    'Gregorio del Pilar',
    'Lidlidda',
    'Magsingal',
    'Nagbukel',
    'Narvacan',
    'Quirino',
    'Salcedo',
    'San Emilio',
    'San Esteban',
    'San Ildefonso',
    'San Juan',
    'San Vicente',
    'Santa',
    'Santa Catalina',
    'Santa Cruz',
    'Santa Lucia',
    'Santa Maria',
    'Santiago',
    'Santo Domingo',
    'Sigay',
    'Sinait',
    'Sugpon',
    'Suyo',
    'Tagudin',
    'Vigan City (Capital)',
  ),

  // Iloilo
  'ILI' => array(
    'Ajuy',
    'Alimodian',
    'Anilao',
    'Badiangan',
    'Balasan',
    'Banate',
    'Barotac Nuevo',
    'Barotac Viejo',
    'Batad',
    'Bingawan',
    'Cabatuan',
    'Calinog',
    'Carles',
    'Concepcion',
    'Dingle',
    'Dueñas',
    'Dumangas',
    'Estancia',
    'Guimbal',
    'Igbaras',
    'Iloilo City (Capital)',
    'Janiuay',
    'Lambunao',
    'Leganes',
    'Lemery',
    'Leon',
    'Maasin',
    'Miagao',
    'Mina',
    'New Lucena',
    'Oton',
    'Passi City',
    'Pavia',
    'Pototan',
    'San Dionisio',
    'San Enrique',
    'San Joaquin',
    'San Miguel',
    'San Rafael',
    'Santa Barbara',
    'Sara',
    'Tigbauan',
    'Tubungan',
    'Zarraga',
  ),

  // Isabela
  'ISA' => array(
    'Alicia',
    'Angadanan',
    'Aurora',
    'Benito Soliven',
    'Burgos',
    'Cabagan',
    'Cabatuan',
    'Cauayan City',
    'Cordon',
    'Delfin Albano',
    'Dinapigue',
    'Divilacan',
    'Echague',
    'Gamu',
    'Ilagan City (Capital)',
    'Jones',
    'Luna',
    'Maconacon',
    'Mallig',
    'Naguilian',
    'Palanan',
    'Quezon',
    'Quirino',
    'Ramon',
    'Reina Mercedes',
    'Roxas',
    'San Agustin',
    'San Guillermo',
    'San Isidro',
    'San Manuel',
    'San Mariano',
    'San Mateo',
    'San Pablo',
    'Santa Maria',
    'Santiago City',
    'Santo Tomas',
    'Tumauini',
  ),

  // Kalinga
  'KAL' => array(
    'Balbalan',
    'Lubuagan',
    'Pasil',
    'Pinukpuk',
    'Rizal',
    'Tabuk City (Capital)',
    'Tanudan',
    'Tinglayan',
  ),

  // La Union
  'LUN' => array(
    'Agoo',
    'Aringay',
    'Bacnotan',
    'Bagulin',
    'Balaoan',
    'Bangar',
    'Bauang',
    'Burgos',
    'Caba',
    'Luna',
    'Naguilian',
    'Pugo',
    'Rosario',
    'San Fernando City (Capital)',
    'San Gabriel',
    'San Juan',
    'Santo Tomas',
    'Santol',
    'Sudipen',
    'Tubao',
  ),

  // Laguna
  'LAG' => array(
    'Alaminos',
    'Bay',
    'Biñan City',
    'Cabuyao City',
    'Calamba City',
    'Calauan',
    'Cavinti',
    'Famy',
    'Kalayaan',
    'Liliw',
    'Los Baños',
    'Luisiana',
    'Lumban',
    'Mabitac',
    'Magdalena',
    'Majayjay',
    'Nagcarlan',
    'Paete',
    'Pagsanjan',
    'Pakil',
    'Pangil',
    'Pila',
    'Rizal',
    'San Pablo City',
    'San Pedro City',
    'Santa Cruz (Capital)',
    'Santa Maria',
    'Santa Rosa City',
    'Siniloan',
    'Victoria',
  ),

  // Lanao del Norte
  'LAN' => array(
    'Bacolod',
    'Baloi',
    'Baroy',
    'Iligan City',
    'Kapatagan',
    'Kauswagan',
    'Kolambugan',
    'Lala',
    'Linamon',
    'Magsaysay',
    'Maigo',
    'Matungao',
    'Munai',
    'Nunungan',
    'Pantao Ragat',
    'Poona Piagapo',
    'Salvador',
    'Sapad',
    'Sultan Naga Dimaporo',
    'Tagoloan',
    'Tangcal',
    'Tubod (Capital)',
    'Pantar',
  ),

  // Lanao del Sur
  'LAS' => array(
    'Amai Manabilang',
    'Bacolod-Kalawi',
    'Balabagan',
    'Balindong',
    'Bayang',
    'Binidayan',
    'Buadiposo-Buntong',
    'Bubong',
    'Butig',
    'Calanogas',
    'Ditsaan-Ramain',
    'Ganassi',
    'Kapai',
    'Kapatagan',
    'Lumba-Bayabao',
    'Lumbaca-Unayan',
    'Lumbatan',
    'Lumbayanague',
    'Madalum',
    'Madamba',
    'Maguing',
    'Malabang',
    'Marantao',
    'Marawi City (Capital)',
    'Marogong',
    'Masiu',
    'Mulondo',
    'Pagayawan',
    'Piagapo',
    'Picong',
    'Poona Bayabao',
    'Pualas',
    'Saguiaran',
    'Sultan Dumalondong',
    'Tagoloan Ii',
    'Tamparan',
    'Taraka',
    'Tubaran',
    'Tugaya',
    'Wao',
  ),

  // Leyte
  'LEY' => array(
    'Abuyog',
    'Alangalang',
    'Albuera',
    'Babatngon',
    'Barugo',
    'Bato',
    'Baybay City',
    'Burauen',
    'Calubian',
    'Capoocan',
    'Carigara',
    'Dagami',
    'Dulag',
    'Hilongos',
    'Hindang',
    'Inopacan',
    'Isabel',
    'Jaro',
    'Javier',
    'Julita',
    'Kananga',
    'La Paz',
    'Leyte',
    'Macarthur',
    'Mahaplag',
    'Matag-Ob',
    'Matalom',
    'Mayorga',
    'Merida',
    'Ormoc City',
    'Palo',
    'Palompon',
    'Pastrana',
    'San Isidro',
    'San Miguel',
    'Santa Fe',
    'Tabango',
    'Tabontabon',
    'Tacloban City (Capital)',
    'Tanauan',
    'Tolosa',
    'Tunga',
    'Villaba',
  ),

  // Maguindanao
  'MAG' => array(
    'Ampatuan',
    'Barira',
    'Buldon',
    'Buluan',
    'Datu Abdullah Sangki',
    'Datu Anggal Midtimbang',
    'Datu Blah T. Sinsuat',
    'Datu Hoffer Ampatuan',
    'Datu Odin Sinsuat',
    'Datu Paglas',
    'Datu Piang',
    'Datu Salibo',
    'Datu Saudi-Ampatuan',
    'Datu Unsay',
    'Gen. S.K. Pendatun',
    'Guindulungan',
    'Kabuntalan',
    'Mamasapano',
    'Mangudadatu',
    'Matanog',
    'Northern Kabuntalan',
    'Pagagawan',
    'Pagalungan',
    'Paglat',
    'Pandag',
    'Parang',
    'Rajah Buayan',
    'Shariff Aguak (Capital)',
    'Shariff Saydona Mustapha',
    'South Upi',
    'Sultan Kudarat',
    'Sultan Mastura',
    'Sultan Sa Barongis',
    'Talayan',
    'Talitay',
    'Upi',
  ),

  // Marinduque
  'MAD' => array(
    'Boac (Capital)',
    'Buenavista',
    'Gasan',
    'Mogpog',
    'Santa Cruz',
    'Torrijos',
  ),

  // Masbate
  'MAS' => array(
    'Aroroy',
    'Baleno',
    'Balud',
    'Batuan',
    'Cataingan',
    'Cawayan',
    'Claveria',
    'Dimasalang',
    'Esperanza',
    'Mandaon',
    'Masbate City (Capital)',
    'Milagros',
    'Mobo',
    'Monreal',
    'Palanas',
    'Pio V. Corpuz',
    'Placer',
    'San Fernando',
    'San Jacinto',
    'San Pascual',
    'Uson',
  ),

  // Misamis Occidental
  'MSC' => array(
    'Aloran',
    'Baliangao',
    'Bonifacio',
    'Calamba',
    'Clarin',
    'Concepcion',
    'Don Victoriano Chiongbian',
    'Jimenez',
    'Lopez Jaena',
    'Oroquieta City (Capital)',
    'Ozamiz City',
    'Panaon',
    'Plaridel',
    'Sapang Dalaga',
    'Sinacaban',
    'Tangub City',
    'Tudela',
  ),

  // Misamis Oriental
  'MSR' => array(
    'Alubijid',
    'Balingasag',
    'Balingoan',
    'Binuangan',
    'Cagayan De Oro City (Capital)',
    'Claveria',
    'El Salvador City',
    'Gingoog City',
    'Gitagum',
    'Initao',
    'Jasaan',
    'Kinoguitan',
    'Lagonglong',
    'Laguindingan',
    'Libertad',
    'Lugait',
    'Magsaysay',
    'Manticao',
    'Medina',
    'Naawan',
    'Opol',
    'Salay',
    'Sugbongcogon',
    'Tagoloan',
    'Talisayan',
    'Villanueva',
  ),

  // Mountain Province
  'MOU' => array(
    'Barlig',
    'Bauko',
    'Besao',
    'Bontoc (Capital)',
    'Natonin',
    'Paracelis',
    'Sabangan',
    'Sadanga',
    'Sagada',
    'Tadian',
  ),

  // Negros Occidental
  'NEC' => array(
    'Bacolod City (Capital)',
    'Bago City',
    'Binalbagan',
    'Cadiz City',
    'Calatrava',
    'Candoni',
    'Cauayan',
    'Enrique B. Magalona',
    'Escalante City',
    'Himamaylan City',
    'Hinigaran',
    'Hinoba-an',
    'Ilog',
    'Isabela',
    'Kabankalan City',
    'La Carlota City',
    'La Castellana',
    'Manapla',
    'Moises Padilla',
    'Murcia',
    'Pontevedra',
    'Pulupandan',
    'Sagay City',
    'Salvador Benedicto',
    'San Carlos City',
    'San Enrique',
    'Silay City',
    'Sipalay City',
    'Talisay City',
    'Toboso',
    'Valladolid',
    'Victorias City',
  ),

  // Negros Oriental
  'NER' => array(
    'Amlan',
    'Ayungon',
    'Bacong',
    'Bais City',
    'Basay',
    'Bayawan City',
    'Bindoy',
    'Canlaon City',
    'Dauin',
    'Dumaguete City (Capital)',
    'Guihulngan City',
    'Jimalalud',
    'La Libertad',
    'Mabinay',
    'Manjuyod',
    'Pamplona',
    'San Jose',
    'Santa Catalina',
    'Siaton',
    'Sibulan',
    'Tanjay City',
    'Tayasan',
    'Valencia',
    'Vallehermoso',
    'Zamboanguita',
  ),

  // Northern Samar
  'NSA' => array(
    'Allen',
    'Biri',
    'Bobon',
    'Capul',
    'Catarman (Capital)',
    'Catubig',
    'Gamay',
    'Laoang',
    'Lapinig',
    'Las Navas',
    'Lavezares',
    'Mapanas',
    'Mondragon',
    'Palapag',
    'Pambujan',
    'Rosario',
    'San Antonio',
    'San Isidro',
    'San Jose',
    'San Roque',
    'San Vicente',
    'Silvino Lobos',
    'Victoria',
    'Lope De Vega',
  ),

  // Nueva Ecija
  'NUE' => array(
    'Aliaga',
    'Bongabon',
    'Cabanatuan City',
    'Cabiao',
    'Carranglan',
    'Cuyapo',
    'Gabaldon',
    'Gapan City',
    'General Mamerto Natividad',
    'General Tinio',
    'Guimba',
    'Jaen',
    'Laur',
    'Licab',
    'Llanera',
    'Lupao',
    'Nampicuan',
    'Palayan City (Capital)',
    'Pantabangan',
    'Peñaranda',
    'Quezon',
    'Rizal',
    'San Antonio',
    'San Isidro',
    'San Jose City',
    'San Leonardo',
    'Santa Rosa',
    'Santo Domingo',
    'Science City of Muñoz',
    'Talavera',
    'Talugtug',
    'Zaragoza',
  ),

  // Nueva Vizcaya
  'NUV' => array(
    'Ambaguio',
    'Aritao',
    'Bagabag',
    'Bambang',
    'Bayombong (Capital)',
    'Diadi',
    'Dupax del Norte',
    'Dupax del Sur',
    'Kasibu',
    'Kayapa',
    'Quezon',
    'Santa Fe',
    'Solano',
    'Villaverde',
    'Alfonso Castaneda',
  ),

  // Occidental Mindoro
  'MDC' => array(
    'Abra De Ilog',
    'Calintaan',
    'Looc',
    'Lubang',
    'Magsaysay',
    'Mamburao (Capital)',
    'Paluan',
    'Rizal',
    'Sablayan',
    'San Jose',
    'Santa Cruz',
  ),

  // Oriental Mindoro
  'MDR' => array(
    'Baco',
    'Bansud',
    'Bongabong',
    'Bulalacao',
    'Calapan City (Capital)',
    'Gloria',
    'Mansalay',
    'Naujan',
    'Pinamalayan',
    'Pola',
    'Puerto Galera',
    'Roxas',
    'San Teodoro',
    'Socorro',
    'Victoria',
  ),

  // Palawan
  'PLW' => array(
    'Aborlan',
    'Agutaya',
    'Araceli',
    'Balabac',
    'Bataraza',
    'Brooke\'s Point',
    'Busuanga',
    'Cagayancillo',
    'Coron',
    'Culion',
    'Cuyo',
    'Dumaran',
    'El Nido',
    'Kalayaan',
    'Linapacan',
    'Magsaysay',
    'Narra',
    'Puerto Princesa City (Capital)',
    'Quezon',
    'Rizal',
    'Roxas',
    'San Vicente',
    'Sofronio Española',
    'Taytay',
  ),

  // Pampanga
  'PAM' => array(
    'Angeles City',
    'Apalit',
    'Arayat',
    'Bacolor',
    'Candaba',
    'Floridablanca',
    'Guagua',
    'Lubao',
    'Mabalacat City',
    'Macabebe',
    'Magalang',
    'Masantol',
    'Mexico',
    'Minalin',
    'Porac',
    'San Fernando City (Capital)',
    'San Luis',
    'San Simon',
    'Santa Ana',
    'Santa Rita',
    'Santo Tomas',
    'Sasmuan',
  ),

  // Pangasinan
  'PAN' => array(
    'Agno',
    'Aguilar',
    'Alaminos City',
    'Alcala',
    'Anda',
    'Asingan',
    'Balungao',
    'Bani',
    'Basista',
    'Bautista',
    'Bayambang',
    'Binalonan',
    'Binmaley',
    'Bolinao',
    'Bugallon',
    'Burgos',
    'Calasiao',
    'Dagupan City',
    'Dasol',
    'Infanta',
    'Labrador',
    'Laoac',
    'Lingayen (Capital)',
    'Mabini',
    'Malasiqui',
    'Manaoag',
    'Mangaldan',
    'Mangatarem',
    'Mapandan',
    'Natividad',
    'Pozorrubio',
    'Rosales',
    'San Carlos City',
    'San Fabian',
    'San Jacinto',
    'San Manuel',
    'San Nicolas',
    'San Quintin',
    'Santa Barbara',
    'Santa Maria',
    'Santo Tomas',
    'Sison',
    'Sual',
    'Tayug',
    'Umingan',
    'Urbiztondo',
    'Urdaneta City',
    'Villasis',
  ),

  // Quezon
  'QUE' => array(
    'Agdangan',
    'Alabat',
    'Atimonan',
    'Buenavista',
    'Burdeos',
    'Calauag',
    'Candelaria',
    'Catanauan',
    'Dolores',
    'General Luna',
    'General Nakar',
    'Guinayangan',
    'Gumaca',
    'Infanta',
    'Jomalig',
    'Lopez',
    'Lucban',
    'Lucena City (Capital)',
    'Macalelon',
    'Mauban',
    'Mulanay',
    'Padre Burgos',
    'Pagbilao',
    'Panukulan',
    'Patnanungan',
    'Perez',
    'Pitogo',
    'Plaridel',
    'Polillo',
    'Quezon',
    'Real',
    'Sampaloc',
    'San Andres',
    'San Antonio',
    'San Francisco',
    'San Narciso',
    'Sariaya',
    'Tagkawayan',
    'Tayabas City',
    'Tiaong',
    'Unisan',
  ),

  // Quirino
  'QUI' => array(
    'Aglipay',
    'Cabarroguis (Capital)',
    'Diffun',
    'Maddela',
    'Nagtipunan',
    'Saguday',
  ),

  // Rizal
  'RIZ' => array(
    'Angono',
    'Antipolo City (Capital)',
    'Baras',
    'Binangonan',
    'Cainta',
    'Cardona',
    'Jala-Jala',
    'Morong',
    'Pililla',
    'Rodriguez',
    'San Mateo',
    'Tanay',
    'Taytay',
    'Teresa',
  ),

  // Romblon
  'ROM' => array(
    'Alcantara',
    'Banton',
    'Cajidiocan',
    'Calatrava',
    'Concepcion',
    'Corcuera',
    'Ferrol',
    'Looc',
    'Magdiwang',
    'Odiongan',
    'Romblon (Capital)',
    'San Agustin',
    'San Andres',
    'San Fernando',
    'San Jose',
    'Santa Fe',
    'Santa Maria',
  ),

  // Samar
  'WSA' => array(
    'Almagro',
    'Basey',
    'Calbayog City',
    'Calbiga',
    'Catbalogan City (Capital)',
    'Daram',
    'Gandara',
    'Hinabangan',
    'Jiabong',
    'Marabut',
    'Matuguinao',
    'Motiong',
    'Pagsanghan',
    'Paranas',
    'Pinabacdao',
    'San Jorge',
    'San Jose De Buan',
    'San Sebastian',
    'Santa Margarita',
    'Santa Rita',
    'Santo Niño',
    'Tagapul-An',
    'Talalora',
    'Tarangnan',
    'Villareal',
    'Zumarraga',
  ),

  // Sarangani
  'SAR' => array(
    'Alabel (Capital)',
    'Glan',
    'Kiamba',
    'Maasim',
    'Maitum',
    'Malapatan',
    'Malungon',
  ),

  // Siquijor
  'SIQ' => array(
    'Enrique Villanueva',
    'Larena',
    'Lazi',
    'Maria',
    'San Juan',
    'Siquijor (Capital)',
  ),

  // Sorsogon
  'SOR' => array(
    'Barcelona',
    'Bulan',
    'Bulusan',
    'Casiguran',
    'Castilla',
    'Donsol',
    'Gubat',
    'Irosin',
    'Juban',
    'Magallanes',
    'Matnog',
    'Pilar',
    'Prieto Diaz',
    'Santa Magdalena',
    'Sorsogon City (Capital)',
  ),

  // South Cotabato
  'SCO' => array(
    'Banga',
    'General Santos City',
    'Koronadal City (Capital)',
    'Lake Sebu',
    'Norala',
    'Polomolok',
    'Santo Niño',
    'Surallah',
    'T\'Boli',
    'Tampakan',
    'Tantangan',
    'Tupi',
  ),

  // Southern Leyte
  'SLE' => array(
    'Anahawan',
    'Bontoc',
    'Hinunangan',
    'Hinundayan',
    'Libagon',
    'Liloan',
    'Limasawa',
    'Maasin City (Capital)',
    'Macrohon',
    'Malitbog',
    'Padre Burgos',
    'Pintuyan',
    'Saint Bernard',
    'San Francisco',
    'San Juan',
    'San Ricardo',
    'Silago',
    'Sogod',
    'Tomas Oppus',
  ),

  // Sultan Kudarat
  'SUK' => array(
    'Bagumbayan',
    'Columbio',
    'Esperanza',
    'Isulan (Capital)',
    'Kalamansig',
    'Lambayong',
    'Lebak',
    'Lutayan',
    'Palimbang',
    'President Quirino',
    'Sen. Ninoy Aquino',
    'Tacurong City',
  ),

  // Sulu
  'SLU' => array(
    'Hadji Panglima Tahil',
    'Indanan',
    'Jolo (Capital)',
    'Kalingalan Caluang',
    'Lugus',
    'Luuk',
    'Maimbung',
    'Old Panamao',
    'Omar',
    'Pandami',
    'Panglima Estino',
    'Pangutaran',
    'Parang',
    'Pata',
    'Patikul',
    'Siasi',
    'Talipao',
    'Tapul',
    'Tongkil',
  ),

  // Surigao del Norte
  'SUN' => array(
    'Alegria',
    'Bacuag',
    'Burgos',
    'Claver',
    'Dapa',
    'Del Carmen',
    'General Luna',
    'Gigaquit',
    'Mainit',
    'Malimono',
    'Pilar',
    'Placer',
    'San Benito',
    'San Francisco',
    'San Isidro',
    'Santa Monica',
    'Sison',
    'Socorro',
    'Surigao City (Capital)',
    'Tagana-An',
    'Tubod',
  ),

  // Surigao del Sur
  'SUR' => array(
    'Barobo',
    'Bayabas',
    'Bislig City',
    'Cagwait',
    'Cantilan',
    'Carmen',
    'Carrascal',
    'Cortes',
    'Hinatuan',
    'Lanuza',
    'Lianga',
    'Lingig',
    'Madrid',
    'Marihatag',
    'San Agustin',
    'San Miguel',
    'Tagbina',
    'Tago',
    'Tandag City (Capital)',
  ),

  // Tarlac
  'TAR' => array(
    'Anao',
    'Bamban',
    'Camiling',
    'Capas',
    'Concepcion',
    'Gerona',
    'La Paz',
    'Mayantoc',
    'Moncada',
    'Paniqui',
    'Pura',
    'Ramos',
    'San Clemente',
    'San Jose',
    'San Manuel',
    'Santa Ignacia',
    'Tarlac City (Capital)',
    'Victoria',
  ),

  // Tawi-Tawi
  'TAW' => array(
    'Bongao (Capital)',
    'Languyan',
    'Mapun',
    'Panglima Sugala',
    'Sapa-Sapa',
    'Sibutu',
    'Simunul',
    'Sitangkai',
    'South Ubian',
    'Tandubas',
    'Turtle Islands',
  ),

  // Zambales
  'ZMB' => array(
    'Botolan',
    'Cabangan',
    'Candelaria',
    'Castillejos',
    'Iba (Capital)',
    'Masinloc',
    'Olongapo City',
    'Palauig',
    'San Antonio',
    'San Felipe',
    'San Marcelino',
    'San Narciso',
    'Santa Cruz',
    'Subic',
  ),

  // Zamboanga del Norte
  'ZAN' => array(
    'Bacungan',
    'Baliguian',
    'Dapitan City',
    'Dipolog City (Capital)',
    'Godod',
    'Gutalac',
    'Jose Dalman',
    'Kalawit',
    'Katipunan',
    'Labason',
    'La Libertad',
    'Liloy',
    'Manukan',
    'Mutia',
    'Piñan',
    'Polanco',
    'Pres. Manuel A. Roxas',
    'Rizal',
    'Salug',
    'Sergio Osmeña Sr.',
    'Siayan',
    'Sibuco',
    'Sibutad',
    'Sindangan',
    'Siocon',
    'Sirawai',
    'Tampilisan',
  ),

  // Zamboanga del Sur
  'ZAS' => array(
    'Aurora',
    'Bayog',
    'Dimataling',
    'Dinas',
    'Dumalinao',
    'Dumingag',
    'Guipos',
    'Josefina',
    'Kumalarang',
    'Labangan',
    'Lakewood',
    'Lapuyan',
    'Mahayag',
    'Margosatubig',
    'Midsalip',
    'Molave',
    'Pagadian City (Capital)',
    'Pitogo',
    'Ramon Magsaysay',
    'San Miguel',
    'San Pablo',
    'Sominot',
    'Tabina',
    'Tambulig',
    'Tigbao',
    'Tukuran',
    'Vincenzo A. Sagun',
    'Zamboanga City',
  ),

  // Zamboanga Sibugay
  'ZSI' => array(
    'Alicia',
    'Buug',
    'Diplahan',
    'Imelda',
    'Ipil (Capital)',
    'Kabasalan',
    'Mabuhay',
    'Malangas',
    'Naga',
    'Olutanga',
    'Payao',
    'Roseller Lim',
    'Siay',
    'Talusan',
    'Titay',
    'Tungawan',
  ),

  // Metro Manila
  '00' => array(
    'Caloocan City',
    'Las Piñas City',
    'Makati City',
    'Malabon City',
    'Mandaluyong City',
    'Manila City',
    'Marikina City',
    'Muntinlupa City',
    'Navotas City',
    'Parañaque City',
    'Pasay City',
    'Pasig City',
    'Pateros',
    'Quezon City',
    'San Juan City',
    'Taguig City',
    'Valenzuela City',
  ),
);
