<?php

/**
 * Cities of Uruguay
 * - 2120 cities
 *  
 * Source:
 * [Source is missing]
 * 
 * Updated: April 06, 2020
 * By Yordan Soares <contact@yordansoar.es> | https://yordansoar.es
 *
 * @author  Alfonso Frachelle <www.idearius.com> | * @version 1.0.0
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 */
global $places;
$places['UY'] = array(
	'UY-AR' => array(
		'Artigas',
		'Baltasar Brum',
		'Bella Union',
		'Bernabe Rivera',
		'Cainsa',
		'Cainza Campo 3',
		'Calnu',
		'Camaño',
		'Catalan Grande',
		'Catalan Volcan',
		'Cerrito',
		'Cerro Ejido',
		'Cerro San Eugenio',
		'Cerro Signorelli',
		'Chiflero',
		'Colonia España',
		'Colonia Estrella',
		'Colonia Jose Artigas',
		'Colonia Palma',
		'Colonia Pintado',
		'Colonia Viñar',
		'Coronado',
		'Cuareim',
		'Cuaro',
		'Diego Lamas',
		'Estiba',
		'Fagundez',
		'Franquia',
		'Guyubira',
		'Javier De Viana',
		'La Bolsa',
		'Las Piedras',
		'Lenguazo',
		'Limite Contestado',
		'Meneses',
		'Mones Quintela',
		'Paguero',
		'Palma Sola',
		'Paredon',
		'Paso Campamento',
		'Paso De La Cruz',
		'Paso De Leon',
		'Paso De Ramos',
		'Paso Farias',
		'Patitas',
		'Piedra Pintada',
		'Pintadito',
		'Pintado',
		'Pintado Grande',
		'Port. De Hierro Y Campodonico',
		'Rincon De Pacheco',
		'Sarandi De Cuaro',
		'Sarandi De Yacuy',
		'Sequeira',
		'Tamandua',
		'Taruman',
		'Tomas Gomensoro',
		'Topador',
		'Zanja Aruera'
	),
	'UY-CA' => array(
		'Aeropuerto Internacional De Carrasco',
		'Aguas Corrientes',
		'Altos De La Tahona',
		'Araminda',
		'Arenal',
		'Argentino',
		'Atlantida',
		'B.H.U.',
		'Barra De Carrasco',
		'Barra De La Pedrera',
		'Barra Del Tala',
		'Barrancas Coloradas',
		'Barrio Artigas',
		'Barrio Benzo',
		'Barrio Copola',
		'Barrio Del Libertador',
		'Barrio La Lucha',
		'Barrio Los Panoramas',
		'Barrio Obrero',
		'Barrio Pretti',
		'Barrio Remanso',
		'Barrio San Cristobal',
		'Barrio Santa Rita',
		'Barrio Traverso',
		'Barrio Villa Murcia',
		'Bello Horizonte',
		'Biarritz',
		'Blanco',
		'Bolivar',
		'Camino De La Cadena',
		'Camino Dodera',
		'Camino Lloveras',
		'Campo Militar',
		'Canelon Chico',
		'Canelon Chico Al Centro',
		'Canelon Chico De Progreso',
		'Canelon Grande',
		'Canelon Grande De Pacheco',
		'Canelon Grande Norte',
		'Canelones',
		'Cañada Cardozo',
		'Cañada De Montaño',
		'Cañada Grande',
		'Cañada Prudencio',
		'Capilla De Cella',
		'Capitan Juan Antonio Artigas',
		'Carmel',
		'Carrasco Del Sauce',
		'Casarino',
		'Cerrillos Al Oeste',
		'Cerrillos Al Sur',
		'City Golf',
		'Ciudad De La Costa',
		'Cochengo',
		'Colinas De Carrasco',
		'Colinas De Solymar',
		'Colonia Nicolich',
		'Colonia Treinta Y Tres Orientales',
		'Colorado Chico',
		'Colorado Y Brujas',
		'Costa Azul',
		'Costa De Pando',
		'Costa De Pando Olmos',
		'Costa De Pando San Bautista',
		'Costa De Pando San Jacinto',
		'Costa Del Pantanoso',
		'Costa Del Sauce',
		'Costa Del Tala Este',
		'Costa Del Tala Norte',
		'Costa Y Guillamon',
		'Costas De Pedernal',
		'Costas De Santa Lucia',
		'Costas De Solis',
		'Costas Del Colorado',
		'Costas Del Colorado Este',
		'Costas Del Tala',
		'Cruz De Los Caminos',
		'Cuchilla Alta',
		'Cuchilla Alta Y El Galeon',
		'Cuchilla Cabo De Hornos',
		'Cuchilla De Machin',
		'Cuchilla De Rocha',
		'Cuchilla De Sierra',
		'Cuchilla De Zeballos',
		'Cuchilla Verde',
		'Cueva Del Tigre',
		'Cumbres De Carrasco',
		'Dr. Francisco Soca',
		'Echevarria',
		'El Bosque',
		'El Bosque De Solymar',
		'El Colorado',
		'El Colorado De Migues',
		'El Colorado San Bautista',
		'El Cuadro',
		'El Dorado',
		'El Galeon',
		'El Pinar',
		'Empalme Dogliotti',
		'Empalme Nicolich',
		'Empalme Olmos',
		'Empalme Sauce',
		'Esquina Gonzalez',
		'Estacion Atlantida',
		'Estacion La Floresta',
		'Estacion Migues',
		'Estacion Pedrera',
		'Estacion Piedras De Afilar',
		'Estacion Tapia',
		'Estanque De Pando',
		'Feliciano',
		'Fortin De Santa Rosa',
		'Fracc Sobre Ruta 74',
		'Fracc. Cno. Andaluz Y R.84',
		'Fracc. Progreso',
		'Guazuvira',
		'Guazuvira Nuevo',
		'Haras Del Lago',
		'Instituto Adventista',
		'Jardines De Pando',
		'Jaureguiberry',
		'Joaquin Suarez',
		'Juanico',
		'La Asuncion',
		'La Chinchilla',
		'La Floresta',
		'La Montañesa',
		'La Palmita',
		'La Paloma',
		'La Paz',
		'La Totora',
		'La Tuna',
		'Lago Jardin Del Bosque',
		'Lagomar',
		'Las Brujas',
		'Las Higueritas',
		'Las Piedras',
		'Las Ranas',
		'Las Toscas',
		'Las Vegas',
		'Las Violetas',
		'Lomas De Carrasco',
		'Lomas De Solymar',
		'Lomas De Toledo',
		'Los Ceibos',
		'Los Cerrillos',
		'Los Hornos',
		'Los Titanes',
		'Macana',
		'Margat',
		'Marindia',
		'Mata Siete',
		'Mataojo',
		'Medanos De Solymar',
		'Melgarejo',
		'Melilla',
		'Migues',
		'Montes',
		'Montes De Solymar',
		'Murialdo',
		'Nataly',
		'Neptunia',
		'Nutrias',
		'Olmos',
		'Pando',
		'Pantanoso',
		'Pantanoso Del Sauce',
		'Parada Cabrera',
		'Parador Tajes',
		'Parque Carrasco',
		'Parque De Solymar',
		'Parque Del Plata',
		'Parque Miramar',
		'Paso Arbelo',
		'Paso Carrasco',
		'Paso De Cuello',
		'Paso De La Cadena',
		'Paso De La Paloma',
		'Paso De La Salamanca',
		'Paso De Las Toscas',
		'Paso De Los Alamos',
		'Paso De Los Difuntos',
		'Paso De Los Francos',
		'Paso De Pache',
		'Paso Del Bote',
		'Paso Del Colorado',
		'Paso Del Medio',
		'Paso Del Sordo',
		'Paso Espinosa',
		'Paso Palomeque',
		'Paso Rivero De Vejigas',
		'Pedernal',
		'Pedernal Chico',
		'Pedernal Grande',
		'Piedra Del Toro',
		'Piedra Sola',
		'Piedras De Afilar',
		'Piedritas',
		'Piedritas De Suarez',
		'Pinamar',
		'Pinamar Y Pinepark',
		'Pinares De Solymar',
		'Pine Park',
		'Ponce Mata Siete',
		'Poquitos',
		'Progreso',
		'Pueblo Castellanos',
		'Puente De Brujas',
		'Puntas De Brujas',
		'Puntas De Canelon Chico',
		'Puntas De Cañada Cardozo',
		'Puntas De Cañada Grande',
		'Puntas De Cochengo',
		'Puntas De Las Violetas',
		'Puntas De Mata Siete',
		'Puntas De Pantanoso',
		'Puntas De Pantanoso Este',
		'Puntas De Pedrera',
		'Puntas De Toledo',
		'Puntas De Vejigas',
		'Puntas Del Arenal',
		'Quinta Los Horneros',
		'Quintas Del Bosque',
		'Rancherios De Ponce',
		'Rincon De Carrasco',
		'Rincon De Pando',
		'Rincon De Portezuelo',
		'Rincon De Velazquez',
		'Rincon De Vidal',
		'Rincon Del Colorado',
		'Rincon Del Conde',
		'Rincon Del Gigante',
		'Salinas',
		'San Andres',
		'San Andres',
		'San Antonio',
		'San Bautista',
		'San Jacinto',
		'San Jose De Carrasco',
		'San Luis',
		'San Pedro',
		'San Ramon',
		'Santa Ana',
		'Santa Lucia',
		'Santa Lucia Del Este',
		'Santa Rosa',
		'Santa Teresita',
		'Santos Lugares',
		'Sarandi De Migues',
		'Sauce',
		'Sauce De Solis',
		'Sauce Solo',
		'Sauce Solo De Migues',
		'Sauce Solo De Montes',
		'Seis Hermanos',
		'Shangrila',
		'Sofia Santos',
		'Solis Chico',
		'Solis Chico De Migues',
		'Solymar',
		'Sosa Diaz',
		'Tala',
		'Talita',
		'Toledo',
		'Totoral Del Sauce',
		'Vejigas',
		'Vejigas De San Ramon',
		'Vejigas De Tala',
		'Viejo Molino San Bernardo',
		'Villa Aeroparque',
		'Villa Arejo',
		'Villa Argentina',
		'Villa Crespo',
		'Villa Crespo',
		'Villa El Tato',
		'Villa Encantada',
		'Villa Felicidad',
		'Villa Foresti',
		'Villa Fortuna',
		'Villa Hadita',
		'Villa Huertos De Toledo',
		'Villa Juana',
		'Villa Juanita',
		'Villa Los Alpes',
		'Villa Marina',
		'Villa Molfino',
		'Villa Nueva',
		'Villa Paz S.A.',
		'Villa Prados De Toledo',
		'Villa San Cono',
		'Villa San Felipe',
		'Villa San Jose',
		'Villa Valverde',
		'Vista Linda'
	),
	'UY-CL' => array(
		'Acegua',
		'Aguirre',
		'Amarillo',
		'Arachania',
		'Arbolito',
		'Arevalo',
		'Arroyo Malo',
		'Arrozal Cesarone',
		'Arrozal Rosales',
		'Asperezas',
		'Bañado De Las Pajas',
		'Bañado De Medina',
		'Barra Del Sauce',
		'Barra Del Tacuari',
		'Barrio La Vinchuca',
		'Barrio Lopez Benitez',
		'Berachi',
		'Buena Vista',
		'Calera De Recalde',
		'Campamento',
		'Cañada Brava',
		'Cañada De Santos',
		'Cañada Grande',
		'Cañada Sarandi',
		'Cañitas',
		'Casa De Las Cronicas',
		'Caserio Las Cañas',
		'Cementerio',
		'Centurion',
		'Cerro De Las Cuentas',
		'Chacras De Melo',
		'Coimbra',
		'Colonia Ceres',
		'Colonia Maria Teresa',
		'Colonia Orozco',
		'Conventos',
		'Corral De Piedra',
		'Cruz De Piedra',
		'Cuchilla Cambota',
		'Cuchilla De Melo',
		'Cuchilla Del Carmen',
		'Cuchilla Del Paraiso',
		'Cuchilla Peralta',
		'Duraznero',
		'Escuela De Agronomia',
		'Esperanza',
		'Falda De Sierra De Los Rios',
		'Fraile Muerto',
		'Ganen',
		'Garao',
		'Granja De Acegua',
		'Granja Pallero',
		'Guazunambi',
		'Hipodromo',
		'Infiernillo',
		'Isidoro Noblia',
		'La Coronilla',
		'La Gloria',
		'La Micaela',
		'La Mina',
		'La Pedrera',
		'Lago Merin',
		'Laguna Del Junco',
		'Las Limas',
		'Los Cerros',
		'Mangrullo',
		'Maria Isabel',
		'Mazangano',
		'Melo',
		'Minuano De Acegua',
		'Misterio',
		'Montecito',
		'Nando',
		'Ñangapire',
		'Panteon',
		'Paso De La Cruz',
		'Paso De Las Tropas',
		'Paso De Las Yeguas',
		'Paso De Los Carros',
		'Paso Melo',
		'Paso Pereira',
		'Peñarol',
		'Picada De Maya',
		'Picada De Salome',
		'Piedra Alta',
		'Piñeiro',
		'Placido Rosas',
		'Poblado Uruguay',
		'Presidente Doctor Getulio Vargas',
		'Puente Negro',
		'Puntas De Amarillo',
		'Puntas De La Mina',
		'Puntas De Molles',
		'Puntas De Palleros',
		'Puntas De Tacuari',
		'Puntas Del Sauce',
		'Quebracho',
		'Ramon Trigo',
		'Rincon De Contreras',
		'Rincon De La Urbana',
		'Rincon De Los Coroneles',
		'Rincon De Los Olivera',
		'Rincon De Paiva',
		'Rincon De Py',
		'Rincon De Suarez',
		'Rincon De Tacuari',
		'Rio Branco',
		'Rodriguez',
		'Saldañas',
		'San Diego',
		'San Servando',
		'Sanchez',
		'Santa Teresa',
		'Sarandi De Acegua',
		'Sarandi De Barcelo',
		'Sarandi De Yaguaron',
		'Sauce De Conventos',
		'Soto Goro',
		'Toledo',
		'Tres Boliches',
		'Tres Islas',
		'Tupambae',
		'Uruguay',
		'Villa Viñoles',
		'Wenceslao Silvera'
	),
	'UY-CO' => array(
		'Agraciada',
		'Arrivillaga',
		'Artilleros',
		'Barker',
		'Barker Norte',
		'Barrancas Coloradas',
		'Barrio Mendaña',
		'Barrio Olimpico',
		'Belgrano Norte',
		'Belgrano Sur',
		'Blanca Arena',
		'Boca Del Rosario',
		'Boca Del Rosario Oeste',
		'Bonjour',
		'Brisas Del Plata',
		'Buena Hora',
		'Campamento Artigas',
		'Campana',
		'Carmelo',
		'Caserio El Cerro',
		'Cerro Carmelo',
		'Cerro De Las Armas',
		'Cerros De San Juan',
		'Cerros Negros',
		'Chico Torino',
		'Colonia Arrue',
		'Colonia Cosmopolita',
		'Colonia Del Sacramento',
		'Colonia Española',
		'Colonia Estrella',
		'Colonia Miguelete',
		'Colonia Peirano',
		'Colonia Quevedo',
		'Colonia Sarandi',
		'Colonia Talice',
		'Colonia Valdense',
		'Conchillas',
		'Concordia',
		'Costa De Colla Al Este',
		'Costa De Rosario',
		'Costa De Tarariras',
		'Costa De Vacas',
		'Costa Del Navarro',
		'Costas De Juan Gonzalez',
		'Costas De Polonia',
		'Costas De San Juan',
		'Cufre',
		'Curupi',
		'El Bañado',
		'El Caño',
		'El Cerro',
		'El Chileno',
		'El Cuadro',
		'El Ensueño',
		'El Faro',
		'El General',
		'El Quinton',
		'El Semillero',
		'Estacion Experimental "La Estanzuela"',
		'Estancia Anchorena',
		'Florencio Sanchez',
		'Gil',
		'Juan Carlos Caseros',
		'Juan Gonzalez',
		'Juan Jackson',
		'Juan Lacaze',
		'La Estanzuela',
		'La Horqueta',
		'La Paz',
		'La Sierra',
		'Laguna De Los Patos',
		'Las Chispas',
		'Las Flores',
		'Lomas De Carmelo',
		'Los Pinos',
		'Manantiales',
		'Martin Chico',
		'Martin Chico De Conchillas',
		'Media Agua',
		'Miguelete De Conchillas',
		'Minas De Narancio',
		'Minuano Y Sauce',
		'Molles De Miguelete',
		'Nueva Helvecia',
		'Nueva Palmira',
		'Ombues De Lavalle',
		'Paraje Minuano',
		'Paso Antolin',
		'Paso Birriel',
		'Paso De La Quinta',
		'Paso Hospital',
		'Paso Hospital Manantiales',
		'Paso Morlan',
		'Paso Quicho',
		'Pastoreo',
		'Picada De Benitez',
		'Piedra Chata',
		'Piedra De Los Indios',
		'Piedras Blancas',
		'Playa Azul',
		'Playa Britopolis',
		'Playa Fomento',
		'Playa Parant',
		'Polancos',
		'Puerto Concordia',
		'Puerto Ingles',
		'Puerto Platero',
		'Puerto Rosario',
		'Punta Francesa',
		'Puntas De Juan Gonzalez',
		'Puntas De Melo',
		'Puntas De San Juan',
		'Puntas De San Pedro',
		'Puntas Del Riachuelo',
		'Puntas Del Rosario',
		'Puntas Del Sauce',
		'Quinton',
		'Radial Hernandez',
		'Radial Rosario',
		'Real De Vera',
		'Reducto',
		'Resguardo Cufre',
		'Riachuelo',
		'Rincon Del Rey',
		'Rosario',
		'Rosario Y Colla',
		'San Juan',
		'San Luis',
		'San Luis De Tarariras',
		'San Luis Sanchez',
		'San Pedro',
		'San Pedro De Arriba',
		'San Pedro Norte',
		'San Roque',
		'Santa Ana',
		'Santa Regina',
		'Santa Rosa',
		'Sarandi Campana',
		'Tarariras',
		'Terminal',
		'Tomas Bell',
		'Tres Esquinas',
		'Viboras',
		'Viboras Y Vacas',
		'Villa Pancha',
		'Zagarzazu',
		'Zunin',
		'Agraciada',
		'Arrivillaga',
		'Artilleros',
		'Barker',
		'Barker Norte',
		'Barrancas Coloradas',
		'Barrio Mendaña',
		'Barrio Olimpico',
		'Belgrano Norte',
		'Belgrano Sur',
		'Blanca Arena',
		'Boca Del Rosario',
		'Boca Del Rosario Oeste',
		'Bonjour',
		'Brisas Del Plata',
		'Buena Hora',
		'Campamento Artigas',
		'Campana',
		'Carmelo',
		'Caserio El Cerro',
		'Cerro Carmelo',
		'Cerro De Las Armas',
		'Cerros De San Juan',
		'Cerros Negros',
		'Chico Torino',
		'Colonia Arrue',
		'Colonia Cosmopolita',
		'Colonia Del Sacramento',
		'Colonia Española',
		'Colonia Estrella',
		'Colonia Miguelete',
		'Colonia Peirano',
		'Colonia Quevedo',
		'Colonia Sarandi',
		'Colonia Talice',
		'Colonia Valdense',
		'Conchillas',
		'Concordia',
		'Costa De Colla Al Este',
		'Costa De Rosario',
		'Costa De Tarariras',
		'Costa De Vacas',
		'Costa Del Navarro',
		'Costas De Juan Gonzalez',
		'Costas De Polonia',
		'Costas De San Juan',
		'Cufre',
		'Curupi',
		'El Bañado',
		'El Caño',
		'El Cerro',
		'El Chileno',
		'El Cuadro',
		'El Ensueño',
		'El Faro',
		'El General',
		'El Quinton',
		'El Semillero',
		'Estacion Experimental "La Estanzuela"',
		'Estancia Anchorena',
		'Florencio Sanchez',
		'Gil',
		'Juan Carlos Caseros',
		'Juan Gonzalez',
		'Juan Jackson',
		'Juan Lacaze',
		'La Estanzuela',
		'La Horqueta',
		'La Paz',
		'La Sierra',
		'Laguna De Los Patos',
		'Las Chispas',
		'Las Flores',
		'Lomas De Carmelo',
		'Los Pinos',
		'Manantiales',
		'Martin Chico',
		'Martin Chico De Conchillas',
		'Media Agua',
		'Miguelete De Conchillas',
		'Minas De Narancio',
		'Minuano Y Sauce',
		'Molles De Miguelete',
		'Nueva Helvecia',
		'Nueva Palmira',
		'Ombues De Lavalle',
		'Paraje Minuano',
		'Paso Antolin',
		'Paso Birriel',
		'Paso De La Quinta',
		'Paso Hospital',
		'Paso Hospital Manantiales',
		'Paso Morlan',
		'Paso Quicho',
		'Pastoreo',
		'Picada De Benitez',
		'Piedra Chata',
		'Piedra De Los Indios',
		'Piedras Blancas',
		'Playa Azul',
		'Playa Britopolis',
		'Playa Fomento',
		'Playa Parant',
		'Polancos',
		'Puerto Concordia',
		'Puerto Ingles',
		'Puerto Platero',
		'Puerto Rosario',
		'Punta Francesa',
		'Puntas De Juan Gonzalez',
		'Puntas De Melo',
		'Puntas De San Juan',
		'Puntas De San Pedro',
		'Puntas Del Riachuelo',
		'Puntas Del Rosario',
		'Puntas Del Sauce',
		'Quinton',
		'Radial Hernandez',
		'Radial Rosario',
		'Real De Vera',
		'Reducto',
		'Resguardo Cufre',
		'Riachuelo',
		'Rincon Del Rey',
		'Rosario',
		'Rosario Y Colla',
		'San Juan',
		'San Luis',
		'San Luis De Tarariras',
		'San Luis Sanchez',
		'San Pedro',
		'San Pedro De Arriba',
		'San Pedro Norte',
		'San Roque',
		'Santa Ana',
		'Santa Regina',
		'Santa Rosa',
		'Sarandi Campana',
		'Tarariras',
		'Terminal',
		'Tomas Bell',
		'Tres Esquinas',
		'Viboras',
		'Viboras Y Vacas',
		'Villa Pancha',
		'Zagarzazu',
		'Zunin'
	),
	'UY-DU' => array(
		'Abella',
		'Aguas Buenas',
		'Arroyo De Los Perros',
		'Barrancas Coloradas',
		'Barrio Duran',
		'Batovi',
		'Baygorria',
		'Blanquillo',
		'Blanquillo Al Oeste',
		'Caballero',
		'Capilla De Farruco',
		'Carlos Reyles',
		'Ceibal',
		'Cerrezuelo',
		'Cerro Convento',
		'Chacras De Durazno',
		'Chileno',
		'Chileno Chico',
		'Chileno Grande (Aguero)',
		'Costa De Cuadra',
		'Cuchilla De Ramirez',
		'Cuchilla Del Rincon',
		'De Dios',
		'Durazno',
		'Elias Regules',
		'Estacion Chileno',
		'Feliciano',
		'Fonseca',
		'Higueras De Carpinteria',
		'La Alegria',
		'La Mazamorra',
		'La Paloma',
		'Las Acacias',
		'Las Cañas',
		'Las Palmas',
		'Las Tunas',
		'Los Agregados',
		'Los Tapes',
		'Maestre Campo',
		'Malbajar Este',
		'Malbajar Oeste',
		'Maria Cejas',
		'Mariscala',
		'Mariscala Del Carmen',
		'Molles Chico',
		'Molles De Quinteros',
		'Mouriño',
		'Municipio De Durazno',
		'Ombues De Oribe',
		'Palmar De Porrua',
		'Parada Sur',
		'Parish',
		'Paso De Aguirre',
		'Paso De Castro',
		'Paso Del Medio Las Palmas',
		'Paso Ramirez',
		'Paso Real De Carpinteria',
		'Paso Tejera',
		'Pueblo Centenario',
		'Pueblo De Alvarez',
		'Puglia',
		'Puntas De Carpinteria',
		'Puntas De Herrera',
		'Puntas De Malbajar',
		'Rincon De Cuadra',
		'Rincon De Los Tapes',
		'Rolon',
		'Rossell Y Rius',
		'Salinas',
		'Salinas Chico',
		'San Jorge',
		'San Jose De Las Cañas',
		'Sandu Chico',
		'Santa Bernardina',
		'Sarandi De La China',
		'Sarandi De Rio Negro',
		'Sarandi Del Yi',
		'Sauce De Herrera',
		'Sauce Del Yi',
		'Tala De Mariscala',
		'Tejera',
		'Verdun',
		'Villa Del Carmen',
		'Villasboas'
	),
	'UY-FS' => array(
		'Ahogados',
		'Andresito',
		'Arenal Chico',
		'Arenal Grande',
		'Arroyo Malo',
		'Cañada Amilivia',
		'Cerro Colorado',
		'Chacras',
		'Chacras De Borghi',
		'Colonia Alemana',
		'Costas De San Jose',
		'Costas Del Tala',
		'Cuchilla De Villasboas',
		'El Coronilla',
		'El Totoral',
		'Ferrizo',
		'Ismael Cortinas',
		'Juan Jose Castro',
		'La Alianza',
		'La Casilla',
		'La Cordobesa',
		'La Guardia',
		'Los Puentes',
		'Marincho',
		'Paso  De Lugo',
		'Paso Hondo',
		'Pueblo Pintos',
		'Puntas De Chamanga',
		'Puntas De Marincho',
		'Puntas De San Jose',
		'Puntas De Sarandi',
		'Puntas Del Corral De Piedra',
		'Puntas Del Sauce',
		'Rincon Del Palacio',
		'San Gregorio De Flores',
		'Santa Adelaida',
		'Sarandi',
		'Talas De Maciel',
		'Trinidad',
		'Villa Pastora',
		'Villasboas'
	),
	'UY-FD' => array(
		'25 De Agosto',
		'25 De Mayo',
		'Alejandro Gallinal',
		'Arrayan',
		'Arroyo Chamizo',
		'Arroyo De Los Negros',
		'Arroyo Latorre',
		'Arroyo Monzon',
		'Arroyo Pelado',
		'Arteaga',
		'Barra Molles Del Timote',
		'Barra Sauce De Mansavillagra',
		'Berrondo',
		'Calleri',
		'Candil',
		'Capilla Del Sauce',
		'Cardal',
		'Caserio La Fundacion',
		'Casupa',
		'Cerro De La Macana',
		'Cerros De Florida',
		'Chacras De Florida',
		'Chacras Del Pintado',
		'Chamizo',
		'Chamizo Chico',
		'Chilcas',
		'Chingolas',
		'Colonia Sanchez',
		'Corral De Piedra',
		'Costa De Arias',
		'Costa De Illescas',
		'Costa De La Cruz',
		'Costa De Parana',
		'Costa Del Tala',
		'Costas De Arias',
		'Costas De Chamizo',
		'Costas De Chamizo Grande',
		'Costas De Maciel',
		'Costas De Santa Lucia Chico',
		'Costas Del Amarillo',
		'Costas Del Pintado',
		'Costas Del Santa Lucia Grande',
		'Cuchilla Santo Domingo',
		'Dr. A. Gallinal',
		'Estacion Capilla Del Sauce',
		'Ferrer',
		'Florida',
		'Fray Marcos',
		'Goñi',
		'Hernandarias',
		'Independencia',
		'Juncal',
		'La Cimbra',
		'La Cruz',
		'La Escobilla',
		'La Macana',
		'La Palma',
		'La Victoria',
		'Las Piedritas',
		'Mansavillagra',
		'Mendoza Chico',
		'Mendoza Grande',
		'Molles Del Pescado',
		'Molles Del Timote',
		'Montecoral',
		'Nico Perez',
		'Palermo',
		'Pantanoso De Castro',
		'Paso Calleros',
		'Paso De Los Novillos',
		'Paso Real De Mansavillagra',
		'Paso Vela',
		'Piedra Campana',
		'Piedras Coloradas',
		'Pintado',
		'Polanco Del Yi',
		'Pueblo De Los Morochos',
		'Puente De Mendoza',
		'Puntas De Calleros',
		'Puntas De Chamame',
		'Puntas De Chamizo',
		'Puntas De Illescas',
		'Puntas De La Escobilla',
		'Puntas De Maciel',
		'Puntas De Mansavillagra',
		'Puntas De Sarandi',
		'Puntas De Sauce De Maciel',
		'Puntas Del Arroyo Latorre',
		'Reboledo',
		'Rincon De Los Camilos',
		'Rincon De Vignoli',
		'Rincon Sauce Del Yi',
		'San Gabriel',
		'San Geronimo',
		'San Juan',
		'San Pedro De Timote',
		'Santa Clara',
		'Santa Teresa',
		'Sarandi Grande',
		'Sauce De Maciel',
		'Sauce De Villanueva',
		'Sauce Del Yi',
		'Tabare',
		'Tala De Castro',
		'Tala De Maciel',
		'Talita',
		'Tornero',
		'Urioste',
		'Vignoli',
		'Villa Hipica',
		'Villa Vieja'
	),
	'UY-LA' => array(
		'19 De Junio',
		'Abra De Zabaleta',
		'Aguas Blancas',
		'Alonso',
		'Aramendia',
		'Arequita',
		'Arroyo De Los Patos',
		'Arroyo Del Medio',
		'Azucar',
		'Barra De Los Chanchos',
		'Barrancas',
		'Barriga Negra',
		'Barrio La Coronilla - Ancap',
		'Blanes Viale',
		'Campanero',
		'Canteras Del Verdun',
		'Carnales',
		'Casupa',
		'Casupa Chico',
		'Cerro Pelado',
		'Chamame',
		'Colon',
		'Consejo Del Niño',
		'Costa Del Lenguazo',
		'Costas De Corrales',
		'Costas Del Soldado',
		'El Alto',
		'El Perdido',
		'El Soldado',
		'El Tigre',
		'Espuelitas',
		'Estacion Andreoni',
		'Estacion Ortiz',
		'Estacion Solis',
		'Gaetan (Cuchilla De Carbajal)',
		'Godoy',
		'Gutierrez',
		'Higueritas',
		'Illescas',
		'Jose Batlle Y Ordoñez',
		'Jose Pedro Varela',
		'La Cuchilla',
		'La Plata',
		'Ladrillos',
		'Larrosa',
		'Las Achiras',
		'Los Tapes',
		'Manguera Azul',
		'Marco De Los Reyes',
		'Mariscala',
		'Marmaraja',
		'Minas',
		'Molles De Aigua',
		'Molles De Cañada Grande',
		'Molles Del Sauce',
		'Ombues De Bentancor',
		'Ortiz Castro',
		'Paso Arbelo',
		'Paso De Los Troncos',
		'Paso De Mesa',
		'Piraraja',
		'Polanco',
		'Polanco Norte',
		'Polanco Sur',
		'Pororo',
		'Puente De Marmaraja',
		'Puntas De Barriga Negra',
		'Puntas De Los Chanchos',
		'Puntas De Polanco',
		'Puntas De San Francisco',
		'Puntas De Santa Lucia',
		'Puntas De Solis',
		'Puntas De Vejigas',
		'Puntas Del Perdido',
		'Retamosa',
		'Rincon De Cebollati',
		'Rincon De Mariscala',
		'Rincon De Silva',
		'Roldan',
		'San Francisco De Las Sierras',
		'Santa Lucia',
		'Sarandi De Gutierrez',
		'Sauce De Aigua',
		'Sauce De Olimar Chico',
		'Sierras Blancas',
		'Soldado',
		'Solis',
		'Solis De Mataojo',
		'Solis Grande',
		'Tapes Chico',
		'Tapes Grande',
		'Valle De Solis',
		'Vejigas',
		'Velazquez',
		'Verdun',
		'Villa Del Rosario',
		'Villa Serrana',
		'Zapican'
	),
	'UY-MA' => array(
		'Abra De Castellanos',
		'Abra De Perdomo',
		'Aigua',
		'Alfaro',
		'Alferez',
		'Arenas De Jose Ignacio',
		'Arroyito De Medina',
		'Balneario Buenos Aires',
		'Barra De Portezuelo',
		'Barra Del Sauce',
		'Barrio Hipodromo',
		'Barrio Kennedy',
		'Bella Vista',
		'Buenos Aires',
		'Canteras De Marelli',
		'Cañada Bellaca',
		'Cañada De La Cruz',
		'Carape',
		'Carlos Cal',
		'Cerro Pelado',
		'Cerros Azules',
		'Chihuahua',
		'Colonia J. Suarez',
		'Coronilla',
		'Corte De La Leña',
		'Costas De Jose Ignacio',
		'Eden Rock',
		'El Chorro',
		'El Eden',
		'El Quijote',
		'El Tesoro',
		'Faro Jose Ignacio',
		'Faro Jose Ignacio Norte',
		'Garzon',
		'Gerona',
		'Gregorio Aznarez',
		'Guardia Vieja',
		'Jose Ignacio',
		'La Barra',
		'La Capuera',
		'La Falda',
		'La Juanita',
		'La Sierra',
		'La Sonrisa',
		'Lago De Los Cisnes',
		'Laguna Blanca',
		'Laguna Del Sauce',
		'Las Cañas',
		'Las Cumbres',
		'Las Flores',
		'Las Flores - Estacion',
		'Los Aromos',
		'Los Ceibos',
		'Los Corchos',
		'Los Talas',
		'Maldonado',
		'Manantiales',
		'Mataojo',
		'Molles De Garzon',
		'Nueva Carrara',
		'Ocean Park',
		'Pago De La Paja',
		'Pan De Azucar',
		'Parque Medina',
		'Partido Norte',
		'Partido Oeste',
		'Paso De La Cantera',
		'Paso De Los Talas',
		'Pinares - Las Delicias',
		'Piriapolis',
		'Playa Grande',
		'Playa Hermosa',
		'Playa Verde',
		'Portezuelo',
		'Pueblo Solis',
		'Punta Ballena',
		'Punta Colorada',
		'Punta Del Este',
		'Punta Negra',
		'Puntas De Jose Ignacio',
		'Puntas De La Sierra',
		'Puntas De Mataojo',
		'Puntas De Pan De Azucar',
		'Puntas Del Campanera',
		'Rincon De Aparicio',
		'Rincon De Los Sosa',
		'Rincon Del Indio',
		'Ruta 37 Y 9',
		'Salamanca',
		'San Carlos',
		'San Francisco',
		'San Juan Del Este',
		'San Rafael - El Placer',
		'San Vicente',
		'Santa Monica',
		'Sarandi De Aigua',
		'Sarandi Del Mataojo',
		'Sauce De Aigua',
		'Sauce De Portezuelo',
		'Solis',
		'Valdivia',
		'Villa Delia',
		'Zanja Del Tigre'
	),
	'UY-MO' => array(
		'Aguada',
		'Aires Puros',
		'Atahualpa',
		'Bañados De Carrasco',
		'Barrio Sur',
		'Belvedere',
		'Brazo Oriental',
		'Buceo',
		'Capurro Bella Vista',
		'Carrasco',
		'Carrasco Norte',
		'Casabo Pajas Blancas',
		'Casavalle',
		'Castro Castellanos',
		'Centro',
		'Cerrito',
		'Cerro',
		'Ciudad Vieja',
		'Colon Centro Y Noroeste',
		'Colon Sureste Abayuba',
		'Conciliacion',
		'Cordon',
		'Figurita',
		'Flor De Maroñas',
		'Ituzaingo',
		'Jacinto Vera',
		'Jardines Del Hipodromo',
		'La Blanqueada',
		'La Comercial',
		'La Paloma Tomkinson',
		'La Teja',
		'Larrañaga',
		'Las Acacias',
		'Las Canteras',
		'Lezica Melilla',
		'Malvin',
		'Malvin Norte',
		'Manga',
		'Manga Toledo Chico',
		'Maroñas Parque Guarani',
		'Mercado Modelo Y Bolivar',
		'Nuevo Paris',
		'Palermo',
		'Parque Rodo',
		'Paso De La Arena',
		'Paso De Las Duranas',
		'Peñarol Lavalleja',
		'Piedras Blancas',
		'Pocitos',
		'Pque Batlle Villa Dolores',
		'Prado Nueva Savona',
		'Puerto',
		'Punta Carretas',
		'Punta Gorda',
		'Punta Rieles Bella Italia',
		'Reducto',
		'Sayago',
		'Toledo Chico',
		'Tres Cruces',
		'Tres Ombues Pblo Victoria',
		'Union',
		'Villa Española',
		'Villa Garcia Manga Rural',
		'Villa Muñoz Retiro'
	),
	'UY-PA' => array(
		'Al Sur De Arroyo Sacra',
		'Araujo',
		'Arbolito (Totoral)',
		'Arroyo Malo',
		'Arroyo Negro',
		'Beisso',
		'Bella Vista',
		'Cangue',
		'Cañada Del Pueblo',
		'Carumbe',
		'Casa Blanca',
		'Cerro Chato',
		'Chacras De Paysandu',
		'Chacras De Paysandu Norte',
		'Chacras De Paysandu Sur',
		'Chapicuy',
		'Colonia Arroyo Malo',
		'Colonia Cangue',
		'Colonia Juncal',
		'Colonia Las Delicias',
		'Colonia Paysandu',
		'Colonia Santa Blanca',
		'Colonia Uruguaya',
		'Constancia',
		'Costa De Sacra',
		'Cuchilla De Buricayupi',
		'Cuchilla De Fuego',
		'Cuchilla San Jose',
		'El Chaco',
		'El Duraznal',
		'El Eucaliptus',
		'El Horno',
		'El Tarugo',
		'Estacion Porvenir',
		'Etchemendi',
		'Gallinal',
		'Guaviyu De Quebracho',
		'Guayabos',
		'Guichon',
		'La Lata Ruta 3 (Km. 375)',
		'La Paz (Ruta 3 Km. 346)',
		'La Tentacion',
		'Las Flores',
		'Las Palmas',
		'Lorenzo Geyres',
		'Molles Grande',
		'Morato (Tres Arboles)',
		'Nuevo Paysandu',
		'Orgoroso',
		'Palmar Del Quebracho',
		'Parada Dayman',
		'Parada Pandule',
		'Parada Rivas',
		'Paso De Los Carros',
		'Paysandu',
		'Perico Moreno',
		'Piedra Sola',
		'Piedras Coloradas',
		'Piñera',
		'Porvenir',
		'Pueblo Alonzo',
		'Pueblo Esperanza',
		'Pueblo Federacion',
		'Puntas De Arroyo Negro',
		'Puntas De Bacacua',
		'Puntas De Buricayupi',
		'Puntas De Cangue',
		'Puntas De Gualeguay',
		'Puntas De Las Isletas',
		'Quebracho',
		'Queguay Grande',
		'Queguayar',
		'Rabon',
		'San Felix',
		'San Francisco',
		'San Mauricio',
		'San Miguel',
		'Santa Kilda',
		'Sauce De Abajo',
		'Sauce Del Buricayupi',
		'Sauce Del Queguay',
		'Soto',
		'Tambores',
		'Termas De Almiron',
		'Termas De Guaviyu',
		'Tomas Paz',
		'Tres Bocas',
		'Valdez',
		'Villa Maria (Tiatucura)',
		'Zeballos'
	),
	'UY-RN' => array(
		'Algorta',
		'Arroyo Negro',
		'Barrio Anglo',
		'Bellaco',
		'Cañitas',
		'Caracoles',
		'Colonia El Ombu',
		'Colonia John F. Kennedy',
		'Don Esteban',
		'El Abrojal',
		'El Progreso',
		'El Surco',
		'Estacion Francia',
		'Estancia Vichadero',
		'Fray Bentos',
		'Isla De Arguelles',
		'La Arena',
		'La Coronilla',
		'La Florida',
		'La Palma',
		'La Union',
		'Las Cañas',
		'Las Flores',
		'Las Fracciones',
		'Las Margaritas',
		'Los Arrayanes',
		'Los Mellizos',
		'Los Ranchos',
		'Mataojo',
		'Menafra',
		'Merinos',
		'Molles De Porrua',
		'Nuevo Berlin',
		'Ombucitos',
		'Palmar Grande',
		'Paso De Balbuena',
		'Paso De Leopoldo',
		'Paso De Los Cobres',
		'Paso De Soca',
		'Paso Ramirez',
		'Pauru',
		'Porton Haedo',
		'Pte. San Martin',
		'Pueblo Grecco',
		'Puntas De Averias',
		'Rolon',
		'San Javier',
		'San Lorenzo',
		'Sanchez',
		'Sanchez Chico',
		'Santa Elisa',
		'Santa Isabel',
		'Santa Rosa',
		'Sarandi',
		'Sarandi De Navarro',
		'Sauce',
		'Tres Bocas',
		'Tres Quintas',
		'Uleste',
		'Valle De Soba',
		'Villa General Borges',
		'Villa Maria',
		'Yaguarete',
		'Young'
	),
	'UY-RV' => array(
		'Abrojal',
		'Alborada',
		'Amarillo',
		'Arroyo Blanco',
		'Arroyo Sauzal',
		'Ataques',
		'Bañado Del Chaja',
		'Barra De Ataques',
		'Barrio Recreo',
		'Batovi',
		'Berruti',
		'Blanquillos',
		'Buena Orden Al Norte',
		'Buena Union',
		'Capon Alto',
		'Caraguata',
		'Carpinteria',
		'Cerrillada',
		'Cerro Alegre',
		'Cerro Blanco De Cuñapiru',
		'Cerro Caqueiro',
		'Cerro Chapeu',
		'Cerro Chato',
		'Cerro Pelado',
		'Cerro Pelado Al Este',
		'Cerro Solito',
		'Cerros Blancos',
		'Cerros De La Calera',
		'Chirca De Caraguata',
		'Coronilla',
		'Coronilla De Corrales',
		'Costas De Cuñapiru',
		'Cruz De San Pedro',
		'Cuchilla De Tres Cerros',
		'Cuchilla De Yaguari',
		'Cuchilla Mangueras',
		'Cuñapiru',
		'Curticeiras',
		'Curtume',
		'El Ceibo',
		'El Palmito',
		'Guaviyu',
		'Hospital',
		'La Caillava',
		'La Calera',
		'La Cerrillada',
		'La Chilca',
		'La Palma',
		'La Pedrera',
		'Lagos Del Norte',
		'Lagunon',
		'Las Flores',
		'Laureles',
		'Los Potreros',
		'Lunarejo',
		'Mandubi',
		'Manuel Diaz',
		'Masoller',
		'Minas De Corrales',
		'Minas De Cuñapiru (Usinas)',
		'Minas De Zapucay',
		'Moirones',
		'Parada Medina',
		'Paso Amarillo',
		'Paso Ataques',
		'Paso Casildo',
		'Paso De Arriera',
		'Paso De Ataques',
		'Paso De Frontera',
		'Paso De Gaire',
		'Paso De La Arena',
		'Paso De La Calera',
		'Paso Del Lagunon',
		'Paso Del Puerto',
		'Paso Del Tapado',
		'Paso Lapuente',
		'Paso Serpa',
		'Piedras Blancas',
		'Platon',
		'Pueblo De Los Santos',
		'Pueblo Socorro',
		'Puntas De Abrojal',
		'Puntas De Corrales',
		'Puntas De Cuñapiru',
		'Puntas Del Sauzal',
		'Puntas Del Yaguari',
		'Rincon De Amarillo',
		'Rincon De Diniz',
		'Rincon De Los Castillos',
		'Rincon De Moraes',
		'Rincon De Rodriguez',
		'Rincon De Roland',
		'Rincon De Tres Cerros',
		'Rincon De Yaguari',
		'Rivera',
		'San Gregorio',
		'Santa Ernestina',
		'Santa Isabel',
		'Santa Teresa',
		'Sauce De Batovi',
		'Sauzal',
		'Segarra',
		'Tranqueras',
		'Tres Cerros',
		'Tres Cruces',
		'Tres Puentes',
		'Vichadero',
		'Villa Indart',
		'Yaguari',
		'Zanja Honda',
		'Zanja Honda De Tranqueras'
	),
	'UY-RO' => array(
		'18 De Julio',
		'19 De Abril',
		'Abra De Alferez',
		'Aguas Dulces',
		'Alferez',
		'Antoniopolis',
		'Arachania',
		'Arbolito',
		'Balneario Pueblo Nuevo',
		'Barra De Valizas',
		'Barra Del Chuy',
		'Barra Isla Negra',
		'Barrancas De La Coronilla',
		'Barrio Cardozo',
		'Barrio Carpacho',
		'Barrio Pereira',
		'Barrio Porvenir',
		'Barrio Torres',
		'Cabo Polonio',
		'Capacho',
		'Castillos',
		'Cebollati',
		'Cerro De Los Rocha',
		'Cerro De Pescadores',
		'Chuy',
		'Colonia Greissing',
		'Costa Azul',
		'Costas De Cebollati',
		'Cuchilla De Garzon',
		'Cuchilla Del Arbolito',
		'El Canelon',
		'El Chimango',
		'Empalme De Velazquez',
		'Fortin De San Miguel',
		'Garzon Abajo',
		'Garzon Al Medio',
		'Garzon Arriba',
		'India Muerta',
		'Isla Negra',
		'Kilometro 18',
		'La Aguada',
		'La Aguada Y Costa Azul',
		'La Centinela',
		'La Coronilla',
		'La Esmeralda',
		'La Fortaleza De Santa Teresa',
		'La Pedrera',
		'La Ribiera',
		'La Sierra',
		'La Tuna',
		'Lascano',
		'Lomas',
		'Los Ajos',
		'Los Cerrillos',
		'Los Indios',
		'Oceania Del Polonio',
		'Oratorio',
		'Palmar',
		'Palmar De Castillos',
		'Palmares De La Coronilla',
		'Paralle',
		'Paso De Lopez',
		'Paso Del Bañado',
		'Paso Del Ombu',
		'Paso Doña Rosa',
		'Picada Tolosa',
		'Plano 291',
		'Pueblo Nuevo',
		'Puente Valizas',
		'Puerto De Los Botes',
		'Puerto La Paloma',
		'Puimayen',
		'Punta Cebollati',
		'Punta Del Diablo',
		'Punta Palmar',
		'Punta Rubia',
		'Puntas De Don Carlos',
		'Quebracho',
		'Rincon De Los Olivera',
		'Rincon De Valizas',
		'Rocha',
		'Samuel',
		'San Antonio',
		'San Luis Al Medio',
		'San Sebastian',
		'San Sebastian De La Pedrera',
		'Sarandi De La India Muerta',
		'Sauce De Rocha',
		'Sierra De Los Rocha',
		'Tajamares De La Pedrera',
		'Velazquez',
		'Vuelta Del Palmar'
	),
	'UY-SA' => array(
		'Arenitas Blancas',
		'Balneario Albisu',
		'Belen',
		'Biassini',
		'Bordenave',
		'Campo De Todos',
		'Carumbe',
		'Celeste',
		'Cerrillada',
		'Cerrilladas De Saucedo',
		'Cerro Chato',
		'Cerros De Vera',
		'Chacras De Belen',
		'Chacras De Constitucion',
		'Colonia 18 De Julio',
		'Colonia Itapebi',
		'Colonia Lavalleja',
		'Colonia Osimani',
		'Colonia Rubio',
		'Constitucion',
		'Corral De Piedra',
		'Corralito',
		'Cuchilla De Guaviyu',
		'Cuchilla Del Salto',
		'El Espinillar',
		'El Mellado',
		'Ferreira',
		'Garibaldi',
		'Guaviyu De Arapey',
		'Itapebi',
		'La Bolsa',
		'La Bolsa 02',
		'La Bolsa 03',
		'La Caballada',
		'La Viticola',
		'Las Flores',
		'Laureles',
		'Lluveras',
		'Los Orientales',
		'Mataojito',
		'Mataojo Grande',
		'Nueva Hesperides',
		'Olivera',
		'Osimani Y Llerena',
		'Palomas',
		'Parada Herreria',
		'Parque Jose Luis',
		'Paso  Valega',
		'Paso Cementerio',
		'Paso De Las Piedras De Arerungua',
		'Paso Del Parque Del Dayman',
		'Paso Del Potrero',
		'Paso Del Tapado',
		'Paso Fialho',
		'Paso Nuevo Del Arapey',
		'Pepe Nuñez',
		'Pueblo Cayetano',
		'Pueblo Farias',
		'Pueblo Fernandez',
		'Pueblo Quintana',
		'Pueblo Ramos',
		'Puntas De Valentin',
		'Rincon De Valentin',
		'Russo',
		'Salto',
		'San Antonio',
		'Sarandi De Arapey',
		'Sauce Chico',
		'Saucedo',
		'Sopas',
		'Talas De Itapebi',
		'Termas Del Arapey',
		'Termas Del Dayman',
		'Toro Negro',
		'Tropezon',
		'Tropiezo',
		'Valentin Grande',
		'Yacuy',
		'Zanja De Alcain',
		'Zanja Del Tigre'
	),
	'UY-SJ' => array(
		'18 De Julio',
		'Arroyo De La Virgen',
		'Arroyo Llano',
		'Autodromo Nacional',
		'Bañado',
		'Bella Vista',
		'Boca Del Cufre',
		'Cagancha',
		'Cagancha Chico',
		'Cañada Grande',
		'Capurro',
		'Carreta Quemada',
		'Ceramicas Del Sur',
		'Chamizo',
		'Ciudad Del Plata',
		'Cololo Tinosa',
		'Colonia America',
		'Colonia Delta',
		'Colonia Dr. Bernardo Etchepare',
		'Colonia Fernandez Crespo',
		'Colonia Italia',
		'Colonia Juan Maria Perez',
		'Colonia San Joaquin',
		'Colonia Wilson',
		'Coronilla',
		'Costa Del Mauricio',
		'Costas De Pereira',
		'Costas Del Sauce',
		'Cruz De Los Caminos',
		'Cuchilla De Pereira',
		'Cuchilla Del Vichadero',
		'Cuchilla Seca',
		'Delta El Tigre',
		'Ecilda Paullier',
		'Escudero',
		'Estacion Rodriguez',
		'Fajardo',
		'Fajina',
		'Gonzalez',
		'Guaycuru',
		'Ituzaingo',
		'Jesus Maria',
		'Juan Soler',
		'Juncal',
		'Kiyu - Ordeig',
		'La Boyada',
		'La Casilla',
		'La Cuchilla',
		'Laurel',
		'Libertad',
		'Mahoma',
		'Mal Abrigo',
		'Mangrullo',
		'Monte Grande',
		'Mundo Azul',
		'Mundo Azul Aguirre',
		'Orillas Del Plata',
		'Pachina',
		'Panta',
		'Pantanoso',
		'Parque Postel',
		'Parque Postel Cnel. Adrian Medina',
		'Paso Belastiqui',
		'Paso De Cames',
		'Paso De Las Piedras',
		'Paso De Mas',
		'Paso Del Carreton',
		'Paso Del Guaycuru',
		'Paso Del Rey',
		'Pavon',
		'Penino',
		'Perico Perez',
		'Picada Gambetta',
		'Playa Pascual',
		'Puntas De Cagancha',
		'Puntas De Cañada Grande',
		'Puntas De Chamizo',
		'Puntas De Gregorio',
		'Puntas De Laurel',
		'Puntas De Laurel',
		'Puntas De Tropa Vieja',
		'Puntas De Valdez',
		'Radial Ruta 3',
		'Rafael Perazza',
		'Raigon',
		'Rincon De Albano',
		'Rincon De Arazati',
		'Rincon De Arias',
		'Rincon De Buschental',
		'Rincon De Cufre',
		'Rincon De La Bolsa',
		'Rincon De La Torre',
		'Rincon De Nazareth',
		'Rincon Del Pino',
		'Rocho',
		'Safici',
		'San Fernando',
		'San Fernando Chico',
		'San Gregorio',
		'San Jose De Mayo',
		'Santa Monica',
		'Sauce',
		'Sauce Chico',
		'Scavino',
		'Tabarez',
		'Tala De Pereira',
		'Tranquera Colorada',
		'Tropas Viejas',
		'Tropezon',
		'Valdez Chico',
		'Villa Maria',
		'Villa Olimpica',
		'Villa Rives',
		'Zanja Honda'
	),
	'UY-SO' => array(
		'Agraciada',
		'Altos Del Perdido',
		'Arenal Chico',
		'Arroyo Del Medio',
		'Arroyo Grande',
		'Asencio',
		'Azotea De Vera',
		'Bajos Del Perdido',
		'Bequelo',
		'Bizcocho',
		'Buena Vista',
		'Cañada Magallanes',
		'Cañada Nieto',
		'Cañada Paraguaya',
		'Cardona',
		'Castillos',
		'Cerro Alegre',
		'Cerro Vera',
		'Chacras De Dolores',
		'Chacras De Mercedes',
		'Cololo',
		'Colonia Concordia',
		'Colonia Diaz',
		'Colonia Larrañaga',
		'Colonia Santa Clara',
		'Colonia Uruguaya',
		'Coquimbo',
		'Corralito',
		'Costa Del Aguila',
		'Costas Del Perdido',
		'Cuatro Bocas De Buena Vista',
		'Cuchilla Del Corralito',
		'Cuchilla Del Perdido',
		'Cueva Del Tigre',
		'Dolores',
		'Duraznito',
		'Egaña',
		'El Aguila',
		'El Tala',
		'Espinillo',
		'Garula',
		'Grito De Asencio',
		'Jose Enrique Rodo',
		'La Concordia',
		'La Laguna',
		'La Loma',
		'La Palma',
		'La Tabla',
		'Lares',
		'Las Maulas',
		'Lata Del Perdido',
		'Maciel',
		'Mercedes',
		'Monzon',
		'Olivera',
		'Palmar',
		'Palmitas',
		'Palo Solo',
		'Parada Suarez',
		'Paso De La Arena',
		'Paso De Ramos',
		'Pedro Chico',
		'Perseverano',
		'Progreso',
		'Puntas De Arenales',
		'Puntas De Durazno',
		'Puntas De San Salvador',
		'Puntas Del Tala',
		'Rincon De Cañada Nieto',
		'Rincon De Cololo',
		'Rincon De Ruiz',
		'Risso',
		'San Dios',
		'San Martin',
		'Santa Blanca',
		'Santa Catalina',
		'Sarandi Chico',
		'Unidad Cooperaria No 1',
		'Villa Alejandrina',
		'Villa Darwin',
		'Villa Soriano',
		'Zanja Honda'
	),
	'UY-TA' => array(
		'Achar',
		'Arroyo Del Medio',
		'Ataque',
		'Balneario Ipora',
		'Bañado De Cañas',
		'Bañado De Rocha',
		'Barrio La Matutina',
		'Barrio Libertad',
		'Barrio Lopez',
		'Barrio Santangelo',
		'Barrio Torres',
		'Blanquillos',
		'Cañada Del Estado',
		'Cañas',
		'Caraguata Al Norte',
		'Cardoso',
		'Cardozo Chico',
		'Carpinteria',
		'Cerro Batovi',
		'Cerro Chato',
		'Cerro De Pastoreo',
		'Cerro De Pereira',
		'Cerro Del Arbolito',
		'Cerros De Clara',
		'Chamberlain',
		'Charata',
		'Churchill',
		'Cinco Sauces',
		'Clara',
		'Clavijo',
		'Colman',
		'Costas De Caraguata',
		'Costas De Tres Cruces',
		'Coyo Martinez',
		'Cruz De Los Caminos',
		'Cuchilla De La Casa De Piedra',
		'Cuchilla De La Palma',
		'Cuchilla De Laureles',
		'Cuchilla De Peralta',
		'Cuchilla Del Ombu',
		'Curtina',
		'El Empalme',
		'Estacion Menendez',
		'Frigorifico Modelo',
		'Heriberto',
		'La Aldea',
		'La Bolsa 01',
		'La Bolsa 02',
		'La Hilera',
		'La Palma',
		'La Pedrera',
		'Lambare',
		'Larrayos',
		'Las Arenas',
		'Las Chircas',
		'Las Pajas',
		'Las Toscas De Caraguata',
		'Laura',
		'Laureles',
		'Los Cerros',
		'Los Coitinhos',
		'Los Cuadrados',
		'Los Feos',
		'Los Furtados',
		'Los Garcia',
		'Los Gomez',
		'Los Laureles',
		'Los Malavares',
		'Los Ortices',
		'Los Rodriguez',
		'Los Rosanos',
		'Los Rosas',
		'Los Semper',
		'Los Vazquez',
		'Martinote',
		'Minuano',
		'Montevideo Chico',
		'Once Cerros',
		'Pampa',
		'Paso Bonilla',
		'Paso De Ceferino',
		'Paso De Las Carretas',
		'Paso De Las Flores',
		'Paso De Las Toscas',
		'Paso De Los Novillos',
		'Paso De Los Toros',
		'Paso De Perez',
		'Paso Del Cerro',
		'Paso Del Medio',
		'Paso Hondo',
		'Paso Livindo',
		'Paso Victor',
		'Picada De Cuello',
		'Pueblo Clavijo',
		'Pueblo De Arriba',
		'Pueblo Del Barro',
		'Punta De Carretera',
		'Puntas De Cinco Sauces',
		'Puntas De Laureles',
		'Rincon De Freitas',
		'Rincon De Giloca',
		'Rincon De La Aldea',
		'Rincon De La Bolsa',
		'Rincon De La Laguna',
		'Rincon De Los Machado',
		'Rincon De Pereira',
		'Rincon De Zamora',
		'Rincon Del Bonete',
		'Rivera Chico',
		'San Benito',
		'San Gregorio De Polanco',
		'San Joaquin',
		'Sauce De Batovi',
		'Sauce De Tranqueras',
		'Sauce Solo',
		'Sauce Solo Del Rio Negro',
		'Tacuarembo',
		'Tacuarembo Chico',
		'Tierras Coloradas',
		'Tres Guitarras',
		'Turupi',
		'Valle Eden',
		'Villa Ansina',
		'Zambullon',
		'Zapara',
		'Zapucay'
	),
	'UY-TT' => array(
		'Acosta',
		'Arrayanes De Cebollati',
		'Arrayanes De Corral De Cebollati',
		'Arrocera Bonomo',
		'Arrocera El Tigre',
		'Arrocera La Catumbera',
		'Arrocera La Querencia',
		'Arrocera Las Palmas',
		'Arrocera Los Ceibos',
		'Arrocera Los Teros',
		'Arrocera Mini',
		'Arrocera Procipa',
		'Arrocera Rincon',
		'Arrocera San Fernando',
		'Arrocera Santa Fe',
		'Arrocera Zapata',
		'Arrozal Treinta Y Tres',
		'Avestruz Chico',
		'Bañado De Oro',
		'Barrio Abreu',
		'Cañada Chica',
		'Cañada De Las Piedras',
		'Cañada Del Sauce',
		'Cerro Chato',
		'Cerro Pelado',
		'Cerros De Amaro',
		'Cipa Cebollati',
		'Cipa Olimar',
		'Cipa Secador',
		'Corrales De Cebollati',
		'Costas De Tacuari',
		'Costas Del Arroyo Malo',
		'Costas Del Sarandi',
		'Cuchilla De Dionisio',
		'Cuchilla De Olmos',
		'Ejido De Treinta Y Tres',
		'El Bellaco',
		'El Carmen',
		'El Catete',
		'Gral. Enrique Martinez',
		'Higuerones',
		'Julio Maria Sanz',
		'La Calavera',
		'La Calera',
		'La Lata',
		'Las Chacras',
		'Las Pavas',
		'Lechiguana De Corrales',
		'Los Ceibos',
		'Maria Albina',
		'Maria Isabel',
		'Mate Dulce',
		'Mendizabal',
		'Molles De Olimar',
		'Noques De Olimar Chico',
		'Olimar Grande',
		'Palo A Pique',
		'Panteon',
		'Paso Ancho',
		'Paso De Averias',
		'Paso De La Atahona',
		'Paso De La Laguna',
		'Paso De Piriz',
		'Paso Del Sauce',
		'Poblado Alonzo',
		'Puntas De Leoncho',
		'Puntas De Los Ceibos',
		'Puntas De Quebracho',
		'Puntas Del Oro',
		'Puntas Del Parao',
		'Rincon',
		'Rincon De Gadea',
		'Rincon De Iguini',
		'Rincon De Los Francos',
		'Rincon De Quintana',
		'Rincon De Urtubey',
		'Santa Clara De Olimar',
		'Sauce De Corrales',
		'Sierra Del Yerbal',
		'Siete Casas',
		'Treinta Y Tres',
		'Valentines',
		'Verde Alto',
		'Vergara',
		'Villa Passano',
		'Villa Sara',
		'Yerbal Chico',
		'Yerbalito'
	),
);

// Use this filter to handle the Cities of Uruguay
$places['UY'] = apply_filters('scpwoo_custom_places_uy', $places['UY']);
