<?php

/**
 * Districts of Vietnam
 * - 705 disctrics
 *
 * Sources:
 * - https://en.wikipedia.org/wiki/Subdivisions_of_Vietnam
 *
 * @author  Nguyen Le <nguyen@bluecoral.vn> | http://bluecoral.vn
 * @version 1.1
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 */

global $places;

$places['VN'] = array(

	'03-89' => array(		
		'Thành phố Long Xuyên',
		'Thành phố Châu Đốc',
		'Huyện An Phú',
		'Thị xã Tân Châu',
		'Huyện Phú Tân',
		'Huyện Châu Phú',
		'Huyện Tịnh Biên',
		'Huyện Tri Tôn',
		'Huyện Châu Thành',
		'Huyện Chợ Mới',
		'Huyện Thoại Sơn',
	),
	'04-77' => array(
		'Thành phố Vũng Tàu',
		'Thành phố Bà Rịa',
		'Huyện Châu Đức',
		'Huyện Xuyên Mộc',
		'Huyện Long Điền',
		'Huyện Đất Đỏ',
		'Thị xã Phú Mỹ',
		'Huyện Côn Đảo',
	),
	'05-24' => array(
		'Thành phố Bắc Giang',
		'Huyện Yên Thế',
		'Huyện Tân Yên',
		'Huyện Lạng Giang',
		'Huyện Lục Nam',
		'Huyện Lục Ngạn',
		'Huyện Sơn Động',
		'Huyện Yên Dũng',
		'Huyện Việt Yên',
		'Huyện Hiệp Hòa',
	),
	'06-06' => array(
		'Thành Phố Bắc Kạn',
		'Huyện Pác Nặm',
		'Huyện Ba Bể',
		'Huyện Ngân Sơn',
		'Huyện Bạch Thông',
		'Huyện Chợ Đồn',
		'Huyện Chợ Mới',
		'Huyện Na Rì',
	),
	'07-95' => array(
		'Thành phố Bạc Liêu',
		'Huyện Hồng Dân',
		'Huyện Phước Long',
		'Huyện Vĩnh Lợi',
		'Thị xã Giá Rai',
		'Huyện Đông Hải',
		'Huyện Hoà Bình',
	),
	'08-27' => array(
		'Thành phố Bắc Ninh',
		'Huyện Yên Phong',
		'Huyện Quế Võ',
		'Huyện Tiên Du',
		'Thị xã Từ Sơn',
		'Huyện Thuận Thành',
		'Huyện Gia Bình',
		'Huyện Lương Tài',
	),
	'09-83' => array(
		'Thành phố Bến Tre',
		'Huyện Châu Thành',
		'Huyện Chợ Lách',
		'Huyện Mỏ Cày Nam',
		'Huyện Giồng Trôm',
		'Huyện Bình Đại',
		'Huyện Ba Tri',
		'Huyện Thạnh Phú',
		'Huyện Mỏ Cày Bắc',
	),
	'10-52' => array(
		'Thành phố Quy Nhơn',
		'Huyện An Lão',
		'Thị xã Hoài Nhơn',
		'Huyện Hoài Ân',
		'Huyện Phù Mỹ',
		'Huyện Vĩnh Thạnh',
		'Huyện Tây Sơn',
		'Huyện Phù Cát',
		'Thị xã An Nhơn',
		'Huyện Tuy Phước',
		'Huyện Vân Canh',
	),
	'11-74' => array(
		'Thành phố Thủ Dầu Một',
		'Huyện Bàu Bàng',
		'Huyện Dầu Tiếng',
		'Thị xã Bến Cát',
		'Huyện Phú Giáo',
		'Thị xã Tân Uyên',
		'Thành phố Dĩ An',
		'Thành phố Thuận An',
		'Huyện Bắc Tân Uyên',
	),
	'12-74' => array(
		'Thị xã Phước Long',
		'Thành phố Đồng Xoài',
		'Thị xã Bình Long',
		'Huyện Bù Gia Mập',
		'Huyện Lộc Ninh',
		'Huyện Bù Đốp',
		'Huyện Hớn Quản',
		'Huyện Đồng Phú',
		'Huyện Bù Đăng',
		'Huyện Chơn Thành',
		'Huyện Phú Riềng',
	),
	'13-60' => array(
		'Thành phố Phan Thiết',
		'Thị xã La Gi',
		'Huyện Tuy Phong',
		'Huyện Bắc Bình',
		'Huyện Hàm Thuận Bắc',
		'Huyện Hàm Thuận Nam',
		'Huyện Tánh Linh',
		'Huyện Đức Linh',
		'Huyện Hàm Tân',
		'Huyện Phú Quí',
	),
	'14-96' => array(
		'Thành phố Cà Mau',
		'Huyện U Minh',
		'Huyện Thới Bình',
		'Huyện Trần Văn Thời',
		'Huyện Cái Nước',
		'Huyện Đầm Dơi',
		'Huyện Năm Căn',
		'Huyện Phú Tân',
		'Huyện Ngọc Hiển',
	),
	'1-592' => array(
		'Quận Ninh Kiều',
		'Quận Ô Môn',
		'Quận Bình Thuỷ',
		'Quận Cái Răng',
		'Quận Thốt Nốt',
		'Huyện Vĩnh Thạnh',
		'Huyện Cờ Đỏ',
		'Huyện Phong Điền',
		'Huyện Thới Lai',
	),
	'16-04' => array(
		'Thành phố Cao Bằng',
		'Huyện Bảo Lâm',
		'Huyện Bảo Lạc',
		'Huyện Hà Quảng',
		'Huyện Trùng Khánh',
		'Huyện Hạ Lang',
		'Huyện Quảng Hòa',
		'Huyện Hoà An',
		'Huyện Nguyên Bình',
		'Huyện Thạch An',
	),
	'17-48' => array(
		'Quận Liên Chiểu',
		'Quận Thanh Khê',
		'Quận Hải Châu',
		'Quận Sơn Trà',
		'Quận Ngũ Hành Sơn',
		'Quận Cẩm Lệ',
		'Huyện Hòa Vang',
		'Huyện Hoàng Sa',
	),
	'18-66' => array(
		'Thành phố Buôn Ma Thuột',
		'Thị xã Buôn Hồ',
		"Huyện Ea H'leo",
		'Huyện Ea Súp',
		'Huyện Buôn Đôn',
		"Huyện Cư M'gar",
		'Huyện Krông Búk',
		'Huyện Krông Năng',
		'Huyện Ea Kar',
		"Huyện M'Đrắk",
		'Huyện Krông Bông',
		'Huyện Krông Pắc',
		'Huyện Krông A Na',
		'Huyện Lắk',
		'Huyện Cư Kuin',
	),
	'19-67' => array(
		'Thành phố Gia Nghĩa',
		'Huyện Đăk Glong',
		'Huyện Cư Jút',
		'Huyện Đắk Mil',
		'Huyện Krông Nô',
		'Huyện Đắk Song',
		"Huyện Đắk R'Lấp",
		'Huyện Tuy Đức',
	),
	'20-11' => array(
		'Thành phố Điện Biên Phủ',
		'Thị xã Mường Lay',
		'Huyện Mường Nhé',
		'Huyện Mường Chà',
		'Huyện Tủa Chùa',
		'Huyện Tuần Giáo',
		'Huyện Điện Biên',
		'Huyện Điện Biên Đông',
		'Huyện Mường Ảng',
		'Huyện Nậm Pồ',
	),
	'21-75' => array(
		'Thành phố Biên Hòa',
		'Thành phố Long Khánh',
		'Huyện Tân Phú',
		'Huyện Vĩnh Cửu',
		'Huyện Định Quán',
		'Huyện Trảng Bom',
		'Huyện Thống Nhất',
		'Huyện Cẩm Mỹ',
		'Huyện Long Thành',
		'Huyện Xuân Lộc',
		'Huyện Nhơn Trạch',
	),
	'22-87' => array(
		'Thành phố Cao Lãnh',
		'Thành phố Sa Đéc',
		'Thành phố Hồng Ngự',
		'Huyện Tân Hồng',
		'Huyện Hồng Ngự',
		'Huyện Tam Nông',
		'Huyện Tháp Mười',
		'Huyện Cao Lãnh',
		'Huyện Thanh Bình',
		'Huyện Lấp Vò',
		'Huyện Lai Vung',
		'Huyện Châu Thành',
	),
	'23-64' => array(
		'Thành phố Pleiku',
		'Thị xã An Khê',
		'Thị xã Ayun Pa',
		'Huyện KBang',
		'Huyện Đăk Đoa',
		'Huyện Chư Păh',
		'Huyện Ia Grai',
		'Huyện Mang Yang',
		'Huyện Kông Chro',
		'Huyện Đức Cơ',
		'Huyện Chư Prông',
		'Huyện Chư Sê',
		'Huyện Đăk Pơ',
		'Huyện Ia Pa',
		'Huyện Krông Pa',
		'Huyện Phú Thiện',
		'Huyện Chư Pưh',
	),
	'24-02' => array(
		'Thành phố Hà Giang',
		'Huyện Đồng Văn',
		'Huyện Mèo Vạc',
		'Huyện Yên Minh',
		'Huyện Quản Bạ',
		'Huyện Vị Xuyên',
		'Huyện Bắc Mê',
		'Huyện Hoàng Su Phì',
		'Huyện Xín Mần',
		'Huyện Bắc Quang',
		'Huyện Quang Bình',
	),
	'25-35' => array(
		'Thành phố Phủ Lý',
		'Thị xã Duy Tiên',
		'Huyện Kim Bảng',
		'Huyện Thanh Liêm',
		'Huyện Bình Lục',
		'Huyện Lý Nhân',
	),
	'02-01' => array(
		'Quận Ba Đình',
		'Quận Hoàn Kiếm',
		'Quận Tây Hồ',
		'Quận Long Biên',
		'Quận Cầu Giấy',
		'Quận Đống Đa',
		'Quận Hai Bà Trưng',
		'Quận Hoàng Mai',
		'Quận Thanh Xuân',
		'Huyện Sóc Sơn',
		'Huyện Đông Anh',
		'Huyện Gia Lâm',
		'Quận Nam Từ Liêm',
		'Huyện Thanh Trì',
		'Quận Bắc Từ Liêm',
		'Huyện Mê Linh',
		'Quận Hà Đông',
		'Thị xã Sơn Tây',
		'Huyện Ba Vì',
		'Huyện Phúc Thọ',
		'Huyện Đan Phượng',
		'Huyện Hoài Đức',
		'Huyện Quốc Oai',
		'Huyện Thạch Thất',
		'Huyện Chương Mỹ',
		'Huyện Thanh Oai',
		'Huyện Thường Tín',
		'Huyện Phú Xuyên',
		'Huyện Ứng Hòa',
		'Huyện Mỹ Đức',
	),
	'26-42' => array(
		'Thành phố Hà Tĩnh',
		'Thị xã Hồng Lĩnh',
		'Huyện Hương Sơn',
		'Huyện Đức Thọ',
		'Huyện Vũ Quang',
		'Huyện Nghi Xuân',
		'Huyện Can Lộc',
		'Huyện Hương Khê',
		'Huyện Thạch Hà',
		'Huyện Cẩm Xuyên',
		'Huyện Kỳ Anh',
		'Huyện Lộc Hà',
		'Thị xã Kỳ Anh',
	),
	'27-30' => array(
		'Thành phố Hải Dương',
		'Thành phố Chí Linh',
		'Huyện Nam Sách',
		'Thị xã Kinh Môn',
		'Huyện Kim Thành',
		'Huyện Thanh Hà',
		'Huyện Cẩm Giàng',
		'Huyện Bình Giang',
		'Huyện Gia Lộc',
		'Huyện Tứ Kỳ',
		'Huyện Ninh Giang',
		'Huyện Thanh Miện',
	),
	'28-31' => array(
		'Quận Hồng Bàng',
		'Quận Ngô Quyền',
		'Quận Lê Chân',
		'Quận Hải An',
		'Quận Kiến An',
		'Quận Đồ Sơn',
		'Quận Dương Kinh',
		'Huyện Thuỷ Nguyên',
		'Huyện An Dương',
		'Huyện An Lão',
		'Huyện Kiến Thuỵ',
		'Huyện Tiên Lãng',
		'Huyện Vĩnh Bảo',
		'Huyện Cát Hải',
		'Huyện Bạch Long Vĩ',
	),
	'29-93' => array(
		'Thành phố Vị Thanh',
		'Thành phố Ngã Bảy',
		'Huyện Châu Thành A',
		'Huyện Châu Thành',
		'Huyện Phụng Hiệp',
		'Huyện Vị Thuỷ',
		'Huyện Long Mỹ',
		'Thị xã Long Mỹ',
	),
	'30-17' => array(
		'Thành phố Hòa Bình',
		'Huyện Đà Bắc',
		'Huyện Lương Sơn',
		'Huyện Kim Bôi',
		'Huyện Cao Phong',
		'Huyện Tân Lạc',
		'Huyện Mai Châu',
		'Huyện Lạc Sơn',
		'Huyện Yên Thủy',
		'Huyện Lạc Thủy',
	),
	'01-79' => array(
		'Quận 1',
		'Quận 3',
		'Quận 4',
		'Quận 5',
		'Quận 6',
		'Quận 8',
		'Quận 7',
		'Quận 10',
		'Quận 11',
		'Quận 12',
		'Quận Gò Vấp',
		'Quận Bình Thạnh',
		'Quận Tân Bình',
		'Quận Tân Phú',
		'Quận Phú Nhuận',
		'Thành phố Thủ Đức',
		'Quận Bình Tân',
		'Huyện Củ Chi',
		'Huyện Hóc Môn',
		'Huyện Bình Chánh',
		'Huyện Nhà Bè',
		'Huyện Cần Giờ',
	),
	'31-33' => array(
		'Thành phố Hưng Yên',
		'Huyện Văn Lâm',
		'Huyện Văn Giang',
		'Huyện Yên Mỹ',
		'Thị xã Mỹ Hào',
		'Huyện Ân Thi',
		'Huyện Khoái Châu',
		'Huyện Kim Động',
		'Huyện Tiên Lữ',
		'Huyện Phù Cừ',
	),
	'32-56' => array(
		'Thành phố Nha Trang',
		'Thành phố Cam Ranh',
		'Huyện Cam Lâm',
		'Huyện Vạn Ninh',
		'Thị xã Ninh Hòa',
		'Huyện Khánh Vĩnh',
		'Huyện Diên Khánh',
		'Huyện Khánh Sơn',
		'Huyện Trường Sa',
	),
	'33-91' => array(
		'Thành phố Rạch Giá',
		'Thành phố Hà Tiên',
		'Huyện Kiên Lương',
		'Huyện Hòn Đất',
		'Huyện Tân Hiệp',
		'Huyện Châu Thành',
		'Huyện Giồng Riềng',
		'Huyện Gò Quao',
		'Huyện An Biên',
		'Huyện An Minh',
		'Huyện Vĩnh Thuận',
		'Thành phố Phú Quốc',
		'Huyện Kiên Hải',
		'Huyện U Minh Thượng',
		'Huyện Giang Thành',
	),
	'34-62' => array(
		'Thành phố Kon Tum',
		'Huyện Đắk Glei',
		'Huyện Ngọc Hồi',
		'Huyện Đắk Tô',
		'Huyện Kon Plông',
		'Huyện Kon Rẫy',
		'Huyện Đắk Hà',
		'Huyện Sa Thầy',
		'Huyện Tu Mơ Rông',
		"Huyện Ia H Drai",
	),
	'35-12' => array(
		'Thành phố Lai Châu',
		'Huyện Tam Đường',
		'Huyện Mường Tè',
		'Huyện Sìn Hồ',
		'Huyện Phong Thổ',
		'Huyện Than Uyên',
		'Huyện Tân Uyên',
		'Huyện Nậm Nhùn',
	),
	'36-68' => array(
		'Thành phố Đà Lạt',
		'Thành phố Bảo Lộc',
		'Huyện Đam Rông',
		'Huyện Lạc Dương',
		'Huyện Lâm Hà',
		'Huyện Đơn Dương',
		'Huyện Đức Trọng',
		'Huyện Di Linh',
		'Huyện Bảo Lâm',
		'Huyện Đạ Huoai',
		'Huyện Đạ Tẻh',
		'Huyện Cát Tiên',
	),
	'37-20' => array(
		'Thành phố Lạng Sơn',
		'Huyện Tràng Định',
		'Huyện Bình Gia',
		'Huyện Văn Lãng',
		'Huyện Cao Lộc',
		'Huyện Văn Quan',
		'Huyện Bắc Sơn',
		'Huyện Hữu Lũng',
		'Huyện Chi Lăng',
		'Huyện Lộc Bình',
		'Huyện Đình Lập',
	),
	'28-10' => array(
		'Thành phố Lào Cai',
		'Huyện Bát Xát',
		'Huyện Mường Khương',
		'Huyện Si Ma Cai',
		'Huyện Bắc Hà',
		'Huyện Bảo Thắng',
		'Huyện Bảo Yên',
		'Thị xã Sa Pa',
		'Huyện Văn Bàn',
	),
	'39-80' => array(
		'Thành phố Tân An',
		'Thị xã Kiến Tường',
		'Huyện Tân Hưng',
		'Huyện Vĩnh Hưng',
		'Huyện Mộc Hóa',
		'Huyện Tân Thạnh',
		'Huyện Thạnh Hóa',
		'Huyện Đức Huệ',
		'Huyện Đức Hòa',
		'Huyện Bến Lức',
		'Huyện Thủ Thừa',
		'Huyện Tân Trụ',
		'Huyện Cần Đước',
		'Huyện Cần Giuộc',
		'Huyện Châu Thành',
	),
	'40-36' => array(
		'Thành phố Nam Định',
		'Huyện Mỹ Lộc',
		'Huyện Vụ Bản',
		'Huyện Ý Yên',
		'Huyện Nghĩa Hưng',
		'Huyện Nam Trực',
		'Huyện Trực Ninh',
		'Huyện Xuân Trường',
		'Huyện Giao Thủy',
		'Huyện Hải Hậu',
	),
	'41-40' => array(
		'Thành phố Vinh',
		'Thị xã Cửa Lò',
		'Thị xã Thái Hoà',
		'Huyện Quế Phong',
		'Huyện Quỳ Châu',
		'Huyện Kỳ Sơn',
		'Huyện Tương Dương',
		'Huyện Nghĩa Đàn',
		'Huyện Quỳ Hợp',
		'Huyện Quỳnh Lưu',
		'Huyện Con Cuông',
		'Huyện Tân Kỳ',
		'Huyện Anh Sơn',
		'Huyện Diễn Châu',
		'Huyện Yên Thành',
		'Huyện Đô Lương',
		'Huyện Thanh Chương',
		'Huyện Nghi Lộc',
		'Huyện Nam Đàn',
		'Huyện Hưng Nguyên',
		'Thị xã Hoàng Mai',
	),
	'42-37' => array(
		'Thành phố Ninh Bình',
		'Thành phố Tam Điệp',
		'Huyện Nho Quan',
		'Huyện Gia Viễn',
		'Huyện Hoa Lư',
		'Huyện Yên Khánh',
		'Huyện Kim Sơn',
		'Huyện Yên Mô',
	),
	'43-58' => array(
		'Thành phố Phan Rang-Tháp Chàm',
		'Huyện Bác Ái',
		'Huyện Ninh Sơn',
		'Huyện Ninh Hải',
		'Huyện Ninh Phước',
		'Huyện Thuận Bắc',
		'Huyện Thuận Nam',
	),
	'44-25' => array(
		'Thành phố Việt Trì',
		'Thị xã Phú Thọ',
		'Huyện Đoan Hùng',
		'Huyện Hạ Hoà',
		'Huyện Thanh Ba',
		'Huyện Phù Ninh',
		'Huyện Yên Lập',
		'Huyện Cẩm Khê',
		'Huyện Tam Nông',
		'Huyện Lâm Thao',
		'Huyện Thanh Sơn',
		'Huyện Thanh Thuỷ',
		'Huyện Tân Sơn',
	),
	'45-54' => array(
		'Thành phố Tuy Hoà',
		'Thị xã Sông Cầu',
		'Huyện Đồng Xuân',
		'Huyện Tuy An',
		'Huyện Sơn Hòa',
		'Huyện Sông Hinh',
		'Huyện Tây Hoà',
		'Huyện Phú Hoà',
		'Thị xã Đông Hòa',
	),
	'46-44' => array(
		'Thành Phố Đồng Hới',
		'Huyện Minh Hóa',
		'Huyện Tuyên Hóa',
		'Huyện Quảng Trạch',
		'Huyện Bố Trạch',
		'Huyện Quảng Ninh',
		'Huyện Lệ Thủy',
		'Thị xã Ba Đồn',
	),
	'47-49' => array(
		'Thành phố Tam Kỳ',
		'Thành phố Hội An',
		'Huyện Tây Giang',
		'Huyện Đông Giang',
		'Huyện Đại Lộc',
		'Thị xã Điện Bàn',
		'Huyện Duy Xuyên',
		'Huyện Quế Sơn',
		'Huyện Nam Giang',
		'Huyện Phước Sơn',
		'Huyện Hiệp Đức',
		'Huyện Thăng Bình',
		'Huyện Tiên Phước',
		'Huyện Bắc Trà My',
		'Huyện Nam Trà My',
		'Huyện Núi Thành',
		'Huyện Phú Ninh',
		'Huyện Nông Sơn',
	),
	'48-51' => array(
		'Thành phố Quảng Ngãi',
		'Huyện Bình Sơn',
		'Huyện Trà Bồng',
		'Huyện Sơn Tịnh',
		'Huyện Tư Nghĩa',
		'Huyện Sơn Hà',
		'Huyện Sơn Tây',
		'Huyện Minh Long',
		'Huyện Nghĩa Hành',
		'Huyện Mộ Đức',
		'Thị xã Đức Phổ',
		'Huyện Ba Tơ',
		'Huyện Lý Sơn',
	),
	'49-22' => array(
		'Thành phố Hạ Long',
		'Thành phố Móng Cái',
		'Thành phố Cẩm Phả',
		'Thành phố Uông Bí',
		'Huyện Bình Liêu',
		'Huyện Tiên Yên',
		'Huyện Đầm Hà',
		'Huyện Hải Hà',
		'Huyện Ba Chẽ',
		'Huyện Vân Đồn',
		'Thị xã Đông Triều',
		'Thị xã Quảng Yên',
		'Huyện Cô Tô',
	),
	'50-45' => array(
		'Thành phố Đông Hà',
		'Thị xã Quảng Trị',
		'Huyện Vĩnh Linh',
		'Huyện Hướng Hóa',
		'Huyện Gio Linh',
		'Huyện Đa Krông',
		'Huyện Cam Lộ',
		'Huyện Triệu Phong',
		'Huyện Hải Lăng',
		'Huyện Cồn Cỏ',
	),
	'51-94' => array(
		'Thành phố Sóc Trăng',
		'Huyện Châu Thành',
		'Huyện Kế Sách',
		'Huyện Mỹ Tú',
		'Huyện Cù Lao Dung',
		'Huyện Long Phú',
		'Huyện Mỹ Xuyên',
		'Thị xã Ngã Năm',
		'Huyện Thạnh Trị',
		'Thị xã Vĩnh Châu',
		'Huyện Trần Đề',
	),
	'52-14' => array(
		'Thành phố Sơn La',
		'Huyện Quỳnh Nhai',
		'Huyện Thuận Châu',
		'Huyện Mường La',
		'Huyện Bắc Yên',
		'Huyện Phù Yên',
		'Huyện Mộc Châu',
		'Huyện Yên Châu',
		'Huyện Mai Sơn',
		'Huyện Sông Mã',
		'Huyện Sốp Cộp',
		'Huyện Vân Hồ',
	),
	'53-72' => array(
		'Thành phố Tây Ninh',
		'Huyện Tân Biên',
		'Huyện Tân Châu',
		'Huyện Dương Minh Châu',
		'Huyện Châu Thành',
		'Thị xã Hòa Thành',
		'Huyện Gò Dầu',
		'Huyện Bến Cầu',
		'Thị xã Trảng Bàng',
	),
	'54-34' => array(
		'Thành phố Thái Bình',
		'Huyện Quỳnh Phụ',
		'Huyện Hưng Hà',
		'Huyện Đông Hưng',
		'Huyện Thái Thụy',
		'Huyện Tiền Hải',
		'Huyện Kiến Xương',
		'Huyện Vũ Thư',
	),
	'55-19' => array(
		'Thành phố Thái Nguyên',
		'Thành phố Sông Công',
		'Huyện Định Hóa',
		'Huyện Phú Lương',
		'Huyện Đồng Hỷ',
		'Huyện Võ Nhai',
		'Huyện Đại Từ',
		'Thị xã Phổ Yên',
		'Huyện Phú Bình',
	),
	'56-38' => array(
		'Thành phố Thanh Hóa',
		'Thị xã Bỉm Sơn',
		'Thành phố Sầm Sơn',
		'Huyện Mường Lát',
		'Huyện Quan Hóa',
		'Huyện Bá Thước',
		'Huyện Quan Sơn',
		'Huyện Lang Chánh',
		'Huyện Ngọc Lặc',
		'Huyện Cẩm Thủy',
		'Huyện Thạch Thành',
		'Huyện Hà Trung',
		'Huyện Vĩnh Lộc',
		'Huyện Yên Định',
		'Huyện Thọ Xuân',
		'Huyện Thường Xuân',
		'Huyện Triệu Sơn',
		'Huyện Thiệu Hóa',
		'Huyện Hoằng Hóa',
		'Huyện Hậu Lộc',
		'Huyện Nga Sơn',
		'Huyện Như Xuân',
		'Huyện Như Thanh',
		'Huyện Nông Cống',
		'Huyện Đông Sơn',
		'Huyện Quảng Xương',
		'Thị xã Nghi Sơn',
	),
	'57-46' => array(
		'Thành phố Huế',
		'Huyện Phong Điền',
		'Huyện Quảng Điền',
		'Huyện Phú Vang',
		'Thị xã Hương Thủy',
		'Thị xã Hương Trà',
		'Huyện A Lưới',
		'Huyện Phú Lộc',
		'Huyện Nam Đông',
	),
	'58-82' => array(
		'Thành phố Mỹ Tho',
		'Thị xã Gò Công',
		'Thị xã Cai Lậy',
		'Huyện Tân Phước',
		'Huyện Cái Bè',
		'Huyện Cai Lậy',
		'Huyện Châu Thành',
		'Huyện Chợ Gạo',
		'Huyện Gò Công Tây',
		'Huyện Gò Công Đông',
		'Huyện Tân Phú Đông',
	),
	'59-84' => array(
		'Thành phố Trà Vinh',
		'Huyện Càng Long',
		'Huyện Cầu Kè',
		'Huyện Tiểu Cần',
		'Huyện Châu Thành',
		'Huyện Cầu Ngang',
		'Huyện Trà Cú',
		'Huyện Duyên Hải',
		'Thị xã Duyên Hải',
	),
	'60-08' => array(
		'Thành phố Tuyên Quang',
		'Huyện Lâm Bình',
		'Huyện Na Hang',
		'Huyện Chiêm Hóa',
		'Huyện Hàm Yên',
		'Huyện Yên Sơn',
		'Huyện Sơn Dương',
	),
	'61-86' => array(
		'Thành phố Vĩnh Long',
		'Huyện Long Hồ',
		'Huyện Mang Thít',
		'Huyện  Vũng Liêm',
		'Huyện Tam Bình',
		'Thị xã Bình Minh',
		'Huyện Trà Ôn',
		'Huyện Bình Tân',
	),
	'62-26' => array(
		'Thành phố Vĩnh Yên',
		'Thành phố Phúc Yên',
		'Huyện Lập Thạch',
		'Huyện Tam Dương',
		'Huyện Tam Đảo',
		'Huyện Bình Xuyên',
		'Huyện Yên Lạc',
		'Huyện Vĩnh Tường',
		'Huyện Sông Lô',
	),
	'63-15' => array(
		'Thành phố Yên Bái',
		'Thị xã Nghĩa Lộ',
		'Huyện Lục Yên',
		'Huyện Văn Yên',
		'Huyện Mù Căng Chải',
		'Huyện Trấn Yên',
		'Huyện Trạm Tấu',
		'Huyện Văn Chấn',
		'Huyện Yên Bình',
	),
);

// Use this filter to handle the Districts of Vietnam
$places['VN'] = apply_filters('scpwoo_custom_places_vn', $places['VN']);