<?php

/**
 * Venezuelan Municipalities:
 * - 335 municipalities and their capitals
 * 
 * Source:
 * - https://es.wikipedia.org/wiki/Anexo:Municipios_de_Venezuela
 *
 * @author  Yordan Soares <contacto@yordansoar.es> | https://yordansoar.es
 * @version 1.0.0
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 */

global $places;

$municipality = __('Municipality', 'states-cities-and-places-for-woocommerce');

$places['VE'] = array(
  'AM' => array(
    $municipality . ' Alto Orinoco (La Esmeralda)',
    $municipality . ' Atabapo (San Fernando de Atabapo)',
    $municipality . ' Atures (Puerto Ayacucho)',
    $municipality . ' Autana (Isla Ratón)',
    $municipality . ' Manapiare (San Juan de Manapiare)',
    $municipality . ' Maroa (Maroa)',
    $municipality . ' Río Negro (San Carlos de Río Negro)'
  ),
  'AN' => array(
    $municipality . ' Anaco (Anaco)',
    $municipality . ' Aragua (Aragua de Barcelona)',
    $municipality . ' Bolívar (Barcelona)',
    $municipality . ' Bruzual (Clarines)',
    $municipality . ' Cajigal (Onoto)',
    $municipality . ' Carvajal (Valle de Guanape)',
    $municipality . ' Diego Bautista Urbaneja (Lechería)',
    $municipality . ' Freites (Cantaura)',
    $municipality . ' Guanipa (San José de Guanipa)',
    $municipality . ' Guanta (Guanta)',
    $municipality . ' Independencia (Soledad)',
    $municipality . ' Libertad (San Mateo)',
    $municipality . ' McGregor (El Chaparro)',
    $municipality . ' Miranda (Pariaguán',
    $municipality . ' Monagas (San Diego de Cabrutica',
    $municipality . ' Peñalver (Puerto Píritu',
    $municipality . ' Píritu (Píritu)',
    $municipality . ' San Juan de Capistrano (Boca de Uchire)',
    $municipality . ' Santa Ana (Santa Ana)',
    $municipality . ' Simón Rodriguez (El Tigre)',
    $municipality . ' Sotillo (Puerto La Cruz)'
  ),
  'AP' => array(
    $municipality . ' Achaguas (Achaguas)',
    $municipality . ' Biruaca (Biruaca)',
    $municipality . ' Muñoz (Bruzual)',
    $municipality . ' Páez (Guasdualito)',
    $municipality . ' Pedro Camejo (San Juan de Payara)',
    $municipality . ' Rómulo Gallegos (Elorza)',
    $municipality . ' San Fernando (San Fernando de Apure)'
  ),
  'AR' => array(
    $municipality . ' Bolívar (San Mateo)',
    $municipality . ' Camatagua (Camatagua)',
    $municipality . ' Francisco Linares Alcántara (Santa Rita)',
    $municipality . ' Girardot (Maracay)',
    $municipality . ' José Ángel Lamas (Santa Cruz)',
    $municipality . ' José Félix Ribas (La Victoria)',
    $municipality . ' José Rafael Revenga (El Consejo)',
    $municipality . ' Libertador (Palo Negro)',
    $municipality . ' Mario Briceño Iragorry (El Limón)',
    $municipality . ' Ocumare de la Costa de Oro (Ocumare de la Costa)',
    $municipality . ' San Casimiro (San Casimiro)',
    $municipality . ' San Sebastián (San Sebastián de los Reyes)',
    $municipality . ' Santiago Mariño (Turmero)',
    $municipality . ' Santos Michelena (Las Tejerías)',
    $municipality . ' Sucre (Cagua)',
    $municipality . ' Tovar (Colonia Tovar)',
    $municipality . ' Urdaneta (Barbacoas)',
    $municipality . ' Zamora (Villa de Cura)'
  ),
  'BA' => array(
    $municipality . ' Alberto Arvelo Torrealba (Sabaneta)',
    $municipality . ' Andrés Eloy Blanco (El Cantón)',
    $municipality . ' Antonio José de Sucre (Socopó)',
    $municipality . ' Arismendi (Arismendi)',
    $municipality . ' Barinas (Barinas)',
    $municipality . ' Bolívar (Barinitas)',
    $municipality . ' Cruz Paredes (Barrancas)',
    $municipality . ' Ezequiel Zamora (Santa Bárbara)',
    $municipality . ' Obispos (Obispos)',
    $municipality . ' Pedraza (Ciudad Bolivia)',
    $municipality . ' Rojas (Libertad)',
    $municipality . ' Sosa (Ciudad de Nutrias)'
  ),
  'BO' => array(
    $municipality . ' Caroní (Ciudad Guayana)',
    $municipality . ' Cedeño (Caicara del Orinoco)',
    $municipality . ' El Callao (El Callao)',
    $municipality . ' Gran Sabana (Santa Elena de Uairén)',
    $municipality . ' Heres (Ciudad Bolívar)',
    $municipality . ' Piar (Upata)',
    $municipality . ' Raúl Leoni (Ciudad Piar)',
    $municipality . ' Roscio (Guasipati)',
    $municipality . ' Sifontes (Tumeremo)',
    $municipality . ' Sucre (Maripa)',
    $municipality . ' Padre Pedro Chen (El Palmar)'
  ),
  'CA' => array(
    $municipality . ' Bejuma (Bejuma)',
    $municipality . ' Carlos Arvelo (Güigüe)',
    $municipality . ' Diego Ibarra (Mariara)',
    $municipality . ' Guacara (Guacara)',
    $municipality . ' Juan José Mora (Morón)',
    $municipality . ' Libertador (Tocuyito)',
    $municipality . ' Los Guayos (Los Guayos)',
    $municipality . ' Miranda (Miranda)',
    $municipality . ' Montalbán (Montalbán)',
    $municipality . ' Naguanagua (Naguanagua)',
    $municipality . ' Puerto Cabello (Puerto Cabello)',
    $municipality . ' San Diego (San Diego)',
    $municipality . ' San Joaquín (San Joaquín)',
    $municipality . ' Valencia (Valencia)'
  ),
  'CO' => array(
    $municipality . ' Anzoátegui (Cojedes)',
    $municipality . ' El Pao de San Juan Bautista (El Pao)',
    $municipality . ' Falcón (Tinaquillo)',
    $municipality . ' Girardot (El Baúl)',
    $municipality . ' Lima Blanco (Macapo)',
    $municipality . ' Ricaurte (Libertad)',
    $municipality . ' Rómulo Gallegos (Las Vegas)',
    $municipality . ' San Carlos de Austria (San Carlos)',
    $municipality . ' Tinaco (Tinaco)'
  ),
  'DE' => array(
    $municipality . ' Antonio Díaz Curiapo (Curiapo)',
    $municipality . ' Casacoima (Sierra Imataca)',
    $municipality . ' Pedernales (Pedernales)',
    $municipality . ' Tucupita (Tucupita)'
  ),
  'DC' => array(
    $municipality . ' Libertador (Caracas)'
  ),
  'FA' => array(
    $municipality . ' Acosta (San Juan de los Cayos)',
    $municipality . ' Bolívar (San Luis)',
    $municipality . ' Buchivacoa (Capatárida)',
    $municipality . ' Cacique Manaure (Yaracal)',
    $municipality . ' Carirubana (Punto Fijo)',
    $municipality . ' Colina (La Vela de Coro)',
    $municipality . ' Dabajuro (Dabajuro)',
    $municipality . ' Democracia (Pedregal)',
    $municipality . ' Falcón (Pueblo Nuevo)',
    $municipality . ' Federación (Churuguara)',
    $municipality . ' Jacura (Jacura)',
    $municipality . ' Los Taques (Santa Cruz de Los Taques)',
    $municipality . ' Mauroa (Mene de Mauroa)',
    $municipality . ' Miranda (Santa Ana de Coro)',
    $municipality . ' Monseñor Iturriza (Chichiriviche)',
    $municipality . ' Palmasola (Palmasola)',
    $municipality . ' Petit (Cabure)',
    $municipality . ' Píritu (Píritu)',
    $municipality . ' San Francisco (Mirimire)',
    $municipality . ' Silva (Tucacas)',
    $municipality . ' Sucre (La Cruz de Taratara)',
    $municipality . ' Tocópero (Tocópero)',
    $municipality . ' Unión (Santa Cruz de Bucaral)',
    $municipality . ' Urumaco (Urumaco)',
    $municipality . ' Zamora (Puerto Cumarebo)'
  ),
  'GU' => array(
    $municipality . ' Esteros de Camaguan(Camaguan)',
    $municipality . ' Chaguaramas(Chaguaramas)',
    $municipality . ' El Socorro (El Socorro)',
    $municipality . ' Francisco de Miranda (Calabozo)',
    $municipality . ' José Félix Ribas (Tucupido)',
    $municipality . ' José Tadeo Monagas (Altagracia de Orituco)',
    $municipality . ' Juan Germán Roscio (San Juan de Los Morros)',
    $municipality . ' Julián Mellado (El Sombrero)',
    $municipality . ' Las Mercedes (Las Mercedes)',
    $municipality . ' Leonardo Infante (Valle de La Pascua)',
    $municipality . ' Pedro Zaraza (Zaraza)',
    $municipality . ' Ortíz (Ortíz)',
    $municipality . ' San Gerónimo de Guayabal (Guayabal)',
    $municipality . ' San José de Guaribe (San José de Guaribe)',
    $municipality . ' Santa María de Ipire (Santa María de Ipire)'
  ),
  'LA' => array(
    $municipality . ' Andrés Eloy Blanco (Sanare)',
    $municipality . ' Crespo (Duaca)',
    $municipality . ' Iribarren (Barquisimeto)',
    $municipality . ' Jiménez (Quibor)',
    $municipality . ' Morán (El Tocuyo)',
    $municipality . ' Palavecino (Cabudare)',
    $municipality . ' Simón Planas (Sarare)',
    $municipality . ' Torres (Carora)',
    $municipality . ' Urdaneta (Siquisique)'
  ),
  'LG' => array(
    $municipality . ' Vargas (La Guaira)'
  ),
  'ME' => array(
    $municipality . ' Alberto Adriani (El Vigía)',
    $municipality . ' Andrés Bello (La Azulita)',
    $municipality . ' Antonio Pinto Salinas (Santa Cruz de Mora)',
    $municipality . ' Aricagua (Aricagua)',
    $municipality . ' Arzobispo Chacón (Canagua)',
    $municipality . ' Campo Elías (Ejido)',
    $municipality . ' Caracciolo Parra Olmedo (Tucani)',
    $municipality . ' Cardenal Quintero (Santo Domingo)',
    $municipality . ' Guaraque (Guaraque)',
    $municipality . ' Julio César Salas (Arapuey)',
    $municipality . ' Justo Briceño (Torondoy)',
    $municipality . ' Libertador (Mérida)',
    $municipality . ' Miranda (Timotes)',
    $municipality . ' Obispo Ramos de Lora (Santa Elena de Arenales)',
    $municipality . ' Padre Noguera (Santa María de Caparo)',
    $municipality . ' Pueblo Llano (Pueblo Llano)',
    $municipality . ' Rangel (Mucuchíes)',
    $municipality . ' Rivas Dávila (Bailadores)',
    $municipality . ' Santos Marquina (Tabay)',
    $municipality . ' Sucre (Lagunillas)',
    $municipality . ' Tovar (Tovar)',
    $municipality . ' Tulio Febres Cordero (Nueva Bolivia)',
    $municipality . ' Zea (Zea)'
  ),
  'MI' => array(
    $municipality . ' Acevedo (Caucagua)',
    $municipality . ' Andrés Bello (San José de Barlovento)',
    $municipality . ' Baruta (Baruta)',
    $municipality . ' Brión (Higuerote)',
    $municipality . ' Buroz (Mamporal)',
    $municipality . ' Carrizal (Carrizal)',
    $municipality . ' Chacao (Chacao)',
    $municipality . ' Cristóbal Rojas (Charallave)',
    $municipality . ' El Hatillo (El Hatillo)',
    $municipality . ' Guaicaipuro (Los Teques)',
    $municipality . ' Independencia (Santa Teresa del Tuy)',
    $municipality . ' Lander (Ocumare del Tuy)',
    $municipality . ' Los Salias (San Antonio de los Altos)',
    $municipality . ' Páez (Río Chico)',
    $municipality . ' Paz Castillo (Santa Lucía)',
    $municipality . ' Pedro Gual (Cúpira)',
    $municipality . ' Plaza (Guarenas)',
    $municipality . ' Simón Bolívar (San Francisco de Yare)',
    $municipality . ' Sucre (Petare)',
    $municipality . ' Urdaneta (Cúa)',
    $municipality . ' Zamora (Guatire)'
  ),
  'MO' => array(
    $municipality . ' Acosta (San Antonio de Capayacuar)',
    $municipality . ' Aguasay (Aguasai)',
    $municipality . ' Bolíva',
    $municipality . ' Caripe(Caripe)',
    $municipality . ' Cedeño (Caicara)',
    $municipality . ' Ezequiel Zamora (Punta de Mata)',
    $municipality . ' Libertador (Temblador)',
    $municipality . ' Maturín (Maturín)',
    $municipality . ' Piar (Aragua)',
    $municipality . ' Punceres (Quiriquire)',
    $municipality . ' Santa Bárbara (Santa Bárbara)',
    $municipality . ' Sotillo (Barrancas del Orinco)',
    $municipality . ' Uracoa (Uracoa)'
  ),
  'NE' => array(
    $municipality . ' Antolín del Campo (La Plaza de Paraguachí)',
    $municipality . ' Arismendi (La Asunción)',
    $municipality . ' Díaz (San Juan Bautista)',
    $municipality . ' García (El Valle del Espíritu Santo)',
    $municipality . ' Gómez (Santa Ana)',
    $municipality . ' Maneiro (Pampatar)',
    $municipality . ' Marcano (Juan Griego)',
    $municipality . ' Mariño (Porlamar)',
    $municipality . ' Península de Macanao (Boca de Río)',
    $municipality . ' Tubores (Punta de Piedras)',
    $municipality . ' Villalba (San Pedro de Coche)'
  ),
  'PO' => array(
    $municipality . ' Agua Blanca (Agua Blanca)',
    $municipality . ' Araure (Araure)',
    $municipality . ' Esteller (Píritu)',
    $municipality . ' Guanare (Guanare)',
    $municipality . ' Guanarito (Guanarito)',
    $municipality . ' Monseñor José Vicenti de Unda (Chabasquén de Unda)',
    $municipality . ' Ospino (Ospino)',
    $municipality . ' Páez (Acarigua)',
    $municipality . ' Papelón (Papelón)',
    $municipality . ' San Genaro de Boconoíto (Boconoíto)',
    $municipality . ' San Rafael de Onoto (San Rafael de Onoto)',
    $municipality . ' Santa Rosalía (El Playón)',
    $municipality . ' Sucre (Biscucuy)',
    $municipality . ' Turén (Villa Bruzual)'
  ),
  'SU' => array(
    $municipality . ' Andrés Eloy Blanco (Casanay)',
    $municipality . ' Andrés Mata (San José de Aerocuar)',
    $municipality . ' Arismendi (Río Caribe)',
    $municipality . ' Benítez (El Pilar)',
    $municipality . ' Bermúdez (Carúpano)',
    $municipality . ' Bolívar (Marigüitar)',
    $municipality . ' Cajigal (Yaguaraparo)',
    $municipality . ' Cruz Salmerón Acosta (Araya)',
    $municipality . ' Libertador (Tunapuy)',
    $municipality . ' Mariño (Irapa)',
    $municipality . ' Mejía (San Antonio del Golfo)',
    $municipality . ' Montes (Cumanacoa)',
    $municipality . ' Ribero (Cariaco)',
    $municipality . ' Sucre (Cumaná)',
    $municipality . ' Valdez (Güiria)'
  ),
  'TA' => array(
    $municipality . ' Andrés Bello(Cordero)',
    $municipality . ' Antonio Rómulo Costa (Las Mesas)',
    $municipality . ' Ayacucho (El Colón)',
    $municipality . ' Bolívar (San Antonio del Táchira)',
    $municipality . ' Cárdenas (Táriba)',
    $municipality . ' Córdoba (Santa Ana de Táchira)',
    $municipality . ' Fernández Feo (San Rafael del Piñal)',
    $municipality . ' Francisco de Miranda (San José de Bolívar)',
    $municipality . ' García de Hevia (La Fría)',
    $municipality . ' Guásimos (Palmira)',
    $municipality . ' Independencia (Capacho Nuevo)',
    $municipality . ' Jáuregui (La Grita)',
    $municipality . ' José María Vargas (El Cobre)',
    $municipality . ' Junín (Rubio)',
    $municipality . ' San Judas Tadeo (Umuquena)',
    $municipality . ' Libertad (Capacho Viejo)',
    $municipality . ' Libertador (Abejales)',
    $municipality . ' Lobatera (Lobatera)',
    $municipality . ' Michelena (Michelena)',
    $municipality . ' Panamericano (Coloncito)',
    $municipality . ' Pedro María Ureña (Ureña)',
    $municipality . ' Rafael Urdaneta (Delicias)',
    $municipality . ' Samuel Dario Maldonado (La Tendida)',
    $municipality . ' San Cristóbal (San Cristóbal)',
    $municipality . ' Seboruco (Seboruco)',
    $municipality . ' Simón Rodríguez (San Simon)',
    $municipality . ' Sucre (Queniquea)',
    $municipality . ' Torbes (San Josesito)',
    $municipality . ' Uribante (Pregonero)'
  ),
  'TR' => array(
    $municipality . ' Andrés Bello (Santa Isabel)',
    $municipality . ' Boconó (Boconó)',
    $municipality . ' Bolívar (Sabana Grande)',
    $municipality . ' Candelaria (Chejendé)',
    $municipality . ' Carache (Carache)',
    $municipality . ' Escuque (Escuque)',
    $municipality . ' José Felipe Márquez Cañizales (El Paradero)',
    $municipality . ' Juan Vicente Campo Elías (Campo Elías)',
    $municipality . ' La Ceiba (Santa Apolonia)',
    $municipality . ' Miranda (El Dividive)',
    $municipality . ' Monte Carmelo (Monte Carmelo)',
    $municipality . ' Motatán (Motatán)',
    $municipality . ' Pampán (Pampán)',
    $municipality . ' Pampanito (Pampanito)',
    $municipality . ' Rafael Rangel (Betijoque)',
    $municipality . ' San Rafael de Carvajal (Carvajal)',
    $municipality . ' Sucre (Sabana de Mendoza)',
    $municipality . ' Trujilo (Trujillo)',
    $municipality . ' Urdaneta (La Quebrada)',
    $municipality . ' Valera (Valera)'
  ),
  'YA' => array(
    $municipality . ' Aristides Bastidas (San Pablo)',
    $municipality . ' Bolívar (Aroa)',
    $municipality . ' Bruzual (Chivacoa)',
    $municipality . ' Cocorote (Cocorote)',
    $municipality . ' Independencia (Independencia)',
    $municipality . ' José Antonio Páez (Sabana de Parra)',
    $municipality . ' La Trinidad (Boraure)',
    $municipality . ' Manuel Monge (Yumare)',
    $municipality . ' Nirgua (Nirgua)',
    $municipality . ' Peña (Yaritagua)',
    $municipality . ' San Felipe',
    $municipality . ' Sucre (Guama)',
    $municipality . ' Urachiche (Urachiche)',
    $municipality . ' Veroes (Farriar)'
  ),
  'ZU' => array(
    $municipality . ' Almirante Padilla (El Toro)',
    $municipality . ' Baralt (San Timoteo)',
    $municipality . ' Cabimas (Cabimas)',
    $municipality . ' Catatumbo (Encontrados)',
    $municipality . ' Colón (San Carlos del Zulia)',
    $municipality . ' Francisco Javier Pulgar (Pueblo Nuevo / El Chivo)',
    $municipality . ' Jesús Enrique Lossada (La Concepción)',
    $municipality . ' Jesús María Semprún (Casigua el Cubo)',
    $municipality . ' La Cañada de Urdaneta (Concepción)',
    $municipality . ' Lagunillas (Ciudad Ojeda)',
    $municipality . ' Machiques de Perijá (Machiques)',
    $municipality . ' Mara (San Rafael del Moján)',
    $municipality . ' Maracaibo (Maracaibo)',
    $municipality . ' Miranda (Los Puertos de Altagracia)',
    $municipality . ' Páez (Sinamaica)',
    $municipality . ' Rosario de Perijá (La Villa del Rosario)',
    $municipality . ' San Francisco (San Francisco)',
    $municipality . ' Santa Rita (Santa Rita)',
    $municipality . ' Simón Bolívar (Tía Juana)',
    $municipality . ' Sucre (Bobures)',
    $municipality . ' Valmore Rodríguez (Bachaquero)'
  ),
);