<?php

/**
* Districts of Malaysia
* 159 districts
*
* Source:
* - https://en.wikipedia.org/wiki/List_of_districts_in_Malaysia
*
* @author  Amirah Zainuddin <web@syscomm.cc>
* @version 1.0.0
* @license http://www.gnu.org/licenses/gpl-2.0.html
*/

global $places;
$places['MY'] = array(
    'JHR' => array(
        'Batu Pahat',
        'Johor Bahru',
        'Kluang',
        'Kota Tinggi',
        'Kulai',
        'Mersing',
        'Muar',
        'Pontian',
        'Segamat',
        'Tangkak',
    ),
    'KDH' => array(
        'Baling',
        'Bandar Baharu',
        'Kota Setar',
        'Kuala Muda',
        'Kubang Pasu',
        'Kulim',
        'Langkawi',
        'Padang Terap',
        'Pendang',
        'Pokok Sena',
        'Sik',
        'Yan',
    ),
    'KTN' => array(
        'Bachok',
        'Gua Musang',
        'Jeli',
        'Kota Bharu',
        'Kuala Krai',
        'Machang',
        'Pasir Mas',
        'Pasir Puteh',
        'Tanah Merah',
        'Tumpat',
    ),
    'MLK' => array(
        'Alor Gajah',
        'Central Melaka',
        'Jasin',
    ),
    'NSN' => array(
        'Jelebu',
        'Jempol',
        'Kuala Pilah',
        'Port Dickson',
        'Rembau',
        'Seremban',
        'Tampin',
    ),
    'PHG' => array(
        'Bentong',
        'Bera',
        'Cameron Highlands',
        'Jerantut',
        'Kuantan',
        'Lipis',
        'Maran',
        'Pekan',
        'Raub',
        'Rompin',
        'Temerloh',

    ),
    'PRK' => array(
        'Bagan Datuk',
        'Tapah',
        'Teluk Intan',
        'Gerik',
        'Kampar',
        'Parit Buntar',
        'Batu Gajah',
        'Kuala Kangsar',
        'Taiping',
        'Seri Manjung',
        'Tanjung Malim',
        'Seri Iskandar',
    ),
    'PLS' => array(
        'Kangar',
    ),
    'PNG' => array(
        'Bukit Mertajam',
        'Kepala Batas',
        'George Town',
        'Sungai Jawi',
        'Balik Pulau',
    ),
    'SBH' => array(
        'Beaufort',
        'Beluran',
        'Kalabakan',
        'Keningau',
        'Kota Belud',
        'Kinabatangan',
        'Kota Kinabalu',
        'Kota Marudu',
        'Kuala Penyu',
        'Kudat',
        'Kunak',
        'Lahad Datu',
        'Nabawan',
        'Papar',
        'Penampang',
        'Putatan',
        'Pitas',
        'Ranau',
        'Sandakan',
        'Semporna',
        'Sipitang',
        'Tambunan',
        'Tawau',
        'Telupid',
        'Tenom',
        'Tongod',
        'Tuaran',
    ),
    'SWK' => array(
        'Betong',
        'Bintulu',
        'Kapit',
        'Kuching',
        'Limbang',
        'Miri',
        'Mukah',
        'Samarahan',
        'Sarikei',
        'Serian',
        'Sibu',
        'Sri Aman',
    ),
    'SGR' => array(
        'Gombak',
        'Hulu Langat',
        'Hulu Selangor',
        'Klang',
        'Kuala Langat',
        'Kuala Selangor',
        'Petaling',
        'Sabak Bernam',
        'Sepang',
    ),
    'TRG' => array(
        'Besut',
        'Dungun',
        'Hulu Terengganu',
        'Kemaman',
        'Kuala Nerus',
        'Kuala Terengganu',
        'Marang',
        'Setiu',
    ),
    'KUL' => array(
        'Bukit Bintang',
        'Titiwangsa',
        'Setiawangsa',
        'Wangsa Maju',
        'Batu',
        'Kepong',
        'Segambut',
        'Lembah Pantai',
        'Seputeh',
        'Bandar Tun Razak',
        'Cheras',
    ),
    'LBN' => array(
        'Labuan',
    ),
    'PJY' => array(
        'Precint 1',
        'Precint 2',
        'Precint 3',
        'Precint 4',
        'Precint 5',
        'Precint 6',
        'Precint 7',
        'Precint 8',
        'Precint 9',
        'Precint 10',
        'Precint 11',
        'Precint 12',
        'Precint 13',
        'Precint 14',
        'Precint 15',
        'Precint 16',
        'Precint 17',
        'Precint 18',
        'Precint 19',
        'Precint 20',
    ),
);

// Use this filter to handle the Districts of Malaysia
$places['MY'] = apply_filters('scpwoo_custom_places_my', $places['MY']);
